// GLOXORG — Sanal Ayna cip etiketleri (sac modeli/renk/kiyafet/makyaj/tirnak/ayakkabi/canta/aksesuar) 12 dile cevirisi (B53).
// Anahtar = Turkce etiket; deger state olarak Turkce kalir, SADECE gorunum cevrilir (ac kullanir). tr icin etiketin kendisi doner.
export const AYNA_CEV = {
 "Ombre": {
  "en": "Ombré",
  "de": "Ombré",
  "ru": "Омбре",
  "uk": "Омбре",
  "es": "Ombré",
  "fr": "Ombré",
  "it": "Ombré",
  "pt": "Ombré",
  "ar": "أومبريه",
  "hi": "ओम्ब्रे",
  "zh": "渐变染",
  "ja": "オンブレ"
 },
 "Balyaj": {
  "en": "Balayage",
  "de": "Balayage",
  "ru": "Балаяж",
  "uk": "Балаяж",
  "es": "Balayage",
  "fr": "Balayage",
  "it": "Balayage",
  "pt": "Balayage",
  "ar": "باليياج",
  "hi": "बलायाज",
  "zh": "挑染",
  "ja": "バレイヤージュ"
 },
 "Uzun Dalgalı": {
  "en": "Long Wavy",
  "de": "Lang Gewellt",
  "ru": "Длинные волнистые",
  "uk": "Довге хвилясте",
  "es": "Largo ondulado",
  "fr": "Long ondulé",
  "it": "Lunghi mossi",
  "pt": "Longo ondulado",
  "ar": "طويل مموّج",
  "hi": "लंबे लहरदार",
  "zh": "长波浪",
  "ja": "ロングウェーブ"
 },
 "Düz Uzun": {
  "en": "Long Straight",
  "de": "Lang Glatt",
  "ru": "Прямые длинные",
  "uk": "Пряме довге",
  "es": "Largo liso",
  "fr": "Long lisse",
  "it": "Lisci lunghi",
  "pt": "Liso longo",
  "ar": "طويل مفرود",
  "hi": "सीधे लंबे",
  "zh": "长直发",
  "ja": "ロングストレート"
 },
 "Kare Kesim (Bob)": {
  "en": "Bob Cut",
  "de": "Bob-Schnitt",
  "ru": "Каре (боб)",
  "uk": "Каре (боб)",
  "es": "Corte bob",
  "fr": "Coupe carré (bob)",
  "it": "Taglio caschetto (Bob)",
  "pt": "Corte chanel (Bob)",
  "ar": "قصّة بوب",
  "hi": "बॉब कट",
  "zh": "波波头（Bob）",
  "ja": "ボブ"
 },
 "Katlı Kesim": {
  "en": "Layered Cut",
  "de": "Stufenschnitt",
  "ru": "Каскад",
  "uk": "Каскад",
  "es": "Corte en capas",
  "fr": "Coupe dégradée",
  "it": "Taglio scalato",
  "pt": "Corte repicado",
  "ar": "قصّة متدرّجة",
  "hi": "लेयर कट",
  "zh": "层次剪",
  "ja": "レイヤーカット"
 },
 "Topuz": {
  "en": "Bun",
  "de": "Dutt",
  "ru": "Пучок",
  "uk": "Пучок",
  "es": "Moño",
  "fr": "Chignon",
  "it": "Chignon",
  "pt": "Coque",
  "ar": "كعكة شعر",
  "hi": "जूड़ा",
  "zh": "发髻",
  "ja": "お団子"
 },
 "At Kuyruğu": {
  "en": "Ponytail",
  "de": "Pferdeschwanz",
  "ru": "Хвост",
  "uk": "Хвіст",
  "es": "Cola de caballo",
  "fr": "Queue-de-cheval",
  "it": "Coda di cavallo",
  "pt": "Rabo de cavalo",
  "ar": "ذيل حصان",
  "hi": "पोनीटेल",
  "zh": "马尾",
  "ja": "ポニーテール"
 },
 "Röfle": {
  "en": "Highlights",
  "de": "Strähnchen",
  "ru": "Мелирование",
  "uk": "Мелірування",
  "es": "Mechas",
  "fr": "Mèches",
  "it": "Colpi di sole",
  "pt": "Luzes",
  "ar": "خصلات",
  "hi": "हाइलाइट्स",
  "zh": "挑染",
  "ja": "ハイライト"
 },
 "Perma": {
  "en": "Perm",
  "de": "Dauerwelle",
  "ru": "Химзавивка",
  "uk": "Хімзавивка",
  "es": "Permanente",
  "fr": "Permanente",
  "it": "Permanente",
  "pt": "Permanente",
  "ar": "تجعيد دائم",
  "hi": "पर्म",
  "zh": "烫发",
  "ja": "パーマ"
 },
 "Fönlü": {
  "en": "Blow-Dried",
  "de": "Geföhnt",
  "ru": "Укладка феном",
  "uk": "Укладка феном",
  "es": "Con secador",
  "fr": "Brushing",
  "it": "Piega a phon",
  "pt": "Escova",
  "ar": "سيشوار",
  "hi": "ब्लो-ड्राई",
  "zh": "吹造型",
  "ja": "ブロー"
 },
 "Küt Kesim": {
  "en": "Blunt Cut",
  "de": "Stumpfer Schnitt",
  "ru": "Ровный срез",
  "uk": "Рівний зріз",
  "es": "Corte recto",
  "fr": "Coupe droite",
  "it": "Taglio netto",
  "pt": "Corte reto",
  "ar": "قصّة مستقيمة",
  "hi": "सीधा कट",
  "zh": "齐剪",
  "ja": "ぱっつんカット"
 },
 "Örgü": {
  "en": "Braid",
  "de": "Zopf",
  "ru": "Коса",
  "uk": "Коса",
  "es": "Trenza",
  "fr": "Tresse",
  "it": "Treccia",
  "pt": "Trança",
  "ar": "ضفيرة",
  "hi": "चोटी",
  "zh": "编发",
  "ja": "編み込み"
 },
 "Fade": {
  "en": "Fade",
  "de": "Fade",
  "ru": "Фейд",
  "uk": "Фейд",
  "es": "Degradado",
  "fr": "Dégradé",
  "it": "Fade",
  "pt": "Fade",
  "ar": "فيد",
  "hi": "फेड",
  "zh": "渐层剪",
  "ja": "フェード"
 },
 "Undercut": {
  "en": "Undercut",
  "de": "Undercut",
  "ru": "Андеркат",
  "uk": "Андеркат",
  "es": "Undercut",
  "fr": "Undercut",
  "it": "Undercut",
  "pt": "Undercut",
  "ar": "أندركت",
  "hi": "अंडरकट",
  "zh": "底剃发",
  "ja": "アンダーカット"
 },
 "Pompadour": {
  "en": "Pompadour",
  "de": "Pompadour",
  "ru": "Помпадур",
  "uk": "Помпадур",
  "es": "Tupé",
  "fr": "Banane",
  "it": "Pompadour",
  "pt": "Pompadour",
  "ar": "بومبادور",
  "hi": "पोम्पाडोर",
  "zh": "庞巴度",
  "ja": "ポンパドール"
 },
 "Uzun Saç": {
  "en": "Long Hair",
  "de": "Lange Haare",
  "ru": "Длинные волосы",
  "uk": "Довге волосся",
  "es": "Pelo largo",
  "fr": "Cheveux longs",
  "it": "Capelli lunghi",
  "pt": "Cabelo longo",
  "ar": "شعر طويل",
  "hi": "लंबे बाल",
  "zh": "长发",
  "ja": "ロングヘア"
 },
 "Ondüle": {
  "en": "Waves",
  "de": "Wellen",
  "ru": "Локоны",
  "uk": "Локони",
  "es": "Ondulado",
  "fr": "Ondulé",
  "it": "Ondulati",
  "pt": "Ondulado",
  "ar": "مموّج",
  "hi": "लहरदार",
  "zh": "微卷",
  "ja": "ゆるウェーブ"
 },
 "Topuz (Man Bun)": {
  "en": "Man Bun",
  "de": "Man Bun",
  "ru": "Пучок (мужской)",
  "uk": "Пучок (чоловічий)",
  "es": "Moño masculino",
  "fr": "Chignon homme",
  "it": "Chignon (Man Bun)",
  "pt": "Coque (Man Bun)",
  "ar": "كعكة رجالية",
  "hi": "मैन बन",
  "zh": "男士发髻",
  "ja": "メンズお団子"
 },
 "Klasik Kesim": {
  "en": "Classic Cut",
  "de": "Klassischer Schnitt",
  "ru": "Классическая стрижка",
  "uk": "Класична стрижка",
  "es": "Corte clásico",
  "fr": "Coupe classique",
  "it": "Taglio classico",
  "pt": "Corte clássico",
  "ar": "قصّة كلاسيكية",
  "hi": "क्लासिक कट",
  "zh": "经典剪",
  "ja": "クラシックカット"
 },
 "Yandan Ayrık": {
  "en": "Side Part",
  "de": "Seitenscheitel",
  "ru": "Пробор сбоку",
  "uk": "Проділ збоку",
  "es": "Raya al lado",
  "fr": "Raie sur le côté",
  "it": "Riga laterale",
  "pt": "Risca lateral",
  "ar": "فرق جانبي",
  "hi": "साइड पार्टिंग",
  "zh": "侧分",
  "ja": "サイドパート"
 },
 "Asker Tıraşı": {
  "en": "Buzz Cut",
  "de": "Kurzhaarschnitt",
  "ru": "Армейская стрижка",
  "uk": "Армійська стрижка",
  "es": "Corte militar",
  "fr": "Coupe militaire",
  "it": "Taglio militare",
  "pt": "Corte militar",
  "ar": "حلاقة عسكرية",
  "hi": "आर्मी कट",
  "zh": "寸头",
  "ja": "坊主"
 },
 "Sakal Şekli": {
  "en": "Beard Shape",
  "de": "Bartform",
  "ru": "Форма бороды",
  "uk": "Форма бороди",
  "es": "Forma de barba",
  "fr": "Forme de barbe",
  "it": "Forma barba",
  "pt": "Formato da barba",
  "ar": "تشكيل اللحية",
  "hi": "दाढ़ी शेप",
  "zh": "胡型",
  "ja": "ひげの形"
 },
 "Uzun Sakal": {
  "en": "Long Beard",
  "de": "Langer Bart",
  "ru": "Длинная борода",
  "uk": "Довга борода",
  "es": "Barba larga",
  "fr": "Barbe longue",
  "it": "Barba lunga",
  "pt": "Barba longa",
  "ar": "لحية طويلة",
  "hi": "लंबी दाढ़ी",
  "zh": "长胡子",
  "ja": "長いひげ"
 },
 "Kirli Sakal": {
  "en": "Stubble",
  "de": "Drei-Tage-Bart",
  "ru": "Щетина",
  "uk": "Щетина",
  "es": "Barba de tres días",
  "fr": "Barbe de trois jours",
  "it": "Barba incolta",
  "pt": "Barba por fazer",
  "ar": "لحية خفيفة",
  "hi": "हल्की दाढ़ी",
  "zh": "胡渣",
  "ja": "無精ひげ"
 },
 "Keçi Sakal": {
  "en": "Goatee",
  "de": "Kinnbart",
  "ru": "Бородка эспаньолка",
  "uk": "Борідка еспаньйолка",
  "es": "Perilla",
  "fr": "Bouc",
  "it": "Pizzetto",
  "pt": "Cavanhaque",
  "ar": "لحية الماعز",
  "hi": "बकरा दाढ़ी",
  "zh": "山羊胡",
  "ja": "やぎひげ"
 },
 "Kısa Kesim": {
  "en": "Short Cut",
  "de": "Kurzer Schnitt",
  "ru": "Короткая стрижка",
  "uk": "Коротка стрижка",
  "es": "Corte corto",
  "fr": "Coupe courte",
  "it": "Taglio corto",
  "pt": "Corte curto",
  "ar": "قصّة قصيرة",
  "hi": "छोटा कट",
  "zh": "短发",
  "ja": "ショートカット"
 },
 "Dalgalı": {
  "en": "Wavy",
  "de": "Gewellt",
  "ru": "Волнистые",
  "uk": "Хвилясте",
  "es": "Ondulado",
  "fr": "Ondulé",
  "it": "Mossi",
  "pt": "Ondulado",
  "ar": "مموّج",
  "hi": "लहरदार",
  "zh": "波浪",
  "ja": "ウェーブ"
 },
 "Renkli Toka": {
  "en": "Colorful Clip",
  "de": "Bunte Spange",
  "ru": "Цветная заколка",
  "uk": "Кольорова заколка",
  "es": "Pinza de color",
  "fr": "Barrette colorée",
  "it": "Fermaglio colorato",
  "pt": "Presilha colorida",
  "ar": "مشبك ملوّن",
  "hi": "रंगीन क्लिप",
  "zh": "彩色发夹",
  "ja": "カラーヘアピン"
 },
 "İki Örgü": {
  "en": "Two Braids",
  "de": "Zwei Zöpfe",
  "ru": "Две косички",
  "uk": "Дві косички",
  "es": "Dos trenzas",
  "fr": "Deux tresses",
  "it": "Due trecce",
  "pt": "Duas tranças",
  "ar": "ضفيرتان",
  "hi": "दो चोटी",
  "zh": "双辫",
  "ja": "ツインおさげ"
 },
 "Kirpi Model": {
  "en": "Spiky Style",
  "de": "Stachelfrisur",
  "ru": "Ёжик",
  "uk": "Їжачок",
  "es": "Estilo púas",
  "fr": "Coupe en pics",
  "it": "Effetto spettinato",
  "pt": "Estilo espetado",
  "ar": "قصّة القنفذ",
  "hi": "स्पाइक कट",
  "zh": "刺猬头",
  "ja": "ツンツンヘア"
 },
 "Yumuşak Kesim": {
  "en": "Soft Cut",
  "de": "Weicher Schnitt",
  "ru": "Мягкая стрижка",
  "uk": "М'яка стрижка",
  "es": "Corte suave",
  "fr": "Coupe douce",
  "it": "Taglio morbido",
  "pt": "Corte suave",
  "ar": "قصّة ناعمة",
  "hi": "मुलायम कट",
  "zh": "柔和剪",
  "ja": "ソフトカット"
 },
 "Kısa Bebek Kesimi": {
  "en": "Short Baby Cut",
  "de": "Kurzer Babyschnitt",
  "ru": "Короткая детская стрижка",
  "uk": "Коротка дитяча стрижка",
  "es": "Corte corto de bebé",
  "fr": "Coupe courte bébé",
  "it": "Taglio corto da bimbo",
  "pt": "Corte curto infantil",
  "ar": "قصّة أطفال قصيرة",
  "hi": "छोटा शिशु कट",
  "zh": "婴儿短发",
  "ja": "ベビーショート"
 },
 "İlk Tıraş": {
  "en": "First Haircut",
  "de": "Erster Haarschnitt",
  "ru": "Первая стрижка",
  "uk": "Перша стрижка",
  "es": "Primer corte",
  "fr": "Première coupe",
  "it": "Primo taglio",
  "pt": "Primeiro corte",
  "ar": "أول حلاقة",
  "hi": "पहली हजामत",
  "zh": "初剪",
  "ja": "初カット"
 },
 "Siyah": {
  "en": "Black",
  "de": "Schwarz",
  "ru": "Чёрный",
  "uk": "Чорний",
  "es": "Negro",
  "fr": "Noir",
  "it": "Nero",
  "pt": "Preto",
  "ar": "أسود",
  "hi": "काला",
  "zh": "黑色",
  "ja": "ブラック"
 },
 "Koyu Kahve": {
  "en": "Dark Brown",
  "de": "Dunkelbraun",
  "ru": "Тёмно-коричневый",
  "uk": "Темно-коричневий",
  "es": "Castaño oscuro",
  "fr": "Châtain foncé",
  "it": "Castano scuro",
  "pt": "Castanho escuro",
  "ar": "بنّي غامق",
  "hi": "गहरा भूरा",
  "zh": "深棕",
  "ja": "ダークブラウン"
 },
 "Kahve": {
  "en": "Brown",
  "de": "Braun",
  "ru": "Коричневый",
  "uk": "Коричневий",
  "es": "Castaño",
  "fr": "Châtain",
  "it": "Castano",
  "pt": "Castanho",
  "ar": "بنّي",
  "hi": "भूरा",
  "zh": "棕色",
  "ja": "ブラウン"
 },
 "Kumral": {
  "en": "Light Brown",
  "de": "Hellbraun",
  "ru": "Русый",
  "uk": "Русявий",
  "es": "Castaño claro",
  "fr": "Châtain clair",
  "it": "Biondo scuro",
  "pt": "Castanho claro",
  "ar": "كستنائي",
  "hi": "हल्का भूरा",
  "zh": "浅棕",
  "ja": "ライトブラウン"
 },
 "Sarı": {
  "en": "Blonde",
  "de": "Blond",
  "ru": "Блонд",
  "uk": "Блонд",
  "es": "Rubio",
  "fr": "Blond",
  "it": "Biondo",
  "pt": "Loiro",
  "ar": "أشقر",
  "hi": "सुनहरा",
  "zh": "金色",
  "ja": "ブロンド"
 },
 "Bal Köpüğü": {
  "en": "Honey Blonde",
  "de": "Honigblond",
  "ru": "Медовый блонд",
  "uk": "Медовий блонд",
  "es": "Rubio miel",
  "fr": "Blond miel",
  "it": "Biondo miele",
  "pt": "Loiro mel",
  "ar": "أشقر عسلي",
  "hi": "शहद सुनहरा",
  "zh": "蜜金",
  "ja": "ハニーブロンド"
 },
 "Kızıl": {
  "en": "Red",
  "de": "Rot",
  "ru": "Рыжий",
  "uk": "Рудий",
  "es": "Pelirrojo",
  "fr": "Roux",
  "it": "Rosso ramato",
  "pt": "Ruivo",
  "ar": "أحمر شعر",
  "hi": "लाल-भूरा",
  "zh": "红棕",
  "ja": "レッドブラウン"
 },
 "Bakır": {
  "en": "Copper",
  "de": "Kupfer",
  "ru": "Медный",
  "uk": "Мідний",
  "es": "Cobre",
  "fr": "Cuivré",
  "it": "Rame",
  "pt": "Acobreado",
  "ar": "نحاسي",
  "hi": "तांबई",
  "zh": "铜色",
  "ja": "カッパー"
 },
 "Platin Sarı": {
  "en": "Platinum Blonde",
  "de": "Platinblond",
  "ru": "Платиновый блонд",
  "uk": "Платиновий блонд",
  "es": "Rubio platino",
  "fr": "Blond platine",
  "it": "Biondo platino",
  "pt": "Loiro platinado",
  "ar": "أشقر بلاتيني",
  "hi": "प्लैटिनम सुनहरा",
  "zh": "铂金",
  "ja": "プラチナブロンド"
 },
 "Gri / Gümüş": {
  "en": "Gray / Silver",
  "de": "Grau / Silber",
  "ru": "Серый / Серебристый",
  "uk": "Сірий / Сріблястий",
  "es": "Gris / plata",
  "fr": "Gris / argent",
  "it": "Grigio / Argento",
  "pt": "Cinza / Prata",
  "ar": "رمادي / فضي",
  "hi": "ग्रे / सिल्वर",
  "zh": "灰 / 银",
  "ja": "グレー / シルバー"
 },
 "Mavi": {
  "en": "Blue",
  "de": "Blau",
  "ru": "Синий",
  "uk": "Синій",
  "es": "Azul",
  "fr": "Bleu",
  "it": "Blu",
  "pt": "Azul",
  "ar": "أزرق",
  "hi": "नीला",
  "zh": "蓝色",
  "ja": "ブルー"
 },
 "Pembe": {
  "en": "Pink",
  "de": "Rosa",
  "ru": "Розовый",
  "uk": "Рожевий",
  "es": "Rosa",
  "fr": "Rose",
  "it": "Rosa",
  "pt": "Rosa",
  "ar": "وردي",
  "hi": "गुलाबी",
  "zh": "粉色",
  "ja": "ピンク"
 },
 "Beyaz": {
  "en": "White",
  "de": "Weiß",
  "ru": "Белый",
  "uk": "Білий",
  "es": "Blanco",
  "fr": "Blanc",
  "it": "Bianco",
  "pt": "Branco",
  "ar": "أبيض",
  "hi": "सफेद",
  "zh": "白色",
  "ja": "ホワイト"
 },
 "Kırmızı": {
  "en": "Red",
  "de": "Rot",
  "ru": "Красный",
  "uk": "Червоний",
  "es": "Rojo",
  "fr": "Rouge",
  "it": "Rosso",
  "pt": "Vermelho",
  "ar": "أحمر",
  "hi": "लाल",
  "zh": "红色",
  "ja": "レッド"
 },
 "Lacivert": {
  "en": "Navy",
  "de": "Marineblau",
  "ru": "Тёмно-синий",
  "uk": "Темно-синій",
  "es": "Azul marino",
  "fr": "Bleu marine",
  "it": "Blu scuro",
  "pt": "Azul-marinho",
  "ar": "كحلي",
  "hi": "गहरा नीला",
  "zh": "藏青",
  "ja": "ネイビー"
 },
 "Yeşil": {
  "en": "Green",
  "de": "Grün",
  "ru": "Зелёный",
  "uk": "Зелений",
  "es": "Verde",
  "fr": "Vert",
  "it": "Verde",
  "pt": "Verde",
  "ar": "أخضر",
  "hi": "हरा",
  "zh": "绿色",
  "ja": "グリーン"
 },
 "Mor": {
  "en": "Purple",
  "de": "Lila",
  "ru": "Фиолетовый",
  "uk": "Фіолетовий",
  "es": "Morado",
  "fr": "Violet",
  "it": "Viola",
  "pt": "Roxo",
  "ar": "بنفسجي",
  "hi": "बैंगनी",
  "zh": "紫色",
  "ja": "パープル"
 },
 "Turuncu": {
  "en": "Orange",
  "de": "Orange",
  "ru": "Оранжевый",
  "uk": "Помаранчевий",
  "es": "Naranja",
  "fr": "Orange",
  "it": "Arancione",
  "pt": "Laranja",
  "ar": "برتقالي",
  "hi": "नारंगी",
  "zh": "橙色",
  "ja": "オレンジ"
 },
 "Bej": {
  "en": "Beige",
  "de": "Beige",
  "ru": "Бежевый",
  "uk": "Бежевий",
  "es": "Beige",
  "fr": "Beige",
  "it": "Beige",
  "pt": "Bege",
  "ar": "بيج",
  "hi": "बेज",
  "zh": "米色",
  "ja": "ベージュ"
 },
 "Gri": {
  "en": "Gray",
  "de": "Grau",
  "ru": "Серый",
  "uk": "Сірий",
  "es": "Gris",
  "fr": "Gris",
  "it": "Grigio",
  "pt": "Cinza",
  "ar": "رمادي",
  "hi": "ग्रे",
  "zh": "灰色",
  "ja": "グレー"
 },
 "Altın": {
  "en": "Gold",
  "de": "Gold",
  "ru": "Золотой",
  "uk": "Золотий",
  "es": "Dorado",
  "fr": "Doré",
  "it": "Oro",
  "pt": "Dourado",
  "ar": "ذهبي",
  "hi": "सुनहरा",
  "zh": "金色",
  "ja": "ゴールド"
 },
 "Gümüş": {
  "en": "Silver",
  "de": "Silber",
  "ru": "Серебряный",
  "uk": "Срібний",
  "es": "Plateado",
  "fr": "Argenté",
  "it": "Argento",
  "pt": "Prata",
  "ar": "فضي",
  "hi": "सिल्वर",
  "zh": "银色",
  "ja": "シルバー"
 },
 "Abiye Elbise": {
  "en": "Evening Gown",
  "de": "Abendkleid",
  "ru": "Вечернее платье",
  "uk": "Вечірня сукня",
  "es": "Vestido de gala",
  "fr": "Robe de soirée",
  "it": "Abito da sera",
  "pt": "Vestido de festa",
  "ar": "فستان سهرة",
  "hi": "शाम की पोशाक",
  "zh": "晚礼服",
  "ja": "イブニングドレス"
 },
 "Yazlık Elbise": {
  "en": "Summer Dress",
  "de": "Sommerkleid",
  "ru": "Летнее платье",
  "uk": "Літня сукня",
  "es": "Vestido de verano",
  "fr": "Robe d'été",
  "it": "Abito estivo",
  "pt": "Vestido de verão",
  "ar": "فستان صيفي",
  "hi": "गर्मी की पोशाक",
  "zh": "夏季连衣裙",
  "ja": "サマードレス"
 },
 "Takım": {
  "en": "Suit",
  "de": "Anzug",
  "ru": "Костюм",
  "uk": "Костюм",
  "es": "Conjunto",
  "fr": "Ensemble",
  "it": "Completo",
  "pt": "Conjunto",
  "ar": "طقم",
  "hi": "सेट",
  "zh": "套装",
  "ja": "セットアップ"
 },
 "Kot & Bluz": {
  "en": "Jeans & Blouse",
  "de": "Jeans & Bluse",
  "ru": "Джинсы и блузка",
  "uk": "Джинси та блузка",
  "es": "Vaqueros y blusa",
  "fr": "Jean et chemisier",
  "it": "Jeans e camicetta",
  "pt": "Jeans e blusa",
  "ar": "جينز وبلوزة",
  "hi": "जीन्स और ब्लाउज़",
  "zh": "牛仔&上衣",
  "ja": "デニム＆ブラウス"
 },
 "Kışlık Mont": {
  "en": "Winter Coat",
  "de": "Wintermantel",
  "ru": "Зимняя куртка",
  "uk": "Зимова куртка",
  "es": "Abrigo de invierno",
  "fr": "Manteau d'hiver",
  "it": "Giubbotto invernale",
  "pt": "Casaco de inverno",
  "ar": "معطف شتوي",
  "hi": "सर्दी का कोट",
  "zh": "冬季外套",
  "ja": "冬用コート"
 },
 "Takım Elbise": {
  "en": "Suit",
  "de": "Anzug",
  "ru": "Деловой костюм",
  "uk": "Діловий костюм",
  "es": "Traje",
  "fr": "Costume",
  "it": "Completo elegante",
  "pt": "Terno",
  "ar": "بدلة",
  "hi": "सूट",
  "zh": "西装",
  "ja": "スーツ"
 },
 "Gömlek": {
  "en": "Shirt",
  "de": "Hemd",
  "ru": "Рубашка",
  "uk": "Сорочка",
  "es": "Camisa",
  "fr": "Chemise",
  "it": "Camicia",
  "pt": "Camisa",
  "ar": "قميص",
  "hi": "शर्ट",
  "zh": "衬衫",
  "ja": "シャツ"
 },
 "Ceket": {
  "en": "Jacket",
  "de": "Jacke",
  "ru": "Пиджак",
  "uk": "Піджак",
  "es": "Chaqueta",
  "fr": "Veste",
  "it": "Giacca",
  "pt": "Jaqueta",
  "ar": "جاكيت",
  "hi": "जैकेट",
  "zh": "夹克",
  "ja": "ジャケット"
 },
 "Kot Pantolon": {
  "en": "Jeans",
  "de": "Jeans",
  "ru": "Джинсы",
  "uk": "Джинси",
  "es": "Pantalón vaquero",
  "fr": "Jean",
  "it": "Jeans",
  "pt": "Calça jeans",
  "ar": "بنطال جينز",
  "hi": "जीन्स",
  "zh": "牛仔裤",
  "ja": "ジーンズ"
 },
 "Spor Giyim": {
  "en": "Sportswear",
  "de": "Sportbekleidung",
  "ru": "Спортивная одежда",
  "uk": "Спортивний одяг",
  "es": "Ropa deportiva",
  "fr": "Vêtements de sport",
  "it": "Abbigliamento sportivo",
  "pt": "Roupa esportiva",
  "ar": "ملابس رياضية",
  "hi": "स्पोर्ट्सवियर",
  "zh": "运动装",
  "ja": "スポーツウェア"
 },
 "Prenses Elbise": {
  "en": "Princess Dress",
  "de": "Prinzessinnenkleid",
  "ru": "Платье принцессы",
  "uk": "Сукня принцеси",
  "es": "Vestido de princesa",
  "fr": "Robe de princesse",
  "it": "Abito da principessa",
  "pt": "Vestido de princesa",
  "ar": "فستان أميرة",
  "hi": "राजकुमारी पोशाक",
  "zh": "公主裙",
  "ja": "プリンセスドレス"
 },
 "Etek & Bluz": {
  "en": "Skirt & Blouse",
  "de": "Rock & Bluse",
  "ru": "Юбка и блузка",
  "uk": "Спідниця та блузка",
  "es": "Falda y blusa",
  "fr": "Jupe et chemisier",
  "it": "Gonna e camicetta",
  "pt": "Saia e blusa",
  "ar": "تنورة وبلوزة",
  "hi": "स्कर्ट और ब्लाउज़",
  "zh": "半裙&上衣",
  "ja": "スカート＆ブラウス"
 },
 "Tulum": {
  "en": "Jumpsuit",
  "de": "Overall",
  "ru": "Комбинезон",
  "uk": "Комбінезон",
  "es": "Mono",
  "fr": "Combinaison",
  "it": "Tuta",
  "pt": "Macacão",
  "ar": "أفرول",
  "hi": "जंपसूट",
  "zh": "连体裤",
  "ja": "オールインワン"
 },
 "Şort & Tişört": {
  "en": "Shorts & T-Shirt",
  "de": "Shorts & T-Shirt",
  "ru": "Шорты и футболка",
  "uk": "Шорти та футболка",
  "es": "Short y camiseta",
  "fr": "Short et t-shirt",
  "it": "Shorts e t-shirt",
  "pt": "Shorts e camiseta",
  "ar": "شورت وتيشيرت",
  "hi": "शॉर्ट्स और टी-शर्ट",
  "zh": "短裤&T恤",
  "ja": "ショートパンツ＆Tシャツ"
 },
 "Bebek Tulumu": {
  "en": "Baby Onesie",
  "de": "Babystrampler",
  "ru": "Детский комбинезон",
  "uk": "Дитячий комбінезон",
  "es": "Pelele de bebé",
  "fr": "Grenouillère bébé",
  "it": "Tutina per neonato",
  "pt": "Macacão de bebê",
  "ar": "أفرول أطفال",
  "hi": "शिशु जंपसूट",
  "zh": "婴儿连体衣",
  "ja": "ベビーロンパース"
 },
 "Bebek Elbisesi": {
  "en": "Baby Dress",
  "de": "Babykleid",
  "ru": "Детское платье",
  "uk": "Дитяча сукня",
  "es": "Vestido de bebé",
  "fr": "Robe de bébé",
  "it": "Vestitino per neonata",
  "pt": "Vestido de bebê",
  "ar": "فستان أطفال",
  "hi": "शिशु पोशाक",
  "zh": "婴儿连衣裙",
  "ja": "ベビードレス"
 },
 "Body Zıbın": {
  "en": "Baby Bodysuit",
  "de": "Babybody",
  "ru": "Боди-распашонка",
  "uk": "Боді-повзунок",
  "es": "Body de bebé",
  "fr": "Body de bébé",
  "it": "Body neonato",
  "pt": "Body de bebê",
  "ar": "بادي أطفال",
  "hi": "बेबी बॉडीसूट",
  "zh": "婴儿包屁衣",
  "ja": "ベビー肌着"
 },
 "Kışlık Tulum": {
  "en": "Winter Snowsuit",
  "de": "Winter-Schneeanzug",
  "ru": "Зимний комбинезон",
  "uk": "Зимовий комбінезон",
  "es": "Buzo de invierno",
  "fr": "Combinaison d'hiver",
  "it": "Tuta invernale",
  "pt": "Macacão de inverno",
  "ar": "أفرول شتوي",
  "hi": "सर्दी का जंपसूट",
  "zh": "冬季连体衣",
  "ja": "冬用ロンパース"
 },
 "Doğal Makyaj": {
  "en": "Natural Makeup",
  "de": "Natürliches Make-up",
  "ru": "Естественный макияж",
  "uk": "Природний макіяж",
  "es": "Maquillaje natural",
  "fr": "Maquillage naturel",
  "it": "Trucco naturale",
  "pt": "Maquiagem natural",
  "ar": "مكياج طبيعي",
  "hi": "नैचुरल मेकअप",
  "zh": "自然妆",
  "ja": "ナチュラルメイク"
 },
 "Smokey Göz": {
  "en": "Smoky Eye",
  "de": "Smokey Eyes",
  "ru": "Смоки айс",
  "uk": "Смокі айс",
  "es": "Ojos ahumados",
  "fr": "Yeux charbonneux",
  "it": "Occhi smokey",
  "pt": "Olho esfumado",
  "ar": "عيون سموكي",
  "hi": "स्मोकी आंखें",
  "zh": "烟熏眼",
  "ja": "スモーキーアイ"
 },
 "Gündüz Makyajı": {
  "en": "Daytime Makeup",
  "de": "Tages-Make-up",
  "ru": "Дневной макияж",
  "uk": "Денний макіяж",
  "es": "Maquillaje de día",
  "fr": "Maquillage de jour",
  "it": "Trucco da giorno",
  "pt": "Maquiagem de dia",
  "ar": "مكياج نهاري",
  "hi": "दिन का मेकअप",
  "zh": "日常妆",
  "ja": "デイメイク"
 },
 "Gece Makyajı": {
  "en": "Evening Makeup",
  "de": "Abend-Make-up",
  "ru": "Вечерний макияж",
  "uk": "Вечірній макіяж",
  "es": "Maquillaje de noche",
  "fr": "Maquillage de soirée",
  "it": "Trucco da sera",
  "pt": "Maquiagem de noite",
  "ar": "مكياج سهرة",
  "hi": "रात का मेकअप",
  "zh": "晚妆",
  "ja": "ナイトメイク"
 },
 "Gelin Makyajı": {
  "en": "Bridal Makeup",
  "de": "Braut-Make-up",
  "ru": "Свадебный макияж",
  "uk": "Весільний макіяж",
  "es": "Maquillaje de novia",
  "fr": "Maquillage de mariée",
  "it": "Trucco da sposa",
  "pt": "Maquiagem de noiva",
  "ar": "مكياج عروس",
  "hi": "दुल्हन मेकअप",
  "zh": "新娘妆",
  "ja": "ブライダルメイク"
 },
 "Işıltılı Ten": {
  "en": "Glowy Skin",
  "de": "Strahlender Teint",
  "ru": "Сияющая кожа",
  "uk": "Сяюча шкіра",
  "es": "Piel radiante",
  "fr": "Teint lumineux",
  "it": "Pelle luminosa",
  "pt": "Pele iluminada",
  "ar": "بشرة متوهّجة",
  "hi": "चमकती त्वचा",
  "zh": "光泽肌",
  "ja": "ツヤ肌"
 },
 "Fransız Tırnak": {
  "en": "French Nails",
  "de": "French Nails",
  "ru": "Французский маникюр",
  "uk": "Французький манікюр",
  "es": "Uñas francesas",
  "fr": "French manucure",
  "it": "French manicure",
  "pt": "Unha francesinha",
  "ar": "أظافر فرنسية",
  "hi": "फ्रेंच नाखून",
  "zh": "法式美甲",
  "ja": "フレンチネイル"
 },
 "Ombre Tırnak": {
  "en": "Ombré Nails",
  "de": "Ombré Nägel",
  "ru": "Омбре на ногтях",
  "uk": "Омбре на нігтях",
  "es": "Uñas ombré",
  "fr": "Ongles ombré",
  "it": "Unghie ombré",
  "pt": "Unha ombré",
  "ar": "أظافر أومبريه",
  "hi": "ओम्ब्रे नाखून",
  "zh": "渐变美甲",
  "ja": "オンブレネイル"
 },
 "Kırmızı Oje": {
  "en": "Red Polish",
  "de": "Roter Nagellack",
  "ru": "Красный лак",
  "uk": "Червоний лак",
  "es": "Esmalte rojo",
  "fr": "Vernis rouge",
  "it": "Smalto rosso",
  "pt": "Esmalte vermelho",
  "ar": "طلاء أحمر",
  "hi": "लाल नेल पॉलिश",
  "zh": "红色指甲油",
  "ja": "赤ネイル"
 },
 "Nude Ton": {
  "en": "Nude Tone",
  "de": "Nude-Ton",
  "ru": "Нюдовый тон",
  "uk": "Нюдовий тон",
  "es": "Tono nude",
  "fr": "Ton nude",
  "it": "Tono nude",
  "pt": "Tom nude",
  "ar": "درجة نود",
  "hi": "न्यूड शेड",
  "zh": "裸色调",
  "ja": "ヌードカラー"
 },
 "Gliter": {
  "en": "Glitter",
  "de": "Glitzer",
  "ru": "Глиттер",
  "uk": "Глітер",
  "es": "Glitter",
  "fr": "Paillettes",
  "it": "Glitter",
  "pt": "Glitter",
  "ar": "غليتر",
  "hi": "ग्लिटर",
  "zh": "闪粉",
  "ja": "グリッター"
 },
 "Kedi Gözü": {
  "en": "Cat Eye",
  "de": "Cat Eye",
  "ru": "Кошачий глаз",
  "uk": "Котяче око",
  "es": "Ojo de gato",
  "fr": "Œil de chat",
  "it": "Cat eye",
  "pt": "Cat eye",
  "ar": "عين القطة",
  "hi": "कैट आई",
  "zh": "猫眼",
  "ja": "キャッツアイ"
 },
 "Mat Siyah": {
  "en": "Matte Black",
  "de": "Mattschwarz",
  "ru": "Матовый чёрный",
  "uk": "Матовий чорний",
  "es": "Negro mate",
  "fr": "Noir mat",
  "it": "Nero opaco",
  "pt": "Preto fosco",
  "ar": "أسود مطفي",
  "hi": "मैट काला",
  "zh": "哑光黑",
  "ja": "マットブラック"
 },
 "Çiçek Desen": {
  "en": "Floral Design",
  "de": "Blumenmuster",
  "ru": "Цветочный узор",
  "uk": "Квітковий візерунок",
  "es": "Estampado floral",
  "fr": "Motif fleuri",
  "it": "Motivo floreale",
  "pt": "Estampa floral",
  "ar": "نقش زهور",
  "hi": "फूल डिज़ाइन",
  "zh": "花朵图案",
  "ja": "花柄"
 },
 "Spor Ayakkabı": {
  "en": "Sneakers",
  "de": "Sneaker",
  "ru": "Кроссовки",
  "uk": "Кросівки",
  "es": "Zapatillas deportivas",
  "fr": "Baskets",
  "it": "Scarpe da ginnastica",
  "pt": "Tênis",
  "ar": "حذاء رياضي",
  "hi": "स्पोर्ट्स जूते",
  "zh": "运动鞋",
  "ja": "スニーカー"
 },
 "Klasik Ayakkabı": {
  "en": "Dress Shoes",
  "de": "Anzugschuhe",
  "ru": "Классические туфли",
  "uk": "Класичні туфлі",
  "es": "Zapatos clásicos",
  "fr": "Chaussures classiques",
  "it": "Scarpe classiche",
  "pt": "Sapato clássico",
  "ar": "حذاء كلاسيكي",
  "hi": "क्लासिक जूते",
  "zh": "经典皮鞋",
  "ja": "革靴"
 },
 "Topuklu": {
  "en": "Heels",
  "de": "High Heels",
  "ru": "Каблуки",
  "uk": "Підбори",
  "es": "Tacones",
  "fr": "Talons",
  "it": "Tacchi",
  "pt": "Salto alto",
  "ar": "كعب عالٍ",
  "hi": "हील",
  "zh": "高跟鞋",
  "ja": "ハイヒール"
 },
 "Bot": {
  "en": "Boots",
  "de": "Stiefel",
  "ru": "Ботинки",
  "uk": "Черевики",
  "es": "Botas",
  "fr": "Bottes",
  "it": "Stivali",
  "pt": "Bota",
  "ar": "بوت",
  "hi": "बूट",
  "zh": "靴子",
  "ja": "ブーツ"
 },
 "Sandalet": {
  "en": "Sandals",
  "de": "Sandalen",
  "ru": "Сандалии",
  "uk": "Сандалі",
  "es": "Sandalias",
  "fr": "Sandales",
  "it": "Sandali",
  "pt": "Sandália",
  "ar": "صندل",
  "hi": "सैंडल",
  "zh": "凉鞋",
  "ja": "サンダル"
 },
 "Loafer": {
  "en": "Loafers",
  "de": "Loafer",
  "ru": "Лоферы",
  "uk": "Лофери",
  "es": "Mocasines",
  "fr": "Mocassins",
  "it": "Mocassini",
  "pt": "Mocassim",
  "ar": "لوفر",
  "hi": "लोफर",
  "zh": "乐福鞋",
  "ja": "ローファー"
 },
 "El Çantası": {
  "en": "Handbag",
  "de": "Handtasche",
  "ru": "Сумочка",
  "uk": "Сумочка",
  "es": "Bolso de mano",
  "fr": "Sac à main",
  "it": "Borsetta",
  "pt": "Bolsa de mão",
  "ar": "حقيبة يد",
  "hi": "हैंडबैग",
  "zh": "手提包",
  "ja": "ハンドバッグ"
 },
 "Sırt Çantası": {
  "en": "Backpack",
  "de": "Rucksack",
  "ru": "Рюкзак",
  "uk": "Рюкзак",
  "es": "Mochila",
  "fr": "Sac à dos",
  "it": "Zaino",
  "pt": "Mochila",
  "ar": "حقيبة ظهر",
  "hi": "बैकपैक",
  "zh": "背包",
  "ja": "リュック"
 },
 "Omuz Çantası": {
  "en": "Shoulder Bag",
  "de": "Umhängetasche",
  "ru": "Сумка через плечо",
  "uk": "Сумка через плече",
  "es": "Bolso de hombro",
  "fr": "Sac à bandoulière",
  "it": "Borsa a tracolla",
  "pt": "Bolsa de ombro",
  "ar": "حقيبة كتف",
  "hi": "शोल्डर बैग",
  "zh": "单肩包",
  "ja": "ショルダーバッグ"
 },
 "Cüzdan": {
  "en": "Wallet",
  "de": "Geldbörse",
  "ru": "Кошелёк",
  "uk": "Гаманець",
  "es": "Cartera",
  "fr": "Portefeuille",
  "it": "Portafoglio",
  "pt": "Carteira",
  "ar": "محفظة",
  "hi": "बटुआ",
  "zh": "钱包",
  "ja": "財布"
 },
 "Spor Çanta": {
  "en": "Gym Bag",
  "de": "Sporttasche",
  "ru": "Спортивная сумка",
  "uk": "Спортивна сумка",
  "es": "Bolsa deportiva",
  "fr": "Sac de sport",
  "it": "Borsa sportiva",
  "pt": "Bolsa esportiva",
  "ar": "حقيبة رياضية",
  "hi": "स्पोर्ट्स बैग",
  "zh": "运动包",
  "ja": "スポーツバッグ"
 },
 "Kolye": {
  "en": "Necklace",
  "de": "Halskette",
  "ru": "Ожерелье",
  "uk": "Намисто",
  "es": "Collar",
  "fr": "Collier",
  "it": "Collana",
  "pt": "Colar",
  "ar": "قلادة",
  "hi": "हार",
  "zh": "项链",
  "ja": "ネックレス"
 },
 "Küpe": {
  "en": "Earrings",
  "de": "Ohrringe",
  "ru": "Серьги",
  "uk": "Сережки",
  "es": "Pendientes",
  "fr": "Boucles d'oreilles",
  "it": "Orecchini",
  "pt": "Brinco",
  "ar": "أقراط",
  "hi": "बालियां",
  "zh": "耳环",
  "ja": "ピアス"
 },
 "Kol Saati": {
  "en": "Watch",
  "de": "Armbanduhr",
  "ru": "Наручные часы",
  "uk": "Наручний годинник",
  "es": "Reloj de pulsera",
  "fr": "Montre",
  "it": "Orologio da polso",
  "pt": "Relógio de pulso",
  "ar": "ساعة يد",
  "hi": "कलाई घड़ी",
  "zh": "手表",
  "ja": "腕時計"
 },
 "Güneş Gözlüğü": {
  "en": "Sunglasses",
  "de": "Sonnenbrille",
  "ru": "Солнцезащитные очки",
  "uk": "Сонцезахисні окуляри",
  "es": "Gafas de sol",
  "fr": "Lunettes de soleil",
  "it": "Occhiali da sole",
  "pt": "Óculos de sol",
  "ar": "نظارة شمسية",
  "hi": "धूप का चश्मा",
  "zh": "太阳镜",
  "ja": "サングラス"
 },
 "Şapka": {
  "en": "Hat",
  "de": "Hut",
  "ru": "Шляпа",
  "uk": "Капелюх",
  "es": "Sombrero",
  "fr": "Chapeau",
  "it": "Cappello",
  "pt": "Chapéu",
  "ar": "قبعة",
  "hi": "टोपी",
  "zh": "帽子",
  "ja": "帽子"
 },
 "Kravat": {
  "en": "Tie",
  "de": "Krawatte",
  "ru": "Галстук",
  "uk": "Краватка",
  "es": "Corbata",
  "fr": "Cravate",
  "it": "Cravatta",
  "pt": "Gravata",
  "ar": "ربطة عنق",
  "hi": "टाई",
  "zh": "领带",
  "ja": "ネクタイ"
 }
};
