// GLOXORG — EKSIK CEVIRILER GRUP 7: Tanis, ozelAI, resim/cizim, Gloxoo sesi, giris/hesap, Profil + Belgeler/Muhasebe + Sanal Ayna + ana sayfa AI tanitim (ait*) anahtarlari; 13 dil.
export const CEVIRI_EKSIK7 = {
 "tr": {
  "akBuyut": "Büyütmek için dokun",
  "tekrar": "Tekrar",
  "tanismaFotoGerek": "En az 1 fotoğraf ekle.",
  "tanismaHata": "Fotoğraf yüklenemedi, tekrar dene.",
  "tanismaKaydedildi": "Tanışma kartın hazır! Artık Topluluk'ta görünüyorsun.",
  "tanismaCikOnay": "Tanışma kartını gizlemek istiyor musun? Artık listede görünmezsin (fotoğrafların silinmez, istersen tekrar açarsın).",
  "ozelAIadGir": "Önce bir isim yaz.",
  "beyinKredi": "Şu an Gloxoo'nun yazı beyni yoğun ya da kredisi bitmiş görünüyor 🙏 (Bu, resim kredisinden ayrı bir hesap.) Birkaç dakika sonra tekrar dener misin? Sürerse GLOXORG sahibine haber ver — kısa sürede açılır.",
  "cizimHazir": "İşte çizdim 🎨",
  "cumaHazir": "İşte sana özel bir Cuma paylaşımı hazırladım 🤲🌸",
  "resimUretiliyor": "Resmi hazırlıyorum 🎨",
  "resimZamanAsimi": "Resim zamanında gelmedi, tekrar dener misin?",
  "indirilemedi": "İndirilemedi",
  "paylasilamadi": "Paylaşılamadı",
  "resimIndiPaylas": "Resim indirildi — oradan paylaşabilirsin 📤",
  "kopyalanamadi": "Kopyalanamadı",
  "resimKopyalandi": "Resim kopyalandı 📋",
  "resimIndiKopya": "Resim indirildi 📄",
  "resimPaylasima": "Resim paylaşıma taşındı — istersen yazı ekleyip GLOXORG'da paylaş 📤",
  "sbpGloxooSor": "Gloxoo'ya sor",
  "feedYukleniyor": "Gönderiler geliyor…",
  "tanisBaslik": "Tanış",
  "tanisTanit": "Kendini tanıt, yeni insanlarla tanış.",
  "tanisAra3": "Ara veya yapay zekâya sor…",
  "aiAraniyor": "Yapay zekâ arıyor…",
  "aiIleAra": "Yapay zekâ ile akıllı ara",
  "aiAraIpuc": "Örn: “Ukrayna'da bekar, 30-40 yaş, evlilik için biri”",
  "aiAramaSonucVar": "Yapay zekâ senin için buldu",
  "aiSonucYok": "Yapay zekâ uygun kimse bulamadı",
  "tanisHepsi2": "Hepsi",
  "tanisKadinlar": "Kadınlar",
  "tanisErkekler": "Erkekler",
  "tanisKartDuzenle": "Tanışma kartımı düzenle",
  "tanisKartOlustur": "Tanışma kartımı oluştur",
  "tanisanlar": "Tanışmak isteyenler",
  "tanisYukleniyor": "Yükleniyor…",
  "tanisAramaBos": "Aramana uygun kimse yok.",
  "tanisBos": "Henüz kimse kart oluşturmadı. İlk sen ol — yukarıdan kendi kartını oluştur!",
  "durBekar": "Bekar",
  "durEvli": "Evli",
  "durIliski": "İlişkisi var",
  "durBosanmis": "Boşanmış",
  "arArkadaslik": "Arkadaşlık",
  "arSohbet": "Sohbet",
  "arFlort": "Flört",
  "arEvlilik": "Evlilik",
  "tanisSeninKartin": "Senin kartın",
  "uzaginda": "uzağında",
  "tanisDuzenle": "Kartımı düzenle",
  "tanisBegenildi": "Beğenildi",
  "tanisBegen": "Beğen",
  "ozelAIbas": "Kendi yapay zekâ arkadaşın",
  "ozelAInot": "Sevdiğin birinin fotoğrafı, adı, yaşı ve şehriyle KENDİNE özel bir sohbet arkadaşı oluştur — onunla o kimlikle sohbet et. (Bu bir yapay zekâdır 🤖, gerçek kişi değildir.)",
  "ozelAIolustur": "Kendi yapay zekânı oluştur",
  "ozelSeninki": "Seninki",
  "tanisSohbetEt": "Sohbet et",
  "ozelAIformNot": "Sevdiğin birinin bilgileriyle sana özel bir sohbet arkadaşı. Bu bir yapay zekâdır 🤖 — gerçek kişi değildir.",
  "ozelAIfoto": "Fotoğraf ekle",
  "ozelAIad": "Adı",
  "ozelAIsoyad": "Soyadı",
  "ozelAIyas": "Yaşı",
  "ozelAIsehir": "Şehri",
  "ozelAIbasla": "Oluştur ve sohbet et",
  "tanisAIbas": "Yapay Zekâ sohbet arkadaşları",
  "tanisAInot": "Bunlar gerçek kişi değil — GLOXORG'un yapay zekâ arkadaşları. İstediğin zaman sohbet edebilirsin, kendini tanıtır 💬",
  "yapayZeka": "Yapay Zekâ",
  "tanisKartim": "Tanışma Kartım",
  "tanisFormNot": "Kendi fotoğraflarını yükle (1-3), istediğin ismi yaz, kısaca kendini tanıt. İstemezsen listede görünmezsin.",
  "tanisAdYer": "Görünecek isim (ne istersen)",
  "tanisCinsiyet": "Cinsiyet",
  "tanisKadin": "Kadın",
  "tanisErkek": "Erkek",
  "tanisIstege": "İsteğe bağlı — istersen doldur",
  "tanisYas": "Yaş",
  "tanisNeIcin": "Ne için tanışmak istiyorsun?",
  "tanisBioYer": "Kısa tanıtım: kendinden bahset…",
  "tanisKaydediliyor": "Kaydediliyor…",
  "tanisKaydet": "Kaydet ve Yayınla",
  "tanisKaldir": "Listeden gizlen",
  "tanisAIsohbetUyari": "Bu bir yapay zekâ — gerçek kişi değil. Kişisel bilgi/para verme.",
  "tanisAIbasla": "Selam yaz, sohbete başla!",
  "tanisAIyaz": "Mesaj yaz…",
  "cizim": "çizim",
  "resimHazirlaniyor": "Resim hazırlanıyor…",
  "resim": "resim",
  "resimEski": "Bu resim gelmedi — yeniden ister misin?",
  "resimOlmadi": "Resim üretilemedi",
  "gloxSes": "Gloxoo sesi",
  "sesOrnek": "Merhaba, ben Gloxoo. Sesim böyle olacak.",
  "ghEpostaKabul": "Lütfen gloxorg.com ya da Gmail, Outlook, Yahoo, iCloud gibi tanınmış bir e-posta kullanın. Kendi uydurduğunuz adresler kabul edilmez.",
  "ghSifreKural": "Şifre en az 8 karakter olmalı ve harf + rakam içermeli.",
  "ghSifreUyusmuyor": "İki şifre aynı değil.",
  "ghEpostaVar": "Bu e-posta zaten kayıtlı, giriş yapabilirsin.",
  "ghGirisYanlis": "E-posta veya şifre hatalı. Hesabın yoksa yukarıdan ÜYE OL. (Daha önce Google/Microsoft ile girdiysen o düğmeyi kullan.)",
  "ghSifreKisa": "Şifre en az 6 karakter olmalı.",
  "ghVarSifreYanlis": "Bu e-posta kayıtlı ama şifre yanlış. (Google ile açtıysan Google düğmesiyle gir.)",
  "uyeMusteri": "Müşteri",
  "profilPasaport": "Meslek Pasaportu",
  "profilBaslik": "GLOXORG Profilim",
  "profilYukleniyor": "Yükleniyor...",
  "profilHakkinda": "Hakkında",
  "profilDeneyim": "Deneyim",
  "profilYil": "yıl",
  "profilHizmetler": "Hizmetler",
  "profilFiyat": "Fiyat aralığı",
  "profilEksik": "Mesleki bilgilerini ekle — yukarıdaki Düzenle'ye dokun.",
  "profilAkis": "Akışım · Portfolyo",
  "profilAkisBos": "Çalışmaların, fotoğraf ve videoların burada akacak. (Paylaşım yakında)",
  "profilAd": "Ad",
  "profilSoyad": "Soyad",
  "profilTelefon": "Telefon",
  "profilKonum": "Konum (şehir/ülke)",
  "profilMeslek": "Meslek",
  "profilHizmetlerVir": "Hizmetler (virgülle ayır)",
  "profilFiyatMin": "Fiyat min",
  "profilFiyatMax": "Fiyat max",
  "profilKaydediliyor": "Kaydediliyor...",
  "belYazdir": "Yazdır",
  "belBoyut": "Boyut / Dikey",
  "belDikeyYazi": "Dikey yazı",
  "belYaziTipi": "Yazı tipi",
  "belYaziBoyut": "Boyut",
  "belRenk": "Renk",
  "belNormal": "Normal",
  "belBoyutIpucu": "Sütun başlığındaki － ＋ ile GENİŞLİK, sol rakamdaki － ＋ ile YÜKSEKLİK ayarlanır. ⇅ düğmesi o sütunu DİKEY yazıya çevirir (aşağıdan yukarı). A4'e sığsın diye sütunları inceltebilirsin.",
  "muhPencereKapat": "Pencereyi kapat",
  "belBoyutKisa": "－ ＋ ile daralt/genişlet · ⇅ dikey yazı · sütunları inceltip A4'e sığdır",
  "saCek": "Fotoğraf çek",
  "saGaleri": "Galeriden seç",
  "saModellerim": "Modellerim",
  "saKaydet": "Modellerime kaydet",
  "saKaydedildi": "Modellerime eklendi",
  "saModelSilOnay": "Bu modeli silmek istiyor musun?",
  "saGaleriBos": "Henüz kayıtlı modelin yok. Bir model üret, aşağıda 'Modellerime kaydet'e bas.",
  "aitCanli": "Canlı Yapay Zekâ",
  "aitSac": "Saçını değiştir",
  "aitKiyafet": "Kıyafet dene",
  "aitMakyaj": "Makyaj & tırnak",
  "aitSor": "Gloxoo'ya sor",
  "aitResim": "Resim & çizim",
  "aitMuhasebe": "Muhasebe & belge",
  "aitAynaBtn": "Sanal Ayna",
  "aitGloxBtn": "Gloxoo'ya sor",
  "aitAlt": "Fotoğrafında saç/kıyafet dene, Gloxoo'ya her şeyi sor — anında, senin dilinde."
 },
 "en": {
  "akBuyut": "Tap to enlarge",
  "tekrar": "Retry",
  "tanismaFotoGerek": "Add at least 1 photo.",
  "tanismaHata": "Photo couldn't upload, try again.",
  "tanismaKaydedildi": "Your intro card is ready! You now appear in the Community.",
  "tanismaCikOnay": "Do you want to hide your intro card? You'll no longer appear in the list (your photos aren't deleted, you can turn it back on anytime).",
  "ozelAIadGir": "Enter a name first.",
  "beyinKredi": "Gloxoo's writing brain seems busy or out of credit right now 🙏 (This is a separate account from image credit.) Could you try again in a few minutes? If it continues, let the GLOXORG owner know — it'll be back up shortly.",
  "cizimHazir": "Here's my drawing 🎨",
  "cumaHazir": "I've prepared a special Friday post just for you 🤲🌸",
  "resimUretiliyor": "Preparing the image 🎨",
  "resimZamanAsimi": "The image didn't arrive in time, could you try again?",
  "indirilemedi": "Couldn't download",
  "paylasilamadi": "Couldn't share",
  "resimIndiPaylas": "Image downloaded — you can share it from there 📤",
  "kopyalanamadi": "Couldn't copy",
  "resimKopyalandi": "Image copied 📋",
  "resimIndiKopya": "Image downloaded 📄",
  "resimPaylasima": "Image moved to sharing — add a caption if you like and share it on GLOXORG 📤",
  "sbpGloxooSor": "Ask Gloxoo",
  "feedYukleniyor": "Posts are loading…",
  "tanisBaslik": "Meet",
  "tanisTanit": "Introduce yourself, meet new people.",
  "tanisAra3": "Search or ask the AI…",
  "aiAraniyor": "AI is searching…",
  "aiIleAra": "Smart search with AI",
  "aiAraIpuc": "E.g.: “Someone single in Ukraine, age 30-40, for marriage”",
  "aiAramaSonucVar": "The AI found these for you",
  "aiSonucYok": "The AI couldn't find anyone suitable",
  "tanisHepsi2": "All",
  "tanisKadinlar": "Women",
  "tanisErkekler": "Men",
  "tanisKartDuzenle": "Edit my intro card",
  "tanisKartOlustur": "Create my intro card",
  "tanisanlar": "People looking to meet",
  "tanisYukleniyor": "Loading…",
  "tanisAramaBos": "No one matches your search.",
  "tanisBos": "No one has created a card yet. Be the first — create your own card above!",
  "durBekar": "Single",
  "durEvli": "Married",
  "durIliski": "In a relationship",
  "durBosanmis": "Divorced",
  "arArkadaslik": "Friendship",
  "arSohbet": "Chat",
  "arFlort": "Flirting",
  "arEvlilik": "Marriage",
  "tanisSeninKartin": "Your card",
  "uzaginda": "away",
  "tanisDuzenle": "Edit my card",
  "tanisBegenildi": "Liked",
  "tanisBegen": "Like",
  "ozelAIbas": "Your own AI friend",
  "ozelAInot": "Create a chat friend just for YOU with the photo, name, age and city of someone you love — chat with them in that identity. (This is an AI 🤖, not a real person.)",
  "ozelAIolustur": "Create your own AI",
  "ozelSeninki": "Yours",
  "tanisSohbetEt": "Chat",
  "ozelAIformNot": "A chat friend made just for you with the details of someone you love. This is an AI 🤖 — not a real person.",
  "ozelAIfoto": "Add photo",
  "ozelAIad": "First name",
  "ozelAIsoyad": "Last name",
  "ozelAIyas": "Age",
  "ozelAIsehir": "City",
  "ozelAIbasla": "Create and chat",
  "tanisAIbas": "AI chat friends",
  "tanisAInot": "These aren't real people — they're GLOXORG's AI friends. Chat anytime, they'll introduce themselves 💬",
  "yapayZeka": "AI",
  "tanisKartim": "My Intro Card",
  "tanisFormNot": "Upload your own photos (1-3), pick any name you like, briefly introduce yourself. If you'd rather not, you won't appear in the list.",
  "tanisAdYer": "Display name (whatever you like)",
  "tanisCinsiyet": "Gender",
  "tanisKadin": "Woman",
  "tanisErkek": "Man",
  "tanisIstege": "Optional — fill in if you like",
  "tanisYas": "Age",
  "tanisNeIcin": "What do you want to meet for?",
  "tanisBioYer": "Short intro: tell us about yourself…",
  "tanisKaydediliyor": "Saving…",
  "tanisKaydet": "Save and Publish",
  "tanisKaldir": "Hide from list",
  "tanisAIsohbetUyari": "This is an AI — not a real person. Don't share personal info/money.",
  "tanisAIbasla": "Say hi and start chatting!",
  "tanisAIyaz": "Write a message…",
  "cizim": "drawing",
  "resimHazirlaniyor": "Preparing image…",
  "resim": "image",
  "resimEski": "This image didn't come through — want to try again?",
  "resimOlmadi": "Couldn't generate image",
  "gloxSes": "Gloxoo voice",
  "sesOrnek": "Hi, I'm Gloxoo. This is how my voice will sound.",
  "ghEpostaKabul": "Please use gloxorg.com or a recognized email like Gmail, Outlook, Yahoo, iCloud. Made-up addresses aren't accepted.",
  "ghSifreKural": "Password must be at least 8 characters and include a letter + a number.",
  "ghSifreUyusmuyor": "The two passwords don't match.",
  "ghEpostaVar": "This email is already registered, you can log in.",
  "ghGirisYanlis": "Wrong email or password. If you don't have an account, SIGN UP above. (If you previously signed in with Google/Microsoft, use that button.)",
  "ghSifreKisa": "Password must be at least 6 characters.",
  "ghVarSifreYanlis": "This email is registered but the password is wrong. (If you set it up with Google, sign in with the Google button.)",
  "uyeMusteri": "Customer",
  "profilPasaport": "Profession Passport",
  "profilBaslik": "My GLOXORG Profile",
  "profilYukleniyor": "Loading...",
  "profilHakkinda": "About",
  "profilDeneyim": "Experience",
  "profilYil": "years",
  "profilHizmetler": "Services",
  "profilFiyat": "Price range",
  "profilEksik": "Add your professional info — tap Edit above.",
  "profilAkis": "My Feed · Portfolio",
  "profilAkisBos": "Your work, photos and videos will flow here. (Posting coming soon)",
  "profilAd": "First name",
  "profilSoyad": "Last name",
  "profilTelefon": "Phone",
  "profilKonum": "Location (city/country)",
  "profilMeslek": "Profession",
  "profilHizmetlerVir": "Services (separate with commas)",
  "profilFiyatMin": "Min price",
  "profilFiyatMax": "Max price",
  "profilKaydediliyor": "Saving...",
  "belYazdir": "Print",
  "belBoyut": "Size / Vertical",
  "belDikeyYazi": "Vertical text",
  "belYaziTipi": "Font",
  "belYaziBoyut": "Size",
  "belRenk": "Color",
  "belNormal": "Normal",
  "belBoyutIpucu": "Use － ＋ on the column header for WIDTH, and － ＋ on the left number for HEIGHT. The ⇅ button makes that column VERTICAL (bottom-to-top). Make columns thinner to fit A4.",
  "muhPencereKapat": "Close window",
  "belBoyutKisa": "－ ＋ to shrink/widen · ⇅ vertical text · thin columns to fit A4",
  "saCek": "Take photo",
  "saGaleri": "From gallery",
  "saModellerim": "My Models",
  "saKaydet": "Save to My Models",
  "saKaydedildi": "Saved to My Models",
  "saModelSilOnay": "Delete this model?",
  "saGaleriBos": "No saved models yet. Create one, then tap 'Save to My Models' below.",
  "aitCanli": "Live AI",
  "aitSac": "Change your hair",
  "aitKiyafet": "Try on clothes",
  "aitMakyaj": "Makeup & nails",
  "aitSor": "Ask Gloxoo",
  "aitResim": "Images & drawing",
  "aitMuhasebe": "Accounting & docs",
  "aitAynaBtn": "Virtual Mirror",
  "aitGloxBtn": "Ask Gloxoo",
  "aitAlt": "Try hair/clothes on your photo, ask Gloxoo anything — instantly, in your language."
 },
 "de": {
  "akBuyut": "Zum Vergrößern tippen",
  "tekrar": "Erneut",
  "tanismaFotoGerek": "Füge mindestens 1 Foto hinzu.",
  "tanismaHata": "Foto konnte nicht hochgeladen werden, versuch es erneut.",
  "tanismaKaydedildi": "Deine Vorstellungskarte ist fertig! Du erscheinst jetzt in der Community.",
  "tanismaCikOnay": "Möchtest du deine Vorstellungskarte ausblenden? Du erscheinst dann nicht mehr in der Liste (deine Fotos werden nicht gelöscht, du kannst sie jederzeit wieder aktivieren).",
  "ozelAIadGir": "Gib zuerst einen Namen ein.",
  "beyinKredi": "Gloxoos Schreib-Gehirn scheint gerade ausgelastet oder ohne Guthaben zu sein 🙏 (Das ist ein separates Konto vom Bild-Guthaben.) Versuchst du es in ein paar Minuten noch einmal? Wenn es weiter besteht, sag dem GLOXORG-Inhaber Bescheid — es ist bald wieder da.",
  "cizimHazir": "Hier ist meine Zeichnung 🎨",
  "cumaHazir": "Ich habe einen besonderen Freitags-Beitrag nur für dich vorbereitet 🤲🌸",
  "resimUretiliyor": "Ich bereite das Bild vor 🎨",
  "resimZamanAsimi": "Das Bild kam nicht rechtzeitig, versuchst du es noch einmal?",
  "indirilemedi": "Download fehlgeschlagen",
  "paylasilamadi": "Teilen fehlgeschlagen",
  "resimIndiPaylas": "Bild heruntergeladen — von dort kannst du es teilen 📤",
  "kopyalanamadi": "Kopieren fehlgeschlagen",
  "resimKopyalandi": "Bild kopiert 📋",
  "resimIndiKopya": "Bild heruntergeladen 📄",
  "resimPaylasima": "Bild zum Teilen verschoben — füge bei Bedarf einen Text hinzu und teile es auf GLOXORG 📤",
  "sbpGloxooSor": "Gloxoo fragen",
  "feedYukleniyor": "Beiträge werden geladen…",
  "tanisBaslik": "Kennenlernen",
  "tanisTanit": "Stell dich vor, lern neue Leute kennen.",
  "tanisAra3": "Suchen oder die KI fragen…",
  "aiAraniyor": "KI sucht…",
  "aiIleAra": "Intelligente Suche mit KI",
  "aiAraIpuc": "Z. B.: „Jemand Single in der Ukraine, 30-40 Jahre, zum Heiraten“",
  "aiAramaSonucVar": "Die KI hat das für dich gefunden",
  "aiSonucYok": "Die KI konnte niemand Passenden finden",
  "tanisHepsi2": "Alle",
  "tanisKadinlar": "Frauen",
  "tanisErkekler": "Männer",
  "tanisKartDuzenle": "Meine Vorstellungskarte bearbeiten",
  "tanisKartOlustur": "Meine Vorstellungskarte erstellen",
  "tanisanlar": "Leute, die sich kennenlernen möchten",
  "tanisYukleniyor": "Wird geladen…",
  "tanisAramaBos": "Niemand passt zu deiner Suche.",
  "tanisBos": "Noch niemand hat eine Karte erstellt. Sei der Erste — erstell oben deine eigene Karte!",
  "durBekar": "Single",
  "durEvli": "Verheiratet",
  "durIliski": "In einer Beziehung",
  "durBosanmis": "Geschieden",
  "arArkadaslik": "Freundschaft",
  "arSohbet": "Chatten",
  "arFlort": "Flirten",
  "arEvlilik": "Heirat",
  "tanisSeninKartin": "Deine Karte",
  "uzaginda": "entfernt",
  "tanisDuzenle": "Meine Karte bearbeiten",
  "tanisBegenildi": "Gefällt dir",
  "tanisBegen": "Gefällt mir",
  "ozelAIbas": "Dein eigener KI-Freund",
  "ozelAInot": "Erstelle einen Chat-Freund nur für DICH mit Foto, Name, Alter und Stadt einer geliebten Person — chatte mit ihr in dieser Identität. (Das ist eine KI 🤖, keine echte Person.)",
  "ozelAIolustur": "Erstelle deine eigene KI",
  "ozelSeninki": "Deine",
  "tanisSohbetEt": "Chatten",
  "ozelAIformNot": "Ein Chat-Freund nur für dich mit den Angaben einer geliebten Person. Das ist eine KI 🤖 — keine echte Person.",
  "ozelAIfoto": "Foto hinzufügen",
  "ozelAIad": "Vorname",
  "ozelAIsoyad": "Nachname",
  "ozelAIyas": "Alter",
  "ozelAIsehir": "Stadt",
  "ozelAIbasla": "Erstellen und chatten",
  "tanisAIbas": "KI-Chat-Freunde",
  "tanisAInot": "Das sind keine echten Personen — es sind GLOXORGs KI-Freunde. Chatte jederzeit, sie stellen sich vor 💬",
  "yapayZeka": "KI",
  "tanisKartim": "Meine Vorstellungskarte",
  "tanisFormNot": "Lade eigene Fotos hoch (1-3), wähle einen beliebigen Namen, stell dich kurz vor. Wenn du nicht möchtest, erscheinst du nicht in der Liste.",
  "tanisAdYer": "Anzeigename (ganz nach Wunsch)",
  "tanisCinsiyet": "Geschlecht",
  "tanisKadin": "Frau",
  "tanisErkek": "Mann",
  "tanisIstege": "Optional — bei Bedarf ausfüllen",
  "tanisYas": "Alter",
  "tanisNeIcin": "Wofür möchtest du jemanden kennenlernen?",
  "tanisBioYer": "Kurze Vorstellung: erzähl von dir…",
  "tanisKaydediliyor": "Wird gespeichert…",
  "tanisKaydet": "Speichern und veröffentlichen",
  "tanisKaldir": "Aus der Liste ausblenden",
  "tanisAIsohbetUyari": "Das ist eine KI — keine echte Person. Gib keine persönlichen Daten/kein Geld.",
  "tanisAIbasla": "Sag Hallo und starte den Chat!",
  "tanisAIyaz": "Nachricht schreiben…",
  "cizim": "Zeichnung",
  "resimHazirlaniyor": "Bild wird vorbereitet…",
  "resim": "Bild",
  "resimEski": "Dieses Bild ist nicht angekommen — möchtest du es erneut?",
  "resimOlmadi": "Bild konnte nicht erstellt werden",
  "gloxSes": "Gloxoo-Stimme",
  "sesOrnek": "Hallo, ich bin Gloxoo. So wird meine Stimme klingen.",
  "ghEpostaKabul": "Bitte nutze gloxorg.com oder eine anerkannte E-Mail wie Gmail, Outlook, Yahoo, iCloud. Selbst ausgedachte Adressen werden nicht akzeptiert.",
  "ghSifreKural": "Das Passwort muss mindestens 8 Zeichen lang sein und einen Buchstaben + eine Zahl enthalten.",
  "ghSifreUyusmuyor": "Die beiden Passwörter stimmen nicht überein.",
  "ghEpostaVar": "Diese E-Mail ist bereits registriert, du kannst dich anmelden.",
  "ghGirisYanlis": "E-Mail oder Passwort falsch. Wenn du kein Konto hast, REGISTRIERE dich oben. (Falls du dich zuvor mit Google/Microsoft angemeldet hast, nutze diese Schaltfläche.)",
  "ghSifreKisa": "Das Passwort muss mindestens 6 Zeichen lang sein.",
  "ghVarSifreYanlis": "Diese E-Mail ist registriert, aber das Passwort ist falsch. (Falls du sie mit Google eingerichtet hast, melde dich mit der Google-Schaltfläche an.)",
  "uyeMusteri": "Kunde",
  "profilPasaport": "Berufspass",
  "profilBaslik": "Mein GLOXORG-Profil",
  "profilYukleniyor": "Wird geladen...",
  "profilHakkinda": "Über mich",
  "profilDeneyim": "Erfahrung",
  "profilYil": "Jahre",
  "profilHizmetler": "Leistungen",
  "profilFiyat": "Preisspanne",
  "profilEksik": "Füge deine beruflichen Angaben hinzu — tippe oben auf Bearbeiten.",
  "profilAkis": "Mein Feed · Portfolio",
  "profilAkisBos": "Deine Arbeiten, Fotos und Videos erscheinen hier. (Beiträge bald verfügbar)",
  "profilAd": "Vorname",
  "profilSoyad": "Nachname",
  "profilTelefon": "Telefon",
  "profilKonum": "Standort (Stadt/Land)",
  "profilMeslek": "Beruf",
  "profilHizmetlerVir": "Leistungen (mit Komma trennen)",
  "profilFiyatMin": "Preis min.",
  "profilFiyatMax": "Preis max.",
  "profilKaydediliyor": "Wird gespeichert...",
  "belYazdir": "Drucken",
  "belBoyut": "Größe / Vertikal",
  "belDikeyYazi": "Vertikaler Text",
  "belYaziTipi": "Schriftart",
  "belYaziBoyut": "Größe",
  "belRenk": "Farbe",
  "belNormal": "Normal",
  "belBoyutIpucu": "Mit － ＋ in der Spaltenüberschrift die BREITE, mit － ＋ an der linken Zahl die HÖHE einstellen. ⇅ macht die Spalte VERTIKAL (unten nach oben). Spalten schmaler machen, damit sie auf A4 passen.",
  "muhPencereKapat": "Fenster schließen",
  "belBoyutKisa": "－ ＋ verschmälern/verbreitern · ⇅ vertikaler Text · Spalten für A4 verschmälern",
  "saCek": "Foto aufnehmen",
  "saGaleri": "Aus Galerie",
  "saModellerim": "Meine Modelle",
  "saKaydet": "Zu meinen Modellen",
  "saKaydedildi": "Gespeichert",
  "saModelSilOnay": "Dieses Modell löschen?",
  "saGaleriBos": "Noch keine gespeicherten Modelle. Erstelle eins und tippe unten auf 'Zu meinen Modellen'.",
  "aitCanli": "Live-KI",
  "aitSac": "Frisur ändern",
  "aitKiyafet": "Kleidung anprobieren",
  "aitMakyaj": "Make-up & Nägel",
  "aitSor": "Frag Gloxoo",
  "aitResim": "Bilder & Zeichnen",
  "aitMuhasebe": "Buchhaltung & Dokumente",
  "aitAynaBtn": "Virtueller Spiegel",
  "aitGloxBtn": "Frag Gloxoo",
  "aitAlt": "Probiere Frisuren/Kleidung an deinem Foto, frag Gloxoo alles — sofort, in deiner Sprache."
 },
 "ru": {
  "akBuyut": "Нажми, чтобы увеличить",
  "tekrar": "Ещё раз",
  "tanismaFotoGerek": "Добавь хотя бы 1 фото.",
  "tanismaHata": "Не удалось загрузить фото, попробуй снова.",
  "tanismaKaydedildi": "Твоя карточка знакомств готова! Теперь ты виден в Сообществе.",
  "tanismaCikOnay": "Скрыть твою карточку знакомств? Тебя больше не будет в списке (фото не удалятся, при желании включишь снова).",
  "ozelAIadGir": "Сначала напиши имя.",
  "beyinKredi": "Похоже, текстовый мозг Gloxoo сейчас перегружен или закончились кредиты 🙏 (Это отдельный счёт от кредитов на картинки.) Попробуй снова через пару минут? Если не пройдёт — сообщи владельцу GLOXORG, скоро подключат.",
  "cizimHazir": "Вот, нарисовал 🎨",
  "cumaHazir": "Я подготовил для тебя особую пятничную открытку 🤲🌸",
  "resimUretiliyor": "Готовлю картинку 🎨",
  "resimZamanAsimi": "Картинка не пришла вовремя, попробуешь снова?",
  "indirilemedi": "Не удалось скачать",
  "paylasilamadi": "Не удалось поделиться",
  "resimIndiPaylas": "Картинка скачана — оттуда можешь поделиться 📤",
  "kopyalanamadi": "Не удалось скопировать",
  "resimKopyalandi": "Картинка скопирована 📋",
  "resimIndiKopya": "Картинка скачана 📄",
  "resimPaylasima": "Картинка отправлена в общий доступ — при желании добавь текст и поделись в GLOXORG 📤",
  "sbpGloxooSor": "Спросить Gloxoo",
  "feedYukleniyor": "Загружаем публикации…",
  "tanisBaslik": "Знакомства",
  "tanisTanit": "Расскажи о себе, знакомься с новыми людьми.",
  "tanisAra3": "Ищи или спроси у ИИ…",
  "aiAraniyor": "ИИ ищет…",
  "aiIleAra": "Умный поиск с ИИ",
  "aiAraIpuc": "Напр.: «Незамужняя в Украине, 30–40 лет, для брака»",
  "aiAramaSonucVar": "ИИ нашёл для тебя",
  "aiSonucYok": "ИИ не нашёл подходящих",
  "tanisHepsi2": "Все",
  "tanisKadinlar": "Женщины",
  "tanisErkekler": "Мужчины",
  "tanisKartDuzenle": "Изменить мою карточку знакомств",
  "tanisKartOlustur": "Создать мою карточку знакомств",
  "tanisanlar": "Хотят познакомиться",
  "tanisYukleniyor": "Загрузка…",
  "tanisAramaBos": "Никого по твоему запросу.",
  "tanisBos": "Пока никто не создал карточку. Будь первым — создай свою наверху!",
  "durBekar": "Не в браке",
  "durEvli": "В браке",
  "durIliski": "В отношениях",
  "durBosanmis": "В разводе",
  "arArkadaslik": "Дружба",
  "arSohbet": "Общение",
  "arFlort": "Флирт",
  "arEvlilik": "Брак",
  "tanisSeninKartin": "Твоя карточка",
  "uzaginda": "в отдалении",
  "tanisDuzenle": "Изменить мою карточку",
  "tanisBegenildi": "Понравилось",
  "tanisBegen": "Нравится",
  "ozelAIbas": "Твой личный ИИ-друг",
  "ozelAInot": "Создай ЛИЧНОГО собеседника с фото, именем, возрастом и городом того, кто тебе дорог — и общайся с ним в этом образе. (Это ИИ 🤖, не реальный человек.)",
  "ozelAIolustur": "Создать своего ИИ",
  "ozelSeninki": "Твой",
  "tanisSohbetEt": "Общаться",
  "ozelAIformNot": "Личный собеседник по данным того, кто тебе дорог. Это ИИ 🤖 — не реальный человек.",
  "ozelAIfoto": "Добавить фото",
  "ozelAIad": "Имя",
  "ozelAIsoyad": "Фамилия",
  "ozelAIyas": "Возраст",
  "ozelAIsehir": "Город",
  "ozelAIbasla": "Создать и общаться",
  "tanisAIbas": "ИИ-собеседники",
  "tanisAInot": "Это не реальные люди — ИИ-друзья GLOXORG. Общайся когда угодно, они сами представятся 💬",
  "yapayZeka": "ИИ",
  "tanisKartim": "Моя карточка знакомств",
  "tanisFormNot": "Загрузи свои фото (1–3), напиши любое имя, коротко расскажи о себе. Не захочешь — не будешь виден в списке.",
  "tanisAdYer": "Отображаемое имя (любое)",
  "tanisCinsiyet": "Пол",
  "tanisKadin": "Женщина",
  "tanisErkek": "Мужчина",
  "tanisIstege": "По желанию — заполни, если хочешь",
  "tanisYas": "Возраст",
  "tanisNeIcin": "Для чего хочешь познакомиться?",
  "tanisBioYer": "Короткое описание: расскажи о себе…",
  "tanisKaydediliyor": "Сохранение…",
  "tanisKaydet": "Сохранить и опубликовать",
  "tanisKaldir": "Скрыться из списка",
  "tanisAIsohbetUyari": "Это ИИ — не реальный человек. Не давай личные данные и деньги.",
  "tanisAIbasla": "Напиши привет, начни общение!",
  "tanisAIyaz": "Напиши сообщение…",
  "cizim": "рисунок",
  "resimHazirlaniyor": "Картинка готовится…",
  "resim": "картинка",
  "resimEski": "Эта картинка не пришла — хочешь ещё раз?",
  "resimOlmadi": "Не удалось создать картинку",
  "gloxSes": "Голос Gloxoo",
  "sesOrnek": "Привет, я Gloxoo. Мой голос будет таким.",
  "ghEpostaKabul": "Используйте gloxorg.com или известную почту, например Gmail, Outlook, Yahoo, iCloud. Придуманные адреса не принимаются.",
  "ghSifreKural": "Пароль должен быть не менее 8 символов и содержать буквы и цифры.",
  "ghSifreUyusmuyor": "Пароли не совпадают.",
  "ghEpostaVar": "Эта почта уже зарегистрирована, можешь войти.",
  "ghGirisYanlis": "Неверная почта или пароль. Нет аккаунта — нажми РЕГИСТРАЦИЯ выше. (Если раньше входил через Google/Microsoft, используй ту кнопку.)",
  "ghSifreKisa": "Пароль должен быть не менее 6 символов.",
  "ghVarSifreYanlis": "Эта почта зарегистрирована, но пароль неверный. (Если открывал через Google, войди кнопкой Google.)",
  "uyeMusteri": "Клиент",
  "profilPasaport": "Паспорт профессии",
  "profilBaslik": "Мой профиль GLOXORG",
  "profilYukleniyor": "Загрузка...",
  "profilHakkinda": "О себе",
  "profilDeneyim": "Опыт",
  "profilYil": "лет",
  "profilHizmetler": "Услуги",
  "profilFiyat": "Ценовой диапазон",
  "profilEksik": "Добавь свои профессиональные данные — нажми «Изменить» выше.",
  "profilAkis": "Моя лента · Портфолио",
  "profilAkisBos": "Здесь будут твои работы, фото и видео. (Публикация скоро)",
  "profilAd": "Имя",
  "profilSoyad": "Фамилия",
  "profilTelefon": "Телефон",
  "profilKonum": "Местоположение (город/страна)",
  "profilMeslek": "Профессия",
  "profilHizmetlerVir": "Услуги (через запятую)",
  "profilFiyatMin": "Цена от",
  "profilFiyatMax": "Цена до",
  "profilKaydediliyor": "Сохранение...",
  "belYazdir": "Печать",
  "belBoyut": "Размер / Вертикально",
  "belDikeyYazi": "Вертикальный текст",
  "belYaziTipi": "Шрифт",
  "belYaziBoyut": "Размер",
  "belRenk": "Цвет",
  "belNormal": "Обычный",
  "belBoyutIpucu": "－ ＋ в заголовке столбца — ШИРИНА, － ＋ у номера слева — ВЫСОТА. Кнопка ⇅ делает столбец ВЕРТИКАЛЬНЫМ (снизу вверх). Сужай столбцы, чтобы поместилось на A4.",
  "muhPencereKapat": "Закрыть окно",
  "belBoyutKisa": "－ ＋ сузить/расширить · ⇅ вертикальный текст · сузь столбцы под A4",
  "saCek": "Сделать фото",
  "saGaleri": "Из галереи",
  "saModellerim": "Мои модели",
  "saKaydet": "В мои модели",
  "saKaydedildi": "Сохранено",
  "saModelSilOnay": "Удалить эту модель?",
  "saGaleriBos": "Пока нет сохранённых моделей. Создай образ и нажми ниже «В мои модели».",
  "aitCanli": "Живой ИИ",
  "aitSac": "Смени причёску",
  "aitKiyafet": "Примерь одежду",
  "aitMakyaj": "Макияж и ногти",
  "aitSor": "Спроси Gloxoo",
  "aitResim": "Картинки и рисунки",
  "aitMuhasebe": "Учёт и документы",
  "aitAynaBtn": "Виртуальное зеркало",
  "aitGloxBtn": "Спроси Gloxoo",
  "aitAlt": "Примеряй причёски/одежду на своём фото, спрашивай Gloxoo о чём угодно — мгновенно, на твоём языке."
 },
 "uk": {
  "akBuyut": "Торкнись, щоб збільшити",
  "tekrar": "Ще раз",
  "tanismaFotoGerek": "Додай щонайменше 1 фото.",
  "tanismaHata": "Не вдалося завантажити фото, спробуй ще раз.",
  "tanismaKaydedildi": "Твоя картка знайомств готова! Тепер ти видимий у Спільноті.",
  "tanismaCikOnay": "Приховати твою картку знайомств? Тебе більше не буде у списку (фото не видаляться, за бажанням увімкнеш знову).",
  "ozelAIadGir": "Спершу напиши ім'я.",
  "beyinKredi": "Схоже, текстовий мозок Gloxoo зараз перевантажений або закінчились кредити 🙏 (Це окремий рахунок від кредитів на зображення.) Спробуй ще раз за кілька хвилин? Якщо не мине — повідом власника GLOXORG, невдовзі підключать.",
  "cizimHazir": "Ось, намалював 🎨",
  "cumaHazir": "Я підготував для тебе особливу п'ятничну листівку 🤲🌸",
  "resimUretiliyor": "Готую зображення 🎨",
  "resimZamanAsimi": "Зображення не прийшло вчасно, спробуєш ще раз?",
  "indirilemedi": "Не вдалося завантажити",
  "paylasilamadi": "Не вдалося поділитися",
  "resimIndiPaylas": "Зображення завантажено — звідти можеш поділитися 📤",
  "kopyalanamadi": "Не вдалося скопіювати",
  "resimKopyalandi": "Зображення скопійовано 📋",
  "resimIndiKopya": "Зображення завантажено 📄",
  "resimPaylasima": "Зображення надіслано в спільний доступ — за бажанням додай текст і поділись у GLOXORG 📤",
  "sbpGloxooSor": "Запитати Gloxoo",
  "feedYukleniyor": "Завантажуємо дописи…",
  "tanisBaslik": "Знайомства",
  "tanisTanit": "Розкажи про себе, знайомся з новими людьми.",
  "tanisAra3": "Шукай або запитай ШІ…",
  "aiAraniyor": "ШІ шукає…",
  "aiIleAra": "Розумний пошук зі ШІ",
  "aiAraIpuc": "Напр.: «Неодружена в Україні, 30–40 років, для шлюбу»",
  "aiAramaSonucVar": "ШІ знайшов для тебе",
  "aiSonucYok": "ШІ не знайшов відповідних",
  "tanisHepsi2": "Усі",
  "tanisKadinlar": "Жінки",
  "tanisErkekler": "Чоловіки",
  "tanisKartDuzenle": "Редагувати мою картку знайомств",
  "tanisKartOlustur": "Створити мою картку знайомств",
  "tanisanlar": "Хочуть познайомитися",
  "tanisYukleniyor": "Завантаження…",
  "tanisAramaBos": "Нікого за твоїм запитом.",
  "tanisBos": "Поки ніхто не створив картку. Будь першим — створи свою вгорі!",
  "durBekar": "Неодружений",
  "durEvli": "Одружений",
  "durIliski": "У стосунках",
  "durBosanmis": "Розлучений",
  "arArkadaslik": "Дружба",
  "arSohbet": "Спілкування",
  "arFlort": "Флірт",
  "arEvlilik": "Шлюб",
  "tanisSeninKartin": "Твоя картка",
  "uzaginda": "на відстані",
  "tanisDuzenle": "Редагувати мою картку",
  "tanisBegenildi": "Сподобалось",
  "tanisBegen": "Подобається",
  "ozelAIbas": "Твій особистий ШІ-друг",
  "ozelAInot": "Створи ОСОБИСТОГО співрозмовника з фото, ім'ям, віком і містом того, хто тобі дорогий — і спілкуйся з ним у цьому образі. (Це ШІ 🤖, не реальна людина.)",
  "ozelAIolustur": "Створити свій ШІ",
  "ozelSeninki": "Твій",
  "tanisSohbetEt": "Спілкуватися",
  "ozelAIformNot": "Особистий співрозмовник за даними того, хто тобі дорогий. Це ШІ 🤖 — не реальна людина.",
  "ozelAIfoto": "Додати фото",
  "ozelAIad": "Ім'я",
  "ozelAIsoyad": "Прізвище",
  "ozelAIyas": "Вік",
  "ozelAIsehir": "Місто",
  "ozelAIbasla": "Створити і спілкуватися",
  "tanisAIbas": "ШІ-співрозмовники",
  "tanisAInot": "Це не реальні люди — ШІ-друзі GLOXORG. Спілкуйся коли завгодно, вони самі представляться 💬",
  "yapayZeka": "ШІ",
  "tanisKartim": "Моя картка знайомств",
  "tanisFormNot": "Завантаж свої фото (1–3), напиши будь-яке ім'я, коротко розкажи про себе. Не захочеш — не будеш видимий у списку.",
  "tanisAdYer": "Відображуване ім'я (будь-яке)",
  "tanisCinsiyet": "Стать",
  "tanisKadin": "Жінка",
  "tanisErkek": "Чоловік",
  "tanisIstege": "За бажанням — заповни, якщо хочеш",
  "tanisYas": "Вік",
  "tanisNeIcin": "Для чого хочеш познайомитися?",
  "tanisBioYer": "Короткий опис: розкажи про себе…",
  "tanisKaydediliyor": "Збереження…",
  "tanisKaydet": "Зберегти та опублікувати",
  "tanisKaldir": "Сховатися зі списку",
  "tanisAIsohbetUyari": "Це ШІ — не реальна людина. Не давай особисті дані та гроші.",
  "tanisAIbasla": "Напиши привіт, почни спілкування!",
  "tanisAIyaz": "Напиши повідомлення…",
  "cizim": "малюнок",
  "resimHazirlaniyor": "Зображення готується…",
  "resim": "зображення",
  "resimEski": "Це зображення не прийшло — хочеш ще раз?",
  "resimOlmadi": "Не вдалося створити зображення",
  "gloxSes": "Голос Gloxoo",
  "sesOrnek": "Привіт, я Gloxoo. Мій голос буде таким.",
  "ghEpostaKabul": "Використовуйте gloxorg.com або відому пошту, наприклад Gmail, Outlook, Yahoo, iCloud. Вигадані адреси не приймаються.",
  "ghSifreKural": "Пароль має містити щонайменше 8 символів і складатися з літер та цифр.",
  "ghSifreUyusmuyor": "Паролі не збігаються.",
  "ghEpostaVar": "Ця пошта вже зареєстрована, можеш увійти.",
  "ghGirisYanlis": "Невірна пошта або пароль. Немає акаунту — натисни РЕЄСТРАЦІЯ вгорі. (Якщо раніше входив через Google/Microsoft, використай ту кнопку.)",
  "ghSifreKisa": "Пароль має містити щонайменше 6 символів.",
  "ghVarSifreYanlis": "Ця пошта зареєстрована, але пароль невірний. (Якщо відкривав через Google, увійди кнопкою Google.)",
  "uyeMusteri": "Клієнт",
  "profilPasaport": "Паспорт професії",
  "profilBaslik": "Мій профіль GLOXORG",
  "profilYukleniyor": "Завантаження...",
  "profilHakkinda": "Про себе",
  "profilDeneyim": "Досвід",
  "profilYil": "років",
  "profilHizmetler": "Послуги",
  "profilFiyat": "Ціновий діапазон",
  "profilEksik": "Додай свої професійні дані — натисни «Редагувати» вгорі.",
  "profilAkis": "Моя стрічка · Портфоліо",
  "profilAkisBos": "Тут будуть твої роботи, фото та відео. (Публікація незабаром)",
  "profilAd": "Ім'я",
  "profilSoyad": "Прізвище",
  "profilTelefon": "Телефон",
  "profilKonum": "Розташування (місто/країна)",
  "profilMeslek": "Професія",
  "profilHizmetlerVir": "Послуги (через кому)",
  "profilFiyatMin": "Ціна від",
  "profilFiyatMax": "Ціна до",
  "profilKaydediliyor": "Збереження...",
  "belYazdir": "Друк",
  "belBoyut": "Розмір / Вертикально",
  "belDikeyYazi": "Вертикальний текст",
  "belYaziTipi": "Шрифт",
  "belYaziBoyut": "Розмір",
  "belRenk": "Колір",
  "belNormal": "Звичайний",
  "belBoyutIpucu": "－ ＋ у заголовку стовпця — ШИРИНА, － ＋ біля номера зліва — ВИСОТА. Кнопка ⇅ робить стовпець ВЕРТИКАЛЬНИМ (знизу вгору). Звужуй стовпці, щоб вмістити на A4.",
  "muhPencereKapat": "Закрити вікно",
  "belBoyutKisa": "－ ＋ звузити/розширити · ⇅ вертикальний текст · звузь стовпці під A4",
  "saCek": "Зробити фото",
  "saGaleri": "З галереї",
  "saModellerim": "Мої моделі",
  "saKaydet": "У мої моделі",
  "saKaydedildi": "Збережено",
  "saModelSilOnay": "Видалити цю модель?",
  "saGaleriBos": "Ще немає збережених моделей. Створи образ і натисни нижче «У мої моделі».",
  "aitCanli": "Живий ШІ",
  "aitSac": "Зміни зачіску",
  "aitKiyafet": "Приміряй одяг",
  "aitMakyaj": "Макіяж і нігті",
  "aitSor": "Запитай Gloxoo",
  "aitResim": "Зображення й малюнки",
  "aitMuhasebe": "Облік і документи",
  "aitAynaBtn": "Віртуальне дзеркало",
  "aitGloxBtn": "Запитай Gloxoo",
  "aitAlt": "Приміряй зачіски/одяг на своєму фото, запитуй Gloxoo про будь-що — миттєво, твоєю мовою."
 },
 "es": {
  "akBuyut": "Toca para ampliar",
  "tekrar": "De nuevo",
  "tanismaFotoGerek": "Añade al menos 1 foto.",
  "tanismaHata": "No se pudo subir la foto, inténtalo de nuevo.",
  "tanismaKaydedildi": "¡Tu tarjeta está lista! Ya apareces en la Comunidad.",
  "tanismaCikOnay": "¿Quieres ocultar tu tarjeta? Ya no aparecerás en la lista (tus fotos no se borran, puedes reactivarla cuando quieras).",
  "ozelAIadGir": "Escribe primero un nombre.",
  "beyinKredi": "Ahora mismo el cerebro de escritura de Gloxoo está saturado o sin crédito 🙏 (Esto es una cuenta aparte del crédito de imágenes.) ¿Puedes intentarlo dentro de unos minutos? Si continúa, avisa al dueño de GLOXORG — se soluciona rápido.",
  "cizimHazir": "Aquí lo dibujé 🎨",
  "cumaHazir": "Te he preparado una publicación especial de viernes 🤲🌸",
  "resimUretiliyor": "Preparando la imagen 🎨",
  "resimZamanAsimi": "La imagen no llegó a tiempo, ¿lo intentas de nuevo?",
  "indirilemedi": "No se pudo descargar",
  "paylasilamadi": "No se pudo compartir",
  "resimIndiPaylas": "Imagen descargada — puedes compartirla desde ahí 📤",
  "kopyalanamadi": "No se pudo copiar",
  "resimKopyalandi": "Imagen copiada 📋",
  "resimIndiKopya": "Imagen descargada 📄",
  "resimPaylasima": "Imagen lista para compartir — añade un texto y publícala en GLOXORG 📤",
  "sbpGloxooSor": "Pregunta a Gloxoo",
  "feedYukleniyor": "Cargando publicaciones…",
  "tanisBaslik": "Conoce",
  "tanisTanit": "Preséntate y conoce gente nueva.",
  "tanisAra3": "Busca o pregunta a la IA…",
  "aiAraniyor": "La IA está buscando…",
  "aiIleAra": "Búsqueda inteligente con IA",
  "aiAraIpuc": "Ej: “Alguien soltero en Ucrania, 30-40 años, para casarse”",
  "aiAramaSonucVar": "La IA encontró esto para ti",
  "aiSonucYok": "La IA no encontró a nadie adecuado",
  "tanisHepsi2": "Todos",
  "tanisKadinlar": "Mujeres",
  "tanisErkekler": "Hombres",
  "tanisKartDuzenle": "Editar mi tarjeta",
  "tanisKartOlustur": "Crear mi tarjeta",
  "tanisanlar": "Quieren conocer gente",
  "tanisYukleniyor": "Cargando…",
  "tanisAramaBos": "Nadie coincide con tu búsqueda.",
  "tanisBos": "Aún nadie ha creado una tarjeta. ¡Sé el primero — crea la tuya arriba!",
  "durBekar": "Soltero/a",
  "durEvli": "Casado/a",
  "durIliski": "En una relación",
  "durBosanmis": "Divorciado/a",
  "arArkadaslik": "Amistad",
  "arSohbet": "Charlar",
  "arFlort": "Ligar",
  "arEvlilik": "Matrimonio",
  "tanisSeninKartin": "Tu tarjeta",
  "uzaginda": "de distancia",
  "tanisDuzenle": "Editar mi tarjeta",
  "tanisBegenildi": "Te gusta",
  "tanisBegen": "Me gusta",
  "ozelAIbas": "Tu propio amigo de IA",
  "ozelAInot": "Crea un compañero de charla SOLO para ti con la foto, el nombre, la edad y la ciudad de alguien que quieres — y chatea con él con esa identidad. (Es una inteligencia artificial 🤖, no una persona real.)",
  "ozelAIolustur": "Crea tu propia IA",
  "ozelSeninki": "El tuyo",
  "tanisSohbetEt": "Chatear",
  "ozelAIformNot": "Un compañero de charla solo para ti con los datos de alguien que quieres. Es una inteligencia artificial 🤖 — no una persona real.",
  "ozelAIfoto": "Añadir foto",
  "ozelAIad": "Nombre",
  "ozelAIsoyad": "Apellido",
  "ozelAIyas": "Edad",
  "ozelAIsehir": "Ciudad",
  "ozelAIbasla": "Crear y chatear",
  "tanisAIbas": "Amigos de charla con IA",
  "tanisAInot": "No son personas reales — son los amigos de IA de GLOXORG. Puedes chatear cuando quieras, se presentan solos 💬",
  "yapayZeka": "Inteligencia Artificial",
  "tanisKartim": "Mi Tarjeta",
  "tanisFormNot": "Sube tus propias fotos (1-3), pon el nombre que quieras y preséntate brevemente. Si no quieres, no aparecerás en la lista.",
  "tanisAdYer": "Nombre visible (el que quieras)",
  "tanisCinsiyet": "Sexo",
  "tanisKadin": "Mujer",
  "tanisErkek": "Hombre",
  "tanisIstege": "Opcional — rellénalo si quieres",
  "tanisYas": "Edad",
  "tanisNeIcin": "¿Para qué quieres conocer gente?",
  "tanisBioYer": "Presentación breve: habla de ti…",
  "tanisKaydediliyor": "Guardando…",
  "tanisKaydet": "Guardar y publicar",
  "tanisKaldir": "Ocultar de la lista",
  "tanisAIsohbetUyari": "Es una IA — no una persona real. No des datos personales ni dinero.",
  "tanisAIbasla": "¡Escribe un saludo y empieza a charlar!",
  "tanisAIyaz": "Escribe un mensaje…",
  "cizim": "dibujo",
  "resimHazirlaniyor": "Preparando la imagen…",
  "resim": "imagen",
  "resimEski": "Esta imagen no llegó — ¿la quieres de nuevo?",
  "resimOlmadi": "No se pudo crear la imagen",
  "gloxSes": "Voz de Gloxoo",
  "sesOrnek": "Hola, soy Gloxoo. Mi voz sonará así.",
  "ghEpostaKabul": "Usa gloxorg.com o un correo conocido como Gmail, Outlook, Yahoo, iCloud. No se aceptan direcciones inventadas.",
  "ghSifreKural": "La contraseña debe tener al menos 8 caracteres e incluir letras y números.",
  "ghSifreUyusmuyor": "Las dos contraseñas no coinciden.",
  "ghEpostaVar": "Este correo ya está registrado, puedes iniciar sesión.",
  "ghGirisYanlis": "Correo o contraseña incorrectos. Si no tienes cuenta, REGÍSTRATE arriba. (Si antes entraste con Google/Microsoft, usa ese botón.)",
  "ghSifreKisa": "La contraseña debe tener al menos 6 caracteres.",
  "ghVarSifreYanlis": "Este correo está registrado pero la contraseña es incorrecta. (Si lo creaste con Google, entra con el botón de Google.)",
  "uyeMusteri": "Cliente",
  "profilPasaport": "Pasaporte Profesional",
  "profilBaslik": "Mi Perfil de GLOXORG",
  "profilYukleniyor": "Cargando...",
  "profilHakkinda": "Sobre mí",
  "profilDeneyim": "Experiencia",
  "profilYil": "años",
  "profilHizmetler": "Servicios",
  "profilFiyat": "Rango de precios",
  "profilEksik": "Añade tu información profesional — toca Editar arriba.",
  "profilAkis": "Mi feed · Portafolio",
  "profilAkisBos": "Aquí aparecerán tus trabajos, fotos y videos. (Publicación próximamente)",
  "profilAd": "Nombre",
  "profilSoyad": "Apellido",
  "profilTelefon": "Teléfono",
  "profilKonum": "Ubicación (ciudad/país)",
  "profilMeslek": "Profesión",
  "profilHizmetlerVir": "Servicios (separa con comas)",
  "profilFiyatMin": "Precio mín",
  "profilFiyatMax": "Precio máx",
  "profilKaydediliyor": "Guardando...",
  "belYazdir": "Imprimir",
  "belBoyut": "Tamaño / Vertical",
  "belDikeyYazi": "Texto vertical",
  "belYaziTipi": "Fuente",
  "belYaziBoyut": "Tamaño",
  "belRenk": "Color",
  "belNormal": "Normal",
  "belBoyutIpucu": "Con － ＋ en el encabezado de columna ajustas el ANCHO, y con － ＋ en el número de la izquierda la ALTURA. El botón ⇅ pone esa columna VERTICAL (de abajo arriba). Estrecha las columnas para que quepan en A4.",
  "muhPencereKapat": "Cerrar ventana",
  "belBoyutKisa": "－ ＋ estrechar/ensanchar · ⇅ texto vertical · estrecha columnas para A4",
  "saCek": "Tomar foto",
  "saGaleri": "De la galería",
  "saModellerim": "Mis modelos",
  "saKaydet": "Guardar en Mis modelos",
  "saKaydedildi": "Guardado",
  "saModelSilOnay": "¿Eliminar este modelo?",
  "saGaleriBos": "Aún no hay modelos guardados. Crea uno y pulsa abajo 'Guardar en Mis modelos'.",
  "aitCanli": "IA en vivo",
  "aitSac": "Cambia tu cabello",
  "aitKiyafet": "Prueba ropa",
  "aitMakyaj": "Maquillaje y uñas",
  "aitSor": "Pregunta a Gloxoo",
  "aitResim": "Imágenes y dibujo",
  "aitMuhasebe": "Contabilidad y documentos",
  "aitAynaBtn": "Espejo virtual",
  "aitGloxBtn": "Pregunta a Gloxoo",
  "aitAlt": "Prueba peinados/ropa en tu foto y pregúntale a Gloxoo lo que sea — al instante, en tu idioma."
 },
 "fr": {
  "akBuyut": "Touche pour agrandir",
  "tekrar": "Recommencer",
  "tanismaFotoGerek": "Ajoute au moins 1 photo.",
  "tanismaHata": "Échec du téléversement de la photo, réessaie.",
  "tanismaKaydedildi": "Ta fiche est prête ! Tu apparais maintenant dans la Communauté.",
  "tanismaCikOnay": "Veux-tu masquer ta fiche ? Tu n'apparaîtras plus dans la liste (tes photos ne sont pas supprimées, tu peux la réactiver quand tu veux).",
  "ozelAIadGir": "Écris d'abord un nom.",
  "beyinKredi": "En ce moment le cerveau d'écriture de Gloxoo est saturé ou n'a plus de crédit 🙏 (C'est un compte distinct du crédit d'images.) Peux-tu réessayer dans quelques minutes ? Si ça persiste, préviens le propriétaire de GLOXORG — ça se règle vite.",
  "cizimHazir": "Voilà, je l'ai dessiné 🎨",
  "cumaHazir": "Je t'ai préparé une publication spéciale du vendredi 🤲🌸",
  "resimUretiliyor": "Je prépare l'image 🎨",
  "resimZamanAsimi": "L'image n'est pas arrivée à temps, tu réessaies ?",
  "indirilemedi": "Téléchargement impossible",
  "paylasilamadi": "Partage impossible",
  "resimIndiPaylas": "Image téléchargée — tu peux la partager de là 📤",
  "kopyalanamadi": "Copie impossible",
  "resimKopyalandi": "Image copiée 📋",
  "resimIndiKopya": "Image téléchargée 📄",
  "resimPaylasima": "Image prête à partager — ajoute un texte et publie-la sur GLOXORG 📤",
  "sbpGloxooSor": "Demande à Gloxoo",
  "feedYukleniyor": "Chargement des publications…",
  "tanisBaslik": "Rencontre",
  "tanisTanit": "Présente-toi et rencontre de nouvelles personnes.",
  "tanisAra3": "Cherche ou demande à l'IA…",
  "aiAraniyor": "L'IA cherche…",
  "aiIleAra": "Recherche intelligente par IA",
  "aiAraIpuc": "Ex : « Quelqu'un célibataire en Ukraine, 30-40 ans, pour le mariage »",
  "aiAramaSonucVar": "L'IA a trouvé ceci pour toi",
  "aiSonucYok": "L'IA n'a trouvé personne de convenable",
  "tanisHepsi2": "Tous",
  "tanisKadinlar": "Femmes",
  "tanisErkekler": "Hommes",
  "tanisKartDuzenle": "Modifier ma fiche",
  "tanisKartOlustur": "Créer ma fiche",
  "tanisanlar": "Veulent faire des rencontres",
  "tanisYukleniyor": "Chargement…",
  "tanisAramaBos": "Personne ne correspond à ta recherche.",
  "tanisBos": "Personne n'a encore créé de fiche. Sois le premier — crée la tienne en haut !",
  "durBekar": "Célibataire",
  "durEvli": "Marié(e)",
  "durIliski": "En couple",
  "durBosanmis": "Divorcé(e)",
  "arArkadaslik": "Amitié",
  "arSohbet": "Discuter",
  "arFlort": "Flirt",
  "arEvlilik": "Mariage",
  "tanisSeninKartin": "Ta fiche",
  "uzaginda": "de distance",
  "tanisDuzenle": "Modifier ma fiche",
  "tanisBegenildi": "Aimé",
  "tanisBegen": "J'aime",
  "ozelAIbas": "Ton propre ami IA",
  "ozelAInot": "Crée un compagnon de discussion RIEN QUE pour toi avec la photo, le nom, l'âge et la ville de quelqu'un que tu aimes — et discute avec lui sous cette identité. (C'est une intelligence artificielle 🤖, pas une vraie personne.)",
  "ozelAIolustur": "Crée ta propre IA",
  "ozelSeninki": "Le tien",
  "tanisSohbetEt": "Discuter",
  "ozelAIformNot": "Un compagnon de discussion rien que pour toi avec les infos de quelqu'un que tu aimes. C'est une intelligence artificielle 🤖 — pas une vraie personne.",
  "ozelAIfoto": "Ajouter une photo",
  "ozelAIad": "Prénom",
  "ozelAIsoyad": "Nom",
  "ozelAIyas": "Âge",
  "ozelAIsehir": "Ville",
  "ozelAIbasla": "Créer et discuter",
  "tanisAIbas": "Amis de discussion IA",
  "tanisAInot": "Ce ne sont pas de vraies personnes — ce sont les amis IA de GLOXORG. Tu peux discuter quand tu veux, ils se présentent d'eux-mêmes 💬",
  "yapayZeka": "Intelligence Artificielle",
  "tanisKartim": "Ma Fiche",
  "tanisFormNot": "Téléverse tes propres photos (1-3), mets le nom que tu veux, présente-toi brièvement. Si tu ne veux pas, tu n'apparaîtras pas dans la liste.",
  "tanisAdYer": "Nom affiché (celui que tu veux)",
  "tanisCinsiyet": "Sexe",
  "tanisKadin": "Femme",
  "tanisErkek": "Homme",
  "tanisIstege": "Facultatif — remplis si tu veux",
  "tanisYas": "Âge",
  "tanisNeIcin": "Pour quoi veux-tu faire des rencontres ?",
  "tanisBioYer": "Courte présentation : parle de toi…",
  "tanisKaydediliyor": "Enregistrement…",
  "tanisKaydet": "Enregistrer et publier",
  "tanisKaldir": "Masquer de la liste",
  "tanisAIsohbetUyari": "C'est une IA — pas une vraie personne. Ne donne ni infos personnelles ni argent.",
  "tanisAIbasla": "Écris un bonjour et commence à discuter !",
  "tanisAIyaz": "Écris un message…",
  "cizim": "dessin",
  "resimHazirlaniyor": "Préparation de l'image…",
  "resim": "image",
  "resimEski": "Cette image n'est pas arrivée — tu la veux à nouveau ?",
  "resimOlmadi": "Impossible de créer l'image",
  "gloxSes": "Voix de Gloxoo",
  "sesOrnek": "Bonjour, je suis Gloxoo. Ma voix ressemblera à ça.",
  "ghEpostaKabul": "Utilise gloxorg.com ou un e-mail connu comme Gmail, Outlook, Yahoo, iCloud. Les adresses inventées ne sont pas acceptées.",
  "ghSifreKural": "Le mot de passe doit contenir au moins 8 caractères, dont des lettres et des chiffres.",
  "ghSifreUyusmuyor": "Les deux mots de passe ne correspondent pas.",
  "ghEpostaVar": "Cet e-mail est déjà enregistré, tu peux te connecter.",
  "ghGirisYanlis": "E-mail ou mot de passe incorrect. Si tu n'as pas de compte, INSCRIS-TOI en haut. (Si tu t'es déjà connecté avec Google/Microsoft, utilise ce bouton.)",
  "ghSifreKisa": "Le mot de passe doit contenir au moins 6 caractères.",
  "ghVarSifreYanlis": "Cet e-mail est enregistré mais le mot de passe est incorrect. (Si tu l'as créé avec Google, connecte-toi avec le bouton Google.)",
  "uyeMusteri": "Client",
  "profilPasaport": "Passeport Professionnel",
  "profilBaslik": "Mon Profil GLOXORG",
  "profilYukleniyor": "Chargement...",
  "profilHakkinda": "À propos",
  "profilDeneyim": "Expérience",
  "profilYil": "ans",
  "profilHizmetler": "Services",
  "profilFiyat": "Fourchette de prix",
  "profilEksik": "Ajoute tes informations professionnelles — touche Modifier ci-dessus.",
  "profilAkis": "Mon fil · Portfolio",
  "profilAkisBos": "Tes travaux, photos et vidéos apparaîtront ici. (Publication bientôt disponible)",
  "profilAd": "Prénom",
  "profilSoyad": "Nom",
  "profilTelefon": "Téléphone",
  "profilKonum": "Lieu (ville/pays)",
  "profilMeslek": "Métier",
  "profilHizmetlerVir": "Services (sépare par des virgules)",
  "profilFiyatMin": "Prix min",
  "profilFiyatMax": "Prix max",
  "profilKaydediliyor": "Enregistrement...",
  "belYazdir": "Imprimer",
  "belBoyut": "Taille / Vertical",
  "belDikeyYazi": "Texte vertical",
  "belYaziTipi": "Police",
  "belYaziBoyut": "Taille",
  "belRenk": "Couleur",
  "belNormal": "Normal",
  "belBoyutIpucu": "Avec － ＋ sur l'en-tête de colonne, règle la LARGEUR ; avec － ＋ sur le numéro à gauche, la HAUTEUR. Le bouton ⇅ met la colonne à la VERTICALE (de bas en haut). Affine les colonnes pour tenir en A4.",
  "muhPencereKapat": "Fermer la fenêtre",
  "belBoyutKisa": "－ ＋ rétrécir/élargir · ⇅ texte vertical · affine les colonnes pour A4",
  "saCek": "Prendre une photo",
  "saGaleri": "Depuis la galerie",
  "saModellerim": "Mes modèles",
  "saKaydet": "Enregistrer dans Mes modèles",
  "saKaydedildi": "Enregistré",
  "saModelSilOnay": "Supprimer ce modèle ?",
  "saGaleriBos": "Aucun modèle enregistré. Crées-en un puis appuie sur 'Enregistrer dans Mes modèles'.",
  "aitCanli": "IA en direct",
  "aitSac": "Change de coiffure",
  "aitKiyafet": "Essaie des vêtements",
  "aitMakyaj": "Maquillage & ongles",
  "aitSor": "Demande à Gloxoo",
  "aitResim": "Images & dessin",
  "aitMuhasebe": "Comptabilité & documents",
  "aitAynaBtn": "Miroir virtuel",
  "aitGloxBtn": "Demande à Gloxoo",
  "aitAlt": "Essaie coiffures/vêtements sur ta photo, demande tout à Gloxoo — instantanément, dans ta langue."
 },
 "it": {
  "akBuyut": "Tocca per ingrandire",
  "tekrar": "Riprova",
  "tanismaFotoGerek": "Aggiungi almeno 1 foto.",
  "tanismaHata": "Foto non caricata, riprova.",
  "tanismaKaydedildi": "La tua scheda è pronta! Ora sei visibile nella Community.",
  "tanismaCikOnay": "Vuoi nascondere la tua scheda? Non apparirai più nella lista (le foto non vengono cancellate, puoi riattivarla quando vuoi).",
  "ozelAIadGir": "Scrivi prima un nome.",
  "beyinKredi": "In questo momento la mente testuale di Gloxoo è sovraccarica o senza crediti 🙏 (È un conteggio separato dai crediti immagini.) Riprovi tra qualche minuto? Se continua, avvisa il proprietario di GLOXORG — si risolve in poco tempo.",
  "cizimHazir": "Ecco il mio disegno 🎨",
  "cumaHazir": "Ho preparato per te un post speciale del Venerdì 🤲🌸",
  "resimUretiliyor": "Sto preparando l'immagine 🎨",
  "resimZamanAsimi": "L'immagine non è arrivata in tempo, riprovi?",
  "indirilemedi": "Download non riuscito",
  "paylasilamadi": "Condivisione non riuscita",
  "resimIndiPaylas": "Immagine scaricata — puoi condividerla da lì 📤",
  "kopyalanamadi": "Copia non riuscita",
  "resimKopyalandi": "Immagine copiata 📋",
  "resimIndiKopya": "Immagine scaricata 📄",
  "resimPaylasima": "Immagine pronta per la condivisione — se vuoi aggiungi un testo e condividi su GLOXORG 📤",
  "sbpGloxooSor": "Chiedi a Gloxoo",
  "feedYukleniyor": "I post stanno arrivando…",
  "tanisBaslik": "Conosci",
  "tanisTanit": "Presentati e conosci nuove persone.",
  "tanisAra3": "Cerca o chiedi all'intelligenza artificiale…",
  "aiAraniyor": "L'intelligenza artificiale sta cercando…",
  "aiIleAra": "Ricerca intelligente con l'IA",
  "aiAraIpuc": "Es: “In Ucraina, single, 30-40 anni, qualcuno per il matrimonio”",
  "aiAramaSonucVar": "L'IA ha trovato per te",
  "aiSonucYok": "L'IA non ha trovato nessuno adatto",
  "tanisHepsi2": "Tutti",
  "tanisKadinlar": "Donne",
  "tanisErkekler": "Uomini",
  "tanisKartDuzenle": "Modifica la mia scheda",
  "tanisKartOlustur": "Crea la mia scheda",
  "tanisanlar": "Chi vuole conoscere",
  "tanisYukleniyor": "Caricamento…",
  "tanisAramaBos": "Nessuno corrisponde alla tua ricerca.",
  "tanisBos": "Ancora nessuno ha creato una scheda. Sii il primo — crea la tua qui sopra!",
  "durBekar": "Single",
  "durEvli": "Sposato/a",
  "durIliski": "Impegnato/a",
  "durBosanmis": "Divorziato/a",
  "arArkadaslik": "Amicizia",
  "arSohbet": "Chiacchierare",
  "arFlort": "Flirt",
  "arEvlilik": "Matrimonio",
  "tanisSeninKartin": "La tua scheda",
  "uzaginda": "di distanza",
  "tanisDuzenle": "Modifica la mia scheda",
  "tanisBegenildi": "Piace",
  "tanisBegen": "Mi piace",
  "ozelAIbas": "Il tuo amico con intelligenza artificiale",
  "ozelAInot": "Crea un compagno di chat TUTTO tuo con la foto, il nome, l'età e la città di una persona che ti piace — e parla con lui con quell'identità. (È un'intelligenza artificiale 🤖, non una persona reale.)",
  "ozelAIolustur": "Crea la tua intelligenza artificiale",
  "ozelSeninki": "Il tuo",
  "tanisSohbetEt": "Chatta",
  "ozelAIformNot": "Un compagno di chat su misura con i dati di una persona che ti piace. È un'intelligenza artificiale 🤖 — non una persona reale.",
  "ozelAIfoto": "Aggiungi foto",
  "ozelAIad": "Nome",
  "ozelAIsoyad": "Cognome",
  "ozelAIyas": "Età",
  "ozelAIsehir": "Città",
  "ozelAIbasla": "Crea e chatta",
  "tanisAIbas": "Amici di chat con intelligenza artificiale",
  "tanisAInot": "Non sono persone reali — sono gli amici IA di GLOXORG. Puoi chattare quando vuoi, si presenteranno 💬",
  "yapayZeka": "Intelligenza Artificiale",
  "tanisKartim": "La mia scheda",
  "tanisFormNot": "Carica le tue foto (1-3), scrivi il nome che vuoi, presentati brevemente. Se non vuoi, non apparirai nella lista.",
  "tanisAdYer": "Nome visibile (come vuoi)",
  "tanisCinsiyet": "Sesso",
  "tanisKadin": "Donna",
  "tanisErkek": "Uomo",
  "tanisIstege": "Facoltativo — compila se vuoi",
  "tanisYas": "Età",
  "tanisNeIcin": "Perché vuoi conoscere qualcuno?",
  "tanisBioYer": "Breve presentazione: parla di te…",
  "tanisKaydediliyor": "Salvataggio…",
  "tanisKaydet": "Salva e pubblica",
  "tanisKaldir": "Nascondi dalla lista",
  "tanisAIsohbetUyari": "È un'intelligenza artificiale — non una persona reale. Non dare dati personali/denaro.",
  "tanisAIbasla": "Scrivi un saluto e inizia a chattare!",
  "tanisAIyaz": "Scrivi un messaggio…",
  "cizim": "disegno",
  "resimHazirlaniyor": "Immagine in preparazione…",
  "resim": "immagine",
  "resimEski": "Questa immagine non è arrivata — la rivuoi?",
  "resimOlmadi": "Impossibile generare l'immagine",
  "gloxSes": "Voce di Gloxoo",
  "sesOrnek": "Ciao, sono Gloxoo. La mia voce sarà così.",
  "ghEpostaKabul": "Usa gloxorg.com oppure un'email nota come Gmail, Outlook, Yahoo, iCloud. Gli indirizzi inventati non sono accettati.",
  "ghSifreKural": "La password deve avere almeno 8 caratteri e contenere lettere + numeri.",
  "ghSifreUyusmuyor": "Le due password non coincidono.",
  "ghEpostaVar": "Questa email è già registrata, puoi accedere.",
  "ghGirisYanlis": "Email o password errata. Se non hai un account, ISCRIVITI qui sopra. (Se prima hai effettuato l'accesso con Google/Microsoft, usa quel pulsante.)",
  "ghSifreKisa": "La password deve avere almeno 6 caratteri.",
  "ghVarSifreYanlis": "Questa email è registrata ma la password è errata. (Se l'hai creata con Google, accedi con il pulsante Google.)",
  "uyeMusteri": "Cliente",
  "profilPasaport": "Passaporto Professionale",
  "profilBaslik": "Il mio profilo GLOXORG",
  "profilYukleniyor": "Caricamento...",
  "profilHakkinda": "Informazioni",
  "profilDeneyim": "Esperienza",
  "profilYil": "anni",
  "profilHizmetler": "Servizi",
  "profilFiyat": "Fascia di prezzo",
  "profilEksik": "Aggiungi le tue informazioni professionali — tocca Modifica qui sopra.",
  "profilAkis": "Il mio flusso · Portfolio",
  "profilAkisBos": "I tuoi lavori, foto e video appariranno qui. (Condivisione in arrivo)",
  "profilAd": "Nome",
  "profilSoyad": "Cognome",
  "profilTelefon": "Telefono",
  "profilKonum": "Località (città/paese)",
  "profilMeslek": "Professione",
  "profilHizmetlerVir": "Servizi (separati da virgola)",
  "profilFiyatMin": "Prezzo min",
  "profilFiyatMax": "Prezzo max",
  "profilKaydediliyor": "Salvataggio...",
  "belYazdir": "Stampa",
  "belBoyut": "Dimensione / Verticale",
  "belDikeyYazi": "Testo verticale",
  "belYaziTipi": "Carattere",
  "belYaziBoyut": "Dimensione",
  "belRenk": "Colore",
  "belNormal": "Normale",
  "belBoyutIpucu": "Con － ＋ nell'intestazione di colonna regoli la LARGHEZZA, con － ＋ sul numero a sinistra l'ALTEZZA. Il pulsante ⇅ rende la colonna VERTICALE (dal basso verso l'alto). Restringi le colonne per stare in A4.",
  "muhPencereKapat": "Chiudi finestra",
  "belBoyutKisa": "－ ＋ restringi/allarga · ⇅ testo verticale · restringi le colonne per A4",
  "saCek": "Scatta foto",
  "saGaleri": "Dalla galleria",
  "saModellerim": "I miei modelli",
  "saKaydet": "Salva nei miei modelli",
  "saKaydedildi": "Salvato",
  "saModelSilOnay": "Eliminare questo modello?",
  "saGaleriBos": "Ancora nessun modello salvato. Creane uno e tocca 'Salva nei miei modelli'.",
  "aitCanli": "IA dal vivo",
  "aitSac": "Cambia capelli",
  "aitKiyafet": "Prova vestiti",
  "aitMakyaj": "Trucco & unghie",
  "aitSor": "Chiedi a Gloxoo",
  "aitResim": "Immagini & disegno",
  "aitMuhasebe": "Contabilità & documenti",
  "aitAynaBtn": "Specchio virtuale",
  "aitGloxBtn": "Chiedi a Gloxoo",
  "aitAlt": "Prova acconciature/abiti sulla tua foto, chiedi tutto a Gloxoo — subito, nella tua lingua."
 },
 "pt": {
  "akBuyut": "Toque para ampliar",
  "tekrar": "Tentar de novo",
  "tanismaFotoGerek": "Adicione pelo menos 1 foto.",
  "tanismaHata": "Não foi possível enviar a foto, tente de novo.",
  "tanismaKaydedildi": "Seu cartão está pronto! Agora você aparece na Comunidade.",
  "tanismaCikOnay": "Quer ocultar seu cartão? Você não aparecerá mais na lista (suas fotos não são apagadas, pode reativar quando quiser).",
  "ozelAIadGir": "Escreva um nome primeiro.",
  "beyinKredi": "No momento a mente de texto do Gloxoo está sobrecarregada ou sem créditos 🙏 (Isso é uma conta separada dos créditos de imagem.) Pode tentar de novo em alguns minutos? Se continuar, avise o dono do GLOXORG — resolve rápido.",
  "cizimHazir": "Aqui está meu desenho 🎨",
  "cumaHazir": "Preparei uma publicação especial de Sexta-feira para você 🤲🌸",
  "resimUretiliyor": "Estou preparando a imagem 🎨",
  "resimZamanAsimi": "A imagem não chegou a tempo, pode tentar de novo?",
  "indirilemedi": "Não foi possível baixar",
  "paylasilamadi": "Não foi possível compartilhar",
  "resimIndiPaylas": "Imagem baixada — pode compartilhar a partir daí 📤",
  "kopyalanamadi": "Não foi possível copiar",
  "resimKopyalandi": "Imagem copiada 📋",
  "resimIndiKopya": "Imagem baixada 📄",
  "resimPaylasima": "Imagem pronta para compartilhar — se quiser, adicione um texto e compartilhe no GLOXORG 📤",
  "sbpGloxooSor": "Pergunte ao Gloxoo",
  "feedYukleniyor": "As publicações estão chegando…",
  "tanisBaslik": "Conheça",
  "tanisTanit": "Apresente-se e conheça novas pessoas.",
  "tanisAra3": "Pesquise ou pergunte à inteligência artificial…",
  "aiAraniyor": "A inteligência artificial está pesquisando…",
  "aiIleAra": "Pesquisa inteligente com IA",
  "aiAraIpuc": "Ex: “Na Ucrânia, solteira, 30-40 anos, alguém para casamento”",
  "aiAramaSonucVar": "A IA encontrou para você",
  "aiSonucYok": "A IA não encontrou ninguém adequado",
  "tanisHepsi2": "Todos",
  "tanisKadinlar": "Mulheres",
  "tanisErkekler": "Homens",
  "tanisKartDuzenle": "Editar meu cartão",
  "tanisKartOlustur": "Criar meu cartão",
  "tanisanlar": "Quem quer se conhecer",
  "tanisYukleniyor": "Carregando…",
  "tanisAramaBos": "Ninguém corresponde à sua pesquisa.",
  "tanisBos": "Ainda ninguém criou um cartão. Seja o primeiro — crie o seu acima!",
  "durBekar": "Solteiro(a)",
  "durEvli": "Casado(a)",
  "durIliski": "Em um relacionamento",
  "durBosanmis": "Divorciado(a)",
  "arArkadaslik": "Amizade",
  "arSohbet": "Conversa",
  "arFlort": "Paquera",
  "arEvlilik": "Casamento",
  "tanisSeninKartin": "Seu cartão",
  "uzaginda": "de distância",
  "tanisDuzenle": "Editar meu cartão",
  "tanisBegenildi": "Curtido",
  "tanisBegen": "Curtir",
  "ozelAIbas": "Seu amigo de inteligência artificial",
  "ozelAInot": "Crie um companheiro de conversa SÓ SEU com a foto, o nome, a idade e a cidade de alguém de quem você gosta — e converse com ele com essa identidade. (Isto é uma inteligência artificial 🤖, não uma pessoa real.)",
  "ozelAIolustur": "Crie sua própria inteligência artificial",
  "ozelSeninki": "O seu",
  "tanisSohbetEt": "Conversar",
  "ozelAIformNot": "Um companheiro de conversa feito sob medida com os dados de alguém de quem você gosta. Isto é uma inteligência artificial 🤖 — não uma pessoa real.",
  "ozelAIfoto": "Adicionar foto",
  "ozelAIad": "Nome",
  "ozelAIsoyad": "Sobrenome",
  "ozelAIyas": "Idade",
  "ozelAIsehir": "Cidade",
  "ozelAIbasla": "Criar e conversar",
  "tanisAIbas": "Amigos de conversa com inteligência artificial",
  "tanisAInot": "Estes não são pessoas reais — são os amigos de IA do GLOXORG. Você pode conversar quando quiser, eles se apresentam 💬",
  "yapayZeka": "Inteligência Artificial",
  "tanisKartim": "Meu cartão",
  "tanisFormNot": "Envie suas próprias fotos (1-3), escreva o nome que quiser, apresente-se brevemente. Se não quiser, não aparecerá na lista.",
  "tanisAdYer": "Nome visível (o que quiser)",
  "tanisCinsiyet": "Sexo",
  "tanisKadin": "Mulher",
  "tanisErkek": "Homem",
  "tanisIstege": "Opcional — preencha se quiser",
  "tanisYas": "Idade",
  "tanisNeIcin": "Por que você quer conhecer alguém?",
  "tanisBioYer": "Breve apresentação: fale sobre você…",
  "tanisKaydediliyor": "Salvando…",
  "tanisKaydet": "Salvar e publicar",
  "tanisKaldir": "Ocultar da lista",
  "tanisAIsohbetUyari": "Isto é uma inteligência artificial — não uma pessoa real. Não forneça dados pessoais/dinheiro.",
  "tanisAIbasla": "Escreva um oi e comece a conversar!",
  "tanisAIyaz": "Escreva uma mensagem…",
  "cizim": "desenho",
  "resimHazirlaniyor": "Imagem sendo preparada…",
  "resim": "imagem",
  "resimEski": "Esta imagem não chegou — quer de novo?",
  "resimOlmadi": "Não foi possível gerar a imagem",
  "gloxSes": "Voz do Gloxoo",
  "sesOrnek": "Olá, eu sou o Gloxoo. Minha voz será assim.",
  "ghEpostaKabul": "Use gloxorg.com ou um e-mail conhecido como Gmail, Outlook, Yahoo, iCloud. Endereços inventados não são aceitos.",
  "ghSifreKural": "A senha deve ter pelo menos 8 caracteres e conter letras + números.",
  "ghSifreUyusmuyor": "As duas senhas não são iguais.",
  "ghEpostaVar": "Este e-mail já está cadastrado, você pode entrar.",
  "ghGirisYanlis": "E-mail ou senha incorretos. Se não tiver conta, CADASTRE-SE acima. (Se antes entrou com Google/Microsoft, use aquele botão.)",
  "ghSifreKisa": "A senha deve ter pelo menos 6 caracteres.",
  "ghVarSifreYanlis": "Este e-mail está cadastrado, mas a senha está incorreta. (Se criou com Google, entre pelo botão do Google.)",
  "uyeMusteri": "Cliente",
  "profilPasaport": "Passaporte Profissional",
  "profilBaslik": "Meu perfil GLOXORG",
  "profilYukleniyor": "Carregando...",
  "profilHakkinda": "Sobre",
  "profilDeneyim": "Experiência",
  "profilYil": "anos",
  "profilHizmetler": "Serviços",
  "profilFiyat": "Faixa de preço",
  "profilEksik": "Adicione suas informações profissionais — toque em Editar acima.",
  "profilAkis": "Meu feed · Portfólio",
  "profilAkisBos": "Seus trabalhos, fotos e vídeos aparecerão aqui. (Compartilhamento em breve)",
  "profilAd": "Nome",
  "profilSoyad": "Sobrenome",
  "profilTelefon": "Telefone",
  "profilKonum": "Localização (cidade/país)",
  "profilMeslek": "Profissão",
  "profilHizmetlerVir": "Serviços (separados por vírgula)",
  "profilFiyatMin": "Preço mín",
  "profilFiyatMax": "Preço máx",
  "profilKaydediliyor": "Salvando...",
  "belYazdir": "Imprimir",
  "belBoyut": "Tamanho / Vertical",
  "belDikeyYazi": "Texto vertical",
  "belYaziTipi": "Fonte",
  "belYaziBoyut": "Tamanho",
  "belRenk": "Cor",
  "belNormal": "Normal",
  "belBoyutIpucu": "Use － ＋ no cabeçalho da coluna para a LARGURA e － ＋ no número à esquerda para a ALTURA. O botão ⇅ deixa a coluna VERTICAL (de baixo para cima). Estreite as colunas para caber em A4.",
  "muhPencereKapat": "Fechar janela",
  "belBoyutKisa": "－ ＋ estreitar/alargar · ⇅ texto vertical · estreite as colunas para A4",
  "saCek": "Tirar foto",
  "saGaleri": "Da galeria",
  "saModellerim": "Meus modelos",
  "saKaydet": "Salvar em Meus modelos",
  "saKaydedildi": "Salvo",
  "saModelSilOnay": "Excluir este modelo?",
  "saGaleriBos": "Ainda sem modelos salvos. Crie um e toque em 'Salvar em Meus modelos'.",
  "aitCanli": "IA ao vivo",
  "aitSac": "Mude o cabelo",
  "aitKiyafet": "Experimente roupas",
  "aitMakyaj": "Maquiagem & unhas",
  "aitSor": "Pergunte ao Gloxoo",
  "aitResim": "Imagens & desenho",
  "aitMuhasebe": "Contabilidade & documentos",
  "aitAynaBtn": "Espelho virtual",
  "aitGloxBtn": "Pergunte ao Gloxoo",
  "aitAlt": "Experimente cabelos/roupas na sua foto, pergunte tudo ao Gloxoo — na hora, no seu idioma."
 },
 "ar": {
  "akBuyut": "المس للتكبير",
  "tekrar": "إعادة",
  "tanismaFotoGerek": "أضف صورة واحدة على الأقل.",
  "tanismaHata": "تعذّر رفع الصورة، حاول مجددًا.",
  "tanismaKaydedildi": "بطاقة تعارفك جاهزة! أصبحت ظاهرًا في المجتمع الآن.",
  "tanismaCikOnay": "هل تريد إخفاء بطاقة تعارفك؟ لن تظهر في القائمة بعد الآن (صورك لا تُحذف، يمكنك تفعيلها مجددًا).",
  "ozelAIadGir": "اكتب اسمًا أولًا.",
  "beyinKredi": "يبدو أن عقل الكتابة لدى Gloxoo مشغول الآن أو نفد رصيده 🙏 (هذا حساب منفصل عن رصيد الصور.) هل تحاول بعد دقائق؟ إن استمر الأمر أبلغ صاحب GLOXORG — يُفتح سريعًا.",
  "cizimHazir": "ها قد رسمت 🎨",
  "cumaHazir": "جهّزت لك منشور جمعة خاصًا 🤲🌸",
  "resimUretiliyor": "أجهّز الصورة 🎨",
  "resimZamanAsimi": "لم تصل الصورة في الوقت، هل تحاول مجددًا؟",
  "indirilemedi": "تعذّر التنزيل",
  "paylasilamadi": "تعذّرت المشاركة",
  "resimIndiPaylas": "تم تنزيل الصورة — يمكنك مشاركتها من هناك 📤",
  "kopyalanamadi": "تعذّر النسخ",
  "resimKopyalandi": "تم نسخ الصورة 📋",
  "resimIndiKopya": "تم تنزيل الصورة 📄",
  "resimPaylasima": "نُقلت الصورة للمشاركة — أضف نصًا وشاركها على GLOXORG إن أردت 📤",
  "sbpGloxooSor": "اسأل Gloxoo",
  "feedYukleniyor": "المنشورات في الطريق…",
  "tanisBaslik": "تعارف",
  "tanisTanit": "عرّف بنفسك، وتعرّف على أناس جدد.",
  "tanisAra3": "ابحث أو اسأل الذكاء الاصطناعي…",
  "aiAraniyor": "الذكاء الاصطناعي يبحث…",
  "aiIleAra": "بحث ذكي بالذكاء الاصطناعي",
  "aiAraIpuc": "مثال: «شخص أعزب في أوكرانيا، 30-40 سنة، للزواج»",
  "aiAramaSonucVar": "وجد لك الذكاء الاصطناعي",
  "aiSonucYok": "لم يجد الذكاء الاصطناعي أحدًا مناسبًا",
  "tanisHepsi2": "الكل",
  "tanisKadinlar": "النساء",
  "tanisErkekler": "الرجال",
  "tanisKartDuzenle": "تعديل بطاقة تعارفي",
  "tanisKartOlustur": "إنشاء بطاقة تعارفي",
  "tanisanlar": "من يرغبون بالتعارف",
  "tanisYukleniyor": "جارٍ التحميل…",
  "tanisAramaBos": "لا أحد يطابق بحثك.",
  "tanisBos": "لم يُنشئ أحد بطاقة بعد. كن الأول — أنشئ بطاقتك من الأعلى!",
  "durBekar": "أعزب",
  "durEvli": "متزوج",
  "durIliski": "مرتبط",
  "durBosanmis": "مطلّق",
  "arArkadaslik": "صداقة",
  "arSohbet": "دردشة",
  "arFlort": "مغازلة",
  "arEvlilik": "زواج",
  "tanisSeninKartin": "بطاقتك",
  "uzaginda": "على بُعد",
  "tanisDuzenle": "تعديل بطاقتي",
  "tanisBegenildi": "أعجبك",
  "tanisBegen": "إعجاب",
  "ozelAIbas": "صديقك من الذكاء الاصطناعي",
  "ozelAInot": "أنشئ صديق دردشة خاصًا بك بصورة شخص تحبه واسمه وعمره ومدينته — وتحدّث معه بتلك الهوية. (هذا ذكاء اصطناعي 🤖، وليس شخصًا حقيقيًا.)",
  "ozelAIolustur": "أنشئ ذكاءك الاصطناعي الخاص",
  "ozelSeninki": "خاصتك",
  "tanisSohbetEt": "دردش",
  "ozelAIformNot": "صديق دردشة خاص بك بمعلومات شخص تحبه. هذا ذكاء اصطناعي 🤖 — وليس شخصًا حقيقيًا.",
  "ozelAIfoto": "أضف صورة",
  "ozelAIad": "الاسم",
  "ozelAIsoyad": "اللقب",
  "ozelAIyas": "العمر",
  "ozelAIsehir": "المدينة",
  "ozelAIbasla": "أنشئ وابدأ الدردشة",
  "tanisAIbas": "أصدقاء دردشة بالذكاء الاصطناعي",
  "tanisAInot": "هؤلاء ليسوا أشخاصًا حقيقيين — إنهم أصدقاء GLOXORG بالذكاء الاصطناعي. دردش متى شئت، وسيعرّفون بأنفسهم 💬",
  "yapayZeka": "ذكاء اصطناعي",
  "tanisKartim": "بطاقة تعارفي",
  "tanisFormNot": "ارفع صورك (1-3)، واكتب أي اسم تريد، وعرّف بنفسك باختصار. إن لم ترغب لن تظهر في القائمة.",
  "tanisAdYer": "الاسم الظاهر (ما تشاء)",
  "tanisCinsiyet": "الجنس",
  "tanisKadin": "أنثى",
  "tanisErkek": "ذكر",
  "tanisIstege": "اختياري — املأه إن أردت",
  "tanisYas": "العمر",
  "tanisNeIcin": "لأي غرض تريد التعارف؟",
  "tanisBioYer": "تعريف قصير: تحدّث عن نفسك…",
  "tanisKaydediliyor": "جارٍ الحفظ…",
  "tanisKaydet": "احفظ وانشر",
  "tanisKaldir": "إخفاء من القائمة",
  "tanisAIsohbetUyari": "هذا ذكاء اصطناعي — وليس شخصًا حقيقيًا. لا تعطِ معلومات شخصية أو مالًا.",
  "tanisAIbasla": "اكتب تحية، وابدأ الدردشة!",
  "tanisAIyaz": "اكتب رسالة…",
  "cizim": "رسم",
  "resimHazirlaniyor": "جارٍ تحضير الصورة…",
  "resim": "صورة",
  "resimEski": "لم تصل هذه الصورة — أتريدها من جديد؟",
  "resimOlmadi": "تعذّر إنشاء الصورة",
  "gloxSes": "صوت Gloxoo",
  "sesOrnek": "مرحبًا، أنا Gloxoo. هكذا سيكون صوتي.",
  "ghEpostaKabul": "يُرجى استخدام gloxorg.com أو بريد معروف مثل Gmail أو Outlook أو Yahoo أو iCloud. العناوين المختلقة غير مقبولة.",
  "ghSifreKural": "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي حروفًا وأرقامًا.",
  "ghSifreUyusmuyor": "كلمتا المرور غير متطابقتين.",
  "ghEpostaVar": "هذا البريد مسجّل مسبقًا، يمكنك تسجيل الدخول.",
  "ghGirisYanlis": "البريد أو كلمة المرور خاطئة. إن لم يكن لديك حساب اضغط انضمّ من الأعلى. (إن سجّلت دخولك سابقًا عبر Google/Microsoft فاستخدم ذلك الزر.)",
  "ghSifreKisa": "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
  "ghVarSifreYanlis": "هذا البريد مسجّل لكن كلمة المرور خاطئة. (إن أنشأته عبر Google فادخل بزر Google.)",
  "uyeMusteri": "عميل",
  "profilPasaport": "جواز المهنة",
  "profilBaslik": "ملفي في GLOXORG",
  "profilYukleniyor": "جارٍ التحميل...",
  "profilHakkinda": "نبذة",
  "profilDeneyim": "الخبرة",
  "profilYil": "سنة",
  "profilHizmetler": "الخدمات",
  "profilFiyat": "نطاق السعر",
  "profilEksik": "أضف معلوماتك المهنية — المس تعديل بالأعلى.",
  "profilAkis": "سِجلّي · معرض الأعمال",
  "profilAkisBos": "أعمالك وصورك وفيديوهاتك ستظهر هنا. (المشاركة قريبًا)",
  "profilAd": "الاسم",
  "profilSoyad": "اللقب",
  "profilTelefon": "الهاتف",
  "profilKonum": "الموقع (مدينة/دولة)",
  "profilMeslek": "المهنة",
  "profilHizmetlerVir": "الخدمات (افصل بفاصلة)",
  "profilFiyatMin": "أقل سعر",
  "profilFiyatMax": "أعلى سعر",
  "profilKaydediliyor": "جارٍ الحفظ...",
  "belYazdir": "طباعة",
  "belBoyut": "الحجم / عمودي",
  "belDikeyYazi": "نص عمودي",
  "belYaziTipi": "الخط",
  "belYaziBoyut": "الحجم",
  "belRenk": "اللون",
  "belNormal": "عادي",
  "belBoyutIpucu": "بـ － ＋ في رأس العمود تضبط العرض، وبـ － ＋ عند الرقم على اليسار الارتفاع. زر ⇅ يجعل العمود عموديًا (من الأسفل للأعلى). صغّر العرض ليتسع في A4.",
  "muhPencereKapat": "إغلاق النافذة",
  "belBoyutKisa": "－ ＋ للتضييق/التوسيع · ⇅ نص عمودي · صغّر الأعمدة لتناسب A4",
  "saCek": "التقاط صورة",
  "saGaleri": "من المعرض",
  "saModellerim": "نماذجي",
  "saKaydet": "حفظ في نماذجي",
  "saKaydedildi": "تم الحفظ",
  "saModelSilOnay": "حذف هذا النموذج؟",
  "saGaleriBos": "لا نماذج محفوظة بعد. أنشئ نموذجًا ثم اضغط 'حفظ في نماذجي' بالأسفل.",
  "aitCanli": "ذكاء اصطناعي مباشر",
  "aitSac": "غيّر شعرك",
  "aitKiyafet": "جرّب ملابس",
  "aitMakyaj": "مكياج وأظافر",
  "aitSor": "اسأل Gloxoo",
  "aitResim": "صور ورسم",
  "aitMuhasebe": "محاسبة ومستندات",
  "aitAynaBtn": "المرآة الافتراضية",
  "aitGloxBtn": "اسأل Gloxoo",
  "aitAlt": "جرّب تسريحات/ملابس على صورتك واسأل Gloxoo أي شيء — فورًا وبلغتك."
 },
 "hi": {
  "akBuyut": "बड़ा करने के लिए छूएं",
  "tekrar": "फिर से",
  "tanismaFotoGerek": "कम से कम 1 फ़ोटो जोड़ें।",
  "tanismaHata": "फ़ोटो अपलोड नहीं हुई, फिर कोशिश करें।",
  "tanismaKaydedildi": "आपका परिचय कार्ड तैयार है! अब आप समुदाय में दिख रहे हैं।",
  "tanismaCikOnay": "क्या आप अपना परिचय कार्ड छिपाना चाहते हैं? अब आप सूची में नहीं दिखेंगे (आपकी फ़ोटो नहीं मिटेंगी, चाहें तो फिर चालू कर लें)।",
  "ozelAIadGir": "पहले एक नाम लिखें।",
  "beyinKredi": "अभी Gloxoo का लेखन-दिमाग व्यस्त है या उसका क्रेडिट खत्म लगता है 🙏 (यह इमेज क्रेडिट से अलग खाता है।) कुछ मिनट बाद फिर कोशिश करेंगे? अगर यही रहे तो GLOXORG के मालिक को बताएं — जल्दी खुल जाता है।",
  "cizimHazir": "लीजिए, मैंने बना दिया 🎨",
  "cumaHazir": "मैंने आपके लिए खास जुमे की पोस्ट तैयार की है 🤲🌸",
  "resimUretiliyor": "मैं तस्वीर तैयार कर रहा हूं 🎨",
  "resimZamanAsimi": "तस्वीर समय पर नहीं आई, फिर कोशिश करेंगे?",
  "indirilemedi": "डाउनलोड नहीं हुआ",
  "paylasilamadi": "साझा नहीं हुआ",
  "resimIndiPaylas": "तस्वीर डाउनलोड हो गई — वहीं से साझा कर सकते हैं 📤",
  "kopyalanamadi": "कॉपी नहीं हुआ",
  "resimKopyalandi": "तस्वीर कॉपी हो गई 📋",
  "resimIndiKopya": "तस्वीर डाउनलोड हो गई 📄",
  "resimPaylasima": "तस्वीर साझा करने में चली गई — चाहें तो लिखकर GLOXORG पर साझा करें 📤",
  "sbpGloxooSor": "Gloxoo से पूछें",
  "feedYukleniyor": "पोस्ट आ रही हैं…",
  "tanisBaslik": "परिचय",
  "tanisTanit": "अपना परिचय दें, नए लोगों से मिलें।",
  "tanisAra3": "खोजें या AI से पूछें…",
  "aiAraniyor": "AI खोज रहा है…",
  "aiIleAra": "AI से स्मार्ट खोज",
  "aiAraIpuc": "जैसे: “यूक्रेन में कुंवारा, 30-40 साल, शादी के लिए कोई”",
  "aiAramaSonucVar": "AI ने आपके लिए ढूंढा",
  "aiSonucYok": "AI को कोई उपयुक्त व्यक्ति नहीं मिला",
  "tanisHepsi2": "सभी",
  "tanisKadinlar": "महिलाएं",
  "tanisErkekler": "पुरुष",
  "tanisKartDuzenle": "मेरा परिचय कार्ड संपादित करें",
  "tanisKartOlustur": "मेरा परिचय कार्ड बनाएं",
  "tanisanlar": "जो मिलना चाहते हैं",
  "tanisYukleniyor": "लोड हो रहा है…",
  "tanisAramaBos": "आपकी खोज से कोई मेल नहीं खाता।",
  "tanisBos": "अभी तक किसी ने कार्ड नहीं बनाया। आप पहले बनें — ऊपर से अपना कार्ड बनाएं!",
  "durBekar": "कुंवारा",
  "durEvli": "विवाहित",
  "durIliski": "रिश्ते में",
  "durBosanmis": "तलाकशुदा",
  "arArkadaslik": "दोस्ती",
  "arSohbet": "बातचीत",
  "arFlort": "फ़्लर्ट",
  "arEvlilik": "शादी",
  "tanisSeninKartin": "आपका कार्ड",
  "uzaginda": "दूर",
  "tanisDuzenle": "मेरा कार्ड संपादित करें",
  "tanisBegenildi": "पसंद किया",
  "tanisBegen": "पसंद",
  "ozelAIbas": "अपना AI दोस्त",
  "ozelAInot": "किसी प्रिय की फ़ोटो, नाम, उम्र और शहर के साथ अपने लिए एक चैट दोस्त बनाएं — उसी पहचान के साथ बात करें। (यह एक AI है 🤖, असली व्यक्ति नहीं।)",
  "ozelAIolustur": "अपना AI बनाएं",
  "ozelSeninki": "आपका",
  "tanisSohbetEt": "बात करें",
  "ozelAIformNot": "किसी प्रिय की जानकारी के साथ आपके लिए खास चैट दोस्त। यह एक AI है 🤖 — असली व्यक्ति नहीं।",
  "ozelAIfoto": "फ़ोटो जोड़ें",
  "ozelAIad": "नाम",
  "ozelAIsoyad": "उपनाम",
  "ozelAIyas": "उम्र",
  "ozelAIsehir": "शहर",
  "ozelAIbasla": "बनाएं और बात करें",
  "tanisAIbas": "AI चैट दोस्त",
  "tanisAInot": "ये असली लोग नहीं हैं — ये GLOXORG के AI दोस्त हैं। जब चाहें बात करें, वे खुद परिचय देंगे 💬",
  "yapayZeka": "AI",
  "tanisKartim": "मेरा परिचय कार्ड",
  "tanisFormNot": "अपनी फ़ोटो अपलोड करें (1-3), जो चाहें नाम लिखें, संक्षेप में परिचय दें। न चाहें तो सूची में नहीं दिखेंगे।",
  "tanisAdYer": "दिखने वाला नाम (जो चाहें)",
  "tanisCinsiyet": "लिंग",
  "tanisKadin": "महिला",
  "tanisErkek": "पुरुष",
  "tanisIstege": "वैकल्पिक — चाहें तो भरें",
  "tanisYas": "उम्र",
  "tanisNeIcin": "किस लिए मिलना चाहते हैं?",
  "tanisBioYer": "संक्षिप्त परिचय: अपने बारे में बताएं…",
  "tanisKaydediliyor": "सहेजा जा रहा है…",
  "tanisKaydet": "सहेजें और प्रकाशित करें",
  "tanisKaldir": "सूची से छिपाएं",
  "tanisAIsohbetUyari": "यह एक AI है — असली व्यक्ति नहीं। निजी जानकारी/पैसा न दें।",
  "tanisAIbasla": "नमस्ते लिखें, बातचीत शुरू करें!",
  "tanisAIyaz": "संदेश लिखें…",
  "cizim": "चित्र",
  "resimHazirlaniyor": "तस्वीर तैयार हो रही है…",
  "resim": "तस्वीर",
  "resimEski": "यह तस्वीर नहीं आई — फिर से चाहिए?",
  "resimOlmadi": "तस्वीर नहीं बन पाई",
  "gloxSes": "Gloxoo की आवाज़",
  "sesOrnek": "नमस्ते, मैं Gloxoo हूं। मेरी आवाज़ ऐसी होगी।",
  "ghEpostaKabul": "कृपया gloxorg.com या Gmail, Outlook, Yahoo, iCloud जैसा जाना-माना ईमेल इस्तेमाल करें। खुद बनाए पते स्वीकार नहीं होते।",
  "ghSifreKural": "पासवर्ड कम से कम 8 अक्षर का हो और उसमें अक्षर + अंक हों।",
  "ghSifreUyusmuyor": "दोनों पासवर्ड एक जैसे नहीं हैं।",
  "ghEpostaVar": "यह ईमेल पहले से पंजीकृत है, आप लॉगिन कर सकते हैं।",
  "ghGirisYanlis": "ईमेल या पासवर्ड गलत है। खाता नहीं है तो ऊपर से सदस्य बनें। (पहले Google/Microsoft से लॉगिन किया हो तो वही बटन इस्तेमाल करें।)",
  "ghSifreKisa": "पासवर्ड कम से कम 6 अक्षर का हो।",
  "ghVarSifreYanlis": "यह ईमेल पंजीकृत है पर पासवर्ड गलत है। (Google से बनाया हो तो Google बटन से लॉगिन करें।)",
  "uyeMusteri": "ग्राहक",
  "profilPasaport": "पेशा पासपोर्ट",
  "profilBaslik": "मेरी GLOXORG प्रोफ़ाइल",
  "profilYukleniyor": "लोड हो रहा है...",
  "profilHakkinda": "बारे में",
  "profilDeneyim": "अनुभव",
  "profilYil": "साल",
  "profilHizmetler": "सेवाएं",
  "profilFiyat": "मूल्य सीमा",
  "profilEksik": "अपनी पेशेवर जानकारी जोड़ें — ऊपर संपादित करें पर छूएं।",
  "profilAkis": "मेरी फ़ीड · पोर्टफ़ोलियो",
  "profilAkisBos": "आपके काम, फ़ोटो और वीडियो यहां दिखेंगे। (साझा करना जल्द आ रहा है)",
  "profilAd": "नाम",
  "profilSoyad": "उपनाम",
  "profilTelefon": "फ़ोन",
  "profilKonum": "स्थान (शहर/देश)",
  "profilMeslek": "पेशा",
  "profilHizmetlerVir": "सेवाएं (अल्पविराम से अलग करें)",
  "profilFiyatMin": "न्यूनतम मूल्य",
  "profilFiyatMax": "अधिकतम मूल्य",
  "profilKaydediliyor": "सहेजा जा रहा है...",
  "belYazdir": "प्रिंट",
  "belBoyut": "आकार / लंबवत",
  "belDikeyYazi": "लंबवत पाठ",
  "belYaziTipi": "फ़ॉन्ट",
  "belYaziBoyut": "आकार",
  "belRenk": "रंग",
  "belNormal": "सामान्य",
  "belBoyutIpucu": "कॉलम हेडर के － ＋ से चौड़ाई और बाएँ नंबर के － ＋ से ऊँचाई सेट करें। ⇅ बटन उस कॉलम को लंबवत (नीचे से ऊपर) कर देता है। A4 में फ़िट करने के लिए कॉलम पतले करें।",
  "muhPencereKapat": "विंडो बंद करें",
  "belBoyutKisa": "－ ＋ से छोटा/चौड़ा · ⇅ लंबवत पाठ · कॉलम पतले कर A4 में फ़िट करें",
  "saCek": "फ़ोटो लें",
  "saGaleri": "गैलरी से",
  "saModellerim": "मेरे मॉडल",
  "saKaydet": "मेरे मॉडल में सहेजें",
  "saKaydedildi": "सहेजा गया",
  "saModelSilOnay": "इस मॉडल को हटाएं?",
  "saGaleriBos": "अभी कोई सहेजा मॉडल नहीं। एक बनाएं, फिर नीचे 'मेरे मॉडल में सहेजें' दबाएं।",
  "aitCanli": "लाइव AI",
  "aitSac": "बाल बदलें",
  "aitKiyafet": "कपड़े आज़माएं",
  "aitMakyaj": "मेकअप और नाखून",
  "aitSor": "Gloxoo से पूछें",
  "aitResim": "चित्र और ड्रॉइंग",
  "aitMuhasebe": "लेखा और दस्तावेज़",
  "aitAynaBtn": "वर्चुअल मिरर",
  "aitGloxBtn": "Gloxoo से पूछें",
  "aitAlt": "अपनी फ़ोटो पर बाल/कपड़े आज़माएं, Gloxoo से कुछ भी पूछें — तुरंत, आपकी भाषा में।"
 },
 "zh": {
  "akBuyut": "点击放大",
  "tekrar": "重试",
  "tanismaFotoGerek": "请至少添加1张照片。",
  "tanismaHata": "照片上传失败，请重试。",
  "tanismaKaydedildi": "你的交友卡已就绪！现在你已显示在社区中。",
  "tanismaCikOnay": "要隐藏你的交友卡吗？隐藏后将不再显示在列表中（照片不会删除，随时可重新开启）。",
  "ozelAIadGir": "请先输入一个名字。",
  "beyinKredi": "Gloxoo的文字大脑当前繁忙或额度已用完 🙏（这与图片额度是独立的账户。）请几分钟后再试好吗？若持续如此请通知GLOXORG的所有者——很快就会恢复。",
  "cizimHazir": "我画好了 🎨",
  "cumaHazir": "我为你准备了一份专属的周五分享 🤲🌸",
  "resimUretiliyor": "正在生成图片 🎨",
  "resimZamanAsimi": "图片未按时生成，再试一次好吗？",
  "indirilemedi": "下载失败",
  "paylasilamadi": "分享失败",
  "resimIndiPaylas": "图片已下载——你可以从那里分享 📤",
  "kopyalanamadi": "复制失败",
  "resimKopyalandi": "图片已复制 📋",
  "resimIndiKopya": "图片已下载 📄",
  "resimPaylasima": "图片已转到分享——你可以加上文字发到GLOXORG 📤",
  "sbpGloxooSor": "问问Gloxoo",
  "feedYukleniyor": "帖子加载中…",
  "tanisBaslik": "结识",
  "tanisTanit": "介绍自己，结识新朋友。",
  "tanisAra3": "搜索或问问人工智能…",
  "aiAraniyor": "人工智能搜索中…",
  "aiIleAra": "用人工智能智能搜索",
  "aiAraIpuc": "例如：“在乌克兰、单身、30-40岁、想结婚的人”",
  "aiAramaSonucVar": "人工智能为你找到了",
  "aiSonucYok": "人工智能没有找到合适的人",
  "tanisHepsi2": "全部",
  "tanisKadinlar": "女性",
  "tanisErkekler": "男性",
  "tanisKartDuzenle": "编辑我的交友卡",
  "tanisKartOlustur": "创建我的交友卡",
  "tanisanlar": "想结识的人",
  "tanisYukleniyor": "加载中…",
  "tanisAramaBos": "没有符合搜索的人。",
  "tanisBos": "还没有人创建卡片。做第一个吧——在上方创建你自己的卡片！",
  "durBekar": "单身",
  "durEvli": "已婚",
  "durIliski": "有恋人",
  "durBosanmis": "离异",
  "arArkadaslik": "交友",
  "arSohbet": "聊天",
  "arFlort": "约会",
  "arEvlilik": "结婚",
  "tanisSeninKartin": "你的卡片",
  "uzaginda": "外",
  "tanisDuzenle": "编辑我的卡片",
  "tanisBegenildi": "已点赞",
  "tanisBegen": "点赞",
  "ozelAIbas": "你专属的人工智能朋友",
  "ozelAInot": "用你喜欢的人的照片、姓名、年龄和城市，创建一个只属于你的聊天伙伴——以那个身份与它聊天。（这是人工智能 🤖，不是真人。）",
  "ozelAIolustur": "创建你自己的人工智能",
  "ozelSeninki": "你的",
  "tanisSohbetEt": "聊天",
  "ozelAIformNot": "用你喜欢的人的信息，为你打造专属聊天伙伴。这是人工智能 🤖——不是真人。",
  "ozelAIfoto": "添加照片",
  "ozelAIad": "名字",
  "ozelAIsoyad": "姓氏",
  "ozelAIyas": "年龄",
  "ozelAIsehir": "城市",
  "ozelAIbasla": "创建并聊天",
  "tanisAIbas": "人工智能聊天伙伴",
  "tanisAInot": "它们不是真人——是GLOXORG的人工智能朋友。你可以随时聊天，它会自我介绍 💬",
  "yapayZeka": "人工智能",
  "tanisKartim": "我的交友卡",
  "tanisFormNot": "上传你自己的照片（1-3张），写上你想用的名字，简短介绍一下自己。若不愿意，可不显示在列表中。",
  "tanisAdYer": "显示的名字（随你喜欢）",
  "tanisCinsiyet": "性别",
  "tanisKadin": "女",
  "tanisErkek": "男",
  "tanisIstege": "可选——愿意的话可填写",
  "tanisYas": "年龄",
  "tanisNeIcin": "你想为了什么结识？",
  "tanisBioYer": "简短介绍：说说你自己…",
  "tanisKaydediliyor": "保存中…",
  "tanisKaydet": "保存并发布",
  "tanisKaldir": "从列表中隐藏",
  "tanisAIsohbetUyari": "这是人工智能——不是真人。请勿提供个人信息/钱财。",
  "tanisAIbasla": "打个招呼，开始聊天吧！",
  "tanisAIyaz": "输入消息…",
  "cizim": "绘图",
  "resimHazirlaniyor": "图片准备中…",
  "resim": "图片",
  "resimEski": "这张图片没生成——要重新来一张吗？",
  "resimOlmadi": "图片生成失败",
  "gloxSes": "Gloxoo的声音",
  "sesOrnek": "你好，我是Gloxoo。我的声音就是这样。",
  "ghEpostaKabul": "请使用gloxorg.com或Gmail、Outlook、Yahoo、iCloud等知名邮箱。不接受自行编造的地址。",
  "ghSifreKural": "密码至少8个字符，且需包含字母+数字。",
  "ghSifreUyusmuyor": "两次密码不一致。",
  "ghEpostaVar": "该邮箱已注册，你可以登录。",
  "ghGirisYanlis": "邮箱或密码错误。若还没有账户，请在上方注册。（若之前用Google/Microsoft登录，请用那个按钮。）",
  "ghSifreKisa": "密码至少6个字符。",
  "ghVarSifreYanlis": "该邮箱已注册，但密码错误。（若用Google开通，请用Google按钮登录。）",
  "uyeMusteri": "客户",
  "profilPasaport": "职业护照",
  "profilBaslik": "我的GLOXORG资料",
  "profilYukleniyor": "加载中...",
  "profilHakkinda": "关于",
  "profilDeneyim": "经验",
  "profilYil": "年",
  "profilHizmetler": "服务",
  "profilFiyat": "价格区间",
  "profilEksik": "添加你的职业信息——点击上方的编辑。",
  "profilAkis": "我的动态 · 作品集",
  "profilAkisBos": "你的作品、照片和视频将在这里展示。（分享功能即将推出）",
  "profilAd": "名",
  "profilSoyad": "姓",
  "profilTelefon": "电话",
  "profilKonum": "位置（城市/国家）",
  "profilMeslek": "职业",
  "profilHizmetlerVir": "服务（用逗号分隔）",
  "profilFiyatMin": "最低价",
  "profilFiyatMax": "最高价",
  "profilKaydediliyor": "保存中...",
  "belYazdir": "打印",
  "belBoyut": "大小/竖排",
  "belDikeyYazi": "竖排文字",
  "belYaziTipi": "字体",
  "belYaziBoyut": "大小",
  "belRenk": "颜色",
  "belNormal": "普通",
  "belBoyutIpucu": "用列标题上的 － ＋ 调整宽度，用左侧数字上的 － ＋ 调整高度。⇅ 按钮让该列变为竖排（自下而上）。把列变窄以适应 A4。",
  "muhPencereKapat": "关闭窗口",
  "belBoyutKisa": "－ ＋ 变窄/变宽 · ⇅ 竖排 · 收窄列以适应A4",
  "saCek": "拍照",
  "saGaleri": "从相册选择",
  "saModellerim": "我的造型",
  "saKaydet": "保存到我的造型",
  "saKaydedildi": "已保存",
  "saModelSilOnay": "删除这个造型？",
  "saGaleriBos": "还没有保存的造型。先生成一个，然后点下方“保存到我的造型”。",
  "aitCanli": "实时 AI",
  "aitSac": "换发型",
  "aitKiyafet": "试穿衣服",
  "aitMakyaj": "妆容和美甲",
  "aitSor": "问 Gloxoo",
  "aitResim": "图片和绘画",
  "aitMuhasebe": "记账和文档",
  "aitAynaBtn": "虚拟镜子",
  "aitGloxBtn": "问 Gloxoo",
  "aitAlt": "在你的照片上试发型/服装，随时问 Gloxoo — 即时，用你的语言。"
 },
 "ja": {
  "akBuyut": "タップで拡大",
  "tekrar": "再試行",
  "tanismaFotoGerek": "写真を1枚以上追加してください。",
  "tanismaHata": "写真をアップロードできませんでした。もう一度お試しください。",
  "tanismaKaydedildi": "出会いカードが完成！コミュニティに表示されるようになりました。",
  "tanismaCikOnay": "出会いカードを非表示にしますか？リストに表示されなくなります（写真は削除されず、いつでも再表示できます）。",
  "ozelAIadGir": "まず名前を入力してください。",
  "beyinKredi": "現在Gloxooの文章エンジンが混雑中か、クレジットが切れているようです 🙏（これは画像クレジットとは別のアカウントです。）数分後にもう一度お試しください。続く場合はGLOXORGの所有者にお知らせください——すぐに復旧します。",
  "cizimHazir": "描きました 🎨",
  "cumaHazir": "あなたのために特別な金曜の投稿を用意しました 🤲🌸",
  "resimUretiliyor": "画像を生成しています 🎨",
  "resimZamanAsimi": "画像が時間内に届きませんでした。もう一度お試しください。",
  "indirilemedi": "ダウンロードできませんでした",
  "paylasilamadi": "共有できませんでした",
  "resimIndiPaylas": "画像をダウンロードしました——そこから共有できます 📤",
  "kopyalanamadi": "コピーできませんでした",
  "resimKopyalandi": "画像をコピーしました 📋",
  "resimIndiKopya": "画像をダウンロードしました 📄",
  "resimPaylasima": "画像を共有に移しました——文章を添えてGLOXORGで共有できます 📤",
  "sbpGloxooSor": "Gloxooに聞く",
  "feedYukleniyor": "投稿を読み込み中…",
  "tanisBaslik": "出会う",
  "tanisTanit": "自己紹介して、新しい人と出会おう。",
  "tanisAra3": "検索、またはAIに質問…",
  "aiAraniyor": "AIが検索中…",
  "aiIleAra": "AIでスマート検索",
  "aiAraIpuc": "例：「ウクライナ在住、独身、30〜40歳、結婚を考えている人」",
  "aiAramaSonucVar": "AIがあなたのために見つけました",
  "aiSonucYok": "AIは該当する人を見つけられませんでした",
  "tanisHepsi2": "すべて",
  "tanisKadinlar": "女性",
  "tanisErkekler": "男性",
  "tanisKartDuzenle": "出会いカードを編集",
  "tanisKartOlustur": "出会いカードを作成",
  "tanisanlar": "出会いたい人",
  "tanisYukleniyor": "読み込み中…",
  "tanisAramaBos": "検索に合う人がいません。",
  "tanisBos": "まだ誰もカードを作成していません。最初の1人になろう——上から自分のカードを作成！",
  "durBekar": "独身",
  "durEvli": "既婚",
  "durIliski": "交際中",
  "durBosanmis": "離婚",
  "arArkadaslik": "友達作り",
  "arSohbet": "おしゃべり",
  "arFlort": "恋愛",
  "arEvlilik": "結婚",
  "tanisSeninKartin": "あなたのカード",
  "uzaginda": "先",
  "tanisDuzenle": "カードを編集",
  "tanisBegenildi": "いいね済み",
  "tanisBegen": "いいね",
  "ozelAIbas": "あなただけのAIフレンド",
  "ozelAInot": "好きな人の写真・名前・年齢・都市で、あなただけのチャット相手を作成——その人格でおしゃべりできます。（これはAI 🤖 であり、実在の人物ではありません。）",
  "ozelAIolustur": "自分だけのAIを作成",
  "ozelSeninki": "あなたの",
  "tanisSohbetEt": "チャットする",
  "ozelAIformNot": "好きな人の情報で、あなただけのチャット相手を。これはAI 🤖 であり、実在の人物ではありません。",
  "ozelAIfoto": "写真を追加",
  "ozelAIad": "名前",
  "ozelAIsoyad": "苗字",
  "ozelAIyas": "年齢",
  "ozelAIsehir": "都市",
  "ozelAIbasla": "作成してチャット",
  "tanisAIbas": "AIチャットフレンド",
  "tanisAInot": "これらは実在の人物ではありません——GLOXORGのAIフレンドです。いつでもチャットでき、自己紹介してくれます 💬",
  "yapayZeka": "AI",
  "tanisKartim": "私の出会いカード",
  "tanisFormNot": "自分の写真をアップロード（1〜3枚）、好きな名前を入力、簡単に自己紹介を。希望しなければリストに表示されません。",
  "tanisAdYer": "表示名（お好きに）",
  "tanisCinsiyet": "性別",
  "tanisKadin": "女性",
  "tanisErkek": "男性",
  "tanisIstege": "任意——よければ入力を",
  "tanisYas": "年齢",
  "tanisNeIcin": "何のために出会いたいですか？",
  "tanisBioYer": "簡単な自己紹介：あなたのことを…",
  "tanisKaydediliyor": "保存中…",
  "tanisKaydet": "保存して公開",
  "tanisKaldir": "リストから非表示",
  "tanisAIsohbetUyari": "これはAIです——実在の人物ではありません。個人情報やお金を渡さないでください。",
  "tanisAIbasla": "挨拶を書いて、チャットを始めよう！",
  "tanisAIyaz": "メッセージを入力…",
  "cizim": "イラスト",
  "resimHazirlaniyor": "画像を準備中…",
  "resim": "画像",
  "resimEski": "この画像は届きませんでした——もう一度作りますか？",
  "resimOlmadi": "画像を生成できませんでした",
  "gloxSes": "Gloxooの声",
  "sesOrnek": "こんにちは、Gloxooです。私の声はこんな感じです。",
  "ghEpostaKabul": "gloxorg.com、またはGmail・Outlook・Yahoo・iCloudなど有名なメールをご利用ください。自作のアドレスは受け付けられません。",
  "ghSifreKural": "パスワードは8文字以上で、英字＋数字を含める必要があります。",
  "ghSifreUyusmuyor": "2つのパスワードが一致しません。",
  "ghEpostaVar": "このメールは既に登録済みです。ログインできます。",
  "ghGirisYanlis": "メールまたはパスワードが違います。アカウントがなければ上から登録してください。（以前Google/Microsoftでログインした場合はそのボタンを使用してください。）",
  "ghSifreKisa": "パスワードは6文字以上にしてください。",
  "ghVarSifreYanlis": "このメールは登録済みですが、パスワードが違います。（Googleで開設した場合はGoogleボタンでログインしてください。）",
  "uyeMusteri": "お客様",
  "profilPasaport": "職業パスポート",
  "profilBaslik": "私のGLOXORGプロフィール",
  "profilYukleniyor": "読み込み中...",
  "profilHakkinda": "紹介",
  "profilDeneyim": "経験",
  "profilYil": "年",
  "profilHizmetler": "サービス",
  "profilFiyat": "料金帯",
  "profilEksik": "職業情報を追加——上の編集をタップ。",
  "profilAkis": "マイフィード · ポートフォリオ",
  "profilAkisBos": "あなたの作品、写真、動画がここに流れます。（投稿機能は近日公開）",
  "profilAd": "名",
  "profilSoyad": "姓",
  "profilTelefon": "電話",
  "profilKonum": "所在地（都市/国）",
  "profilMeslek": "職業",
  "profilHizmetlerVir": "サービス（カンマ区切り）",
  "profilFiyatMin": "料金 最低",
  "profilFiyatMax": "料金 最高",
  "profilKaydediliyor": "保存中...",
  "belYazdir": "印刷",
  "belBoyut": "サイズ／縦書き",
  "belDikeyYazi": "縦書き",
  "belYaziTipi": "フォント",
  "belYaziBoyut": "サイズ",
  "belRenk": "色",
  "belNormal": "標準",
  "belBoyutIpucu": "列見出しの － ＋ で幅、左の数字の － ＋ で高さを調整。⇅ ボタンでその列を縦書き（下から上）に。A4に収まるよう列を細くできます。",
  "muhPencereKapat": "ウィンドウを閉じる",
  "belBoyutKisa": "－ ＋ で幅調整 · ⇅ 縦書き · 列を細くしてA4に",
  "saCek": "写真を撮る",
  "saGaleri": "ギャラリーから",
  "saModellerim": "マイモデル",
  "saKaydet": "マイモデルに保存",
  "saKaydedildi": "保存しました",
  "saModelSilOnay": "このモデルを削除しますか？",
  "saGaleriBos": "保存済みのモデルはまだありません。作成して下の「マイモデルに保存」を押してください。",
  "aitCanli": "ライブAI",
  "aitSac": "髪を変える",
  "aitKiyafet": "服を試す",
  "aitMakyaj": "メイク＆ネイル",
  "aitSor": "Gloxooに聞く",
  "aitResim": "画像＆お絵かき",
  "aitMuhasebe": "会計＆書類",
  "aitAynaBtn": "バーチャルミラー",
  "aitGloxBtn": "Gloxooに聞く",
  "aitAlt": "写真で髪や服を試して、Gloxooに何でも質問 — すぐに、あなたの言葉で。"
 }
};
