// GROXORG — ayar paneli (?) açıklamaları 13 dil (B116).
export const AYAR_CEVIRI4 = {
  tr: {
    aciklamaHesabim:"Ana e-posta ve adın burada görünür. İstersen müşterilerin sana ulaşması için 2. bir iletişim e-postası ve telefon ekleyebilirsin. Telefon için ülke kodunu seç, numaranı yaz, Kaydet'e bas.",
    aciklamaProfil:"Profil fotoğrafını ya da şirketinin amblemini buradan yükler/değiştirirsin. Bu görsel profilinde ve paylaşımlarında görünür.",
    aciklamaSifre:"Şifreni unuttuysan giriş e-postana bir sıfırlama bağlantısı göndeririz. Google ile girdiysen şifren Google tarafında yönetilir.",
    aciklamaSektor:"Hangi alanda çalıştığını seç. Bir kategoriye dokun, içinden mesleğini ara ve seç — birden fazla seçebilirsin (aramalarda hepsi çıkar). Listede yoksa kendin yazıp ekle. Profilinde görünecek ANA mesleği yıldızla.",
    aciklamaKonum:"İşini nerede yaptığını ayarla. 'Konumumu bul' otomatik doldurur ya da 'Haritada bul' ile haritadan seçersin. Alanları kendin de yazabilirsin. Adres profilinde/aramada konumun olarak kullanılır.",
    aciklamaBildirim:"Telefon bildirimlerini açarsan beğeni, yorum ve mesajları anında alırsın. İstediğin zaman kapatabilirsin.",
    aciklamaDil:"Uygulamanın dilini buradan seçersin. Menü, ayarlar ve harita arayüzü seçtiğin dile geçer.",
    aciklamaUyelik:"Üyelik türün ve günlük yapay zeka hakkın burada görünür. Müşteri ücretsizdir; günde 20 AI hakkın gece yarısı yenilenir.",
    aciklamaHakkinda:"GROXORG — küresel profesyonel sosyal platform. Üye olarak Kullanım Koşulları ve Gizlilik Politikası'nı kabul etmiş olursun.",
  },
  en: {
    aciklamaHesabim:"Your main e-mail and name appear here. You can add a 2nd contact e-mail and a phone so customers can reach you. For the phone, pick the country code, type your number, and tap Save.",
    aciklamaProfil:"Upload or change your profile photo or company emblem here. This image appears on your profile and posts.",
    aciklamaSifre:"If you forgot your password, we send a reset link to your sign-in e-mail. If you signed in with Google, your password is managed on Google's side.",
    aciklamaSektor:"Choose your field. Tap a category, search your profession inside it and select — you can pick several (all appear in searches). If it's not listed, type and add it. Star the MAIN profession to show on your profile.",
    aciklamaKonum:"Set where you work. 'Find my location' fills it automatically, or use 'Find on map' to pick from the map. You can also type the fields yourself. The address is used as your location on your profile/in search.",
    aciklamaBildirim:"Turn on phone notifications to get likes, comments and messages instantly. You can turn it off anytime.",
    aciklamaDil:"Choose the app language here. The menu, settings and map interface switch to your chosen language.",
    aciklamaUyelik:"Your membership type and daily AI quota appear here. Customer is free; your 20 daily AI credits renew at midnight.",
    aciklamaHakkinda:"GROXORG — a global professional social platform. By joining you accept the Terms of Use and Privacy Policy.",
  },
  de: {
    aciklamaHesabim:"Deine Haupt-E-Mail und dein Name erscheinen hier. Du kannst eine 2. Kontakt-E-Mail und ein Telefon hinzufügen, damit Kunden dich erreichen. Wähle für das Telefon die Vorwahl, gib deine Nummer ein und tippe Speichern.",
    aciklamaProfil:"Lade hier dein Profilfoto oder Firmenlogo hoch oder ändere es. Dieses Bild erscheint in deinem Profil und deinen Beiträgen.",
    aciklamaSifre:"Wenn du dein Passwort vergessen hast, senden wir einen Reset-Link an deine Anmelde-E-Mail. Bei Google-Anmeldung wird dein Passwort bei Google verwaltet.",
    aciklamaSektor:"Wähle deinen Bereich. Tippe eine Kategorie an, suche darin deinen Beruf und wähle ihn — mehrere möglich (alle erscheinen in Suchen). Nicht gelistet? Selbst eintippen, hinzufügen. Markiere den HAUPTberuf mit Stern fürs Profil.",
    aciklamaKonum:"Lege fest, wo du arbeitest. 'Meinen Standort finden' füllt automatisch, oder wähle mit 'Auf Karte finden' aus. Du kannst die Felder auch selbst ausfüllen. Die Adresse dient als dein Standort im Profil/in der Suche.",
    aciklamaBildirim:"Aktiviere Telefonbenachrichtigungen, um Likes, Kommentare und Nachrichten sofort zu erhalten. Jederzeit abschaltbar.",
    aciklamaDil:"Wähle hier die App-Sprache. Menü, Einstellungen und Kartenoberfläche wechseln in die gewählte Sprache.",
    aciklamaUyelik:"Dein Mitgliedschaftstyp und dein tägliches KI-Kontingent erscheinen hier. Kunde ist kostenlos; deine 20 täglichen KI-Credits erneuern sich um Mitternacht.",
    aciklamaHakkinda:"GROXORG — eine globale professionelle soziale Plattform. Mit der Anmeldung akzeptierst du die Nutzungsbedingungen und die Datenschutzrichtlinie.",
  },
  fr: {
    aciklamaHesabim:"Votre e-mail principal et votre nom apparaissent ici. Vous pouvez ajouter un 2e e-mail de contact et un téléphone pour que les clients vous joignent. Pour le téléphone, choisissez l'indicatif, saisissez votre numéro et appuyez sur Enregistrer.",
    aciklamaProfil:"Téléchargez ou changez ici votre photo de profil ou le logo de l'entreprise. Cette image apparaît sur votre profil et vos publications.",
    aciklamaSifre:"Si vous avez oublié votre mot de passe, nous envoyons un lien de réinitialisation à votre e-mail de connexion. Si vous vous êtes connecté avec Google, votre mot de passe est géré côté Google.",
    aciklamaSektor:"Choisissez votre domaine. Touchez une catégorie, cherchez-y votre métier et sélectionnez — plusieurs possibles (tous apparaissent dans les recherches). Absent ? Tapez et ajoutez. Mettez une étoile au métier PRINCIPAL pour le profil.",
    aciklamaKonum:"Définissez où vous travaillez. 'Trouver ma position' remplit automatiquement, ou utilisez 'Trouver sur la carte'. Vous pouvez aussi remplir les champs vous-même. L'adresse sert de localisation sur votre profil/dans la recherche.",
    aciklamaBildirim:"Activez les notifications du téléphone pour recevoir j'aime, commentaires et messages instantanément. Désactivable à tout moment.",
    aciklamaDil:"Choisissez ici la langue de l'application. Le menu, les paramètres et l'interface de la carte passent dans la langue choisie.",
    aciklamaUyelik:"Votre type d'abonnement et votre quota IA quotidien apparaissent ici. Client est gratuit ; vos 20 crédits IA quotidiens se renouvellent à minuit.",
    aciklamaHakkinda:"GROXORG — une plateforme sociale professionnelle mondiale. En vous inscrivant, vous acceptez les Conditions d'utilisation et la Politique de confidentialité.",
  },
  es: {
    aciklamaHesabim:"Tu correo principal y tu nombre aparecen aquí. Puedes añadir un 2.º correo de contacto y un teléfono para que los clientes te contacten. Para el teléfono, elige el código de país, escribe tu número y pulsa Guardar.",
    aciklamaProfil:"Sube o cambia aquí tu foto de perfil o el emblema de la empresa. Esta imagen aparece en tu perfil y publicaciones.",
    aciklamaSifre:"Si olvidaste tu contraseña, enviamos un enlace de restablecimiento a tu correo de acceso. Si entraste con Google, tu contraseña se gestiona en Google.",
    aciklamaSektor:"Elige tu campo. Toca una categoría, busca tu profesión dentro y selecciónala — puedes elegir varias (todas aparecen en las búsquedas). ¿No está? Escríbela y añádela. Marca con estrella la profesión PRINCIPAL para el perfil.",
    aciklamaKonum:"Define dónde trabajas. 'Encontrar mi ubicación' lo rellena automáticamente, o usa 'Buscar en el mapa'. También puedes escribir los campos. La dirección se usa como tu ubicación en el perfil/en la búsqueda.",
    aciklamaBildirim:"Activa las notificaciones del teléfono para recibir me gusta, comentarios y mensajes al instante. Puedes desactivarlas cuando quieras.",
    aciklamaDil:"Elige aquí el idioma de la app. El menú, los ajustes y la interfaz del mapa cambian al idioma elegido.",
    aciklamaUyelik:"Tu tipo de membresía y tu cuota diaria de IA aparecen aquí. Cliente es gratis; tus 20 créditos de IA diarios se renuevan a medianoche.",
    aciklamaHakkinda:"GROXORG — una plataforma social profesional global. Al unirte aceptas las Condiciones de uso y la Política de privacidad.",
  },
  it: {
    aciklamaHesabim:"La tua e-mail principale e il tuo nome appaiono qui. Puoi aggiungere una 2ª e-mail di contatto e un telefono affinché i clienti ti raggiungano. Per il telefono scegli il prefisso, inserisci il numero e tocca Salva.",
    aciklamaProfil:"Carica o cambia qui la foto profilo o il logo aziendale. Questa immagine appare sul profilo e nei post.",
    aciklamaSifre:"Se hai dimenticato la password, inviamo un link di reimpostazione alla tua e-mail di accesso. Se hai effettuato l'accesso con Google, la password è gestita da Google.",
    aciklamaSektor:"Scegli il tuo campo. Tocca una categoria, cerca la tua professione e selezionala — puoi sceglierne più di una (appaiono tutte nelle ricerche). Non c'è? Scrivila e aggiungila. Metti la stella alla professione PRINCIPALE per il profilo.",
    aciklamaKonum:"Imposta dove lavori. 'Trova la mia posizione' compila automaticamente, oppure usa 'Trova sulla mappa'. Puoi anche compilare i campi da solo. L'indirizzo è usato come posizione sul profilo/nella ricerca.",
    aciklamaBildirim:"Attiva le notifiche del telefono per ricevere mi piace, commenti e messaggi all'istante. Disattivabili in qualsiasi momento.",
    aciklamaDil:"Scegli qui la lingua dell'app. Menu, impostazioni e interfaccia della mappa passano alla lingua scelta.",
    aciklamaUyelik:"Il tuo tipo di abbonamento e la quota IA giornaliera appaiono qui. Cliente è gratuito; i tuoi 20 crediti IA giornalieri si rinnovano a mezzanotte.",
    aciklamaHakkinda:"GROXORG — una piattaforma sociale professionale globale. Iscrivendoti accetti i Termini d'uso e l'Informativa sulla privacy.",
  },
  pt: {
    aciklamaHesabim:"Seu e-mail principal e seu nome aparecem aqui. Você pode adicionar um 2.º e-mail de contato e um telefone para os clientes te encontrarem. Para o telefone, escolha o código do país, digite seu número e toque em Salvar.",
    aciklamaProfil:"Envie ou troque aqui sua foto de perfil ou o emblema da empresa. Esta imagem aparece no seu perfil e publicações.",
    aciklamaSifre:"Se esqueceu sua senha, enviamos um link de redefinição para seu e-mail de acesso. Se entrou com Google, sua senha é gerida no Google.",
    aciklamaSektor:"Escolha sua área. Toque numa categoria, busque sua profissão e selecione — pode escolher várias (todas aparecem nas buscas). Não está? Digite e adicione. Marque com estrela a profissão PRINCIPAL para o perfil.",
    aciklamaKonum:"Defina onde você trabalha. 'Encontrar minha localização' preenche automaticamente, ou use 'Buscar no mapa'. Você também pode preencher os campos. O endereço é usado como sua localização no perfil/na busca.",
    aciklamaBildirim:"Ative as notificações do telefone para receber curtidas, comentários e mensagens na hora. Pode desativar quando quiser.",
    aciklamaDil:"Escolha aqui o idioma do app. O menu, as configurações e a interface do mapa mudam para o idioma escolhido.",
    aciklamaUyelik:"Seu tipo de assinatura e a cota diária de IA aparecem aqui. Cliente é grátis; seus 20 créditos de IA diários renovam à meia-noite.",
    aciklamaHakkinda:"GROXORG — uma plataforma social profissional global. Ao se cadastrar, você aceita os Termos de Uso e a Política de Privacidade.",
  },
  ru: {
    aciklamaHesabim:"Здесь показаны ваша основная почта и имя. Можно добавить 2-ю контактную почту и телефон, чтобы клиенты могли с вами связаться. Для телефона выберите код страны, введите номер и нажмите Сохранить.",
    aciklamaProfil:"Загрузите или измените здесь фото профиля или эмблему компании. Это изображение показывается в профиле и публикациях.",
    aciklamaSifre:"Если вы забыли пароль, мы отправим ссылку для сброса на вашу почту входа. Если вход через Google, пароль управляется на стороне Google.",
    aciklamaSektor:"Выберите свою сферу. Коснитесь категории, найдите в ней свою профессию и выберите — можно несколько (все появятся в поиске). Нет в списке? Введите и добавьте. Отметьте звездой ОСНОВНУЮ профессию для профиля.",
    aciklamaKonum:"Укажите, где вы работаете. 'Найти моё местоположение' заполнит автоматически, или используйте 'Найти на карте'. Поля можно заполнить и вручную. Адрес используется как ваше местоположение в профиле/в поиске.",
    aciklamaBildirim:"Включите уведомления телефона, чтобы мгновенно получать лайки, комментарии и сообщения. Можно отключить в любой момент.",
    aciklamaDil:"Выберите здесь язык приложения. Меню, настройки и интерфейс карты переключатся на выбранный язык.",
    aciklamaUyelik:"Здесь показаны ваш тип подписки и дневной лимит ИИ. Клиент бесплатно; ваши 20 запросов ИИ в день обновляются в полночь.",
    aciklamaHakkinda:"GROXORG — глобальная профессиональная социальная платформа. Регистрируясь, вы принимаете Условия использования и Политику конфиденциальности.",
  },
  uk: {
    aciklamaHesabim:"Тут показані ваша основна пошта та ім'я. Можна додати 2-гу контактну пошту й телефон, щоб клієнти могли з вами зв'язатися. Для телефону виберіть код країни, введіть номер і натисніть Зберегти.",
    aciklamaProfil:"Завантажте або змініть тут фото профілю чи емблему компанії. Це зображення показується в профілі та дописах.",
    aciklamaSifre:"Якщо ви забули пароль, ми надішлемо посилання для скидання на вашу пошту входу. Якщо вхід через Google, пароль керується на боці Google.",
    aciklamaSektor:"Виберіть свою сферу. Торкніться категорії, знайдіть у ній свою професію та виберіть — можна кілька (усі з'являться в пошуку). Немає? Введіть і додайте. Позначте зіркою ОСНОВНУ професію для профілю.",
    aciklamaKonum:"Вкажіть, де ви працюєте. 'Знайти моє місцезнаходження' заповнить автоматично, або використайте 'Знайти на карті'. Поля можна заповнити й вручну. Адреса використовується як ваше місцезнаходження у профілі/в пошуку.",
    aciklamaBildirim:"Увімкніть сповіщення телефону, щоб миттєво отримувати вподобання, коментарі й повідомлення. Можна вимкнути будь-коли.",
    aciklamaDil:"Виберіть тут мову застосунку. Меню, налаштування та інтерфейс карти перемкнуться на вибрану мову.",
    aciklamaUyelik:"Тут показані ваш тип підписки й денний ліміт ШІ. Клієнт безкоштовно; ваші 20 запитів ШІ на день оновлюються опівночі.",
    aciklamaHakkinda:"GROXORG — глобальна професійна соціальна платформа. Реєструючись, ви приймаєте Умови використання та Політику конфіденційності.",
  },
  ar: {
    aciklamaHesabim:"يظهر هنا بريدك الأساسي واسمك. يمكنك إضافة بريد تواصل ثانٍ ورقم هاتف ليصل إليك العملاء. للهاتف اختر رمز الدولة، اكتب رقمك واضغط حفظ.",
    aciklamaProfil:"ارفع أو غيّر هنا صورة ملفك أو شعار شركتك. تظهر هذه الصورة في ملفك ومنشوراتك.",
    aciklamaSifre:"إذا نسيت كلمة المرور، نرسل رابط إعادة تعيين إلى بريد دخولك. إذا دخلت عبر Google، تُدار كلمة المرور لدى Google.",
    aciklamaSektor:"اختر مجالك. المس فئة، ابحث فيها عن مهنتك واخترها — يمكنك اختيار أكثر من واحدة (تظهر كلها في البحث). غير موجودة؟ اكتبها وأضفها. ضع نجمة على المهنة الرئيسية لتظهر في ملفك.",
    aciklamaKonum:"حدّد مكان عملك. 'تحديد موقعي' يملأ تلقائياً، أو استخدم 'البحث على الخريطة'. يمكنك ملء الحقول بنفسك أيضاً. يُستخدم العنوان كموقعك في ملفك/في البحث.",
    aciklamaBildirim:"فعّل إشعارات الهاتف لتصلك الإعجابات والتعليقات والرسائل فوراً. يمكنك إيقافها في أي وقت.",
    aciklamaDil:"اختر هنا لغة التطبيق. تتحول القائمة والإعدادات وواجهة الخريطة إلى اللغة المختارة.",
    aciklamaUyelik:"يظهر هنا نوع عضويتك وحصتك اليومية من الذكاء الاصطناعي. العميل مجاني؛ تتجدد حصتك (20) منتصف الليل.",
    aciklamaHakkinda:"GROXORG — منصة اجتماعية مهنية عالمية. بالانضمام فإنك تقبل شروط الاستخدام وسياسة الخصوصية.",
  },
  zh: {
    aciklamaHesabim:"这里显示你的主邮箱和姓名。你可以添加第二个联系邮箱和电话，方便客户联系你。电话请选择国家代码、输入号码并点击保存。",
    aciklamaProfil:"在这里上传或更换你的头像或公司标志。该图片会显示在你的资料和帖子上。",
    aciklamaSifre:"如果忘记密码，我们会向你的登录邮箱发送重置链接。若用 Google 登录，密码由 Google 管理。",
    aciklamaSektor:"选择你的领域。点按一个类别，在其中搜索并选择你的职业——可多选（都会出现在搜索中）。没有？自己输入并添加。给主要职业加星标，它会显示在你的资料上。",
    aciklamaKonum:"设置你的工作地点。'查找我的位置'会自动填充，或用'在地图上查找'。也可以自己填写字段。该地址用作你在资料/搜索中的位置。",
    aciklamaBildirim:"开启手机通知，即时收到点赞、评论和消息。可随时关闭。",
    aciklamaDil:"在这里选择应用语言。菜单、设置和地图界面都会切换到所选语言。",
    aciklamaUyelik:"这里显示你的会员类型和每日 AI 额度。客户免费；每日 20 次 AI 额度在午夜刷新。",
    aciklamaHakkinda:"GROXORG——全球专业社交平台。注册即表示你接受使用条款和隐私政策。",
  },
  ja: {
    aciklamaHesabim:"ここに主要メールと名前が表示されます。顧客が連絡できるよう2つ目の連絡用メールと電話を追加できます。電話は国番号を選び、番号を入力して保存を押してください。",
    aciklamaProfil:"ここでプロフィール写真または会社のエンブレムをアップロード／変更します。この画像はプロフィールと投稿に表示されます。",
    aciklamaSifre:"パスワードを忘れた場合、ログイン用メールにリセットリンクを送ります。Googleでログインした場合、パスワードはGoogle側で管理されます。",
    aciklamaSektor:"分野を選びます。カテゴリをタップし、その中で職業を検索して選択——複数選択可（すべて検索に表示）。なければ自分で入力して追加。プロフィールに表示する主要な職業に星を付けてください。",
    aciklamaKonum:"働く場所を設定します。『現在地を取得』で自動入力、または『地図で探す』で選択。欄は自分でも入力できます。住所はプロフィール／検索での位置として使われます。",
    aciklamaBildirim:"電話の通知をオンにすると、いいね・コメント・メッセージをすぐ受け取れます。いつでもオフにできます。",
    aciklamaDil:"ここでアプリの言語を選びます。メニュー・設定・地図の表示が選んだ言語に切り替わります。",
    aciklamaUyelik:"ここにメンバーシップの種類と1日のAI利用枠が表示されます。顧客は無料。1日20回のAI枠は深夜に更新されます。",
    aciklamaHakkinda:"GROXORG——世界的なプロフェッショナル向けソーシャルプラットフォーム。登録すると利用規約とプライバシーポリシーに同意したことになります。",
  },
  hi: {
    aciklamaHesabim:"यहाँ आपका मुख्य ई-मेल और नाम दिखता है। ग्राहक आप तक पहुँच सकें इसलिए दूसरा संपर्क ई-मेल और फ़ोन जोड़ सकते हैं। फ़ोन के लिए देश कोड चुनें, नंबर लिखें और सहेजें दबाएँ।",
    aciklamaProfil:"यहाँ अपनी प्रोफ़ाइल फ़ोटो या कंपनी का प्रतीक अपलोड/बदलें। यह छवि आपकी प्रोफ़ाइल और पोस्ट में दिखती है।",
    aciklamaSifre:"पासवर्ड भूल गए हैं तो हम आपके लॉगिन ई-मेल पर रीसेट लिंक भेजते हैं। Google से लॉगिन किया हो तो पासवर्ड Google पर प्रबंधित होता है।",
    aciklamaSektor:"अपना क्षेत्र चुनें। किसी श्रेणी पर टैप करें, उसमें अपना पेशा खोजें और चुनें — कई चुन सकते हैं (सभी खोज में दिखते हैं)। नहीं है? खुद लिखें, जोड़ें। प्रोफ़ाइल पर दिखने वाले मुख्य पेशे को तारा दें।",
    aciklamaKonum:"तय करें कि आप कहाँ काम करते हैं। 'मेरा स्थान खोजें' अपने आप भर देता है, या 'मानचित्र पर खोजें' से चुनें। फ़ील्ड खुद भी भर सकते हैं। पता आपकी प्रोफ़ाइल/खोज में स्थान के रूप में उपयोग होता है।",
    aciklamaBildirim:"फ़ोन सूचनाएँ चालू करें ताकि लाइक, कमेंट और संदेश तुरंत मिलें। कभी भी बंद कर सकते हैं।",
    aciklamaDil:"यहाँ ऐप की भाषा चुनें। मेन्यू, सेटिंग्स और मानचित्र इंटरफ़ेस चुनी हुई भाषा में बदल जाते हैं।",
    aciklamaUyelik:"यहाँ आपकी सदस्यता का प्रकार और दैनिक AI सीमा दिखती है। ग्राहक निःशुल्क है; आपकी दैनिक 20 AI सीमाएँ आधी रात को नवीनीकृत होती हैं।",
    aciklamaHakkinda:"GROXORG — एक वैश्विक पेशेवर सामाजिक मंच। शामिल होकर आप उपयोग की शर्तें और गोपनीयता नीति स्वीकार करते हैं।",
  },
};
