// GLOXORG — ELİTE PAZAR ÇEVİRİLERİ (13 dil). Elite Pazar sayfası eskiden hep Türkçe'ydi;
// kullanıcı dili değiştirince orası Türkçe kalıyordu. Artık tüm yazılar burada, i18n'e ekleniyor.
// Anahtarlar: epKat_<kategoriId> (kategoriler), epEt_<etiketId> (etiket kelimeleri), ep* (arayüz yazıları).
// Emoji'ler KODDA duruyor (evrensel), burada sadece KELİMELER çevrildi.
export const CEVIRI_ELITEPAZAR = {
  tr: { translation: {
    epKat_tumu:"Tümü", epKat_moda:"Moda", epKat_ayakkabi:"Ayakkabı & Çanta", epKat_elektronik:"Elektronik", epKat_telefon:"Telefon", epKat_ev:"Ev & Yaşam", epKat_arac:"Araç", epKat_moto:"Motosiklet", epKat_yedek:"Yedek Parça", epKat_emlak:"Emlak", epKat_bebek:"Bebek", epKat_spor:"Spor", epKat_hayvan:"Hayvan", epKat_kozmetik:"Kozmetik", epKat_saglik:"Sağlık", epKat_kitap:"Kitap & Hobi", epKat_oyun:"Oyun & Konsol", epKat_muzik:"Müzik", epKat_bahce:"Bahçe & Yapı", epKat_antika:"Antika", epKat_hizmet:"İş / Hizmet", epKat_luks:"Lüks", epKat_diger:"Diğer",
    epEt_pazarlik:"Pazarlık", epEt_kargo:"Kargo", epEt_elden:"Elden", epEt_acil:"Acil", epEt_takas:"Takas", epEt_ucretsiz:"Ücretsiz",
    epTagA:"Seçkin ürünler", epTagB:"al, sat, kazan",
    epAraPh:"Ara ya da Gloxoo'ya sor: 20 bin altı temiz telefon",
    epAkilliAra:"Gloxoo ile akıllı ara", epAkilliAriyor:"Gloxoo arıyor…",
    epAkilliOnce:"Önce ne aradığını yaz — örn: 20 bin altı temiz telefon 🙂",
    epAkilliCozemedi:"Gloxoo tam çözemedi — kelimeyle arıyorum.",
    epGloxPre:"Gloxoo:", epAlti:"altı", epUstu:"üstü",
    epIlanBulundu:"{{n}} ilan bulundu", epUygunYok:"uygun ilan yok (henüz)",
    epSat:"Ürününü Sat · İlan Ver", epOneCikan:"Öne Çıkan İlanlar",
    epIlanYukleniyor:"İlanlar yükleniyor…", epHenuzYok:"Henüz ilan yok — ilk satan sen ol! 🎉",
    epAramaYok:"Bu aramaya uygun ilan yok.", epIlkIlan:"İlk ilanı ver",
    epIlan:"İlan", epUcretsiz:"Ücretsiz", epSilOnay:"Bu ilanı silmek istiyor musun?",
    epYeni:"Yeni", epIkinciEl:"İkinci el", epSatici:"Satıcı",
    epFiyatUygun:"Bu fiyat uygun mu?", epBakiyor:"Bakıyor…", epPazarlikMesaji:"Pazarlık mesajı", epYaziyor:"Yazıyor…",
    epBuMesajla:"Bu mesajla yaz", epKopyala:"Kopyala", epMesajGonder:"Mesaj Gönder", epAra:"Ara", epEposta:"E-posta",
    epFavorimde:"Favorimde", epFavori:"Favori", epIlaniSil:"İlanı Sil",
    epDegerlendiremedim:"Şu an değerlendiremedim, birazdan tekrar dene.",
    epUrununuSat:"Ürününü Sat", epFotoVideo:"FOTOĞRAF & VİDEO", epFoto:"Foto", epVideo:"Video",
    epYukleniyorKisa:"Yükleniyor… ⏳", epVideoBuyuk:"Video çok büyük (en fazla 60MB)", epVideoYuklenemedi:"Video yüklenemedi",
    epGloxYardimcin:"Gloxoo yardımcın", epGloxAlt:"Fotoğrafa bakıp ilanını yazar, fiyat önerir.",
    epIlaniGloxYazsin:"İlanı Gloxoo yazsın", epFiyatOner:"Fiyat öner",
    epBaslik:"BAŞLIK", epBaslikPh:"Örn: iPhone 15 Pro — temiz, kutulu", epAciklama:"AÇIKLAMA", epAciklamaPh:"Ürünü anlat: durumu, özellikleri…",
    epFiyatEtk:"FİYAT (₺)", epGloxFiyatOneri:"Gloxoo fiyat önerisi", epOneriKullan:"Öneriyi kullan",
    epKategoriEtk:"KATEGORİ", epDurumEtk:"DURUM",
    epKonumEtk:"KONUM (nereden satıyorsun)", epKonumPh:"Şehir / İlçe (örn: İstanbul, Kadıköy)",
    epHaritadanSec:"Haritadan Konum Seç", epKonumIsaretli:"Konum haritada işaretlendi ✓ (değiştir)",
    epKonumIpucu:"Haritadan seçersen alıcı ürünün yerini haritada ve kaç km uzakta olduğunu görür. Kargo = her yere, Elden = yüz yüze.",
    epEtiketlerEtk:"ETİKETLER (nereye/nasıl)", epIletisimEtk:"İLETİŞİM (alıcı sana nasıl ulaşsın)",
    epIletisimNot:"Uygulama içi mesaj her zaman açık. İstersen telefon / e-posta / adres de ekle — alıcı hangisini koyduysan onu görür, ona göre yazar ya da arar.",
    epTelefonPh:"📞 Telefon (isteğe bağlı)", epEpostaPh:"✉️ E-posta (isteğe bağlı)", epAdresPh:"🏠 Adres (isteğe bağlı)",
    epIlaniYayinla:"İlanı Yayınla", epYayinlaniyor:"Yayınlanıyor…",
    epHataFoto:"Önce bir fotoğraf ekle (Gloxoo ona baksın) ya da başlığa birkaç kelime yaz.",
    epHataFotoFiyat:"Önce fotoğraf ekle ya da başlık yaz — Gloxoo ona göre fiyat önersin.",
    epHataBaslik:"Bir başlık yaz (Gloxoo da yazabilir).", epHataFiyat:"Fiyat yaz (ya da 'Ücretsiz' etiketini seç).",
    epHataKategori:"Bir kategori seç.", epHataFotoEkle:"En az bir fotoğraf ekle.",
    epHataYayin:"İlan yayınlanamadı: {{hata}} (giriş yaptığından ve kuralların yayınlandığından emin ol)",
    epKonumSec:"Konum Seç", epHaritaNot:"Haritaya dokunarak yerini işaretle, ya da Konumumu Kullan'a bas. Alıcı bunu haritada ve kaç km uzakta görecek.",
    epKonumumuKullan:"Konumumu Kullan", epBuKonumuSec:"Bu Konumu Seç",
    epKonum:"KONUM", epUzaklik:"Sana yaklaşık {{mesafe}} uzaklıkta", epUrununKonumu:"Ürünün konumu", epYolTarifi:"Yol tarifi",
  }},
  en: { translation: {
    epKat_tumu:"All", epKat_moda:"Fashion", epKat_ayakkabi:"Shoes & Bags", epKat_elektronik:"Electronics", epKat_telefon:"Phone", epKat_ev:"Home & Living", epKat_arac:"Vehicle", epKat_moto:"Motorcycle", epKat_yedek:"Spare Parts", epKat_emlak:"Real Estate", epKat_bebek:"Baby", epKat_spor:"Sports", epKat_hayvan:"Pets", epKat_kozmetik:"Cosmetics", epKat_saglik:"Health", epKat_kitap:"Books & Hobby", epKat_oyun:"Games & Consoles", epKat_muzik:"Music", epKat_bahce:"Garden & DIY", epKat_antika:"Antiques", epKat_hizmet:"Jobs / Services", epKat_luks:"Luxury", epKat_diger:"Other",
    epEt_pazarlik:"Negotiable", epEt_kargo:"Shipping", epEt_elden:"In Person", epEt_acil:"Urgent", epEt_takas:"Swap", epEt_ucretsiz:"Free",
    epTagA:"Curated items", epTagB:"buy, sell, earn",
    epAraPh:"Search or ask Gloxoo: clean phone under 20k",
    epAkilliAra:"Smart search with Gloxoo", epAkilliAriyor:"Gloxoo is searching…",
    epAkilliOnce:"First type what you're looking for — e.g. clean phone under 20k 🙂",
    epAkilliCozemedi:"Gloxoo couldn't fully parse it — searching by keyword.",
    epGloxPre:"Gloxoo:", epAlti:"below", epUstu:"above",
    epIlanBulundu:"{{n}} listings found", epUygunYok:"no matching listing (yet)",
    epSat:"Sell Your Item · Post Listing", epOneCikan:"Featured Listings",
    epIlanYukleniyor:"Loading listings…", epHenuzYok:"No listings yet — be the first to sell! 🎉",
    epAramaYok:"No listing matches this search.", epIlkIlan:"Post the first listing",
    epIlan:"Listing", epUcretsiz:"Free", epSilOnay:"Do you want to delete this listing?",
    epYeni:"New", epIkinciEl:"Used", epSatici:"Seller",
    epFiyatUygun:"Is this price fair?", epBakiyor:"Checking…", epPazarlikMesaji:"Negotiation message", epYaziyor:"Writing…",
    epBuMesajla:"Send with this message", epKopyala:"Copy", epMesajGonder:"Send Message", epAra:"Call", epEposta:"Email",
    epFavorimde:"Favorited", epFavori:"Favorite", epIlaniSil:"Delete Listing",
    epDegerlendiremedim:"I couldn't evaluate it right now, please try again shortly.",
    epUrununuSat:"Sell Your Item", epFotoVideo:"PHOTO & VIDEO", epFoto:"Photo", epVideo:"Video",
    epYukleniyorKisa:"Uploading… ⏳", epVideoBuyuk:"Video too large (60MB max)", epVideoYuklenemedi:"Video upload failed",
    epGloxYardimcin:"Gloxoo, your assistant", epGloxAlt:"It looks at your photo, writes your listing and suggests a price.",
    epIlaniGloxYazsin:"Let Gloxoo write it", epFiyatOner:"Suggest price",
    epBaslik:"TITLE", epBaslikPh:"e.g. iPhone 15 Pro — clean, boxed", epAciklama:"DESCRIPTION", epAciklamaPh:"Describe the item: condition, features…",
    epFiyatEtk:"PRICE (₺)", epGloxFiyatOneri:"Gloxoo price suggestion", epOneriKullan:"Use suggestion",
    epKategoriEtk:"CATEGORY", epDurumEtk:"CONDITION",
    epKonumEtk:"LOCATION (where you sell from)", epKonumPh:"City / District (e.g. Istanbul, Kadıköy)",
    epHaritadanSec:"Pick Location on Map", epKonumIsaretli:"Location marked on map ✓ (change)",
    epKonumIpucu:"If you pick it on the map, the buyer sees the item's spot on the map and how many km away it is. Shipping = anywhere, In Person = face to face.",
    epEtiketlerEtk:"TAGS (where/how)", epIletisimEtk:"CONTACT (how the buyer reaches you)",
    epIletisimNot:"In-app messaging is always on. You can also add phone / email / address — the buyer sees whichever you provide and writes or calls accordingly.",
    epTelefonPh:"📞 Phone (optional)", epEpostaPh:"✉️ Email (optional)", epAdresPh:"🏠 Address (optional)",
    epIlaniYayinla:"Publish Listing", epYayinlaniyor:"Publishing…",
    epHataFoto:"Add a photo first (so Gloxoo can look) or type a few words in the title.",
    epHataFotoFiyat:"Add a photo or write a title first — so Gloxoo can suggest a price.",
    epHataBaslik:"Write a title (Gloxoo can write it too).", epHataFiyat:"Enter a price (or choose the 'Free' tag).",
    epHataKategori:"Choose a category.", epHataFotoEkle:"Add at least one photo.",
    epHataYayin:"Listing couldn't be published: {{hata}} (make sure you're signed in and the rules are published)",
    epKonumSec:"Pick Location", epHaritaNot:"Tap the map to mark your spot, or tap Use My Location. The buyer sees it on the map and how many km away.",
    epKonumumuKullan:"Use My Location", epBuKonumuSec:"Select This Location",
    epKonum:"LOCATION", epUzaklik:"About {{mesafe}} away from you", epUrununKonumu:"Item location", epYolTarifi:"Directions",
  }},
  de: { translation: {
    epKat_tumu:"Alle", epKat_moda:"Mode", epKat_ayakkabi:"Schuhe & Taschen", epKat_elektronik:"Elektronik", epKat_telefon:"Telefon", epKat_ev:"Haus & Wohnen", epKat_arac:"Fahrzeug", epKat_moto:"Motorrad", epKat_yedek:"Ersatzteile", epKat_emlak:"Immobilien", epKat_bebek:"Baby", epKat_spor:"Sport", epKat_hayvan:"Tiere", epKat_kozmetik:"Kosmetik", epKat_saglik:"Gesundheit", epKat_kitap:"Bücher & Hobby", epKat_oyun:"Spiele & Konsolen", epKat_muzik:"Musik", epKat_bahce:"Garten & Bau", epKat_antika:"Antiquitäten", epKat_hizmet:"Jobs / Dienste", epKat_luks:"Luxus", epKat_diger:"Sonstiges",
    epEt_pazarlik:"Verhandelbar", epEt_kargo:"Versand", epEt_elden:"Vor Ort", epEt_acil:"Dringend", epEt_takas:"Tausch", epEt_ucretsiz:"Gratis",
    epTagA:"Ausgewählte Artikel", epTagB:"kaufen, verkaufen, verdienen",
    epAraPh:"Suchen oder Gloxoo fragen: sauberes Handy unter 20k",
    epAkilliAra:"Intelligente Suche mit Gloxoo", epAkilliAriyor:"Gloxoo sucht…",
    epAkilliOnce:"Tippe zuerst, was du suchst — z. B. sauberes Handy unter 20k 🙂",
    epAkilliCozemedi:"Gloxoo konnte es nicht ganz deuten — suche nach Stichwort.",
    epGloxPre:"Gloxoo:", epAlti:"unter", epUstu:"über",
    epIlanBulundu:"{{n}} Anzeigen gefunden", epUygunYok:"keine passende Anzeige (noch nicht)",
    epSat:"Artikel verkaufen · Anzeige aufgeben", epOneCikan:"Empfohlene Anzeigen",
    epIlanYukleniyor:"Anzeigen werden geladen…", epHenuzYok:"Noch keine Anzeigen — sei der Erste! 🎉",
    epAramaYok:"Keine Anzeige passt zu dieser Suche.", epIlkIlan:"Erste Anzeige aufgeben",
    epIlan:"Anzeige", epUcretsiz:"Gratis", epSilOnay:"Möchtest du diese Anzeige löschen?",
    epYeni:"Neu", epIkinciEl:"Gebraucht", epSatici:"Verkäufer",
    epFiyatUygun:"Ist dieser Preis fair?", epBakiyor:"Prüft…", epPazarlikMesaji:"Verhandlungsnachricht", epYaziyor:"Schreibt…",
    epBuMesajla:"Mit dieser Nachricht senden", epKopyala:"Kopieren", epMesajGonder:"Nachricht senden", epAra:"Anrufen", epEposta:"E-Mail",
    epFavorimde:"Favorit", epFavori:"Favorit", epIlaniSil:"Anzeige löschen",
    epDegerlendiremedim:"Ich konnte es gerade nicht bewerten, bitte versuche es gleich erneut.",
    epUrununuSat:"Artikel verkaufen", epFotoVideo:"FOTO & VIDEO", epFoto:"Foto", epVideo:"Video",
    epYukleniyorKisa:"Wird hochgeladen… ⏳", epVideoBuyuk:"Video zu groß (max. 60MB)", epVideoYuklenemedi:"Video-Upload fehlgeschlagen",
    epGloxYardimcin:"Gloxoo, dein Helfer", epGloxAlt:"Er sieht sich dein Foto an, schreibt deine Anzeige und schlägt einen Preis vor.",
    epIlaniGloxYazsin:"Gloxoo schreiben lassen", epFiyatOner:"Preis vorschlagen",
    epBaslik:"TITEL", epBaslikPh:"z. B. iPhone 15 Pro — sauber, mit OVP", epAciklama:"BESCHREIBUNG", epAciklamaPh:"Beschreibe den Artikel: Zustand, Merkmale…",
    epFiyatEtk:"PREIS (₺)", epGloxFiyatOneri:"Gloxoo Preisvorschlag", epOneriKullan:"Vorschlag übernehmen",
    epKategoriEtk:"KATEGORIE", epDurumEtk:"ZUSTAND",
    epKonumEtk:"STANDORT (von wo du verkaufst)", epKonumPh:"Stadt / Bezirk (z. B. Istanbul, Kadıköy)",
    epHaritadanSec:"Standort auf Karte wählen", epKonumIsaretli:"Standort auf Karte markiert ✓ (ändern)",
    epKonumIpucu:"Wenn du ihn auf der Karte wählst, sieht der Käufer den Ort des Artikels auf der Karte und wie viele km entfernt. Versand = überallhin, Vor Ort = persönlich.",
    epEtiketlerEtk:"TAGS (wohin/wie)", epIletisimEtk:"KONTAKT (wie der Käufer dich erreicht)",
    epIletisimNot:"In-App-Nachrichten sind immer aktiv. Du kannst auch Telefon / E-Mail / Adresse hinzufügen — der Käufer sieht, was du angibst, und schreibt oder ruft an.",
    epTelefonPh:"📞 Telefon (optional)", epEpostaPh:"✉️ E-Mail (optional)", epAdresPh:"🏠 Adresse (optional)",
    epIlaniYayinla:"Anzeige veröffentlichen", epYayinlaniyor:"Wird veröffentlicht…",
    epHataFoto:"Füge zuerst ein Foto hinzu (damit Gloxoo es sieht) oder schreibe ein paar Wörter in den Titel.",
    epHataFotoFiyat:"Füge zuerst ein Foto hinzu oder schreibe einen Titel — damit Gloxoo einen Preis vorschlagen kann.",
    epHataBaslik:"Schreibe einen Titel (Gloxoo kann ihn auch schreiben).", epHataFiyat:"Gib einen Preis ein (oder wähle das Tag 'Gratis').",
    epHataKategori:"Wähle eine Kategorie.", epHataFotoEkle:"Füge mindestens ein Foto hinzu.",
    epHataYayin:"Anzeige konnte nicht veröffentlicht werden: {{hata}} (stelle sicher, dass du angemeldet bist und die Regeln veröffentlicht sind)",
    epKonumSec:"Standort wählen", epHaritaNot:"Tippe auf die Karte, um deinen Ort zu markieren, oder tippe auf Meinen Standort verwenden. Der Käufer sieht ihn auf der Karte und wie viele km entfernt.",
    epKonumumuKullan:"Meinen Standort verwenden", epBuKonumuSec:"Diesen Standort wählen",
    epKonum:"STANDORT", epUzaklik:"Etwa {{mesafe}} von dir entfernt", epUrununKonumu:"Standort des Artikels", epYolTarifi:"Route",
  }},
  ar: { translation: {
    epKat_tumu:"الكل", epKat_moda:"أزياء", epKat_ayakkabi:"أحذية وحقائب", epKat_elektronik:"إلكترونيات", epKat_telefon:"هاتف", epKat_ev:"المنزل والمعيشة", epKat_arac:"مركبة", epKat_moto:"دراجة نارية", epKat_yedek:"قطع غيار", epKat_emlak:"عقارات", epKat_bebek:"أطفال", epKat_spor:"رياضة", epKat_hayvan:"حيوانات", epKat_kozmetik:"مستحضرات تجميل", epKat_saglik:"صحة", epKat_kitap:"كتب وهوايات", epKat_oyun:"ألعاب وأجهزة", epKat_muzik:"موسيقى", epKat_bahce:"حديقة وبناء", epKat_antika:"تحف", epKat_hizmet:"أعمال / خدمات", epKat_luks:"فخامة", epKat_diger:"أخرى",
    epEt_pazarlik:"قابل للتفاوض", epEt_kargo:"شحن", epEt_elden:"تسليم يدوي", epEt_acil:"عاجل", epEt_takas:"مقايضة", epEt_ucretsiz:"مجاني",
    epTagA:"منتجات مختارة", epTagB:"اشترِ، بِع، اربح",
    epAraPh:"ابحث أو اسأل Gloxoo: هاتف نظيف تحت 20 ألف",
    epAkilliAra:"بحث ذكي مع Gloxoo", epAkilliAriyor:"Gloxoo يبحث…",
    epAkilliOnce:"اكتب أولًا ما تبحث عنه — مثل: هاتف نظيف تحت 20 ألف 🙂",
    epAkilliCozemedi:"لم يفهمه Gloxoo تمامًا — أبحث بالكلمة.",
    epGloxPre:"Gloxoo:", epAlti:"أقل من", epUstu:"أكثر من",
    epIlanBulundu:"تم العثور على {{n}} إعلان", epUygunYok:"لا يوجد إعلان مطابق (بعد)",
    epSat:"بِع منتجك · انشر إعلانًا", epOneCikan:"إعلانات مميزة",
    epIlanYukleniyor:"جارٍ تحميل الإعلانات…", epHenuzYok:"لا توجد إعلانات بعد — كن أول بائع! 🎉",
    epAramaYok:"لا يوجد إعلان يطابق هذا البحث.", epIlkIlan:"انشر أول إعلان",
    epIlan:"إعلان", epUcretsiz:"مجاني", epSilOnay:"هل تريد حذف هذا الإعلان؟",
    epYeni:"جديد", epIkinciEl:"مستعمل", epSatici:"البائع",
    epFiyatUygun:"هل هذا السعر مناسب؟", epBakiyor:"يتحقق…", epPazarlikMesaji:"رسالة تفاوض", epYaziyor:"يكتب…",
    epBuMesajla:"أرسل بهذه الرسالة", epKopyala:"نسخ", epMesajGonder:"إرسال رسالة", epAra:"اتصال", epEposta:"بريد إلكتروني",
    epFavorimde:"في المفضلة", epFavori:"مفضلة", epIlaniSil:"حذف الإعلان",
    epDegerlendiremedim:"لم أتمكن من التقييم الآن، حاول مرة أخرى بعد قليل.",
    epUrununuSat:"بِع منتجك", epFotoVideo:"صورة وفيديو", epFoto:"صورة", epVideo:"فيديو",
    epYukleniyorKisa:"جارٍ الرفع… ⏳", epVideoBuyuk:"الفيديو كبير جدًا (60 ميغابايت كحد أقصى)", epVideoYuklenemedi:"فشل رفع الفيديو",
    epGloxYardimcin:"Gloxoo مساعدك", epGloxAlt:"ينظر إلى صورتك، يكتب إعلانك ويقترح سعرًا.",
    epIlaniGloxYazsin:"دع Gloxoo يكتبه", epFiyatOner:"اقترح سعرًا",
    epBaslik:"العنوان", epBaslikPh:"مثال: iPhone 15 Pro — نظيف، بالعلبة", epAciklama:"الوصف", epAciklamaPh:"صِف المنتج: حالته، مميزاته…",
    epFiyatEtk:"السعر (₺)", epGloxFiyatOneri:"اقتراح سعر Gloxoo", epOneriKullan:"استخدم الاقتراح",
    epKategoriEtk:"الفئة", epDurumEtk:"الحالة",
    epKonumEtk:"الموقع (من أين تبيع)", epKonumPh:"المدينة / الحي (مثل: إسطنبول، كاديكوي)",
    epHaritadanSec:"اختر الموقع من الخريطة", epKonumIsaretli:"تم تحديد الموقع على الخريطة ✓ (تغيير)",
    epKonumIpucu:"إذا اخترته على الخريطة، يرى المشتري موقع المنتج على الخريطة وكم كيلومترًا يبعد. شحن = إلى كل مكان، تسليم يدوي = وجهًا لوجه.",
    epEtiketlerEtk:"الوسوم (أين/كيف)", epIletisimEtk:"التواصل (كيف يصل إليك المشتري)",
    epIletisimNot:"الرسائل داخل التطبيق مفعّلة دائمًا. يمكنك أيضًا إضافة هاتف / بريد / عنوان — يرى المشتري ما تضعه ويكتب أو يتصل بناءً عليه.",
    epTelefonPh:"📞 هاتف (اختياري)", epEpostaPh:"✉️ بريد إلكتروني (اختياري)", epAdresPh:"🏠 عنوان (اختياري)",
    epIlaniYayinla:"نشر الإعلان", epYayinlaniyor:"جارٍ النشر…",
    epHataFoto:"أضف صورة أولًا (كي يراها Gloxoo) أو اكتب بضع كلمات في العنوان.",
    epHataFotoFiyat:"أضف صورة أو اكتب عنوانًا أولًا — كي يقترح Gloxoo سعرًا.",
    epHataBaslik:"اكتب عنوانًا (يمكن لـ Gloxoo كتابته أيضًا).", epHataFiyat:"أدخل سعرًا (أو اختر وسم 'مجاني').",
    epHataKategori:"اختر فئة.", epHataFotoEkle:"أضف صورة واحدة على الأقل.",
    epHataYayin:"تعذّر نشر الإعلان: {{hata}} (تأكد من تسجيل الدخول ومن نشر القواعد)",
    epKonumSec:"اختر الموقع", epHaritaNot:"اضغط على الخريطة لتحديد موقعك، أو اضغط استخدم موقعي. سيراه المشتري على الخريطة وكم كيلومترًا يبعد.",
    epKonumumuKullan:"استخدم موقعي", epBuKonumuSec:"اختر هذا الموقع",
    epKonum:"الموقع", epUzaklik:"على بعد {{mesafe}} تقريبًا منك", epUrununKonumu:"موقع المنتج", epYolTarifi:"الاتجاهات",
  }},
  ru: { translation: {
    epKat_tumu:"Все", epKat_moda:"Мода", epKat_ayakkabi:"Обувь и сумки", epKat_elektronik:"Электроника", epKat_telefon:"Телефон", epKat_ev:"Дом и быт", epKat_arac:"Транспорт", epKat_moto:"Мотоцикл", epKat_yedek:"Запчасти", epKat_emlak:"Недвижимость", epKat_bebek:"Для детей", epKat_spor:"Спорт", epKat_hayvan:"Животные", epKat_kozmetik:"Косметика", epKat_saglik:"Здоровье", epKat_kitap:"Книги и хобби", epKat_oyun:"Игры и консоли", epKat_muzik:"Музыка", epKat_bahce:"Сад и стройка", epKat_antika:"Антиквариат", epKat_hizmet:"Работа / услуги", epKat_luks:"Люкс", epKat_diger:"Прочее",
    epEt_pazarlik:"Торг", epEt_kargo:"Доставка", epEt_elden:"Из рук в руки", epEt_acil:"Срочно", epEt_takas:"Обмен", epEt_ucretsiz:"Бесплатно",
    epTagA:"Избранные товары", epTagB:"покупай, продавай, зарабатывай",
    epAraPh:"Найдите или спросите Gloxoo: чистый телефон до 20к",
    epAkilliAra:"Умный поиск с Gloxoo", epAkilliAriyor:"Gloxoo ищет…",
    epAkilliOnce:"Сначала напишите, что ищете — напр.: чистый телефон до 20к 🙂",
    epAkilliCozemedi:"Gloxoo не всё понял — ищу по слову.",
    epGloxPre:"Gloxoo:", epAlti:"до", epUstu:"от",
    epIlanBulundu:"Найдено объявлений: {{n}}", epUygunYok:"подходящих объявлений нет (пока)",
    epSat:"Продать товар · Разместить", epOneCikan:"Избранные объявления",
    epIlanYukleniyor:"Загрузка объявлений…", epHenuzYok:"Объявлений пока нет — станьте первым продавцом! 🎉",
    epAramaYok:"Нет объявлений по этому запросу.", epIlkIlan:"Разместить первое объявление",
    epIlan:"Объявление", epUcretsiz:"Бесплатно", epSilOnay:"Удалить это объявление?",
    epYeni:"Новое", epIkinciEl:"Б/у", epSatici:"Продавец",
    epFiyatUygun:"Цена справедливая?", epBakiyor:"Проверяю…", epPazarlikMesaji:"Сообщение о торге", epYaziyor:"Пишу…",
    epBuMesajla:"Отправить с этим сообщением", epKopyala:"Копировать", epMesajGonder:"Отправить сообщение", epAra:"Позвонить", epEposta:"E-mail",
    epFavorimde:"В избранном", epFavori:"В избранное", epIlaniSil:"Удалить объявление",
    epDegerlendiremedim:"Сейчас не удалось оценить, попробуйте чуть позже.",
    epUrununuSat:"Продать товар", epFotoVideo:"ФОТО И ВИДЕО", epFoto:"Фото", epVideo:"Видео",
    epYukleniyorKisa:"Загрузка… ⏳", epVideoBuyuk:"Видео слишком большое (макс. 60 МБ)", epVideoYuklenemedi:"Не удалось загрузить видео",
    epGloxYardimcin:"Gloxoo, ваш помощник", epGloxAlt:"Смотрит на фото, пишет объявление и предлагает цену.",
    epIlaniGloxYazsin:"Пусть напишет Gloxoo", epFiyatOner:"Предложить цену",
    epBaslik:"ЗАГОЛОВОК", epBaslikPh:"Напр.: iPhone 15 Pro — чистый, в коробке", epAciklama:"ОПИСАНИЕ", epAciklamaPh:"Опишите товар: состояние, характеристики…",
    epFiyatEtk:"ЦЕНА (₺)", epGloxFiyatOneri:"Предложение цены Gloxoo", epOneriKullan:"Использовать",
    epKategoriEtk:"КАТЕГОРИЯ", epDurumEtk:"СОСТОЯНИЕ",
    epKonumEtk:"МЕСТО (откуда продаёте)", epKonumPh:"Город / район (напр.: Стамбул, Кадыкёй)",
    epHaritadanSec:"Выбрать место на карте", epKonumIsaretli:"Место отмечено на карте ✓ (изменить)",
    epKonumIpucu:"Если выбрать на карте, покупатель увидит место товара на карте и сколько км до него. Доставка = куда угодно, Из рук в руки = лично.",
    epEtiketlerEtk:"МЕТКИ (куда/как)", epIletisimEtk:"КОНТАКТ (как покупатель свяжется с вами)",
    epIletisimNot:"Сообщения в приложении всегда включены. Можно добавить телефон / e-mail / адрес — покупатель увидит то, что вы указали, и напишет или позвонит.",
    epTelefonPh:"📞 Телефон (необязательно)", epEpostaPh:"✉️ E-mail (необязательно)", epAdresPh:"🏠 Адрес (необязательно)",
    epIlaniYayinla:"Опубликовать", epYayinlaniyor:"Публикуется…",
    epHataFoto:"Сначала добавьте фото (чтобы Gloxoo посмотрел) или впишите пару слов в заголовок.",
    epHataFotoFiyat:"Сначала добавьте фото или напишите заголовок — чтобы Gloxoo предложил цену.",
    epHataBaslik:"Напишите заголовок (Gloxoo тоже может).", epHataFiyat:"Укажите цену (или выберите метку 'Бесплатно').",
    epHataKategori:"Выберите категорию.", epHataFotoEkle:"Добавьте хотя бы одно фото.",
    epHataYayin:"Не удалось опубликовать объявление: {{hata}} (убедитесь, что вы вошли и правила опубликованы)",
    epKonumSec:"Выбрать место", epHaritaNot:"Коснитесь карты, чтобы отметить место, или нажмите Использовать моё местоположение. Покупатель увидит его на карте и расстояние в км.",
    epKonumumuKullan:"Использовать моё местоположение", epBuKonumuSec:"Выбрать это место",
    epKonum:"МЕСТО", epUzaklik:"Примерно в {{mesafe}} от вас", epUrununKonumu:"Место товара", epYolTarifi:"Маршрут",
  }},
  uk: { translation: {
    epKat_tumu:"Усі", epKat_moda:"Мода", epKat_ayakkabi:"Взуття та сумки", epKat_elektronik:"Електроніка", epKat_telefon:"Телефон", epKat_ev:"Дім і побут", epKat_arac:"Транспорт", epKat_moto:"Мотоцикл", epKat_yedek:"Запчастини", epKat_emlak:"Нерухомість", epKat_bebek:"Малюки", epKat_spor:"Спорт", epKat_hayvan:"Тварини", epKat_kozmetik:"Косметика", epKat_saglik:"Здоров'я", epKat_kitap:"Книги та хобі", epKat_oyun:"Ігри та консолі", epKat_muzik:"Музика", epKat_bahce:"Сад і будівництво", epKat_antika:"Антикваріат", epKat_hizmet:"Робота / послуги", epKat_luks:"Люкс", epKat_diger:"Інше",
    epEt_pazarlik:"Торг", epEt_kargo:"Доставка", epEt_elden:"Особисто", epEt_acil:"Терміново", epEt_takas:"Обмін", epEt_ucretsiz:"Безкоштовно",
    epTagA:"Вибрані товари", epTagB:"купуй, продавай, заробляй",
    epAraPh:"Знайдіть або спитайте Gloxoo: чистий телефон до 20к",
    epAkilliAra:"Розумний пошук із Gloxoo", epAkilliAriyor:"Gloxoo шукає…",
    epAkilliOnce:"Спершу напишіть, що шукаєте — напр.: чистий телефон до 20к 🙂",
    epAkilliCozemedi:"Gloxoo не все зрозумів — шукаю за словом.",
    epGloxPre:"Gloxoo:", epAlti:"до", epUstu:"від",
    epIlanBulundu:"Знайдено оголошень: {{n}}", epUygunYok:"відповідних оголошень немає (поки що)",
    epSat:"Продати товар · Розмістити", epOneCikan:"Обрані оголошення",
    epIlanYukleniyor:"Завантаження оголошень…", epHenuzYok:"Оголошень ще немає — станьте першим продавцем! 🎉",
    epAramaYok:"Немає оголошень за цим запитом.", epIlkIlan:"Розмістити перше оголошення",
    epIlan:"Оголошення", epUcretsiz:"Безкоштовно", epSilOnay:"Видалити це оголошення?",
    epYeni:"Нове", epIkinciEl:"Вживане", epSatici:"Продавець",
    epFiyatUygun:"Ціна справедлива?", epBakiyor:"Перевіряю…", epPazarlikMesaji:"Повідомлення про торг", epYaziyor:"Пишу…",
    epBuMesajla:"Надіслати з цим повідомленням", epKopyala:"Копіювати", epMesajGonder:"Надіслати повідомлення", epAra:"Подзвонити", epEposta:"E-mail",
    epFavorimde:"В обраному", epFavori:"В обране", epIlaniSil:"Видалити оголошення",
    epDegerlendiremedim:"Зараз не вдалося оцінити, спробуйте трохи згодом.",
    epUrununuSat:"Продати товар", epFotoVideo:"ФОТО І ВІДЕО", epFoto:"Фото", epVideo:"Відео",
    epYukleniyorKisa:"Завантаження… ⏳", epVideoBuyuk:"Відео завелике (макс. 60 МБ)", epVideoYuklenemedi:"Не вдалося завантажити відео",
    epGloxYardimcin:"Gloxoo, ваш помічник", epGloxAlt:"Дивиться на фото, пише оголошення й пропонує ціну.",
    epIlaniGloxYazsin:"Нехай напише Gloxoo", epFiyatOner:"Запропонувати ціну",
    epBaslik:"ЗАГОЛОВОК", epBaslikPh:"Напр.: iPhone 15 Pro — чистий, у коробці", epAciklama:"ОПИС", epAciklamaPh:"Опишіть товар: стан, характеристики…",
    epFiyatEtk:"ЦІНА (₺)", epGloxFiyatOneri:"Пропозиція ціни Gloxoo", epOneriKullan:"Використати",
    epKategoriEtk:"КАТЕГОРІЯ", epDurumEtk:"СТАН",
    epKonumEtk:"МІСЦЕ (звідки продаєте)", epKonumPh:"Місто / район (напр.: Стамбул, Кадикей)",
    epHaritadanSec:"Обрати місце на карті", epKonumIsaretli:"Місце позначено на карті ✓ (змінити)",
    epKonumIpucu:"Якщо обрати на карті, покупець побачить місце товару на карті та скільки км до нього. Доставка = будь-куди, Особисто = віч-на-віч.",
    epEtiketlerEtk:"МІТКИ (куди/як)", epIletisimEtk:"КОНТАКТ (як покупець зв'яжеться з вами)",
    epIletisimNot:"Повідомлення в застосунку завжди ввімкнені. Можна додати телефон / e-mail / адресу — покупець побачить те, що ви вказали, і напише чи подзвонить.",
    epTelefonPh:"📞 Телефон (необов'язково)", epEpostaPh:"✉️ E-mail (необов'язково)", epAdresPh:"🏠 Адреса (необов'язково)",
    epIlaniYayinla:"Опублікувати", epYayinlaniyor:"Публікується…",
    epHataFoto:"Спершу додайте фото (щоб Gloxoo подивився) або напишіть кілька слів у заголовку.",
    epHataFotoFiyat:"Спершу додайте фото або напишіть заголовок — щоб Gloxoo запропонував ціну.",
    epHataBaslik:"Напишіть заголовок (Gloxoo теж може).", epHataFiyat:"Вкажіть ціну (або оберіть мітку 'Безкоштовно').",
    epHataKategori:"Оберіть категорію.", epHataFotoEkle:"Додайте хоча б одне фото.",
    epHataYayin:"Не вдалося опублікувати оголошення: {{hata}} (переконайтеся, що ви увійшли й правила опубліковані)",
    epKonumSec:"Обрати місце", epHaritaNot:"Торкніться карти, щоб позначити місце, або натисніть Використати моє місцезнаходження. Покупець побачить його на карті та відстань у км.",
    epKonumumuKullan:"Використати моє місцезнаходження", epBuKonumuSec:"Обрати це місце",
    epKonum:"МІСЦЕ", epUzaklik:"Приблизно за {{mesafe}} від вас", epUrununKonumu:"Місце товару", epYolTarifi:"Маршрут",
  }},
  es: { translation: {
    epKat_tumu:"Todos", epKat_moda:"Moda", epKat_ayakkabi:"Zapatos y bolsos", epKat_elektronik:"Electrónica", epKat_telefon:"Teléfono", epKat_ev:"Hogar y vida", epKat_arac:"Vehículo", epKat_moto:"Motocicleta", epKat_yedek:"Repuestos", epKat_emlak:"Inmuebles", epKat_bebek:"Bebé", epKat_spor:"Deportes", epKat_hayvan:"Mascotas", epKat_kozmetik:"Cosmética", epKat_saglik:"Salud", epKat_kitap:"Libros y hobbies", epKat_oyun:"Juegos y consolas", epKat_muzik:"Música", epKat_bahce:"Jardín y obra", epKat_antika:"Antigüedades", epKat_hizmet:"Trabajo / Servicios", epKat_luks:"Lujo", epKat_diger:"Otros",
    epEt_pazarlik:"Negociable", epEt_kargo:"Envío", epEt_elden:"En mano", epEt_acil:"Urgente", epEt_takas:"Trueque", epEt_ucretsiz:"Gratis",
    epTagA:"Artículos selectos", epTagB:"compra, vende, gana",
    epAraPh:"Busca o pregunta a Gloxoo: móvil limpio bajo 20k",
    epAkilliAra:"Búsqueda inteligente con Gloxoo", epAkilliAriyor:"Gloxoo está buscando…",
    epAkilliOnce:"Primero escribe qué buscas — p. ej.: móvil limpio bajo 20k 🙂",
    epAkilliCozemedi:"Gloxoo no lo entendió del todo — busco por palabra.",
    epGloxPre:"Gloxoo:", epAlti:"bajo", epUstu:"sobre",
    epIlanBulundu:"{{n}} anuncios encontrados", epUygunYok:"no hay anuncio adecuado (aún)",
    epSat:"Vende tu artículo · Publicar", epOneCikan:"Anuncios destacados",
    epIlanYukleniyor:"Cargando anuncios…", epHenuzYok:"Aún no hay anuncios — ¡sé el primero en vender! 🎉",
    epAramaYok:"Ningún anuncio coincide con esta búsqueda.", epIlkIlan:"Publicar el primer anuncio",
    epIlan:"Anuncio", epUcretsiz:"Gratis", epSilOnay:"¿Quieres eliminar este anuncio?",
    epYeni:"Nuevo", epIkinciEl:"Usado", epSatici:"Vendedor",
    epFiyatUygun:"¿Es justo este precio?", epBakiyor:"Comprobando…", epPazarlikMesaji:"Mensaje de negociación", epYaziyor:"Escribiendo…",
    epBuMesajla:"Enviar con este mensaje", epKopyala:"Copiar", epMesajGonder:"Enviar mensaje", epAra:"Llamar", epEposta:"Correo",
    epFavorimde:"En favoritos", epFavori:"Favorito", epIlaniSil:"Eliminar anuncio",
    epDegerlendiremedim:"No pude evaluarlo ahora, inténtalo de nuevo en un momento.",
    epUrununuSat:"Vende tu artículo", epFotoVideo:"FOTO Y VIDEO", epFoto:"Foto", epVideo:"Video",
    epYukleniyorKisa:"Subiendo… ⏳", epVideoBuyuk:"Video demasiado grande (máx. 60MB)", epVideoYuklenemedi:"No se pudo subir el video",
    epGloxYardimcin:"Gloxoo, tu ayudante", epGloxAlt:"Mira tu foto, escribe tu anuncio y sugiere un precio.",
    epIlaniGloxYazsin:"Que lo escriba Gloxoo", epFiyatOner:"Sugerir precio",
    epBaslik:"TÍTULO", epBaslikPh:"P. ej.: iPhone 15 Pro — limpio, con caja", epAciklama:"DESCRIPCIÓN", epAciklamaPh:"Describe el artículo: estado, características…",
    epFiyatEtk:"PRECIO (₺)", epGloxFiyatOneri:"Sugerencia de precio de Gloxoo", epOneriKullan:"Usar sugerencia",
    epKategoriEtk:"CATEGORÍA", epDurumEtk:"ESTADO",
    epKonumEtk:"UBICACIÓN (desde dónde vendes)", epKonumPh:"Ciudad / distrito (p. ej.: Estambul, Kadıköy)",
    epHaritadanSec:"Elegir ubicación en el mapa", epKonumIsaretli:"Ubicación marcada en el mapa ✓ (cambiar)",
    epKonumIpucu:"Si la eliges en el mapa, el comprador ve el lugar del artículo en el mapa y a cuántos km está. Envío = a cualquier sitio, En mano = cara a cara.",
    epEtiketlerEtk:"ETIQUETAS (dónde/cómo)", epIletisimEtk:"CONTACTO (cómo te contacta el comprador)",
    epIletisimNot:"La mensajería en la app siempre está activa. También puedes añadir teléfono / correo / dirección — el comprador ve lo que pongas y escribe o llama.",
    epTelefonPh:"📞 Teléfono (opcional)", epEpostaPh:"✉️ Correo (opcional)", epAdresPh:"🏠 Dirección (opcional)",
    epIlaniYayinla:"Publicar anuncio", epYayinlaniyor:"Publicando…",
    epHataFoto:"Primero añade una foto (para que Gloxoo la vea) o escribe unas palabras en el título.",
    epHataFotoFiyat:"Primero añade una foto o escribe un título — para que Gloxoo sugiera un precio.",
    epHataBaslik:"Escribe un título (Gloxoo también puede).", epHataFiyat:"Introduce un precio (o elige la etiqueta 'Gratis').",
    epHataKategori:"Elige una categoría.", epHataFotoEkle:"Añade al menos una foto.",
    epHataYayin:"No se pudo publicar el anuncio: {{hata}} (asegúrate de haber iniciado sesión y de que las reglas estén publicadas)",
    epKonumSec:"Elegir ubicación", epHaritaNot:"Toca el mapa para marcar tu lugar, o toca Usar mi ubicación. El comprador lo verá en el mapa y a cuántos km.",
    epKonumumuKullan:"Usar mi ubicación", epBuKonumuSec:"Elegir esta ubicación",
    epKonum:"UBICACIÓN", epUzaklik:"A unos {{mesafe}} de ti", epUrununKonumu:"Ubicación del artículo", epYolTarifi:"Cómo llegar",
  }},
  fr: { translation: {
    epKat_tumu:"Tous", epKat_moda:"Mode", epKat_ayakkabi:"Chaussures & Sacs", epKat_elektronik:"Électronique", epKat_telefon:"Téléphone", epKat_ev:"Maison & Vie", epKat_arac:"Véhicule", epKat_moto:"Moto", epKat_yedek:"Pièces détachées", epKat_emlak:"Immobilier", epKat_bebek:"Bébé", epKat_spor:"Sport", epKat_hayvan:"Animaux", epKat_kozmetik:"Cosmétiques", epKat_saglik:"Santé", epKat_kitap:"Livres & Loisirs", epKat_oyun:"Jeux & Consoles", epKat_muzik:"Musique", epKat_bahce:"Jardin & Bricolage", epKat_antika:"Antiquités", epKat_hizmet:"Emploi / Services", epKat_luks:"Luxe", epKat_diger:"Autre",
    epEt_pazarlik:"Négociable", epEt_kargo:"Livraison", epEt_elden:"En main propre", epEt_acil:"Urgent", epEt_takas:"Échange", epEt_ucretsiz:"Gratuit",
    epTagA:"Articles sélectionnés", epTagB:"achète, vends, gagne",
    epAraPh:"Cherchez ou demandez à Gloxoo : téléphone propre sous 20k",
    epAkilliAra:"Recherche intelligente avec Gloxoo", epAkilliAriyor:"Gloxoo cherche…",
    epAkilliOnce:"Écrivez d'abord ce que vous cherchez — p. ex. : téléphone propre sous 20k 🙂",
    epAkilliCozemedi:"Gloxoo n'a pas tout compris — je cherche par mot-clé.",
    epGloxPre:"Gloxoo :", epAlti:"sous", epUstu:"au-dessus de",
    epIlanBulundu:"{{n}} annonces trouvées", epUygunYok:"aucune annonce correspondante (pour l'instant)",
    epSat:"Vends ton article · Publier", epOneCikan:"Annonces en vedette",
    epIlanYukleniyor:"Chargement des annonces…", epHenuzYok:"Pas encore d'annonces — sois le premier à vendre ! 🎉",
    epAramaYok:"Aucune annonce ne correspond à cette recherche.", epIlkIlan:"Publier la première annonce",
    epIlan:"Annonce", epUcretsiz:"Gratuit", epSilOnay:"Voulez-vous supprimer cette annonce ?",
    epYeni:"Neuf", epIkinciEl:"Occasion", epSatici:"Vendeur",
    epFiyatUygun:"Ce prix est-il correct ?", epBakiyor:"Vérifie…", epPazarlikMesaji:"Message de négociation", epYaziyor:"Écrit…",
    epBuMesajla:"Envoyer avec ce message", epKopyala:"Copier", epMesajGonder:"Envoyer un message", epAra:"Appeler", epEposta:"E-mail",
    epFavorimde:"En favori", epFavori:"Favori", epIlaniSil:"Supprimer l'annonce",
    epDegerlendiremedim:"Je n'ai pas pu l'évaluer maintenant, réessayez dans un instant.",
    epUrununuSat:"Vends ton article", epFotoVideo:"PHOTO & VIDÉO", epFoto:"Photo", epVideo:"Vidéo",
    epYukleniyorKisa:"Envoi… ⏳", epVideoBuyuk:"Vidéo trop volumineuse (60 Mo max)", epVideoYuklenemedi:"Échec de l'envoi de la vidéo",
    epGloxYardimcin:"Gloxoo, ton assistant", epGloxAlt:"Il regarde ta photo, rédige ton annonce et suggère un prix.",
    epIlaniGloxYazsin:"Laisse Gloxoo l'écrire", epFiyatOner:"Suggérer un prix",
    epBaslik:"TITRE", epBaslikPh:"P. ex. : iPhone 15 Pro — propre, en boîte", epAciklama:"DESCRIPTION", epAciklamaPh:"Décris l'article : état, caractéristiques…",
    epFiyatEtk:"PRIX (₺)", epGloxFiyatOneri:"Suggestion de prix de Gloxoo", epOneriKullan:"Utiliser la suggestion",
    epKategoriEtk:"CATÉGORIE", epDurumEtk:"ÉTAT",
    epKonumEtk:"LIEU (d'où tu vends)", epKonumPh:"Ville / quartier (p. ex. : Istanbul, Kadıköy)",
    epHaritadanSec:"Choisir le lieu sur la carte", epKonumIsaretli:"Lieu marqué sur la carte ✓ (modifier)",
    epKonumIpucu:"Si tu le choisis sur la carte, l'acheteur voit l'emplacement de l'article sur la carte et à combien de km. Livraison = partout, En main propre = en personne.",
    epEtiketlerEtk:"ÉTIQUETTES (où/comment)", epIletisimEtk:"CONTACT (comment l'acheteur te joint)",
    epIletisimNot:"La messagerie de l'app est toujours active. Tu peux aussi ajouter téléphone / e-mail / adresse — l'acheteur voit ce que tu mets et écrit ou appelle.",
    epTelefonPh:"📞 Téléphone (facultatif)", epEpostaPh:"✉️ E-mail (facultatif)", epAdresPh:"🏠 Adresse (facultatif)",
    epIlaniYayinla:"Publier l'annonce", epYayinlaniyor:"Publication…",
    epHataFoto:"Ajoute d'abord une photo (pour que Gloxoo la voie) ou écris quelques mots dans le titre.",
    epHataFotoFiyat:"Ajoute d'abord une photo ou écris un titre — pour que Gloxoo suggère un prix.",
    epHataBaslik:"Écris un titre (Gloxoo peut aussi).", epHataFiyat:"Saisis un prix (ou choisis l'étiquette 'Gratuit').",
    epHataKategori:"Choisis une catégorie.", epHataFotoEkle:"Ajoute au moins une photo.",
    epHataYayin:"L'annonce n'a pas pu être publiée : {{hata}} (assure-toi d'être connecté et que les règles sont publiées)",
    epKonumSec:"Choisir le lieu", epHaritaNot:"Touche la carte pour marquer ton lieu, ou touche Utiliser ma position. L'acheteur le verra sur la carte et à combien de km.",
    epKonumumuKullan:"Utiliser ma position", epBuKonumuSec:"Choisir ce lieu",
    epKonum:"LIEU", epUzaklik:"À environ {{mesafe}} de vous", epUrununKonumu:"Emplacement de l'article", epYolTarifi:"Itinéraire",
  }},
  it: { translation: {
    epKat_tumu:"Tutti", epKat_moda:"Moda", epKat_ayakkabi:"Scarpe e borse", epKat_elektronik:"Elettronica", epKat_telefon:"Telefono", epKat_ev:"Casa e vita", epKat_arac:"Veicolo", epKat_moto:"Moto", epKat_yedek:"Ricambi", epKat_emlak:"Immobili", epKat_bebek:"Bimbi", epKat_spor:"Sport", epKat_hayvan:"Animali", epKat_kozmetik:"Cosmetici", epKat_saglik:"Salute", epKat_kitap:"Libri e hobby", epKat_oyun:"Giochi e console", epKat_muzik:"Musica", epKat_bahce:"Giardino e fai-da-te", epKat_antika:"Antiquariato", epKat_hizmet:"Lavoro / Servizi", epKat_luks:"Lusso", epKat_diger:"Altro",
    epEt_pazarlik:"Trattabile", epEt_kargo:"Spedizione", epEt_elden:"A mano", epEt_acil:"Urgente", epEt_takas:"Scambio", epEt_ucretsiz:"Gratis",
    epTagA:"Articoli selezionati", epTagB:"compra, vendi, guadagna",
    epAraPh:"Cerca o chiedi a Gloxoo: telefono pulito sotto i 20k",
    epAkilliAra:"Ricerca intelligente con Gloxoo", epAkilliAriyor:"Gloxoo sta cercando…",
    epAkilliOnce:"Scrivi prima cosa cerchi — es.: telefono pulito sotto i 20k 🙂",
    epAkilliCozemedi:"Gloxoo non ha capito del tutto — cerco per parola.",
    epGloxPre:"Gloxoo:", epAlti:"sotto", epUstu:"sopra",
    epIlanBulundu:"{{n}} annunci trovati", epUygunYok:"nessun annuncio adatto (per ora)",
    epSat:"Vendi il tuo articolo · Pubblica", epOneCikan:"Annunci in evidenza",
    epIlanYukleniyor:"Caricamento annunci…", epHenuzYok:"Ancora nessun annuncio — sii il primo a vendere! 🎉",
    epAramaYok:"Nessun annuncio corrisponde a questa ricerca.", epIlkIlan:"Pubblica il primo annuncio",
    epIlan:"Annuncio", epUcretsiz:"Gratis", epSilOnay:"Vuoi eliminare questo annuncio?",
    epYeni:"Nuovo", epIkinciEl:"Usato", epSatici:"Venditore",
    epFiyatUygun:"Questo prezzo è giusto?", epBakiyor:"Controllo…", epPazarlikMesaji:"Messaggio di trattativa", epYaziyor:"Scrivo…",
    epBuMesajla:"Invia con questo messaggio", epKopyala:"Copia", epMesajGonder:"Invia messaggio", epAra:"Chiama", epEposta:"E-mail",
    epFavorimde:"Nei preferiti", epFavori:"Preferito", epIlaniSil:"Elimina annuncio",
    epDegerlendiremedim:"Non sono riuscito a valutarlo ora, riprova tra poco.",
    epUrununuSat:"Vendi il tuo articolo", epFotoVideo:"FOTO E VIDEO", epFoto:"Foto", epVideo:"Video",
    epYukleniyorKisa:"Caricamento… ⏳", epVideoBuyuk:"Video troppo grande (max 60MB)", epVideoYuklenemedi:"Caricamento video non riuscito",
    epGloxYardimcin:"Gloxoo, il tuo assistente", epGloxAlt:"Guarda la tua foto, scrive l'annuncio e suggerisce un prezzo.",
    epIlaniGloxYazsin:"Fallo scrivere a Gloxoo", epFiyatOner:"Suggerisci prezzo",
    epBaslik:"TITOLO", epBaslikPh:"Es.: iPhone 15 Pro — pulito, con scatola", epAciklama:"DESCRIZIONE", epAciklamaPh:"Descrivi l'articolo: condizioni, caratteristiche…",
    epFiyatEtk:"PREZZO (₺)", epGloxFiyatOneri:"Suggerimento di prezzo di Gloxoo", epOneriKullan:"Usa suggerimento",
    epKategoriEtk:"CATEGORIA", epDurumEtk:"CONDIZIONE",
    epKonumEtk:"LUOGO (da dove vendi)", epKonumPh:"Città / quartiere (es.: Istanbul, Kadıköy)",
    epHaritadanSec:"Scegli luogo sulla mappa", epKonumIsaretli:"Luogo segnato sulla mappa ✓ (cambia)",
    epKonumIpucu:"Se lo scegli sulla mappa, l'acquirente vede il luogo dell'articolo sulla mappa e a quanti km. Spedizione = ovunque, A mano = di persona.",
    epEtiketlerEtk:"ETICHETTE (dove/come)", epIletisimEtk:"CONTATTO (come ti raggiunge l'acquirente)",
    epIletisimNot:"La messaggistica nell'app è sempre attiva. Puoi anche aggiungere telefono / e-mail / indirizzo — l'acquirente vede ciò che inserisci e scrive o chiama.",
    epTelefonPh:"📞 Telefono (facoltativo)", epEpostaPh:"✉️ E-mail (facoltativo)", epAdresPh:"🏠 Indirizzo (facoltativo)",
    epIlaniYayinla:"Pubblica annuncio", epYayinlaniyor:"Pubblicazione…",
    epHataFoto:"Aggiungi prima una foto (così Gloxoo la vede) o scrivi qualche parola nel titolo.",
    epHataFotoFiyat:"Aggiungi prima una foto o scrivi un titolo — così Gloxoo suggerisce un prezzo.",
    epHataBaslik:"Scrivi un titolo (può farlo anche Gloxoo).", epHataFiyat:"Inserisci un prezzo (o scegli l'etichetta 'Gratis').",
    epHataKategori:"Scegli una categoria.", epHataFotoEkle:"Aggiungi almeno una foto.",
    epHataYayin:"Impossibile pubblicare l'annuncio: {{hata}} (assicurati di aver effettuato l'accesso e che le regole siano pubblicate)",
    epKonumSec:"Scegli luogo", epHaritaNot:"Tocca la mappa per segnare il tuo luogo, o tocca Usa la mia posizione. L'acquirente lo vedrà sulla mappa e a quanti km.",
    epKonumumuKullan:"Usa la mia posizione", epBuKonumuSec:"Scegli questo luogo",
    epKonum:"LUOGO", epUzaklik:"A circa {{mesafe}} da te", epUrununKonumu:"Luogo dell'articolo", epYolTarifi:"Indicazioni",
  }},
  zh: { translation: {
    epKat_tumu:"全部", epKat_moda:"时尚", epKat_ayakkabi:"鞋履箱包", epKat_elektronik:"电子产品", epKat_telefon:"手机", epKat_ev:"家居生活", epKat_arac:"车辆", epKat_moto:"摩托车", epKat_yedek:"备件", epKat_emlak:"房产", epKat_bebek:"母婴", epKat_spor:"运动", epKat_hayvan:"宠物", epKat_kozmetik:"美妆", epKat_saglik:"健康", epKat_kitap:"图书爱好", epKat_oyun:"游戏主机", epKat_muzik:"音乐", epKat_bahce:"园艺建材", epKat_antika:"古董", epKat_hizmet:"工作 / 服务", epKat_luks:"奢侈品", epKat_diger:"其他",
    epEt_pazarlik:"可议价", epEt_kargo:"包邮", epEt_elden:"当面交易", epEt_acil:"急售", epEt_takas:"交换", epEt_ucretsiz:"免费",
    epTagA:"精选商品", epTagB:"买、卖、赚",
    epAraPh:"搜索或问 Gloxoo：2万以下成色好的手机",
    epAkilliAra:"用 Gloxoo 智能搜索", epAkilliAriyor:"Gloxoo 正在搜索…",
    epAkilliOnce:"先写下你要找什么 — 例如：2万以下成色好的手机 🙂",
    epAkilliCozemedi:"Gloxoo 没完全理解 — 按关键词搜索。",
    epGloxPre:"Gloxoo：", epAlti:"以下", epUstu:"以上",
    epIlanBulundu:"找到 {{n}} 条商品", epUygunYok:"暂无匹配的商品",
    epSat:"出售物品 · 发布", epOneCikan:"精选商品",
    epIlanYukleniyor:"正在加载商品…", epHenuzYok:"还没有商品 — 来当第一个卖家吧！🎉",
    epAramaYok:"没有符合此搜索的商品。", epIlkIlan:"发布第一条商品",
    epIlan:"商品", epUcretsiz:"免费", epSilOnay:"要删除此商品吗？",
    epYeni:"全新", epIkinciEl:"二手", epSatici:"卖家",
    epFiyatUygun:"这个价格合理吗？", epBakiyor:"查看中…", epPazarlikMesaji:"议价消息", epYaziyor:"撰写中…",
    epBuMesajla:"用此消息发送", epKopyala:"复制", epMesajGonder:"发送消息", epAra:"拨打", epEposta:"邮箱",
    epFavorimde:"已收藏", epFavori:"收藏", epIlaniSil:"删除商品",
    epDegerlendiremedim:"现在无法评估，请稍后再试。",
    epUrununuSat:"出售物品", epFotoVideo:"照片和视频", epFoto:"照片", epVideo:"视频",
    epYukleniyorKisa:"上传中… ⏳", epVideoBuyuk:"视频过大（最大 60MB）", epVideoYuklenemedi:"视频上传失败",
    epGloxYardimcin:"Gloxoo 你的助手", epGloxAlt:"它看你的照片、写商品文案并给出定价建议。",
    epIlaniGloxYazsin:"让 Gloxoo 来写", epFiyatOner:"建议价格",
    epBaslik:"标题", epBaslikPh:"例如：iPhone 15 Pro — 成色好，带盒", epAciklama:"描述", epAciklamaPh:"描述商品：成色、特点…",
    epFiyatEtk:"价格 (₺)", epGloxFiyatOneri:"Gloxoo 价格建议", epOneriKullan:"采用建议",
    epKategoriEtk:"分类", epDurumEtk:"成色",
    epKonumEtk:"位置（从哪里出售）", epKonumPh:"城市 / 区（例如：伊斯坦布尔，卡德柯伊）",
    epHaritadanSec:"在地图上选择位置", epKonumIsaretli:"已在地图上标记位置 ✓（更改）",
    epKonumIpucu:"若在地图上选择，买家会在地图上看到商品位置及距离多少公里。包邮 = 全国，当面交易 = 面对面。",
    epEtiketlerEtk:"标签（去哪/怎样）", epIletisimEtk:"联系方式（买家如何联系你）",
    epIletisimNot:"应用内消息始终开启。你也可以添加电话 / 邮箱 / 地址 — 买家会看到你填写的内容，据此留言或致电。",
    epTelefonPh:"📞 电话（可选）", epEpostaPh:"✉️ 邮箱（可选）", epAdresPh:"🏠 地址（可选）",
    epIlaniYayinla:"发布商品", epYayinlaniyor:"发布中…",
    epHataFoto:"先添加一张照片（让 Gloxoo 看看）或在标题里写几个字。",
    epHataFotoFiyat:"先添加照片或写标题 — 好让 Gloxoo 给出价格建议。",
    epHataBaslik:"写个标题（Gloxoo 也能写）。", epHataFiyat:"输入价格（或选择“免费”标签）。",
    epHataKategori:"选择一个分类。", epHataFotoEkle:"至少添加一张照片。",
    epHataYayin:"无法发布商品：{{hata}}（请确认已登录且规则已发布）",
    epKonumSec:"选择位置", epHaritaNot:"点按地图标记你的位置，或点“使用我的位置”。买家会在地图上看到并显示距离多少公里。",
    epKonumumuKullan:"使用我的位置", epBuKonumuSec:"选择此位置",
    epKonum:"位置", epUzaklik:"距您约 {{mesafe}}", epUrununKonumu:"商品位置", epYolTarifi:"导航",
  }},
  hi: { translation: {
    epKat_tumu:"सभी", epKat_moda:"फ़ैशन", epKat_ayakkabi:"जूते और बैग", epKat_elektronik:"इलेक्ट्रॉनिक्स", epKat_telefon:"फ़ोन", epKat_ev:"घर और जीवन", epKat_arac:"वाहन", epKat_moto:"मोटरसाइकिल", epKat_yedek:"स्पेयर पार्ट्स", epKat_emlak:"रियल एस्टेट", epKat_bebek:"शिशु", epKat_spor:"खेल", epKat_hayvan:"पालतू", epKat_kozmetik:"सौंदर्य प्रसाधन", epKat_saglik:"स्वास्थ्य", epKat_kitap:"किताबें और शौक", epKat_oyun:"गेम्स और कंसोल", epKat_muzik:"संगीत", epKat_bahce:"बगीचा और निर्माण", epKat_antika:"एंटीक", epKat_hizmet:"काम / सेवाएँ", epKat_luks:"लक्ज़री", epKat_diger:"अन्य",
    epEt_pazarlik:"मोलभाव", epEt_kargo:"शिपिंग", epEt_elden:"हाथोंहाथ", epEt_acil:"तत्काल", epEt_takas:"अदला-बदली", epEt_ucretsiz:"मुफ़्त",
    epTagA:"चुनिंदा वस्तुएँ", epTagB:"खरीदें, बेचें, कमाएँ",
    epAraPh:"खोजें या Gloxoo से पूछें: 20 हज़ार से कम साफ़ फ़ोन",
    epAkilliAra:"Gloxoo के साथ स्मार्ट खोज", epAkilliAriyor:"Gloxoo खोज रहा है…",
    epAkilliOnce:"पहले लिखें कि आप क्या ढूँढ रहे हैं — जैसे: 20 हज़ार से कम साफ़ फ़ोन 🙂",
    epAkilliCozemedi:"Gloxoo पूरी तरह समझ नहीं पाया — शब्द से खोज रहा हूँ।",
    epGloxPre:"Gloxoo:", epAlti:"से कम", epUstu:"से अधिक",
    epIlanBulundu:"{{n}} विज्ञापन मिले", epUygunYok:"कोई मेल खाता विज्ञापन नहीं (अभी)",
    epSat:"अपनी वस्तु बेचें · विज्ञापन डालें", epOneCikan:"फ़ीचर्ड विज्ञापन",
    epIlanYukleniyor:"विज्ञापन लोड हो रहे हैं…", epHenuzYok:"अभी कोई विज्ञापन नहीं — पहले बेचने वाले बनें! 🎉",
    epAramaYok:"इस खोज से मेल खाता कोई विज्ञापन नहीं।", epIlkIlan:"पहला विज्ञापन डालें",
    epIlan:"विज्ञापन", epUcretsiz:"मुफ़्त", epSilOnay:"क्या आप यह विज्ञापन हटाना चाहते हैं?",
    epYeni:"नया", epIkinciEl:"पुराना", epSatici:"विक्रेता",
    epFiyatUygun:"क्या यह कीमत उचित है?", epBakiyor:"देख रहा है…", epPazarlikMesaji:"मोलभाव संदेश", epYaziyor:"लिख रहा है…",
    epBuMesajla:"इस संदेश के साथ भेजें", epKopyala:"कॉपी करें", epMesajGonder:"संदेश भेजें", epAra:"कॉल करें", epEposta:"ईमेल",
    epFavorimde:"पसंदीदा में", epFavori:"पसंदीदा", epIlaniSil:"विज्ञापन हटाएँ",
    epDegerlendiremedim:"अभी मूल्यांकन नहीं कर सका, कृपया थोड़ी देर में फिर कोशिश करें।",
    epUrununuSat:"अपनी वस्तु बेचें", epFotoVideo:"फ़ोटो और वीडियो", epFoto:"फ़ोटो", epVideo:"वीडियो",
    epYukleniyorKisa:"अपलोड हो रहा है… ⏳", epVideoBuyuk:"वीडियो बहुत बड़ा है (अधिकतम 60MB)", epVideoYuklenemedi:"वीडियो अपलोड नहीं हुआ",
    epGloxYardimcin:"Gloxoo आपका सहायक", epGloxAlt:"आपकी फ़ोटो देखकर विज्ञापन लिखता है और कीमत सुझाता है।",
    epIlaniGloxYazsin:"Gloxoo से लिखवाएँ", epFiyatOner:"कीमत सुझाएँ",
    epBaslik:"शीर्षक", epBaslikPh:"जैसे: iPhone 15 Pro — साफ़, बॉक्स सहित", epAciklama:"विवरण", epAciklamaPh:"वस्तु का वर्णन करें: स्थिति, विशेषताएँ…",
    epFiyatEtk:"कीमत (₺)", epGloxFiyatOneri:"Gloxoo की कीमत सलाह", epOneriKullan:"सुझाव इस्तेमाल करें",
    epKategoriEtk:"श्रेणी", epDurumEtk:"स्थिति",
    epKonumEtk:"स्थान (कहाँ से बेच रहे हैं)", epKonumPh:"शहर / क्षेत्र (जैसे: इस्तांबुल, कादिकोय)",
    epHaritadanSec:"नक्शे पर स्थान चुनें", epKonumIsaretli:"स्थान नक्शे पर चिह्नित ✓ (बदलें)",
    epKonumIpucu:"नक्शे पर चुनने पर खरीदार वस्तु का स्थान नक्शे पर और कितने किमी दूर है, देखेगा। शिपिंग = कहीं भी, हाथोंहाथ = आमने-सामने।",
    epEtiketlerEtk:"टैग (कहाँ/कैसे)", epIletisimEtk:"संपर्क (खरीदार आप तक कैसे पहुँचे)",
    epIletisimNot:"ऐप में मैसेज हमेशा चालू है। आप फ़ोन / ईमेल / पता भी जोड़ सकते हैं — खरीदार जो आपने डाला वही देखेगा और उसी अनुसार लिखेगा या कॉल करेगा।",
    epTelefonPh:"📞 फ़ोन (वैकल्पिक)", epEpostaPh:"✉️ ईमेल (वैकल्पिक)", epAdresPh:"🏠 पता (वैकल्पिक)",
    epIlaniYayinla:"विज्ञापन प्रकाशित करें", epYayinlaniyor:"प्रकाशित हो रहा है…",
    epHataFoto:"पहले एक फ़ोटो जोड़ें (ताकि Gloxoo देख सके) या शीर्षक में कुछ शब्द लिखें।",
    epHataFotoFiyat:"पहले फ़ोटो जोड़ें या शीर्षक लिखें — ताकि Gloxoo कीमत सुझा सके।",
    epHataBaslik:"एक शीर्षक लिखें (Gloxoo भी लिख सकता है)।", epHataFiyat:"कीमत डालें (या 'मुफ़्त' टैग चुनें)।",
    epHataKategori:"एक श्रेणी चुनें।", epHataFotoEkle:"कम से कम एक फ़ोटो जोड़ें।",
    epHataYayin:"विज्ञापन प्रकाशित नहीं हो सका: {{hata}} (सुनिश्चित करें कि आप लॉग इन हैं और नियम प्रकाशित हैं)",
    epKonumSec:"स्थान चुनें", epHaritaNot:"अपना स्थान चिह्नित करने के लिए नक्शे पर टैप करें, या मेरा स्थान उपयोग करें दबाएँ। खरीदार इसे नक्शे पर और कितने किमी दूर देखेगा।",
    epKonumumuKullan:"मेरा स्थान उपयोग करें", epBuKonumuSec:"यह स्थान चुनें",
    epKonum:"स्थान", epUzaklik:"आपसे लगभग {{mesafe}} दूर", epUrununKonumu:"वस्तु का स्थान", epYolTarifi:"दिशा-निर्देश",
  }},
  pt: { translation: {
    epKat_tumu:"Todos", epKat_moda:"Moda", epKat_ayakkabi:"Sapatos e bolsas", epKat_elektronik:"Eletrônicos", epKat_telefon:"Telefone", epKat_ev:"Casa e vida", epKat_arac:"Veículo", epKat_moto:"Motocicleta", epKat_yedek:"Peças", epKat_emlak:"Imóveis", epKat_bebek:"Bebê", epKat_spor:"Esportes", epKat_hayvan:"Animais", epKat_kozmetik:"Cosméticos", epKat_saglik:"Saúde", epKat_kitap:"Livros e hobby", epKat_oyun:"Jogos e consoles", epKat_muzik:"Música", epKat_bahce:"Jardim e construção", epKat_antika:"Antiguidades", epKat_hizmet:"Trabalho / Serviços", epKat_luks:"Luxo", epKat_diger:"Outros",
    epEt_pazarlik:"Negociável", epEt_kargo:"Envio", epEt_elden:"Em mãos", epEt_acil:"Urgente", epEt_takas:"Troca", epEt_ucretsiz:"Grátis",
    epTagA:"Itens selecionados", epTagB:"compre, venda, ganhe",
    epAraPh:"Busque ou pergunte ao Gloxoo: celular limpo abaixo de 20k",
    epAkilliAra:"Busca inteligente com Gloxoo", epAkilliAriyor:"Gloxoo está buscando…",
    epAkilliOnce:"Escreva primeiro o que procura — ex.: celular limpo abaixo de 20k 🙂",
    epAkilliCozemedi:"O Gloxoo não entendeu totalmente — buscando por palavra.",
    epGloxPre:"Gloxoo:", epAlti:"abaixo de", epUstu:"acima de",
    epIlanBulundu:"{{n}} anúncios encontrados", epUygunYok:"nenhum anúncio correspondente (ainda)",
    epSat:"Venda seu item · Anunciar", epOneCikan:"Anúncios em destaque",
    epIlanYukleniyor:"Carregando anúncios…", epHenuzYok:"Ainda não há anúncios — seja o primeiro a vender! 🎉",
    epAramaYok:"Nenhum anúncio corresponde a esta busca.", epIlkIlan:"Publicar o primeiro anúncio",
    epIlan:"Anúncio", epUcretsiz:"Grátis", epSilOnay:"Deseja excluir este anúncio?",
    epYeni:"Novo", epIkinciEl:"Usado", epSatici:"Vendedor",
    epFiyatUygun:"Este preço é justo?", epBakiyor:"Verificando…", epPazarlikMesaji:"Mensagem de negociação", epYaziyor:"Escrevendo…",
    epBuMesajla:"Enviar com esta mensagem", epKopyala:"Copiar", epMesajGonder:"Enviar mensagem", epAra:"Ligar", epEposta:"E-mail",
    epFavorimde:"Nos favoritos", epFavori:"Favorito", epIlaniSil:"Excluir anúncio",
    epDegerlendiremedim:"Não consegui avaliar agora, tente novamente em instantes.",
    epUrununuSat:"Venda seu item", epFotoVideo:"FOTO E VÍDEO", epFoto:"Foto", epVideo:"Vídeo",
    epYukleniyorKisa:"Enviando… ⏳", epVideoBuyuk:"Vídeo muito grande (máx. 60MB)", epVideoYuklenemedi:"Falha ao enviar o vídeo",
    epGloxYardimcin:"Gloxoo, seu assistente", epGloxAlt:"Ele olha sua foto, escreve seu anúncio e sugere um preço.",
    epIlaniGloxYazsin:"Deixe o Gloxoo escrever", epFiyatOner:"Sugerir preço",
    epBaslik:"TÍTULO", epBaslikPh:"Ex.: iPhone 15 Pro — limpo, com caixa", epAciklama:"DESCRIÇÃO", epAciklamaPh:"Descreva o item: estado, características…",
    epFiyatEtk:"PREÇO (₺)", epGloxFiyatOneri:"Sugestão de preço do Gloxoo", epOneriKullan:"Usar sugestão",
    epKategoriEtk:"CATEGORIA", epDurumEtk:"ESTADO",
    epKonumEtk:"LOCAL (de onde você vende)", epKonumPh:"Cidade / bairro (ex.: Istambul, Kadıköy)",
    epHaritadanSec:"Escolher local no mapa", epKonumIsaretli:"Local marcado no mapa ✓ (alterar)",
    epKonumIpucu:"Se escolher no mapa, o comprador vê o local do item no mapa e a quantos km está. Envio = para qualquer lugar, Em mãos = pessoalmente.",
    epEtiketlerEtk:"ETIQUETAS (onde/como)", epIletisimEtk:"CONTATO (como o comprador fala com você)",
    epIletisimNot:"As mensagens no app estão sempre ativas. Você também pode adicionar telefone / e-mail / endereço — o comprador vê o que você colocar e escreve ou liga.",
    epTelefonPh:"📞 Telefone (opcional)", epEpostaPh:"✉️ E-mail (opcional)", epAdresPh:"🏠 Endereço (opcional)",
    epIlaniYayinla:"Publicar anúncio", epYayinlaniyor:"Publicando…",
    epHataFoto:"Adicione uma foto primeiro (para o Gloxoo ver) ou escreva algumas palavras no título.",
    epHataFotoFiyat:"Adicione uma foto ou escreva um título primeiro — para o Gloxoo sugerir um preço.",
    epHataBaslik:"Escreva um título (o Gloxoo também pode).", epHataFiyat:"Digite um preço (ou escolha a etiqueta 'Grátis').",
    epHataKategori:"Escolha uma categoria.", epHataFotoEkle:"Adicione pelo menos uma foto.",
    epHataYayin:"Não foi possível publicar o anúncio: {{hata}} (verifique se você está conectado e se as regras estão publicadas)",
    epKonumSec:"Escolher local", epHaritaNot:"Toque no mapa para marcar seu local, ou toque em Usar minha localização. O comprador verá no mapa e a quantos km.",
    epKonumumuKullan:"Usar minha localização", epBuKonumuSec:"Escolher este local",
    epKonum:"LOCAL", epUzaklik:"A cerca de {{mesafe}} de você", epUrununKonumu:"Local do item", epYolTarifi:"Rotas",
  }},
  ja: { translation: {
    epKat_tumu:"すべて", epKat_moda:"ファッション", epKat_ayakkabi:"靴・バッグ", epKat_elektronik:"電子機器", epKat_telefon:"スマホ", epKat_ev:"住まい・暮らし", epKat_arac:"車", epKat_moto:"バイク", epKat_yedek:"部品", epKat_emlak:"不動産", epKat_bebek:"ベビー", epKat_spor:"スポーツ", epKat_hayvan:"ペット", epKat_kozmetik:"コスメ", epKat_saglik:"健康", epKat_kitap:"本・趣味", epKat_oyun:"ゲーム・機器", epKat_muzik:"音楽", epKat_bahce:"園芸・DIY", epKat_antika:"アンティーク", epKat_hizmet:"仕事・サービス", epKat_luks:"ラグジュアリー", epKat_diger:"その他",
    epEt_pazarlik:"交渉可", epEt_kargo:"配送", epEt_elden:"手渡し", epEt_acil:"急ぎ", epEt_takas:"交換", epEt_ucretsiz:"無料",
    epTagA:"厳選アイテム", epTagB:"買う・売る・稼ぐ",
    epAraPh:"検索、または Gloxoo に相談：2万以下のきれいなスマホ",
    epAkilliAra:"Gloxoo でスマート検索", epAkilliAriyor:"Gloxoo が検索中…",
    epAkilliOnce:"まず探しているものを入力 — 例：2万以下のきれいなスマホ 🙂",
    epAkilliCozemedi:"Gloxoo が完全に理解できませんでした — キーワードで検索します。",
    epGloxPre:"Gloxoo：", epAlti:"以下", epUstu:"以上",
    epIlanBulundu:"{{n}}件の出品", epUygunYok:"該当する出品はありません（まだ）",
    epSat:"商品を売る · 出品する", epOneCikan:"注目の出品",
    epIlanYukleniyor:"出品を読み込み中…", epHenuzYok:"まだ出品がありません — 最初の出品者になろう！🎉",
    epAramaYok:"この検索に該当する出品はありません。", epIlkIlan:"最初の出品をする",
    epIlan:"出品", epUcretsiz:"無料", epSilOnay:"この出品を削除しますか？",
    epYeni:"新品", epIkinciEl:"中古", epSatici:"出品者",
    epFiyatUygun:"この価格は妥当？", epBakiyor:"確認中…", epPazarlikMesaji:"交渉メッセージ", epYaziyor:"作成中…",
    epBuMesajla:"このメッセージで送る", epKopyala:"コピー", epMesajGonder:"メッセージを送る", epAra:"電話", epEposta:"メール",
    epFavorimde:"お気に入り済み", epFavori:"お気に入り", epIlaniSil:"出品を削除",
    epDegerlendiremedim:"今は評価できませんでした。しばらくして再度お試しください。",
    epUrununuSat:"商品を売る", epFotoVideo:"写真・動画", epFoto:"写真", epVideo:"動画",
    epYukleniyorKisa:"アップロード中… ⏳", epVideoBuyuk:"動画が大きすぎます（最大60MB）", epVideoYuklenemedi:"動画のアップロードに失敗しました",
    epGloxYardimcin:"Gloxoo あなたのアシスタント", epGloxAlt:"写真を見て出品文を書き、価格を提案します。",
    epIlaniGloxYazsin:"Gloxoo に書いてもらう", epFiyatOner:"価格を提案",
    epBaslik:"タイトル", epBaslikPh:"例：iPhone 15 Pro — きれい、箱あり", epAciklama:"説明", epAciklamaPh:"商品を説明：状態、特徴…",
    epFiyatEtk:"価格 (₺)", epGloxFiyatOneri:"Gloxoo の価格提案", epOneriKullan:"提案を使う",
    epKategoriEtk:"カテゴリー", epDurumEtk:"状態",
    epKonumEtk:"場所（どこから売るか）", epKonumPh:"市 / 区（例：イスタンブール、カドゥキョイ）",
    epHaritadanSec:"地図で場所を選ぶ", epKonumIsaretli:"地図に場所を記録 ✓（変更）",
    epKonumIpucu:"地図で選ぶと、買い手は商品の場所を地図上で、そして何km先かを確認できます。配送＝どこでも、手渡し＝対面。",
    epEtiketlerEtk:"タグ（どこへ/どう）", epIletisimEtk:"連絡先（買い手の連絡方法）",
    epIletisimNot:"アプリ内メッセージは常に有効です。電話 / メール / 住所も追加できます — 買い手はあなたが入れたものを見て、それに応じて連絡します。",
    epTelefonPh:"📞 電話（任意）", epEpostaPh:"✉️ メール（任意）", epAdresPh:"🏠 住所（任意）",
    epIlaniYayinla:"出品を公開", epYayinlaniyor:"公開中…",
    epHataFoto:"まず写真を追加（Gloxoo が見られるように）するか、タイトルに数語入力してください。",
    epHataFotoFiyat:"まず写真を追加するかタイトルを書いてください — Gloxoo が価格を提案できるように。",
    epHataBaslik:"タイトルを入力してください（Gloxoo も書けます）。", epHataFiyat:"価格を入力してください（または「無料」タグを選択）。",
    epHataKategori:"カテゴリーを選んでください。", epHataFotoEkle:"写真を少なくとも1枚追加してください。",
    epHataYayin:"出品を公開できませんでした：{{hata}}（ログイン済みで、ルールが公開されていることを確認してください）",
    epKonumSec:"場所を選ぶ", epHaritaNot:"地図をタップして場所を記録するか、「現在地を使う」をタップ。買い手は地図上で、何km先かも確認できます。",
    epKonumumuKullan:"現在地を使う", epBuKonumuSec:"この場所を選ぶ",
    epKonum:"場所", epUzaklik:"あなたから約 {{mesafe}}", epUrununKonumu:"商品の場所", epYolTarifi:"経路",
  }},
};
