// GLOXORG Muhasebe + Belgeler modulu cevirileri (13 dil). i18n.js icinde resources ile birlestirilir.
export const CEVIRI_MUHASEBE = {
  "tr": {
    "muhOlmadi": "Olmadı, tekrar dener misin?",
    "muhCopeGitti": "Çöp kutusuna gönderildi 🗑️",
    "muhGeriYuklendi": "Geri yüklendi ✓",
    "muhKaliciSor": "KALICI silinsin mi? Bu geri alınamaz.",
    "muhKaliciSilindi": "Kalıcı silindi",
    "muhExcelIndi": "Excel indirildi 📊",
    "muhPdfHazir": "PDF hazır 📄",
    "muhMenu": "Menü",
    "sil": "Sil",
    "muhMusteri": "Müşteri",
    "muhUrun": "Ürün",
    "muhIslemK": "İşlem",
    "muhKasaK": "Kasa",
    "muhBelgeler": "Belgeler",
    "muhMusteriler": "Müşteriler",
    "muhStok": "Stok",
    "muhAlisSatis": "Alış-Satış",
    "muhKasa": "Kasa",
    "muhCop": "Çöp",
    "muhBaslik": "Muhasebe",
    "kapat": "Kapat",
    "muhYukleniyor": "Yükleniyor…",
    "muhYeniMusteri": "Yeni müşteri / tedarikçi",
    "muhEklendi": "Eklendi ✓",
    "muhHicMusteri": "Henüz müşteri yok. Yukarıdan ekle.",
    "muhTedarikci": "Tedarikçi",
    "muhToplamBorc": "Toplam Borç",
    "muhToplamTahsilat": "Tahsilat",
    "muhKalan": "Kalan",
    "muhKayitEklendi": "Eklendi ✓",
    "muhKayitYok": "Kayıt yok. Borç ya da tahsilat ekle.",
    "muhBorc": "Borç",
    "muhTahsilat": "Tahsilat",
    "muhTarih": "Tarih",
    "muhAciklama": "Açıklama",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Paylaş",
    "muhYeniUrun": "Yeni ürün",
    "muhHicUrun": "Henüz ürün yok. Yukarıdan ekle.",
    "muhAlisF": "Alış fiyatı",
    "muhSatisF": "Satış fiyatı",
    "muhKalanStok": "Kalan Stok",
    "muhHareketYok": "Hareket yok. Giriş ya da çıkış ekle.",
    "muhGiris": "Giriş",
    "muhCikis": "Çıkış",
    "muhYeniIslem": "Yeni alış / satış",
    "muhIslemYok": "Henüz alış-satış yok.",
    "muhSatis": "Satış",
    "muhAlis": "Alış",
    "muhGelir": "Gelir",
    "muhGider": "Gider",
    "muhKasaBakiye": "Kasa",
    "muhYeniKasa": "Gelir / gider ekle",
    "muhKasaYok": "Henüz kasa hareketi yok.",
    "muhBanka": "Banka",
    "muhNakit": "Nakit",
    "muhCopAlt": "Sildiklerin burada ~30 gün saklanır. Geri yükleyebilir ya da hemen kalıcı silebilirsin. Süre dolunca kendiliğinden silinir.",
    "muhCopBos": "Çöp kutusu boş.",
    "muhGun": "gün",
    "muhGeriYukle": "Geri",
    "muhHazirlaniyor": "Hazırlanıyor…",
    "muhAd": "Ad",
    "muhTel": "Telefon",
    "istege": "isteğe bağlı",
    "muhNot": "Not",
    "muhKaydet": "Kaydet",
    "muhVazgec": "Vazgeç",
    "muhTutar": "Tutar",
    "muhKayitEkle": "Ekle",
    "muhUrunAd": "Ürün adı",
    "muhBirim": "Birim (adet, kg, m…)",
    "muhMiktar": "Miktar",
    "muhCariSec": "Müşteri/Tedarikçi seç (isteğe bağlı)",
    "muhUrunSec": "Ürün seç (isteğe bağlı)",
    "belTablo": "Excel tablosu",
    "belFatura": "Fatura",
    "belMeslek": "Meslek sayfası",
    "belYazi": "Word belgesi",
    "belKaydedildi": "Kaydedildi ✓",
    "belBugun": "Bugün",
    "belBuAy": "Bu Ay",
    "belBuYil": "Bu Yıl",
    "belEski": "Daha Eski",
    "belAlt2": "Kendi Excel/Word/Fatura belgeni oluştur, foto→PDF yap, mesleğine göre hazır sayfa seç ya da kendi meslek sayfanı yapıp paylaş. Her şey arşivlenir, sen silmeden gitmez.",
    "belFotoPdf": "Foto → PDF",
    "belSablon": "Hazır şablon",
    "belMeslekSayfam": "Meslek sayfam",
    "belAraPh": "Belgelerinde ara",
    "belAraBos": "Aramana uygun belge yok.",
    "belYok": "Henüz belge yok. Yukarıdan oluştur.",
    "belAdsiz": "Adsız belge",
    "belEnAz2": "En az 2 hücre seç",
    "belHesaplandi": "Hesaplandı ✓ sonuç hücreye yazıldı",
    "belOnceIslem": "Önce işlem seç: ＋ － × ÷",
    "belTopla2": "Topla",
    "belCikar": "Çıkar",
    "belCarp": "Çarp",
    "belBol": "Böl",
    "belGeri": "Belgeler",
    "belTabloAd": "Tablo adı",
    "belYaziMod": "Yazı / Rakam gir",
    "belHesapMod": "Düğmeyle hesapla",
    "belSatir": "Satır",
    "belSutun": "Sütun",
    "belToplam": "Toplam",
    "belGenislik": "Genişlik",
    "belSonucDokun": "Sonucun çıkacağı BOŞ hücreye dokun",
    "belHucreleriSec": "Hesaplanacak sayı hücrelerine dokun (seçilir)",
    "belIslemSec": "Önce işlem seç: Topla / Çıkar / Çarp / Böl",
    "belSonucDokun2": "Şimdi sonucun çıkacağı boş hücreye dokun",
    "belSonucYaz": "Sonucu yaz",
    "belTemizle": "Temizle",
    "belYaziIpucu": "✍️ Hücrelere yazı ya da rakam yaz. Hesap yapmak için üstten 🔢 Düğmeyle hesapla'ya geç. (İstersen elle formül de yazabilirsin: =A1+B1) Üstteki harfe dokun → sırala.",
    "belKaydet": "Kaydet",
    "belExcelIndi": "Excel indirildi 📊",
    "belOlmadi": "Olmadı",
    "belPdfHazir": "PDF hazır 📄",
    "belYaziAd": "Belge adı",
    "belBaslik": "Başlık",
    "belListe": "Liste",
    "belWordIndi": "Word indirildi 📘",
    "belFotoYok": "Önce fotoğraf ekle",
    "belFotoBaslik": "Başlık (isteğe bağlı)",
    "belFotoEkle": "Fotoğraf ekle",
    "belFotoAlt": "Fotoğraf ekle (birden çok olabilir). Sıralayıp tek PDF yap, indir/paylaş.",
    "belPdfYapPaylas": "PDF yap — indir / paylaş",
    "belUrun": "Ürün/Hizmet",
    "belMiktar": "Miktar",
    "belFiyat": "Birim Fiyat",
    "belTutar": "Tutar",
    "belAraToplam": "Ara Toplam",
    "belGenelToplam": "GENEL TOPLAM",
    "belFaturaAd": "Fatura adı",
    "belSatici": "Satıcı (senin firman)",
    "belAlici": "Alıcı (müşteri)",
    "belFaturaNo": "Fatura No",
    "belSatirEkle": "Satır ekle",
    "belSablonSec": "Mesleğine göre hazır şablon seç",
    "belSablonAlt": "Mesleğini seç, hazır sayfa açılsın; içini kendine göre doldur, sonra Excel/Word/PDF indir.",
    "belPaylasildi": "Paylaşıldı ✓",
    "belMeslekAd": "Sayfa adı",
    "belMeslekAlt": "Mesleğine göre kendi tanıtım sayfanı yap: firma adı, ne iş yaptığın, hizmetler, telefon, adres, fotoğraf. Sonra PDF/foto indir, paylaş ya da GLOXORG'da yayınla.",
    "belFirma": "Firma / İşletme adı",
    "belMeslekTur": "Meslek (ör. Kuaför, Terzi, Restoran)",
    "belSlogan": "Slogan (kısa tanıtım)",
    "belMeslekAciklama": "Kendini / işini anlat",
    "belHizmetler": "Hizmetler (her satıra bir tane)",
    "belTelefon": "Telefon",
    "belAdres": "Adres / Konum",
    "belFotoDegis": "Fotoğrafı değiştir",
    "belFotoEkleBtn": "Fotoğraf / logo ekle",
    "belFirmaOrnek": "Firma Adı",
    "belPaylas": "Paylaş",
    "belGloxorda": "GLOXORG'da paylaş",
    "sanalAyna": "Sanal Ayna",
    "sanalAynaKisa": "Ayna"
  },
  "en": {
    "muhOlmadi": "Didn't work, try again?",
    "muhCopeGitti": "Moved to trash 🗑️",
    "muhGeriYuklendi": "Restored ✓",
    "muhKaliciSor": "Delete PERMANENTLY? This can't be undone.",
    "muhKaliciSilindi": "Permanently deleted",
    "muhExcelIndi": "Excel downloaded 📊",
    "muhPdfHazir": "PDF ready 📄",
    "muhMenu": "Menu",
    "sil": "Delete",
    "muhMusteri": "Customer",
    "muhUrun": "Product",
    "muhIslemK": "Transaction",
    "muhKasaK": "Cash",
    "muhBelgeler": "Documents",
    "muhMusteriler": "Customers",
    "muhStok": "Stock",
    "muhAlisSatis": "Buy-Sell",
    "muhKasa": "Cash",
    "muhCop": "Trash",
    "muhBaslik": "Accounting",
    "kapat": "Close",
    "muhYukleniyor": "Loading…",
    "muhYeniMusteri": "New customer / supplier",
    "muhEklendi": "Added ✓",
    "muhHicMusteri": "No customers yet. Add one above.",
    "muhTedarikci": "Supplier",
    "muhToplamBorc": "Total Debt",
    "muhToplamTahsilat": "Collected",
    "muhKalan": "Remaining",
    "muhKayitEklendi": "Added ✓",
    "muhKayitYok": "No records. Add debt or payment.",
    "muhBorc": "Debt",
    "muhTahsilat": "Collection",
    "muhTarih": "Date",
    "muhAciklama": "Description",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Share",
    "muhYeniUrun": "New product",
    "muhHicUrun": "No products yet. Add one above.",
    "muhAlisF": "Buy price",
    "muhSatisF": "Sell price",
    "muhKalanStok": "Remaining Stock",
    "muhHareketYok": "No activity. Add in or out.",
    "muhGiris": "In",
    "muhCikis": "Out",
    "muhYeniIslem": "New buy / sell",
    "muhIslemYok": "No buy-sell yet.",
    "muhSatis": "Sell",
    "muhAlis": "Buy",
    "muhGelir": "Income",
    "muhGider": "Expense",
    "muhKasaBakiye": "Cash",
    "muhYeniKasa": "Add income / expense",
    "muhKasaYok": "No cash activity yet.",
    "muhBanka": "Bank",
    "muhNakit": "Cash",
    "muhCopAlt": "Deleted items are kept here for ~30 days. You can restore them or delete them permanently right away. They disappear on their own when time's up.",
    "muhCopBos": "Trash is empty.",
    "muhGun": "days",
    "muhGeriYukle": "Restore",
    "muhHazirlaniyor": "Preparing…",
    "muhAd": "Name",
    "muhTel": "Phone",
    "istege": "optional",
    "muhNot": "Note",
    "muhKaydet": "Save",
    "muhVazgec": "Cancel",
    "muhTutar": "Amount",
    "muhKayitEkle": "Add",
    "muhUrunAd": "Product name",
    "muhBirim": "Unit (piece, kg, m…)",
    "muhMiktar": "Quantity",
    "muhCariSec": "Select customer/supplier (optional)",
    "muhUrunSec": "Select product (optional)",
    "belTablo": "Excel table",
    "belFatura": "Invoice",
    "belMeslek": "Profession page",
    "belYazi": "Word document",
    "belKaydedildi": "Saved ✓",
    "belBugun": "Today",
    "belBuAy": "This Month",
    "belBuYil": "This Year",
    "belEski": "Older",
    "belAlt2": "Create your own Excel/Word/Invoice, turn photos→PDF, pick a ready page for your profession or make your own profession page and share it. Everything is archived and stays until you delete it.",
    "belFotoPdf": "Photo → PDF",
    "belSablon": "Ready template",
    "belMeslekSayfam": "My profession page",
    "belAraPh": "Search your documents",
    "belAraBos": "No document matches your search.",
    "belYok": "No documents yet. Create one above.",
    "belAdsiz": "Untitled document",
    "belEnAz2": "Select at least 2 cells",
    "belHesaplandi": "Calculated ✓ result written to cell",
    "belOnceIslem": "First pick an operation: ＋ － × ÷",
    "belTopla2": "Add",
    "belCikar": "Subtract",
    "belCarp": "Multiply",
    "belBol": "Divide",
    "belGeri": "Documents",
    "belTabloAd": "Table name",
    "belYaziMod": "Enter text / number",
    "belHesapMod": "Calculate with button",
    "belSatir": "Row",
    "belSutun": "Column",
    "belToplam": "Total",
    "belGenislik": "Width",
    "belSonucDokun": "Tap the EMPTY cell for the result",
    "belHucreleriSec": "Tap the number cells to calculate (they get selected)",
    "belIslemSec": "First pick an operation: Add / Subtract / Multiply / Divide",
    "belSonucDokun2": "Now tap the empty cell for the result",
    "belSonucYaz": "Write result",
    "belTemizle": "Clear",
    "belYaziIpucu": "✍️ Write text or numbers in the cells. To do math, switch to 🔢 Calculate with button above. (You can also type a formula by hand: =A1+B1) Tap the letter on top → sort.",
    "belKaydet": "Save",
    "belExcelIndi": "Excel downloaded 📊",
    "belOlmadi": "Didn't work",
    "belPdfHazir": "PDF ready 📄",
    "belYaziAd": "Document name",
    "belBaslik": "Title",
    "belListe": "List",
    "belWordIndi": "Word downloaded 📘",
    "belFotoYok": "Add a photo first",
    "belFotoBaslik": "Title (optional)",
    "belFotoEkle": "Add photo",
    "belFotoAlt": "Add photos (can be several). Order them, make one PDF, download/share.",
    "belPdfYapPaylas": "Make PDF — download / share",
    "belUrun": "Product/Service",
    "belMiktar": "Quantity",
    "belFiyat": "Unit Price",
    "belTutar": "Amount",
    "belAraToplam": "Subtotal",
    "belGenelToplam": "GRAND TOTAL",
    "belFaturaAd": "Invoice name",
    "belSatici": "Seller (your company)",
    "belAlici": "Buyer (customer)",
    "belFaturaNo": "Invoice No",
    "belSatirEkle": "Add row",
    "belSablonSec": "Pick a ready template for your profession",
    "belSablonAlt": "Pick your profession, a ready page opens; fill it in your way, then download Excel/Word/PDF.",
    "belPaylasildi": "Shared ✓",
    "belMeslekAd": "Page name",
    "belMeslekAlt": "Make your own intro page for your profession: company name, what you do, services, phone, address, photo. Then download PDF/photo, share or publish on GLOXORG.",
    "belFirma": "Company / Business name",
    "belMeslekTur": "Profession (e.g. Hairdresser, Tailor, Restaurant)",
    "belSlogan": "Slogan (short intro)",
    "belMeslekAciklama": "Describe yourself / your work",
    "belHizmetler": "Services (one per line)",
    "belTelefon": "Phone",
    "belAdres": "Address / Location",
    "belFotoDegis": "Change photo",
    "belFotoEkleBtn": "Add photo / logo",
    "belFirmaOrnek": "Company Name",
    "belPaylas": "Share",
    "belGloxorda": "Share on GLOXORG",
    "sanalAyna": "Virtual Mirror",
    "sanalAynaKisa": "Mirror"
  },
  "de": {
    "muhOlmadi": "Hat nicht geklappt, nochmal versuchen?",
    "muhCopeGitti": "In den Papierkorb verschoben 🗑️",
    "muhGeriYuklendi": "Wiederhergestellt ✓",
    "muhKaliciSor": "ENDGÜLTIG löschen? Das kann nicht rückgängig gemacht werden.",
    "muhKaliciSilindi": "Endgültig gelöscht",
    "muhExcelIndi": "Excel heruntergeladen 📊",
    "muhPdfHazir": "PDF fertig 📄",
    "muhMenu": "Menü",
    "sil": "Löschen",
    "muhMusteri": "Kunde",
    "muhUrun": "Produkt",
    "muhIslemK": "Vorgang",
    "muhKasaK": "Kasse",
    "muhBelgeler": "Dokumente",
    "muhMusteriler": "Kunden",
    "muhStok": "Lager",
    "muhAlisSatis": "Ein-/Verkauf",
    "muhKasa": "Kasse",
    "muhCop": "Papierkorb",
    "muhBaslik": "Buchhaltung",
    "kapat": "Schließen",
    "muhYukleniyor": "Wird geladen…",
    "muhYeniMusteri": "Neuer Kunde / Lieferant",
    "muhEklendi": "Hinzugefügt ✓",
    "muhHicMusteri": "Noch keine Kunden. Oben hinzufügen.",
    "muhTedarikci": "Lieferant",
    "muhToplamBorc": "Gesamtschuld",
    "muhToplamTahsilat": "Eingänge",
    "muhKalan": "Rest",
    "muhKayitEklendi": "Hinzugefügt ✓",
    "muhKayitYok": "Keine Einträge. Schuld oder Zahlung hinzufügen.",
    "muhBorc": "Schuld",
    "muhTahsilat": "Eingang",
    "muhTarih": "Datum",
    "muhAciklama": "Beschreibung",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Teilen",
    "muhYeniUrun": "Neues Produkt",
    "muhHicUrun": "Noch keine Produkte. Oben hinzufügen.",
    "muhAlisF": "Einkaufspreis",
    "muhSatisF": "Verkaufspreis",
    "muhKalanStok": "Restbestand",
    "muhHareketYok": "Keine Bewegung. Zugang oder Abgang hinzufügen.",
    "muhGiris": "Zugang",
    "muhCikis": "Abgang",
    "muhYeniIslem": "Neuer Ein-/Verkauf",
    "muhIslemYok": "Noch kein Ein-/Verkauf.",
    "muhSatis": "Verkauf",
    "muhAlis": "Einkauf",
    "muhGelir": "Einnahme",
    "muhGider": "Ausgabe",
    "muhKasaBakiye": "Kasse",
    "muhYeniKasa": "Einnahme / Ausgabe hinzufügen",
    "muhKasaYok": "Noch keine Kassenbewegung.",
    "muhBanka": "Bank",
    "muhNakit": "Bar",
    "muhCopAlt": "Gelöschtes bleibt hier ~30 Tage. Du kannst es wiederherstellen oder sofort endgültig löschen. Nach Ablauf wird es von selbst gelöscht.",
    "muhCopBos": "Papierkorb ist leer.",
    "muhGun": "Tage",
    "muhGeriYukle": "Zurück",
    "muhHazirlaniyor": "Wird vorbereitet…",
    "muhAd": "Name",
    "muhTel": "Telefon",
    "istege": "optional",
    "muhNot": "Notiz",
    "muhKaydet": "Speichern",
    "muhVazgec": "Abbrechen",
    "muhTutar": "Betrag",
    "muhKayitEkle": "Hinzufügen",
    "muhUrunAd": "Produktname",
    "muhBirim": "Einheit (Stück, kg, m…)",
    "muhMiktar": "Menge",
    "muhCariSec": "Kunde/Lieferant wählen (optional)",
    "muhUrunSec": "Produkt wählen (optional)",
    "belTablo": "Excel-Tabelle",
    "belFatura": "Rechnung",
    "belMeslek": "Berufsseite",
    "belYazi": "Word-Dokument",
    "belKaydedildi": "Gespeichert ✓",
    "belBugun": "Heute",
    "belBuAy": "Diesen Monat",
    "belBuYil": "Dieses Jahr",
    "belEski": "Älter",
    "belAlt2": "Erstelle dein eigenes Excel/Word/Rechnung, mach aus Fotos→PDF, wähle eine fertige Seite für deinen Beruf oder erstelle deine eigene Berufsseite und teile sie. Alles wird archiviert und bleibt, bis du es löschst.",
    "belFotoPdf": "Foto → PDF",
    "belSablon": "Fertige Vorlage",
    "belMeslekSayfam": "Meine Berufsseite",
    "belAraPh": "In deinen Dokumenten suchen",
    "belAraBos": "Kein Dokument passt zu deiner Suche.",
    "belYok": "Noch keine Dokumente. Oben erstellen.",
    "belAdsiz": "Unbenanntes Dokument",
    "belEnAz2": "Mindestens 2 Zellen wählen",
    "belHesaplandi": "Berechnet ✓ Ergebnis in die Zelle geschrieben",
    "belOnceIslem": "Zuerst eine Rechenart wählen: ＋ － × ÷",
    "belTopla2": "Addieren",
    "belCikar": "Subtrahieren",
    "belCarp": "Multiplizieren",
    "belBol": "Dividieren",
    "belGeri": "Dokumente",
    "belTabloAd": "Tabellenname",
    "belYaziMod": "Text / Zahl eingeben",
    "belHesapMod": "Mit Taste berechnen",
    "belSatir": "Zeile",
    "belSutun": "Spalte",
    "belToplam": "Summe",
    "belGenislik": "Breite",
    "belSonucDokun": "Tippe auf die LEERE Zelle für das Ergebnis",
    "belHucreleriSec": "Tippe auf die Zahlenzellen zum Berechnen (werden ausgewählt)",
    "belIslemSec": "Zuerst eine Rechenart wählen: Addieren / Subtrahieren / Multiplizieren / Dividieren",
    "belSonucDokun2": "Tippe jetzt auf die leere Zelle für das Ergebnis",
    "belSonucYaz": "Ergebnis schreiben",
    "belTemizle": "Leeren",
    "belYaziIpucu": "✍️ Schreibe Text oder Zahlen in die Zellen. Zum Rechnen oben zu 🔢 Mit Taste berechnen wechseln. (Du kannst auch von Hand eine Formel eingeben: =A1+B1) Tippe oben auf den Buchstaben → sortieren.",
    "belKaydet": "Speichern",
    "belExcelIndi": "Excel heruntergeladen 📊",
    "belOlmadi": "Hat nicht geklappt",
    "belPdfHazir": "PDF fertig 📄",
    "belYaziAd": "Dokumentname",
    "belBaslik": "Titel",
    "belListe": "Liste",
    "belWordIndi": "Word heruntergeladen 📘",
    "belFotoYok": "Zuerst ein Foto hinzufügen",
    "belFotoBaslik": "Titel (optional)",
    "belFotoEkle": "Foto hinzufügen",
    "belFotoAlt": "Fotos hinzufügen (auch mehrere). Sortieren, ein PDF erstellen, herunterladen/teilen.",
    "belPdfYapPaylas": "PDF erstellen — herunterladen / teilen",
    "belUrun": "Produkt/Leistung",
    "belMiktar": "Menge",
    "belFiyat": "Einzelpreis",
    "belTutar": "Betrag",
    "belAraToplam": "Zwischensumme",
    "belGenelToplam": "GESAMTSUMME",
    "belFaturaAd": "Rechnungsname",
    "belSatici": "Verkäufer (deine Firma)",
    "belAlici": "Käufer (Kunde)",
    "belFaturaNo": "Rechnungsnr.",
    "belSatirEkle": "Zeile hinzufügen",
    "belSablonSec": "Fertige Vorlage für deinen Beruf wählen",
    "belSablonAlt": "Wähle deinen Beruf, eine fertige Seite öffnet sich; fülle sie nach deinen Wünschen aus, dann Excel/Word/PDF herunterladen.",
    "belPaylasildi": "Geteilt ✓",
    "belMeslekAd": "Seitenname",
    "belMeslekAlt": "Erstelle deine eigene Vorstellungsseite für deinen Beruf: Firmenname, was du machst, Leistungen, Telefon, Adresse, Foto. Dann PDF/Foto herunterladen, teilen oder auf GLOXORG veröffentlichen.",
    "belFirma": "Firma / Betriebsname",
    "belMeslekTur": "Beruf (z. B. Friseur, Schneider, Restaurant)",
    "belSlogan": "Slogan (kurze Vorstellung)",
    "belMeslekAciklama": "Beschreibe dich / deine Arbeit",
    "belHizmetler": "Leistungen (eine pro Zeile)",
    "belTelefon": "Telefon",
    "belAdres": "Adresse / Standort",
    "belFotoDegis": "Foto ändern",
    "belFotoEkleBtn": "Foto / Logo hinzufügen",
    "belFirmaOrnek": "Firmenname",
    "belPaylas": "Teilen",
    "belGloxorda": "Auf GLOXORG teilen",
    "sanalAyna": "Virtueller Spiegel",
    "sanalAynaKisa": "Spiegel"
  },
  "ru": {
    "muhOlmadi": "Не вышло, попробуешь ещё раз?",
    "muhCopeGitti": "Отправлено в корзину 🗑️",
    "muhGeriYuklendi": "Восстановлено ✓",
    "muhKaliciSor": "Удалить НАВСЕГДА? Это необратимо.",
    "muhKaliciSilindi": "Удалено навсегда",
    "muhExcelIndi": "Excel загружен 📊",
    "muhPdfHazir": "PDF готов 📄",
    "muhMenu": "Меню",
    "sil": "Удалить",
    "muhMusteri": "Клиент",
    "muhUrun": "Товар",
    "muhIslemK": "Операция",
    "muhKasaK": "Касса",
    "muhBelgeler": "Документы",
    "muhMusteriler": "Клиенты",
    "muhStok": "Склад",
    "muhAlisSatis": "Закупка-продажа",
    "muhKasa": "Касса",
    "muhCop": "Корзина",
    "muhBaslik": "Бухгалтерия",
    "kapat": "Закрыть",
    "muhYukleniyor": "Загрузка…",
    "muhYeniMusteri": "Новый клиент / поставщик",
    "muhEklendi": "Добавлено ✓",
    "muhHicMusteri": "Клиентов пока нет. Добавь сверху.",
    "muhTedarikci": "Поставщик",
    "muhToplamBorc": "Общий долг",
    "muhToplamTahsilat": "Оплаты",
    "muhKalan": "Остаток",
    "muhKayitEklendi": "Добавлено ✓",
    "muhKayitYok": "Записей нет. Добавь долг или оплату.",
    "muhBorc": "Долг",
    "muhTahsilat": "Оплата",
    "muhTarih": "Дата",
    "muhAciklama": "Описание",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Поделиться",
    "muhYeniUrun": "Новый товар",
    "muhHicUrun": "Товаров пока нет. Добавь сверху.",
    "muhAlisF": "Цена закупки",
    "muhSatisF": "Цена продажи",
    "muhKalanStok": "Остаток на складе",
    "muhHareketYok": "Движений нет. Добавь приход или расход.",
    "muhGiris": "Приход",
    "muhCikis": "Расход",
    "muhYeniIslem": "Новая закупка / продажа",
    "muhIslemYok": "Закупок-продаж пока нет.",
    "muhSatis": "Продажа",
    "muhAlis": "Закупка",
    "muhGelir": "Доход",
    "muhGider": "Расход",
    "muhKasaBakiye": "Касса",
    "muhYeniKasa": "Добавить доход / расход",
    "muhKasaYok": "Движений по кассе пока нет.",
    "muhBanka": "Банк",
    "muhNakit": "Наличные",
    "muhCopAlt": "Удалённое хранится здесь ~30 дней. Можешь восстановить или сразу удалить навсегда. По истечении срока удалится само.",
    "muhCopBos": "Корзина пуста.",
    "muhGun": "дн.",
    "muhGeriYukle": "Вернуть",
    "muhHazirlaniyor": "Подготовка…",
    "muhAd": "Имя",
    "muhTel": "Телефон",
    "istege": "необязательно",
    "muhNot": "Заметка",
    "muhKaydet": "Сохранить",
    "muhVazgec": "Отмена",
    "muhTutar": "Сумма",
    "muhKayitEkle": "Добавить",
    "muhUrunAd": "Название товара",
    "muhBirim": "Единица (шт., кг, м…)",
    "muhMiktar": "Количество",
    "muhCariSec": "Выбери клиента/поставщика (необязательно)",
    "muhUrunSec": "Выбери товар (необязательно)",
    "belTablo": "Таблица Excel",
    "belFatura": "Счёт",
    "belMeslek": "Страница профессии",
    "belYazi": "Документ Word",
    "belKaydedildi": "Сохранено ✓",
    "belBugun": "Сегодня",
    "belBuAy": "Этот месяц",
    "belBuYil": "Этот год",
    "belEski": "Более старые",
    "belAlt2": "Создай свой документ Excel/Word/Счёт, преврати фото→PDF, выбери готовую страницу по профессии или сделай свою страницу профессии и поделись. Всё архивируется, без твоего удаления не пропадёт.",
    "belFotoPdf": "Фото → PDF",
    "belSablon": "Готовый шаблон",
    "belMeslekSayfam": "Моя страница профессии",
    "belAraPh": "Поиск в документах",
    "belAraBos": "Документов по запросу нет.",
    "belYok": "Документов пока нет. Создай сверху.",
    "belAdsiz": "Документ без названия",
    "belEnAz2": "Выбери минимум 2 ячейки",
    "belHesaplandi": "Посчитано ✓ результат записан в ячейку",
    "belOnceIslem": "Сначала выбери действие: ＋ － × ÷",
    "belTopla2": "Сложить",
    "belCikar": "Вычесть",
    "belCarp": "Умножить",
    "belBol": "Разделить",
    "belGeri": "Документы",
    "belTabloAd": "Название таблицы",
    "belYaziMod": "Ввод текста / чисел",
    "belHesapMod": "Считать кнопкой",
    "belSatir": "Строка",
    "belSutun": "Столбец",
    "belToplam": "Итого",
    "belGenislik": "Ширина",
    "belSonucDokun": "Коснись ПУСТОЙ ячейки, где появится результат",
    "belHucreleriSec": "Коснись ячеек с числами для расчёта (выделятся)",
    "belIslemSec": "Сначала выбери действие: Сложить / Вычесть / Умножить / Разделить",
    "belSonucDokun2": "Теперь коснись пустой ячейки, где появится результат",
    "belSonucYaz": "Записать результат",
    "belTemizle": "Очистить",
    "belYaziIpucu": "✍️ Пиши текст или числа в ячейки. Для расчёта перейди сверху на 🔢 Считать кнопкой. (При желании можешь ввести формулу вручную: =A1+B1) Коснись буквы сверху → сортировка.",
    "belKaydet": "Сохранить",
    "belExcelIndi": "Excel загружен 📊",
    "belOlmadi": "Не вышло",
    "belPdfHazir": "PDF готов 📄",
    "belYaziAd": "Название документа",
    "belBaslik": "Заголовок",
    "belListe": "Список",
    "belWordIndi": "Word загружен 📘",
    "belFotoYok": "Сначала добавь фото",
    "belFotoBaslik": "Заголовок (необязательно)",
    "belFotoEkle": "Добавить фото",
    "belFotoAlt": "Добавь фото (можно несколько). Расставь по порядку, сделай один PDF, скачай/поделись.",
    "belPdfYapPaylas": "Сделать PDF — скачать / поделиться",
    "belUrun": "Товар/Услуга",
    "belMiktar": "Количество",
    "belFiyat": "Цена за единицу",
    "belTutar": "Сумма",
    "belAraToplam": "Промежуточный итог",
    "belGenelToplam": "ОБЩИЙ ИТОГ",
    "belFaturaAd": "Название счёта",
    "belSatici": "Продавец (твоя фирма)",
    "belAlici": "Покупатель (клиент)",
    "belFaturaNo": "Номер счёта",
    "belSatirEkle": "Добавить строку",
    "belSablonSec": "Выбери готовый шаблон по профессии",
    "belSablonAlt": "Выбери профессию, откроется готовая страница; заполни под себя, затем скачай Excel/Word/PDF.",
    "belPaylasildi": "Опубликовано ✓",
    "belMeslekAd": "Название страницы",
    "belMeslekAlt": "Сделай свою рекламную страницу по профессии: название фирмы, чем занимаешься, услуги, телефон, адрес, фото. Затем скачай PDF/фото, поделись или опубликуй в GLOXORG.",
    "belFirma": "Название фирмы / бизнеса",
    "belMeslekTur": "Профессия (напр. Парикмахер, Портной, Ресторан)",
    "belSlogan": "Слоган (краткое описание)",
    "belMeslekAciklama": "Расскажи о себе / своём деле",
    "belHizmetler": "Услуги (по одной в строке)",
    "belTelefon": "Телефон",
    "belAdres": "Адрес / Местоположение",
    "belFotoDegis": "Заменить фото",
    "belFotoEkleBtn": "Добавить фото / логотип",
    "belFirmaOrnek": "Название фирмы",
    "belPaylas": "Поделиться",
    "belGloxorda": "Опубликовать в GLOXORG",
    "sanalAyna": "Виртуальное зеркало",
    "sanalAynaKisa": "Зеркало"
  },
  "uk": {
    "muhOlmadi": "Не вийшло, спробуєш ще раз?",
    "muhCopeGitti": "Надіслано до кошика 🗑️",
    "muhGeriYuklendi": "Відновлено ✓",
    "muhKaliciSor": "Видалити НАЗАВЖДИ? Це не можна скасувати.",
    "muhKaliciSilindi": "Видалено назавжди",
    "muhExcelIndi": "Excel завантажено 📊",
    "muhPdfHazir": "PDF готовий 📄",
    "muhMenu": "Меню",
    "sil": "Видалити",
    "muhMusteri": "Клієнт",
    "muhUrun": "Товар",
    "muhIslemK": "Операція",
    "muhKasaK": "Каса",
    "muhBelgeler": "Документи",
    "muhMusteriler": "Клієнти",
    "muhStok": "Склад",
    "muhAlisSatis": "Закупівля-продаж",
    "muhKasa": "Каса",
    "muhCop": "Кошик",
    "muhBaslik": "Бухгалтерія",
    "kapat": "Закрити",
    "muhYukleniyor": "Завантаження…",
    "muhYeniMusteri": "Новий клієнт / постачальник",
    "muhEklendi": "Додано ✓",
    "muhHicMusteri": "Клієнтів поки немає. Додай згори.",
    "muhTedarikci": "Постачальник",
    "muhToplamBorc": "Загальний борг",
    "muhToplamTahsilat": "Оплати",
    "muhKalan": "Залишок",
    "muhKayitEklendi": "Додано ✓",
    "muhKayitYok": "Записів немає. Додай борг або оплату.",
    "muhBorc": "Борг",
    "muhTahsilat": "Оплата",
    "muhTarih": "Дата",
    "muhAciklama": "Опис",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Поділитися",
    "muhYeniUrun": "Новий товар",
    "muhHicUrun": "Товарів поки немає. Додай згори.",
    "muhAlisF": "Ціна закупівлі",
    "muhSatisF": "Ціна продажу",
    "muhKalanStok": "Залишок на складі",
    "muhHareketYok": "Рухів немає. Додай прихід або видаток.",
    "muhGiris": "Прихід",
    "muhCikis": "Видаток",
    "muhYeniIslem": "Нова закупівля / продаж",
    "muhIslemYok": "Закупівель-продажів поки немає.",
    "muhSatis": "Продаж",
    "muhAlis": "Закупівля",
    "muhGelir": "Дохід",
    "muhGider": "Витрата",
    "muhKasaBakiye": "Каса",
    "muhYeniKasa": "Додати дохід / витрату",
    "muhKasaYok": "Рухів по касі поки немає.",
    "muhBanka": "Банк",
    "muhNakit": "Готівка",
    "muhCopAlt": "Видалене зберігається тут ~30 днів. Можеш відновити або одразу видалити назавжди. Після завершення терміну видалиться саме.",
    "muhCopBos": "Кошик порожній.",
    "muhGun": "дн.",
    "muhGeriYukle": "Повернути",
    "muhHazirlaniyor": "Підготовка…",
    "muhAd": "Ім'я",
    "muhTel": "Телефон",
    "istege": "за бажанням",
    "muhNot": "Нотатка",
    "muhKaydet": "Зберегти",
    "muhVazgec": "Скасувати",
    "muhTutar": "Сума",
    "muhKayitEkle": "Додати",
    "muhUrunAd": "Назва товару",
    "muhBirim": "Одиниця (шт., кг, м…)",
    "muhMiktar": "Кількість",
    "muhCariSec": "Обери клієнта/постачальника (за бажанням)",
    "muhUrunSec": "Обери товар (за бажанням)",
    "belTablo": "Таблиця Excel",
    "belFatura": "Рахунок",
    "belMeslek": "Сторінка професії",
    "belYazi": "Документ Word",
    "belKaydedildi": "Збережено ✓",
    "belBugun": "Сьогодні",
    "belBuAy": "Цей місяць",
    "belBuYil": "Цей рік",
    "belEski": "Давніші",
    "belAlt2": "Створи свій документ Excel/Word/Рахунок, перетвори фото→PDF, обери готову сторінку за професією або зроби власну сторінку професії й поділись. Усе архівується, без твого видалення не зникне.",
    "belFotoPdf": "Фото → PDF",
    "belSablon": "Готовий шаблон",
    "belMeslekSayfam": "Моя сторінка професії",
    "belAraPh": "Пошук у документах",
    "belAraBos": "Документів за запитом немає.",
    "belYok": "Документів поки немає. Створи згори.",
    "belAdsiz": "Документ без назви",
    "belEnAz2": "Обери щонайменше 2 клітинки",
    "belHesaplandi": "Пораховано ✓ результат записано в клітинку",
    "belOnceIslem": "Спершу обери дію: ＋ － × ÷",
    "belTopla2": "Додати",
    "belCikar": "Відняти",
    "belCarp": "Помножити",
    "belBol": "Поділити",
    "belGeri": "Документи",
    "belTabloAd": "Назва таблиці",
    "belYaziMod": "Введення тексту / чисел",
    "belHesapMod": "Рахувати кнопкою",
    "belSatir": "Рядок",
    "belSutun": "Стовпець",
    "belToplam": "Разом",
    "belGenislik": "Ширина",
    "belSonucDokun": "Торкнись ПОРОЖНЬОЇ клітинки, де з'явиться результат",
    "belHucreleriSec": "Торкнись клітинок із числами для розрахунку (виділяться)",
    "belIslemSec": "Спершу обери дію: Додати / Відняти / Помножити / Поділити",
    "belSonucDokun2": "Тепер торкнись порожньої клітинки, де з'явиться результат",
    "belSonucYaz": "Записати результат",
    "belTemizle": "Очистити",
    "belYaziIpucu": "✍️ Пиши текст або числа в клітинки. Для розрахунку перейди згори на 🔢 Рахувати кнопкою. (За бажанням можеш ввести формулу вручну: =A1+B1) Торкнись літери згори → сортування.",
    "belKaydet": "Зберегти",
    "belExcelIndi": "Excel завантажено 📊",
    "belOlmadi": "Не вийшло",
    "belPdfHazir": "PDF готовий 📄",
    "belYaziAd": "Назва документа",
    "belBaslik": "Заголовок",
    "belListe": "Список",
    "belWordIndi": "Word завантажено 📘",
    "belFotoYok": "Спершу додай фото",
    "belFotoBaslik": "Заголовок (за бажанням)",
    "belFotoEkle": "Додати фото",
    "belFotoAlt": "Додай фото (можна кілька). Розстав по порядку, зроби один PDF, завантаж/поділись.",
    "belPdfYapPaylas": "Зробити PDF — завантажити / поділитися",
    "belUrun": "Товар/Послуга",
    "belMiktar": "Кількість",
    "belFiyat": "Ціна за одиницю",
    "belTutar": "Сума",
    "belAraToplam": "Проміжний підсумок",
    "belGenelToplam": "ЗАГАЛЬНИЙ ПІДСУМОК",
    "belFaturaAd": "Назва рахунку",
    "belSatici": "Продавець (твоя фірма)",
    "belAlici": "Покупець (клієнт)",
    "belFaturaNo": "Номер рахунку",
    "belSatirEkle": "Додати рядок",
    "belSablonSec": "Обери готовий шаблон за професією",
    "belSablonAlt": "Обери професію, відкриється готова сторінка; заповни під себе, потім завантаж Excel/Word/PDF.",
    "belPaylasildi": "Опубліковано ✓",
    "belMeslekAd": "Назва сторінки",
    "belMeslekAlt": "Зроби свою рекламну сторінку за професією: назва фірми, чим займаєшся, послуги, телефон, адреса, фото. Потім завантаж PDF/фото, поділись або опублікуй у GLOXORG.",
    "belFirma": "Назва фірми / бізнесу",
    "belMeslekTur": "Професія (напр. Перукар, Кравець, Ресторан)",
    "belSlogan": "Слоган (короткий опис)",
    "belMeslekAciklama": "Розкажи про себе / свою справу",
    "belHizmetler": "Послуги (по одній у рядку)",
    "belTelefon": "Телефон",
    "belAdres": "Адреса / Місцезнаходження",
    "belFotoDegis": "Замінити фото",
    "belFotoEkleBtn": "Додати фото / логотип",
    "belFirmaOrnek": "Назва фірми",
    "belPaylas": "Поділитися",
    "belGloxorda": "Опублікувати в GLOXORG",
    "sanalAyna": "Віртуальне дзеркало",
    "sanalAynaKisa": "Дзеркало"
  },
  "es": {
    "muhOlmadi": "No funcionó, ¿lo intentas de nuevo?",
    "muhCopeGitti": "Enviado a la papelera 🗑️",
    "muhGeriYuklendi": "Restaurado ✓",
    "muhKaliciSor": "¿Borrar de forma PERMANENTE? No se puede deshacer.",
    "muhKaliciSilindi": "Borrado permanentemente",
    "muhExcelIndi": "Excel descargado 📊",
    "muhPdfHazir": "PDF listo 📄",
    "muhMenu": "Menú",
    "sil": "Borrar",
    "muhMusteri": "Cliente",
    "muhUrun": "Producto",
    "muhIslemK": "Operación",
    "muhKasaK": "Caja",
    "muhBelgeler": "Documentos",
    "muhMusteriler": "Clientes",
    "muhStok": "Stock",
    "muhAlisSatis": "Compra-Venta",
    "muhKasa": "Caja",
    "muhCop": "Papelera",
    "muhBaslik": "Contabilidad",
    "kapat": "Cerrar",
    "muhYukleniyor": "Cargando…",
    "muhYeniMusteri": "Nuevo cliente / proveedor",
    "muhEklendi": "Añadido ✓",
    "muhHicMusteri": "Aún no hay clientes. Añade arriba.",
    "muhTedarikci": "Proveedor",
    "muhToplamBorc": "Deuda Total",
    "muhToplamTahsilat": "Cobros",
    "muhKalan": "Restante",
    "muhKayitEklendi": "Añadido ✓",
    "muhKayitYok": "Sin registros. Añade deuda o cobro.",
    "muhBorc": "Deuda",
    "muhTahsilat": "Cobro",
    "muhTarih": "Fecha",
    "muhAciklama": "Descripción",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Compartir",
    "muhYeniUrun": "Nuevo producto",
    "muhHicUrun": "Aún no hay productos. Añade arriba.",
    "muhAlisF": "Precio de compra",
    "muhSatisF": "Precio de venta",
    "muhKalanStok": "Stock Restante",
    "muhHareketYok": "Sin movimientos. Añade entrada o salida.",
    "muhGiris": "Entrada",
    "muhCikis": "Salida",
    "muhYeniIslem": "Nueva compra / venta",
    "muhIslemYok": "Aún no hay compra-venta.",
    "muhSatis": "Venta",
    "muhAlis": "Compra",
    "muhGelir": "Ingreso",
    "muhGider": "Gasto",
    "muhKasaBakiye": "Caja",
    "muhYeniKasa": "Añadir ingreso / gasto",
    "muhKasaYok": "Aún no hay movimientos de caja.",
    "muhBanka": "Banco",
    "muhNakit": "Efectivo",
    "muhCopAlt": "Lo que borres se guarda aquí ~30 días. Puedes restaurarlo o borrarlo permanentemente ya. Al vencer el plazo se borra solo.",
    "muhCopBos": "La papelera está vacía.",
    "muhGun": "días",
    "muhGeriYukle": "Restaurar",
    "muhHazirlaniyor": "Preparando…",
    "muhAd": "Nombre",
    "muhTel": "Teléfono",
    "istege": "opcional",
    "muhNot": "Nota",
    "muhKaydet": "Guardar",
    "muhVazgec": "Cancelar",
    "muhTutar": "Importe",
    "muhKayitEkle": "Añadir",
    "muhUrunAd": "Nombre del producto",
    "muhBirim": "Unidad (uds, kg, m…)",
    "muhMiktar": "Cantidad",
    "muhCariSec": "Elegir cliente/proveedor (opcional)",
    "muhUrunSec": "Elegir producto (opcional)",
    "belTablo": "Tabla de Excel",
    "belFatura": "Factura",
    "belMeslek": "Página profesional",
    "belYazi": "Documento de Word",
    "belKaydedildi": "Guardado ✓",
    "belBugun": "Hoy",
    "belBuAy": "Este Mes",
    "belBuYil": "Este Año",
    "belEski": "Más Antiguos",
    "belAlt2": "Crea tu propio documento Excel/Word/Factura, convierte foto→PDF, elige una página lista según tu oficio o crea tu propia página profesional y compártela. Todo se archiva, no se borra sin que tú lo hagas.",
    "belFotoPdf": "Foto → PDF",
    "belSablon": "Plantilla lista",
    "belMeslekSayfam": "Mi página profesional",
    "belAraPh": "Buscar en tus documentos",
    "belAraBos": "No hay documentos para tu búsqueda.",
    "belYok": "Aún no hay documentos. Crea arriba.",
    "belAdsiz": "Documento sin nombre",
    "belEnAz2": "Elige al menos 2 celdas",
    "belHesaplandi": "Calculado ✓ resultado escrito en la celda",
    "belOnceIslem": "Elige primero la operación: ＋ － × ÷",
    "belTopla2": "Sumar",
    "belCikar": "Restar",
    "belCarp": "Multiplicar",
    "belBol": "Dividir",
    "belGeri": "Documentos",
    "belTabloAd": "Nombre de la tabla",
    "belYaziMod": "Escribir texto / número",
    "belHesapMod": "Calcular con botón",
    "belSatir": "Fila",
    "belSutun": "Columna",
    "belToplam": "Total",
    "belGenislik": "Ancho",
    "belSonucDokun": "Toca la celda VACÍA donde saldrá el resultado",
    "belHucreleriSec": "Toca las celdas de números a calcular (se seleccionan)",
    "belIslemSec": "Elige primero la operación: Sumar / Restar / Multiplicar / Dividir",
    "belSonucDokun2": "Ahora toca la celda vacía donde saldrá el resultado",
    "belSonucYaz": "Escribir resultado",
    "belTemizle": "Limpiar",
    "belYaziIpucu": "✍️ Escribe texto o número en las celdas. Para calcular, pasa arriba a 🔢 Calcular con botón. (Si quieres, también puedes escribir la fórmula a mano: =A1+B1) Toca la letra de arriba → ordenar.",
    "belKaydet": "Guardar",
    "belExcelIndi": "Excel descargado 📊",
    "belOlmadi": "No funcionó",
    "belPdfHazir": "PDF listo 📄",
    "belYaziAd": "Nombre del documento",
    "belBaslik": "Título",
    "belListe": "Lista",
    "belWordIndi": "Word descargado 📘",
    "belFotoYok": "Añade primero una foto",
    "belFotoBaslik": "Título (opcional)",
    "belFotoEkle": "Añadir foto",
    "belFotoAlt": "Añade fotos (pueden ser varias). Ordénalas y haz un solo PDF, descárgalo/compártelo.",
    "belPdfYapPaylas": "Hacer PDF — descargar / compartir",
    "belUrun": "Producto/Servicio",
    "belMiktar": "Cantidad",
    "belFiyat": "Precio Unitario",
    "belTutar": "Importe",
    "belAraToplam": "Subtotal",
    "belGenelToplam": "TOTAL GENERAL",
    "belFaturaAd": "Nombre de la factura",
    "belSatici": "Vendedor (tu empresa)",
    "belAlici": "Comprador (cliente)",
    "belFaturaNo": "N.º de Factura",
    "belSatirEkle": "Añadir fila",
    "belSablonSec": "Elige una plantilla lista según tu oficio",
    "belSablonAlt": "Elige tu oficio para abrir una página lista; rellénala a tu medida y luego descarga Excel/Word/PDF.",
    "belPaylasildi": "Compartido ✓",
    "belMeslekAd": "Nombre de la página",
    "belMeslekAlt": "Crea tu propia página de presentación según tu oficio: nombre de la empresa, a qué te dedicas, servicios, teléfono, dirección, foto. Luego descarga PDF/foto, comparte o publica en GLOXORG.",
    "belFirma": "Nombre de empresa / negocio",
    "belMeslekTur": "Oficio (ej. Peluquero, Sastre, Restaurante)",
    "belSlogan": "Eslogan (presentación breve)",
    "belMeslekAciklama": "Describe tu trabajo / a ti mismo",
    "belHizmetler": "Servicios (uno por línea)",
    "belTelefon": "Teléfono",
    "belAdres": "Dirección / Ubicación",
    "belFotoDegis": "Cambiar la foto",
    "belFotoEkleBtn": "Añadir foto / logo",
    "belFirmaOrnek": "Nombre de Empresa",
    "belPaylas": "Compartir",
    "belGloxorda": "Compartir en GLOXORG",
    "sanalAyna": "Espejo Virtual",
    "sanalAynaKisa": "Espejo"
  },
  "fr": {
    "muhOlmadi": "Ça n'a pas marché, tu réessaies ?",
    "muhCopeGitti": "Envoyé à la corbeille 🗑️",
    "muhGeriYuklendi": "Restauré ✓",
    "muhKaliciSor": "Supprimer DÉFINITIVEMENT ? C'est irréversible.",
    "muhKaliciSilindi": "Supprimé définitivement",
    "muhExcelIndi": "Excel téléchargé 📊",
    "muhPdfHazir": "PDF prêt 📄",
    "muhMenu": "Menu",
    "sil": "Supprimer",
    "muhMusteri": "Client",
    "muhUrun": "Produit",
    "muhIslemK": "Opération",
    "muhKasaK": "Caisse",
    "muhBelgeler": "Documents",
    "muhMusteriler": "Clients",
    "muhStok": "Stock",
    "muhAlisSatis": "Achat-Vente",
    "muhKasa": "Caisse",
    "muhCop": "Corbeille",
    "muhBaslik": "Comptabilité",
    "kapat": "Fermer",
    "muhYukleniyor": "Chargement…",
    "muhYeniMusteri": "Nouveau client / fournisseur",
    "muhEklendi": "Ajouté ✓",
    "muhHicMusteri": "Pas encore de client. Ajoute ci-dessus.",
    "muhTedarikci": "Fournisseur",
    "muhToplamBorc": "Dette Totale",
    "muhToplamTahsilat": "Encaissements",
    "muhKalan": "Reste",
    "muhKayitEklendi": "Ajouté ✓",
    "muhKayitYok": "Aucun enregistrement. Ajoute une dette ou un encaissement.",
    "muhBorc": "Dette",
    "muhTahsilat": "Encaissement",
    "muhTarih": "Date",
    "muhAciklama": "Description",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Partager",
    "muhYeniUrun": "Nouveau produit",
    "muhHicUrun": "Pas encore de produit. Ajoute ci-dessus.",
    "muhAlisF": "Prix d'achat",
    "muhSatisF": "Prix de vente",
    "muhKalanStok": "Stock Restant",
    "muhHareketYok": "Aucun mouvement. Ajoute une entrée ou une sortie.",
    "muhGiris": "Entrée",
    "muhCikis": "Sortie",
    "muhYeniIslem": "Nouvel achat / vente",
    "muhIslemYok": "Pas encore d'achat-vente.",
    "muhSatis": "Vente",
    "muhAlis": "Achat",
    "muhGelir": "Recette",
    "muhGider": "Dépense",
    "muhKasaBakiye": "Caisse",
    "muhYeniKasa": "Ajouter recette / dépense",
    "muhKasaYok": "Pas encore de mouvement de caisse.",
    "muhBanka": "Banque",
    "muhNakit": "Espèces",
    "muhCopAlt": "Ce que tu supprimes est gardé ici ~30 jours. Tu peux le restaurer ou le supprimer définitivement tout de suite. À l'échéance, il s'efface tout seul.",
    "muhCopBos": "La corbeille est vide.",
    "muhGun": "jours",
    "muhGeriYukle": "Restaurer",
    "muhHazirlaniyor": "Préparation…",
    "muhAd": "Nom",
    "muhTel": "Téléphone",
    "istege": "facultatif",
    "muhNot": "Note",
    "muhKaydet": "Enregistrer",
    "muhVazgec": "Annuler",
    "muhTutar": "Montant",
    "muhKayitEkle": "Ajouter",
    "muhUrunAd": "Nom du produit",
    "muhBirim": "Unité (pce, kg, m…)",
    "muhMiktar": "Quantité",
    "muhCariSec": "Choisir client/fournisseur (facultatif)",
    "muhUrunSec": "Choisir un produit (facultatif)",
    "belTablo": "Tableau Excel",
    "belFatura": "Facture",
    "belMeslek": "Page métier",
    "belYazi": "Document Word",
    "belKaydedildi": "Enregistré ✓",
    "belBugun": "Aujourd'hui",
    "belBuAy": "Ce Mois",
    "belBuYil": "Cette Année",
    "belEski": "Plus Anciens",
    "belAlt2": "Crée ton propre document Excel/Word/Facture, transforme une photo→PDF, choisis une page prête selon ton métier ou crée ta propre page métier et partage-la. Tout est archivé, rien ne disparaît sans que tu le supprimes.",
    "belFotoPdf": "Photo → PDF",
    "belSablon": "Modèle prêt",
    "belMeslekSayfam": "Ma page métier",
    "belAraPh": "Rechercher dans tes documents",
    "belAraBos": "Aucun document ne correspond à ta recherche.",
    "belYok": "Pas encore de document. Crée ci-dessus.",
    "belAdsiz": "Document sans nom",
    "belEnAz2": "Choisis au moins 2 cellules",
    "belHesaplandi": "Calculé ✓ résultat écrit dans la cellule",
    "belOnceIslem": "Choisis d'abord l'opération : ＋ － × ÷",
    "belTopla2": "Additionner",
    "belCikar": "Soustraire",
    "belCarp": "Multiplier",
    "belBol": "Diviser",
    "belGeri": "Documents",
    "belTabloAd": "Nom du tableau",
    "belYaziMod": "Saisir texte / chiffre",
    "belHesapMod": "Calculer avec un bouton",
    "belSatir": "Ligne",
    "belSutun": "Colonne",
    "belToplam": "Total",
    "belGenislik": "Largeur",
    "belSonucDokun": "Touche la cellule VIDE où le résultat apparaîtra",
    "belHucreleriSec": "Touche les cellules de chiffres à calculer (elles se sélectionnent)",
    "belIslemSec": "Choisis d'abord l'opération : Additionner / Soustraire / Multiplier / Diviser",
    "belSonucDokun2": "Touche maintenant la cellule vide où le résultat apparaîtra",
    "belSonucYaz": "Écrire le résultat",
    "belTemizle": "Effacer",
    "belYaziIpucu": "✍️ Écris du texte ou un chiffre dans les cellules. Pour calculer, passe en haut à 🔢 Calculer avec un bouton. (Si tu veux, tu peux aussi écrire la formule à la main : =A1+B1) Touche la lettre en haut → trier.",
    "belKaydet": "Enregistrer",
    "belExcelIndi": "Excel téléchargé 📊",
    "belOlmadi": "Ça n'a pas marché",
    "belPdfHazir": "PDF prêt 📄",
    "belYaziAd": "Nom du document",
    "belBaslik": "Titre",
    "belListe": "Liste",
    "belWordIndi": "Word téléchargé 📘",
    "belFotoYok": "Ajoute d'abord une photo",
    "belFotoBaslik": "Titre (facultatif)",
    "belFotoEkle": "Ajouter une photo",
    "belFotoAlt": "Ajoute des photos (plusieurs possibles). Range-les et fais un seul PDF, télécharge/partage.",
    "belPdfYapPaylas": "Faire un PDF — télécharger / partager",
    "belUrun": "Produit/Service",
    "belMiktar": "Quantité",
    "belFiyat": "Prix Unitaire",
    "belTutar": "Montant",
    "belAraToplam": "Sous-Total",
    "belGenelToplam": "TOTAL GÉNÉRAL",
    "belFaturaAd": "Nom de la facture",
    "belSatici": "Vendeur (ton entreprise)",
    "belAlici": "Acheteur (client)",
    "belFaturaNo": "N° de Facture",
    "belSatirEkle": "Ajouter une ligne",
    "belSablonSec": "Choisis un modèle prêt selon ton métier",
    "belSablonAlt": "Choisis ton métier pour ouvrir une page prête ; remplis-la à ta façon, puis télécharge Excel/Word/PDF.",
    "belPaylasildi": "Partagé ✓",
    "belMeslekAd": "Nom de la page",
    "belMeslekAlt": "Crée ta propre page de présentation selon ton métier : nom de l'entreprise, ce que tu fais, services, téléphone, adresse, photo. Puis télécharge PDF/photo, partage ou publie sur GLOXORG.",
    "belFirma": "Nom de l'entreprise / du commerce",
    "belMeslekTur": "Métier (ex. Coiffeur, Couturier, Restaurant)",
    "belSlogan": "Slogan (courte présentation)",
    "belMeslekAciklama": "Présente ton travail / toi-même",
    "belHizmetler": "Services (un par ligne)",
    "belTelefon": "Téléphone",
    "belAdres": "Adresse / Localisation",
    "belFotoDegis": "Changer la photo",
    "belFotoEkleBtn": "Ajouter photo / logo",
    "belFirmaOrnek": "Nom de l'Entreprise",
    "belPaylas": "Partager",
    "belGloxorda": "Partager sur GLOXORG",
    "sanalAyna": "Miroir Virtuel",
    "sanalAynaKisa": "Miroir"
  },
  "it": {
    "muhOlmadi": "Non è riuscito, riprovi?",
    "muhCopeGitti": "Spostato nel cestino 🗑️",
    "muhGeriYuklendi": "Ripristinato ✓",
    "muhKaliciSor": "Eliminare DEFINITIVAMENTE? Non è reversibile.",
    "muhKaliciSilindi": "Eliminato definitivamente",
    "muhExcelIndi": "Excel scaricato 📊",
    "muhPdfHazir": "PDF pronto 📄",
    "muhMenu": "Menu",
    "sil": "Elimina",
    "muhMusteri": "Cliente",
    "muhUrun": "Prodotto",
    "muhIslemK": "Operazione",
    "muhKasaK": "Cassa",
    "muhBelgeler": "Documenti",
    "muhMusteriler": "Clienti",
    "muhStok": "Magazzino",
    "muhAlisSatis": "Acquisti-Vendite",
    "muhKasa": "Cassa",
    "muhCop": "Cestino",
    "muhBaslik": "Contabilità",
    "kapat": "Chiudi",
    "muhYukleniyor": "Caricamento…",
    "muhYeniMusteri": "Nuovo cliente / fornitore",
    "muhEklendi": "Aggiunto ✓",
    "muhHicMusteri": "Ancora nessun cliente. Aggiungi sopra.",
    "muhTedarikci": "Fornitore",
    "muhToplamBorc": "Debito totale",
    "muhToplamTahsilat": "Incassi",
    "muhKalan": "Rimanente",
    "muhKayitEklendi": "Aggiunto ✓",
    "muhKayitYok": "Nessun record. Aggiungi un debito o un incasso.",
    "muhBorc": "Debito",
    "muhTahsilat": "Incasso",
    "muhTarih": "Data",
    "muhAciklama": "Descrizione",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Condividi",
    "muhYeniUrun": "Nuovo prodotto",
    "muhHicUrun": "Ancora nessun prodotto. Aggiungi sopra.",
    "muhAlisF": "Prezzo di acquisto",
    "muhSatisF": "Prezzo di vendita",
    "muhKalanStok": "Stock rimanente",
    "muhHareketYok": "Nessun movimento. Aggiungi entrata o uscita.",
    "muhGiris": "Entrata",
    "muhCikis": "Uscita",
    "muhYeniIslem": "Nuovo acquisto / vendita",
    "muhIslemYok": "Ancora nessun acquisto-vendita.",
    "muhSatis": "Vendita",
    "muhAlis": "Acquisto",
    "muhGelir": "Entrata",
    "muhGider": "Uscita",
    "muhKasaBakiye": "Cassa",
    "muhYeniKasa": "Aggiungi entrata / uscita",
    "muhKasaYok": "Ancora nessun movimento di cassa.",
    "muhBanka": "Banca",
    "muhNakit": "Contanti",
    "muhCopAlt": "Gli elementi eliminati restano qui ~30 giorni. Puoi ripristinarli o eliminarli subito in modo definitivo. Alla scadenza vengono eliminati da soli.",
    "muhCopBos": "Il cestino è vuoto.",
    "muhGun": "giorni",
    "muhGeriYukle": "Ripristina",
    "muhHazirlaniyor": "In preparazione…",
    "muhAd": "Nome",
    "muhTel": "Telefono",
    "istege": "facoltativo",
    "muhNot": "Nota",
    "muhKaydet": "Salva",
    "muhVazgec": "Annulla",
    "muhTutar": "Importo",
    "muhKayitEkle": "Aggiungi",
    "muhUrunAd": "Nome prodotto",
    "muhBirim": "Unità (pz, kg, m…)",
    "muhMiktar": "Quantità",
    "muhCariSec": "Scegli cliente/fornitore (facoltativo)",
    "muhUrunSec": "Scegli prodotto (facoltativo)",
    "belTablo": "Tabella Excel",
    "belFatura": "Fattura",
    "belMeslek": "Pagina professionale",
    "belYazi": "Documento Word",
    "belKaydedildi": "Salvato ✓",
    "belBugun": "Oggi",
    "belBuAy": "Questo mese",
    "belBuYil": "Quest'anno",
    "belEski": "Più vecchi",
    "belAlt2": "Crea il tuo documento Excel/Word/Fattura, foto→PDF, scegli una pagina pronta per la tua professione o crea la tua pagina professionale e condividila. Tutto viene archiviato, non sparisce finché non lo elimini.",
    "belFotoPdf": "Foto → PDF",
    "belSablon": "Modello pronto",
    "belMeslekSayfam": "La mia pagina professionale",
    "belAraPh": "Cerca nei tuoi documenti",
    "belAraBos": "Nessun documento corrisponde alla ricerca.",
    "belYok": "Ancora nessun documento. Creane uno sopra.",
    "belAdsiz": "Documento senza nome",
    "belEnAz2": "Seleziona almeno 2 celle",
    "belHesaplandi": "Calcolato ✓ risultato scritto nella cella",
    "belOnceIslem": "Prima scegli l'operazione: ＋ － × ÷",
    "belTopla2": "Somma",
    "belCikar": "Sottrai",
    "belCarp": "Moltiplica",
    "belBol": "Dividi",
    "belGeri": "Documenti",
    "belTabloAd": "Nome tabella",
    "belYaziMod": "Inserisci testo / numero",
    "belHesapMod": "Calcola col pulsante",
    "belSatir": "Riga",
    "belSutun": "Colonna",
    "belToplam": "Totale",
    "belGenislik": "Larghezza",
    "belSonucDokun": "Tocca la cella VUOTA dove uscirà il risultato",
    "belHucreleriSec": "Tocca le celle con i numeri da calcolare (si selezionano)",
    "belIslemSec": "Prima scegli l'operazione: Somma / Sottrai / Moltiplica / Dividi",
    "belSonucDokun2": "Ora tocca la cella vuota dove uscirà il risultato",
    "belSonucYaz": "Scrivi il risultato",
    "belTemizle": "Pulisci",
    "belYaziIpucu": "✍️ Scrivi testo o numeri nelle celle. Per calcolare, passa in alto a 🔢 Calcola col pulsante. (Se vuoi puoi scrivere la formula a mano: =A1+B1) Tocca la lettera in alto → ordina.",
    "belKaydet": "Salva",
    "belExcelIndi": "Excel scaricato 📊",
    "belOlmadi": "Non è riuscito",
    "belPdfHazir": "PDF pronto 📄",
    "belYaziAd": "Nome documento",
    "belBaslik": "Titolo",
    "belListe": "Elenco",
    "belWordIndi": "Word scaricato 📘",
    "belFotoYok": "Prima aggiungi una foto",
    "belFotoBaslik": "Titolo (facoltativo)",
    "belFotoEkle": "Aggiungi foto",
    "belFotoAlt": "Aggiungi foto (anche più di una). Ordinale e crea un unico PDF, scarica/condividi.",
    "belPdfYapPaylas": "Crea PDF — scarica / condividi",
    "belUrun": "Prodotto/Servizio",
    "belMiktar": "Quantità",
    "belFiyat": "Prezzo unitario",
    "belTutar": "Importo",
    "belAraToplam": "Subtotale",
    "belGenelToplam": "TOTALE GENERALE",
    "belFaturaAd": "Nome fattura",
    "belSatici": "Venditore (la tua azienda)",
    "belAlici": "Acquirente (cliente)",
    "belFaturaNo": "N. fattura",
    "belSatirEkle": "Aggiungi riga",
    "belSablonSec": "Scegli un modello pronto per la tua professione",
    "belSablonAlt": "Scegli la tua professione, si apre una pagina pronta; compilala a modo tuo, poi scarica Excel/Word/PDF.",
    "belPaylasildi": "Condiviso ✓",
    "belMeslekAd": "Nome pagina",
    "belMeslekAlt": "Crea la tua pagina di presentazione per la tua professione: nome azienda, cosa fai, servizi, telefono, indirizzo, foto. Poi scarica PDF/foto, condividi o pubblica su GLOXORG.",
    "belFirma": "Nome azienda / attività",
    "belMeslekTur": "Professione (es. Parrucchiere, Sarto, Ristorante)",
    "belSlogan": "Slogan (breve presentazione)",
    "belMeslekAciklama": "Racconta te stesso / il tuo lavoro",
    "belHizmetler": "Servizi (uno per riga)",
    "belTelefon": "Telefono",
    "belAdres": "Indirizzo / Posizione",
    "belFotoDegis": "Cambia foto",
    "belFotoEkleBtn": "Aggiungi foto / logo",
    "belFirmaOrnek": "Nome azienda",
    "belPaylas": "Condividi",
    "belGloxorda": "Condividi su GLOXORG",
    "sanalAyna": "Specchio virtuale",
    "sanalAynaKisa": "Specchio"
  },
  "pt": {
    "muhOlmadi": "Não deu certo, tenta de novo?",
    "muhCopeGitti": "Enviado para a lixeira 🗑️",
    "muhGeriYuklendi": "Restaurado ✓",
    "muhKaliciSor": "Excluir DEFINITIVAMENTE? Isso é irreversível.",
    "muhKaliciSilindi": "Excluído definitivamente",
    "muhExcelIndi": "Excel baixado 📊",
    "muhPdfHazir": "PDF pronto 📄",
    "muhMenu": "Menu",
    "sil": "Excluir",
    "muhMusteri": "Cliente",
    "muhUrun": "Produto",
    "muhIslemK": "Operação",
    "muhKasaK": "Caixa",
    "muhBelgeler": "Documentos",
    "muhMusteriler": "Clientes",
    "muhStok": "Estoque",
    "muhAlisSatis": "Compra-Venda",
    "muhKasa": "Caixa",
    "muhCop": "Lixeira",
    "muhBaslik": "Contabilidade",
    "kapat": "Fechar",
    "muhYukleniyor": "Carregando…",
    "muhYeniMusteri": "Novo cliente / fornecedor",
    "muhEklendi": "Adicionado ✓",
    "muhHicMusteri": "Ainda sem clientes. Adicione acima.",
    "muhTedarikci": "Fornecedor",
    "muhToplamBorc": "Dívida total",
    "muhToplamTahsilat": "Recebimentos",
    "muhKalan": "Restante",
    "muhKayitEklendi": "Adicionado ✓",
    "muhKayitYok": "Sem registros. Adicione dívida ou recebimento.",
    "muhBorc": "Dívida",
    "muhTahsilat": "Recebimento",
    "muhTarih": "Data",
    "muhAciklama": "Descrição",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / Compartilhar",
    "muhYeniUrun": "Novo produto",
    "muhHicUrun": "Ainda sem produtos. Adicione acima.",
    "muhAlisF": "Preço de compra",
    "muhSatisF": "Preço de venda",
    "muhKalanStok": "Estoque restante",
    "muhHareketYok": "Sem movimentos. Adicione entrada ou saída.",
    "muhGiris": "Entrada",
    "muhCikis": "Saída",
    "muhYeniIslem": "Nova compra / venda",
    "muhIslemYok": "Ainda sem compra-venda.",
    "muhSatis": "Venda",
    "muhAlis": "Compra",
    "muhGelir": "Receita",
    "muhGider": "Despesa",
    "muhKasaBakiye": "Caixa",
    "muhYeniKasa": "Adicionar receita / despesa",
    "muhKasaYok": "Ainda sem movimento de caixa.",
    "muhBanka": "Banco",
    "muhNakit": "Dinheiro",
    "muhCopAlt": "O que você excluiu fica aqui ~30 dias. Você pode restaurar ou excluir definitivamente agora. No fim do prazo, some sozinho.",
    "muhCopBos": "A lixeira está vazia.",
    "muhGun": "dias",
    "muhGeriYukle": "Restaurar",
    "muhHazirlaniyor": "Preparando…",
    "muhAd": "Nome",
    "muhTel": "Telefone",
    "istege": "opcional",
    "muhNot": "Nota",
    "muhKaydet": "Salvar",
    "muhVazgec": "Cancelar",
    "muhTutar": "Valor",
    "muhKayitEkle": "Adicionar",
    "muhUrunAd": "Nome do produto",
    "muhBirim": "Unidade (un, kg, m…)",
    "muhMiktar": "Quantidade",
    "muhCariSec": "Escolher cliente/fornecedor (opcional)",
    "muhUrunSec": "Escolher produto (opcional)",
    "belTablo": "Tabela Excel",
    "belFatura": "Fatura",
    "belMeslek": "Página profissional",
    "belYazi": "Documento Word",
    "belKaydedildi": "Salvo ✓",
    "belBugun": "Hoje",
    "belBuAy": "Este mês",
    "belBuYil": "Este ano",
    "belEski": "Mais antigos",
    "belAlt2": "Crie seu próprio documento Excel/Word/Fatura, foto→PDF, escolha uma página pronta para sua profissão ou crie sua página profissional e compartilhe. Tudo é arquivado, não some até você excluir.",
    "belFotoPdf": "Foto → PDF",
    "belSablon": "Modelo pronto",
    "belMeslekSayfam": "Minha página profissional",
    "belAraPh": "Buscar nos seus documentos",
    "belAraBos": "Nenhum documento corresponde à busca.",
    "belYok": "Ainda sem documentos. Crie acima.",
    "belAdsiz": "Documento sem nome",
    "belEnAz2": "Selecione ao menos 2 células",
    "belHesaplandi": "Calculado ✓ resultado escrito na célula",
    "belOnceIslem": "Primeiro escolha a operação: ＋ － × ÷",
    "belTopla2": "Somar",
    "belCikar": "Subtrair",
    "belCarp": "Multiplicar",
    "belBol": "Dividir",
    "belGeri": "Documentos",
    "belTabloAd": "Nome da tabela",
    "belYaziMod": "Digite texto / número",
    "belHesapMod": "Calcular com botão",
    "belSatir": "Linha",
    "belSutun": "Coluna",
    "belToplam": "Total",
    "belGenislik": "Largura",
    "belSonucDokun": "Toque na célula VAZIA onde sairá o resultado",
    "belHucreleriSec": "Toque nas células dos números a calcular (ficam selecionadas)",
    "belIslemSec": "Primeiro escolha a operação: Somar / Subtrair / Multiplicar / Dividir",
    "belSonucDokun2": "Agora toque na célula vazia onde sairá o resultado",
    "belSonucYaz": "Escrever o resultado",
    "belTemizle": "Limpar",
    "belYaziIpucu": "✍️ Escreva texto ou números nas células. Para calcular, vá em cima a 🔢 Calcular com botão. (Se quiser, pode escrever a fórmula à mão: =A1+B1) Toque na letra em cima → ordenar.",
    "belKaydet": "Salvar",
    "belExcelIndi": "Excel baixado 📊",
    "belOlmadi": "Não deu certo",
    "belPdfHazir": "PDF pronto 📄",
    "belYaziAd": "Nome do documento",
    "belBaslik": "Título",
    "belListe": "Lista",
    "belWordIndi": "Word baixado 📘",
    "belFotoYok": "Primeiro adicione uma foto",
    "belFotoBaslik": "Título (opcional)",
    "belFotoEkle": "Adicionar foto",
    "belFotoAlt": "Adicione fotos (pode ser várias). Ordene e crie um único PDF, baixe/compartilhe.",
    "belPdfYapPaylas": "Criar PDF — baixar / compartilhar",
    "belUrun": "Produto/Serviço",
    "belMiktar": "Quantidade",
    "belFiyat": "Preço unitário",
    "belTutar": "Valor",
    "belAraToplam": "Subtotal",
    "belGenelToplam": "TOTAL GERAL",
    "belFaturaAd": "Nome da fatura",
    "belSatici": "Vendedor (sua empresa)",
    "belAlici": "Comprador (cliente)",
    "belFaturaNo": "Nº da fatura",
    "belSatirEkle": "Adicionar linha",
    "belSablonSec": "Escolha um modelo pronto para sua profissão",
    "belSablonAlt": "Escolha sua profissão, abre uma página pronta; preencha do seu jeito e baixe Excel/Word/PDF.",
    "belPaylasildi": "Compartilhado ✓",
    "belMeslekAd": "Nome da página",
    "belMeslekAlt": "Crie sua página de apresentação para sua profissão: nome da empresa, o que você faz, serviços, telefone, endereço, foto. Depois baixe PDF/foto, compartilhe ou publique no GLOXORG.",
    "belFirma": "Nome da empresa / negócio",
    "belMeslekTur": "Profissão (ex. Cabeleireiro, Alfaiate, Restaurante)",
    "belSlogan": "Slogan (breve apresentação)",
    "belMeslekAciklama": "Fale sobre você / seu trabalho",
    "belHizmetler": "Serviços (um por linha)",
    "belTelefon": "Telefone",
    "belAdres": "Endereço / Localização",
    "belFotoDegis": "Trocar foto",
    "belFotoEkleBtn": "Adicionar foto / logo",
    "belFirmaOrnek": "Nome da empresa",
    "belPaylas": "Compartilhar",
    "belGloxorda": "Compartilhar no GLOXORG",
    "sanalAyna": "Espelho virtual",
    "sanalAynaKisa": "Espelho"
  },
  "ar": {
    "muhOlmadi": "لم ينجح، هل تحاول مرة أخرى؟",
    "muhCopeGitti": "أُرسل إلى سلة المهملات 🗑️",
    "muhGeriYuklendi": "تمت الاستعادة ✓",
    "muhKaliciSor": "حذف نهائي؟ لا يمكن التراجع.",
    "muhKaliciSilindi": "حُذف نهائياً",
    "muhExcelIndi": "تم تنزيل Excel 📊",
    "muhPdfHazir": "PDF جاهز 📄",
    "muhMenu": "القائمة",
    "sil": "حذف",
    "muhMusteri": "العميل",
    "muhUrun": "المنتج",
    "muhIslemK": "عملية",
    "muhKasaK": "الصندوق",
    "muhBelgeler": "المستندات",
    "muhMusteriler": "العملاء",
    "muhStok": "المخزون",
    "muhAlisSatis": "شراء-بيع",
    "muhKasa": "الصندوق",
    "muhCop": "المهملات",
    "muhBaslik": "المحاسبة",
    "kapat": "إغلاق",
    "muhYukleniyor": "جارٍ التحميل…",
    "muhYeniMusteri": "عميل / مورّد جديد",
    "muhEklendi": "تمت الإضافة ✓",
    "muhHicMusteri": "لا يوجد عملاء بعد. أضف من الأعلى.",
    "muhTedarikci": "المورّد",
    "muhToplamBorc": "إجمالي الدين",
    "muhToplamTahsilat": "التحصيل",
    "muhKalan": "المتبقي",
    "muhKayitEklendi": "تمت الإضافة ✓",
    "muhKayitYok": "لا توجد سجلات. أضف ديناً أو تحصيلاً.",
    "muhBorc": "دين",
    "muhTahsilat": "تحصيل",
    "muhTarih": "التاريخ",
    "muhAciklama": "الوصف",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / مشاركة",
    "muhYeniUrun": "منتج جديد",
    "muhHicUrun": "لا توجد منتجات بعد. أضف من الأعلى.",
    "muhAlisF": "سعر الشراء",
    "muhSatisF": "سعر البيع",
    "muhKalanStok": "المخزون المتبقي",
    "muhHareketYok": "لا توجد حركات. أضف إدخالاً أو إخراجاً.",
    "muhGiris": "إدخال",
    "muhCikis": "إخراج",
    "muhYeniIslem": "شراء / بيع جديد",
    "muhIslemYok": "لا توجد عمليات شراء-بيع بعد.",
    "muhSatis": "بيع",
    "muhAlis": "شراء",
    "muhGelir": "إيراد",
    "muhGider": "مصروف",
    "muhKasaBakiye": "الصندوق",
    "muhYeniKasa": "إضافة إيراد / مصروف",
    "muhKasaYok": "لا توجد حركات صندوق بعد.",
    "muhBanka": "البنك",
    "muhNakit": "نقداً",
    "muhCopAlt": "يُحفظ ما حذفته هنا لنحو 30 يوماً. يمكنك استعادته أو حذفه نهائياً فوراً. عند انتهاء المدة يُحذف تلقائياً.",
    "muhCopBos": "سلة المهملات فارغة.",
    "muhGun": "يوم",
    "muhGeriYukle": "استعادة",
    "muhHazirlaniyor": "جارٍ التحضير…",
    "muhAd": "الاسم",
    "muhTel": "الهاتف",
    "istege": "اختياري",
    "muhNot": "ملاحظة",
    "muhKaydet": "حفظ",
    "muhVazgec": "إلغاء",
    "muhTutar": "المبلغ",
    "muhKayitEkle": "إضافة",
    "muhUrunAd": "اسم المنتج",
    "muhBirim": "الوحدة (قطعة، كغ، م…)",
    "muhMiktar": "الكمية",
    "muhCariSec": "اختر العميل/المورّد (اختياري)",
    "muhUrunSec": "اختر المنتج (اختياري)",
    "belTablo": "جدول Excel",
    "belFatura": "فاتورة",
    "belMeslek": "صفحة المهنة",
    "belYazi": "مستند Word",
    "belKaydedildi": "تم الحفظ ✓",
    "belBugun": "اليوم",
    "belBuAy": "هذا الشهر",
    "belBuYil": "هذه السنة",
    "belEski": "أقدم",
    "belAlt2": "أنشئ مستند Excel/Word/فاتورة خاص بك، حوّل صورة→PDF، اختر صفحة جاهزة حسب مهنتك أو اصنع صفحة مهنتك وشاركها. كل شيء يُؤرشف ولا يُحذف إلا بيدك.",
    "belFotoPdf": "صورة → PDF",
    "belSablon": "قالب جاهز",
    "belMeslekSayfam": "صفحة مهنتي",
    "belAraPh": "ابحث في مستنداتك",
    "belAraBos": "لا يوجد مستند يطابق بحثك.",
    "belYok": "لا توجد مستندات بعد. أنشئ من الأعلى.",
    "belAdsiz": "مستند بلا اسم",
    "belEnAz2": "اختر خليتين على الأقل",
    "belHesaplandi": "تم الحساب ✓ كُتبت النتيجة في الخلية",
    "belOnceIslem": "اختر العملية أولاً: ＋ － × ÷",
    "belTopla2": "جمع",
    "belCikar": "طرح",
    "belCarp": "ضرب",
    "belBol": "قسمة",
    "belGeri": "المستندات",
    "belTabloAd": "اسم الجدول",
    "belYaziMod": "إدخال نص / أرقام",
    "belHesapMod": "احسب بالزر",
    "belSatir": "صف",
    "belSutun": "عمود",
    "belToplam": "الإجمالي",
    "belGenislik": "العرض",
    "belSonucDokun": "المس الخلية الفارغة التي ستظهر فيها النتيجة",
    "belHucreleriSec": "المس خلايا الأرقام المراد حسابها (تُحدَّد)",
    "belIslemSec": "اختر العملية أولاً: جمع / طرح / ضرب / قسمة",
    "belSonucDokun2": "الآن المس الخلية الفارغة التي ستظهر فيها النتيجة",
    "belSonucYaz": "اكتب النتيجة",
    "belTemizle": "مسح",
    "belYaziIpucu": "✍️ اكتب نصاً أو أرقاماً في الخلايا. للحساب انتقل من الأعلى إلى 🔢 احسب بالزر. (يمكنك أيضاً كتابة صيغة يدوياً: =A1+B1) المس الحرف في الأعلى → رتّب.",
    "belKaydet": "حفظ",
    "belExcelIndi": "تم تنزيل Excel 📊",
    "belOlmadi": "لم ينجح",
    "belPdfHazir": "PDF جاهز 📄",
    "belYaziAd": "اسم المستند",
    "belBaslik": "العنوان",
    "belListe": "قائمة",
    "belWordIndi": "تم تنزيل Word 📘",
    "belFotoYok": "أضف صورة أولاً",
    "belFotoBaslik": "العنوان (اختياري)",
    "belFotoEkle": "إضافة صورة",
    "belFotoAlt": "أضف صوراً (يمكن أكثر من واحدة). رتّبها واصنع PDF واحداً، نزّل/شارك.",
    "belPdfYapPaylas": "اصنع PDF — نزّل / شارك",
    "belUrun": "منتج/خدمة",
    "belMiktar": "الكمية",
    "belFiyat": "سعر الوحدة",
    "belTutar": "المبلغ",
    "belAraToplam": "المجموع الفرعي",
    "belGenelToplam": "المجموع الكلي",
    "belFaturaAd": "اسم الفاتورة",
    "belSatici": "البائع (شركتك)",
    "belAlici": "المشتري (العميل)",
    "belFaturaNo": "رقم الفاتورة",
    "belSatirEkle": "إضافة صف",
    "belSablonSec": "اختر قالباً جاهزاً حسب مهنتك",
    "belSablonAlt": "اختر مهنتك لتُفتح صفحة جاهزة؛ املأها حسبك، ثم نزّل Excel/Word/PDF.",
    "belPaylasildi": "تمت المشاركة ✓",
    "belMeslekAd": "اسم الصفحة",
    "belMeslekAlt": "اصنع صفحة تعريف خاصة بمهنتك: اسم الشركة، ماذا تعمل، الخدمات، الهاتف، العنوان، صورة. ثم نزّل PDF/صورة، شارك أو انشر على GLOXORG.",
    "belFirma": "اسم الشركة / المنشأة",
    "belMeslekTur": "المهنة (مثل: حلاق، خياط، مطعم)",
    "belSlogan": "شعار (تعريف قصير)",
    "belMeslekAciklama": "عرّف بنفسك / عملك",
    "belHizmetler": "الخدمات (واحدة في كل سطر)",
    "belTelefon": "الهاتف",
    "belAdres": "العنوان / الموقع",
    "belFotoDegis": "تغيير الصورة",
    "belFotoEkleBtn": "إضافة صورة / شعار",
    "belFirmaOrnek": "اسم الشركة",
    "belPaylas": "مشاركة",
    "belGloxorda": "شارك على GLOXORG",
    "sanalAyna": "مرآة افتراضية",
    "sanalAynaKisa": "مرآة"
  },
  "hi": {
    "muhOlmadi": "नहीं हुआ, फिर कोशिश करें?",
    "muhCopeGitti": "कचरे में भेजा गया 🗑️",
    "muhGeriYuklendi": "वापस लाया गया ✓",
    "muhKaliciSor": "स्थायी रूप से हटाएँ? यह वापस नहीं आएगा।",
    "muhKaliciSilindi": "स्थायी रूप से हटाया गया",
    "muhExcelIndi": "Excel डाउनलोड हुआ 📊",
    "muhPdfHazir": "PDF तैयार 📄",
    "muhMenu": "मेन्यू",
    "sil": "हटाएँ",
    "muhMusteri": "ग्राहक",
    "muhUrun": "उत्पाद",
    "muhIslemK": "लेन-देन",
    "muhKasaK": "नकदी",
    "muhBelgeler": "दस्तावेज़",
    "muhMusteriler": "ग्राहक",
    "muhStok": "स्टॉक",
    "muhAlisSatis": "खरीद-बिक्री",
    "muhKasa": "नकदी",
    "muhCop": "कचरा",
    "muhBaslik": "लेखा",
    "kapat": "बंद करें",
    "muhYukleniyor": "लोड हो रहा है…",
    "muhYeniMusteri": "नया ग्राहक / आपूर्तिकर्ता",
    "muhEklendi": "जोड़ा गया ✓",
    "muhHicMusteri": "अभी कोई ग्राहक नहीं। ऊपर से जोड़ें।",
    "muhTedarikci": "आपूर्तिकर्ता",
    "muhToplamBorc": "कुल उधार",
    "muhToplamTahsilat": "वसूली",
    "muhKalan": "शेष",
    "muhKayitEklendi": "जोड़ा गया ✓",
    "muhKayitYok": "कोई रिकॉर्ड नहीं। उधार या वसूली जोड़ें।",
    "muhBorc": "उधार",
    "muhTahsilat": "वसूली",
    "muhTarih": "तारीख",
    "muhAciklama": "विवरण",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / साझा करें",
    "muhYeniUrun": "नया उत्पाद",
    "muhHicUrun": "अभी कोई उत्पाद नहीं। ऊपर से जोड़ें।",
    "muhAlisF": "खरीद मूल्य",
    "muhSatisF": "बिक्री मूल्य",
    "muhKalanStok": "शेष स्टॉक",
    "muhHareketYok": "कोई गतिविधि नहीं। आवक या जावक जोड़ें।",
    "muhGiris": "आवक",
    "muhCikis": "जावक",
    "muhYeniIslem": "नई खरीद / बिक्री",
    "muhIslemYok": "अभी कोई खरीद-बिक्री नहीं।",
    "muhSatis": "बिक्री",
    "muhAlis": "खरीद",
    "muhGelir": "आय",
    "muhGider": "व्यय",
    "muhKasaBakiye": "नकदी",
    "muhYeniKasa": "आय / व्यय जोड़ें",
    "muhKasaYok": "अभी कोई नकदी गतिविधि नहीं।",
    "muhBanka": "बैंक",
    "muhNakit": "नकद",
    "muhCopAlt": "हटाई गई चीज़ें यहाँ ~30 दिन रखी जाती हैं। वापस ला सकते हैं या तुरंत स्थायी रूप से हटा सकते हैं। समय पूरा होने पर अपने आप हट जाती हैं।",
    "muhCopBos": "कचरा खाली है।",
    "muhGun": "दिन",
    "muhGeriYukle": "वापस",
    "muhHazirlaniyor": "तैयार हो रहा है…",
    "muhAd": "नाम",
    "muhTel": "फ़ोन",
    "istege": "वैकल्पिक",
    "muhNot": "नोट",
    "muhKaydet": "सहेजें",
    "muhVazgec": "रद्द करें",
    "muhTutar": "राशि",
    "muhKayitEkle": "जोड़ें",
    "muhUrunAd": "उत्पाद का नाम",
    "muhBirim": "इकाई (नग, किग्रा, मी…)",
    "muhMiktar": "मात्रा",
    "muhCariSec": "ग्राहक/आपूर्तिकर्ता चुनें (वैकल्पिक)",
    "muhUrunSec": "उत्पाद चुनें (वैकल्पिक)",
    "belTablo": "Excel तालिका",
    "belFatura": "बिल",
    "belMeslek": "पेशा पृष्ठ",
    "belYazi": "Word दस्तावेज़",
    "belKaydedildi": "सहेजा गया ✓",
    "belBugun": "आज",
    "belBuAy": "इस महीने",
    "belBuYil": "इस साल",
    "belEski": "पुराने",
    "belAlt2": "अपना Excel/Word/बिल दस्तावेज़ बनाएँ, फ़ोटो→PDF करें, अपने पेशे के अनुसार तैयार पृष्ठ चुनें या अपना पेशा पृष्ठ बनाकर साझा करें। सब कुछ संग्रहित रहता है, आपके हटाए बिना नहीं जाता।",
    "belFotoPdf": "फ़ोटो → PDF",
    "belSablon": "तैयार टेम्पलेट",
    "belMeslekSayfam": "मेरा पेशा पृष्ठ",
    "belAraPh": "अपने दस्तावेज़ों में खोजें",
    "belAraBos": "आपकी खोज से मेल खाता कोई दस्तावेज़ नहीं।",
    "belYok": "अभी कोई दस्तावेज़ नहीं। ऊपर से बनाएँ।",
    "belAdsiz": "बिना नाम दस्तावेज़",
    "belEnAz2": "कम से कम 2 सेल चुनें",
    "belHesaplandi": "गणना हुई ✓ परिणाम सेल में लिखा गया",
    "belOnceIslem": "पहले क्रिया चुनें: ＋ － × ÷",
    "belTopla2": "जोड़",
    "belCikar": "घटाव",
    "belCarp": "गुणा",
    "belBol": "भाग",
    "belGeri": "दस्तावेज़",
    "belTabloAd": "तालिका का नाम",
    "belYaziMod": "टेक्स्ट / अंक भरें",
    "belHesapMod": "बटन से गणना करें",
    "belSatir": "पंक्ति",
    "belSutun": "स्तंभ",
    "belToplam": "कुल",
    "belGenislik": "चौड़ाई",
    "belSonucDokun": "जिस खाली सेल में परिणाम आएगा उसे छुएँ",
    "belHucreleriSec": "जिन अंक सेल की गणना करनी है उन्हें छुएँ (चुन जाएँगे)",
    "belIslemSec": "पहले क्रिया चुनें: जोड़ / घटाव / गुणा / भाग",
    "belSonucDokun2": "अब जिस खाली सेल में परिणाम आएगा उसे छुएँ",
    "belSonucYaz": "परिणाम लिखें",
    "belTemizle": "साफ़ करें",
    "belYaziIpucu": "✍️ सेल में टेक्स्ट या अंक लिखें। गणना के लिए ऊपर से 🔢 बटन से गणना करें पर जाएँ। (चाहें तो हाथ से सूत्र भी लिख सकते हैं: =A1+B1) ऊपर के अक्षर को छुएँ → क्रमबद्ध करें।",
    "belKaydet": "सहेजें",
    "belExcelIndi": "Excel डाउनलोड हुआ 📊",
    "belOlmadi": "नहीं हुआ",
    "belPdfHazir": "PDF तैयार 📄",
    "belYaziAd": "दस्तावेज़ का नाम",
    "belBaslik": "शीर्षक",
    "belListe": "सूची",
    "belWordIndi": "Word डाउनलोड हुआ 📘",
    "belFotoYok": "पहले फ़ोटो जोड़ें",
    "belFotoBaslik": "शीर्षक (वैकल्पिक)",
    "belFotoEkle": "फ़ोटो जोड़ें",
    "belFotoAlt": "फ़ोटो जोड़ें (एक से अधिक हो सकती हैं)। क्रमबद्ध करके एक PDF बनाएँ, डाउनलोड/साझा करें।",
    "belPdfYapPaylas": "PDF बनाएँ — डाउनलोड / साझा करें",
    "belUrun": "उत्पाद/सेवा",
    "belMiktar": "मात्रा",
    "belFiyat": "इकाई मूल्य",
    "belTutar": "राशि",
    "belAraToplam": "उप-योग",
    "belGenelToplam": "कुल योग",
    "belFaturaAd": "बिल का नाम",
    "belSatici": "विक्रेता (आपकी फर्म)",
    "belAlici": "खरीदार (ग्राहक)",
    "belFaturaNo": "बिल नंबर",
    "belSatirEkle": "पंक्ति जोड़ें",
    "belSablonSec": "अपने पेशे के अनुसार तैयार टेम्पलेट चुनें",
    "belSablonAlt": "अपना पेशा चुनें, तैयार पृष्ठ खुलेगा; उसे अपने अनुसार भरें, फिर Excel/Word/PDF डाउनलोड करें।",
    "belPaylasildi": "साझा किया गया ✓",
    "belMeslekAd": "पृष्ठ का नाम",
    "belMeslekAlt": "अपने पेशे के अनुसार अपना परिचय पृष्ठ बनाएँ: फर्म का नाम, आप क्या काम करते हैं, सेवाएँ, फ़ोन, पता, फ़ोटो। फिर PDF/फ़ोटो डाउनलोड करें, साझा करें या GLOXORG पर प्रकाशित करें।",
    "belFirma": "फर्म / व्यवसाय का नाम",
    "belMeslekTur": "पेशा (जैसे नाई, दर्ज़ी, रेस्तरां)",
    "belSlogan": "नारा (संक्षिप्त परिचय)",
    "belMeslekAciklama": "अपने / अपने काम के बारे में बताएँ",
    "belHizmetler": "सेवाएँ (हर पंक्ति में एक)",
    "belTelefon": "फ़ोन",
    "belAdres": "पता / स्थान",
    "belFotoDegis": "फ़ोटो बदलें",
    "belFotoEkleBtn": "फ़ोटो / लोगो जोड़ें",
    "belFirmaOrnek": "फर्म का नाम",
    "belPaylas": "साझा करें",
    "belGloxorda": "GLOXORG पर साझा करें",
    "sanalAyna": "आभासी दर्पण",
    "sanalAynaKisa": "दर्पण"
  },
  "zh": {
    "muhOlmadi": "没成功，再试一次好吗？",
    "muhCopeGitti": "已移入回收站 🗑️",
    "muhGeriYuklendi": "已还原 ✓",
    "muhKaliciSor": "要永久删除吗？此操作无法撤销。",
    "muhKaliciSilindi": "已永久删除",
    "muhExcelIndi": "Excel 已下载 📊",
    "muhPdfHazir": "PDF 已就绪 📄",
    "muhMenu": "菜单",
    "sil": "删除",
    "muhMusteri": "客户",
    "muhUrun": "产品",
    "muhIslemK": "交易",
    "muhKasaK": "现金",
    "muhBelgeler": "文件",
    "muhMusteriler": "客户",
    "muhStok": "库存",
    "muhAlisSatis": "进销",
    "muhKasa": "现金",
    "muhCop": "回收站",
    "muhBaslik": "会计",
    "kapat": "关闭",
    "muhYukleniyor": "加载中…",
    "muhYeniMusteri": "新客户 / 供应商",
    "muhEklendi": "已添加 ✓",
    "muhHicMusteri": "暂无客户。请在上方添加。",
    "muhTedarikci": "供应商",
    "muhToplamBorc": "欠款合计",
    "muhToplamTahsilat": "收款",
    "muhKalan": "余额",
    "muhKayitEklendi": "已添加 ✓",
    "muhKayitYok": "暂无记录。添加欠款或收款。",
    "muhBorc": "欠款",
    "muhTahsilat": "收款",
    "muhTarih": "日期",
    "muhAciklama": "说明",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / 分享",
    "muhYeniUrun": "新产品",
    "muhHicUrun": "暂无产品。请在上方添加。",
    "muhAlisF": "进价",
    "muhSatisF": "售价",
    "muhKalanStok": "剩余库存",
    "muhHareketYok": "暂无变动。添加入库或出库。",
    "muhGiris": "入库",
    "muhCikis": "出库",
    "muhYeniIslem": "新进货 / 销售",
    "muhIslemYok": "暂无进销。",
    "muhSatis": "销售",
    "muhAlis": "进货",
    "muhGelir": "收入",
    "muhGider": "支出",
    "muhKasaBakiye": "现金",
    "muhYeniKasa": "添加收入 / 支出",
    "muhKasaYok": "暂无现金变动。",
    "muhBanka": "银行",
    "muhNakit": "现金",
    "muhCopAlt": "删除的内容在此保留约 30 天。可还原或立即永久删除。到期后自动删除。",
    "muhCopBos": "回收站为空。",
    "muhGun": "天",
    "muhGeriYukle": "还原",
    "muhHazirlaniyor": "准备中…",
    "muhAd": "姓名",
    "muhTel": "电话",
    "istege": "可选",
    "muhNot": "备注",
    "muhKaydet": "保存",
    "muhVazgec": "取消",
    "muhTutar": "金额",
    "muhKayitEkle": "添加",
    "muhUrunAd": "产品名称",
    "muhBirim": "单位（个、公斤、米…）",
    "muhMiktar": "数量",
    "muhCariSec": "选择客户/供应商（可选）",
    "muhUrunSec": "选择产品（可选）",
    "belTablo": "Excel 表格",
    "belFatura": "发票",
    "belMeslek": "行业页面",
    "belYazi": "Word 文档",
    "belKaydedildi": "已保存 ✓",
    "belBugun": "今天",
    "belBuAy": "本月",
    "belBuYil": "本年",
    "belEski": "更早",
    "belAlt2": "制作你自己的 Excel/Word/发票文件，把照片转成 PDF，按行业选现成页面，或做自己的行业页面并分享。全部归档，不删不丢。",
    "belFotoPdf": "照片 → PDF",
    "belSablon": "现成模板",
    "belMeslekSayfam": "我的行业页面",
    "belAraPh": "在文件中搜索",
    "belAraBos": "没有符合搜索的文件。",
    "belYok": "暂无文件。请在上方创建。",
    "belAdsiz": "未命名文件",
    "belEnAz2": "至少选 2 个单元格",
    "belHesaplandi": "已计算 ✓ 结果已写入单元格",
    "belOnceIslem": "请先选运算：＋ － × ÷",
    "belTopla2": "求和",
    "belCikar": "相减",
    "belCarp": "相乘",
    "belBol": "相除",
    "belGeri": "文件",
    "belTabloAd": "表格名称",
    "belYaziMod": "输入文字 / 数字",
    "belHesapMod": "用按钮计算",
    "belSatir": "行",
    "belSutun": "列",
    "belToplam": "合计",
    "belGenislik": "宽度",
    "belSonucDokun": "点击要显示结果的空单元格",
    "belHucreleriSec": "点击要计算的数字单元格（即选中）",
    "belIslemSec": "请先选运算：求和 / 相减 / 相乘 / 相除",
    "belSonucDokun2": "现在点击要显示结果的空单元格",
    "belSonucYaz": "写入结果",
    "belTemizle": "清除",
    "belYaziIpucu": "✍️ 在单元格里写文字或数字。要计算就切到上方的 🔢 用按钮计算。（也可手动输入公式：=A1+B1）点击上方字母 → 排序。",
    "belKaydet": "保存",
    "belExcelIndi": "Excel 已下载 📊",
    "belOlmadi": "没成功",
    "belPdfHazir": "PDF 已就绪 📄",
    "belYaziAd": "文档名称",
    "belBaslik": "标题",
    "belListe": "列表",
    "belWordIndi": "Word 已下载 📘",
    "belFotoYok": "请先添加照片",
    "belFotoBaslik": "标题（可选）",
    "belFotoEkle": "添加照片",
    "belFotoAlt": "添加照片（可多张）。排序后合成单个 PDF，下载/分享。",
    "belPdfYapPaylas": "生成 PDF — 下载 / 分享",
    "belUrun": "产品/服务",
    "belMiktar": "数量",
    "belFiyat": "单价",
    "belTutar": "金额",
    "belAraToplam": "小计",
    "belGenelToplam": "总计",
    "belFaturaAd": "发票名称",
    "belSatici": "卖方（你的公司）",
    "belAlici": "买方（客户）",
    "belFaturaNo": "发票号",
    "belSatirEkle": "添加行",
    "belSablonSec": "按行业选择现成模板",
    "belSablonAlt": "选择你的行业，打开现成页面；按自己的情况填写，然后下载 Excel/Word/PDF。",
    "belPaylasildi": "已分享 ✓",
    "belMeslekAd": "页面名称",
    "belMeslekAlt": "按行业做自己的宣传页面：公司名、业务内容、服务、电话、地址、照片。然后下载 PDF/照片，分享或发布到 GLOXORG。",
    "belFirma": "公司 / 商号名称",
    "belMeslekTur": "行业（如 美发、裁缝、餐厅）",
    "belSlogan": "标语（简短介绍）",
    "belMeslekAciklama": "介绍你 / 你的业务",
    "belHizmetler": "服务（每行一项）",
    "belTelefon": "电话",
    "belAdres": "地址 / 位置",
    "belFotoDegis": "更换照片",
    "belFotoEkleBtn": "添加照片 / 徽标",
    "belFirmaOrnek": "公司名称",
    "belPaylas": "分享",
    "belGloxorda": "在 GLOXORG 上分享",
    "sanalAyna": "虚拟镜",
    "sanalAynaKisa": "镜子"
  },
  "ja": {
    "muhOlmadi": "うまくいきませんでした。もう一度お試しください。",
    "muhCopeGitti": "ゴミ箱に移動しました 🗑️",
    "muhGeriYuklendi": "復元しました ✓",
    "muhKaliciSor": "完全に削除しますか？元に戻せません。",
    "muhKaliciSilindi": "完全に削除しました",
    "muhExcelIndi": "Excel をダウンロードしました 📊",
    "muhPdfHazir": "PDF ができました 📄",
    "muhMenu": "メニュー",
    "sil": "削除",
    "muhMusteri": "顧客",
    "muhUrun": "商品",
    "muhIslemK": "取引",
    "muhKasaK": "現金",
    "muhBelgeler": "書類",
    "muhMusteriler": "顧客",
    "muhStok": "在庫",
    "muhAlisSatis": "仕入・販売",
    "muhKasa": "現金",
    "muhCop": "ゴミ箱",
    "muhBaslik": "会計",
    "kapat": "閉じる",
    "muhYukleniyor": "読み込み中…",
    "muhYeniMusteri": "新規顧客 / 仕入先",
    "muhEklendi": "追加しました ✓",
    "muhHicMusteri": "まだ顧客がいません。上から追加してください。",
    "muhTedarikci": "仕入先",
    "muhToplamBorc": "未払合計",
    "muhToplamTahsilat": "入金",
    "muhKalan": "残高",
    "muhKayitEklendi": "追加しました ✓",
    "muhKayitYok": "記録がありません。未払または入金を追加してください。",
    "muhBorc": "未払",
    "muhTahsilat": "入金",
    "muhTarih": "日付",
    "muhAciklama": "説明",
    "muhExcel": "Excel",
    "muhPdfPaylas": "PDF / 共有",
    "muhYeniUrun": "新規商品",
    "muhHicUrun": "まだ商品がありません。上から追加してください。",
    "muhAlisF": "仕入価格",
    "muhSatisF": "販売価格",
    "muhKalanStok": "在庫残数",
    "muhHareketYok": "変動がありません。入庫または出庫を追加してください。",
    "muhGiris": "入庫",
    "muhCikis": "出庫",
    "muhYeniIslem": "新規仕入 / 販売",
    "muhIslemYok": "まだ仕入・販売がありません。",
    "muhSatis": "販売",
    "muhAlis": "仕入",
    "muhGelir": "収入",
    "muhGider": "支出",
    "muhKasaBakiye": "現金",
    "muhYeniKasa": "収入 / 支出を追加",
    "muhKasaYok": "まだ現金の動きがありません。",
    "muhBanka": "銀行",
    "muhNakit": "現金",
    "muhCopAlt": "削除したものはここに約30日間保存されます。復元またはすぐに完全削除できます。期限が過ぎると自動的に削除されます。",
    "muhCopBos": "ゴミ箱は空です。",
    "muhGun": "日",
    "muhGeriYukle": "復元",
    "muhHazirlaniyor": "準備中…",
    "muhAd": "名前",
    "muhTel": "電話",
    "istege": "任意",
    "muhNot": "メモ",
    "muhKaydet": "保存",
    "muhVazgec": "キャンセル",
    "muhTutar": "金額",
    "muhKayitEkle": "追加",
    "muhUrunAd": "商品名",
    "muhBirim": "単位（個・kg・m…）",
    "muhMiktar": "数量",
    "muhCariSec": "顧客/仕入先を選択（任意）",
    "muhUrunSec": "商品を選択（任意）",
    "belTablo": "Excel 表",
    "belFatura": "請求書",
    "belMeslek": "業種ページ",
    "belYazi": "Word 文書",
    "belKaydedildi": "保存しました ✓",
    "belBugun": "今日",
    "belBuAy": "今月",
    "belBuYil": "今年",
    "belEski": "さらに前",
    "belAlt2": "自分の Excel/Word/請求書を作成、写真を PDF に、業種別の既製ページを選択、または自分の業種ページを作って共有。すべて保存され、削除しない限り残ります。",
    "belFotoPdf": "写真 → PDF",
    "belSablon": "既製テンプレート",
    "belMeslekSayfam": "マイ業種ページ",
    "belAraPh": "書類を検索",
    "belAraBos": "検索に一致する書類がありません。",
    "belYok": "まだ書類がありません。上から作成してください。",
    "belAdsiz": "無題の書類",
    "belEnAz2": "セルを2つ以上選択",
    "belHesaplandi": "計算しました ✓ 結果をセルに書き込みました",
    "belOnceIslem": "先に演算を選択：＋ － × ÷",
    "belTopla2": "合計",
    "belCikar": "引く",
    "belCarp": "掛ける",
    "belBol": "割る",
    "belGeri": "書類",
    "belTabloAd": "表の名前",
    "belYaziMod": "文字 / 数字を入力",
    "belHesapMod": "ボタンで計算",
    "belSatir": "行",
    "belSutun": "列",
    "belToplam": "合計",
    "belGenislik": "幅",
    "belSonucDokun": "結果を表示する空のセルをタップ",
    "belHucreleriSec": "計算する数字のセルをタップ（選択されます）",
    "belIslemSec": "先に演算を選択：合計 / 引く / 掛ける / 割る",
    "belSonucDokun2": "次に結果を表示する空のセルをタップ",
    "belSonucYaz": "結果を書き込む",
    "belTemizle": "クリア",
    "belYaziIpucu": "✍️ セルに文字や数字を入力。計算するには上の 🔢 ボタンで計算 に切り替え。（手動で数式も入力可：=A1+B1）上の文字をタップ → 並べ替え。",
    "belKaydet": "保存",
    "belExcelIndi": "Excel をダウンロードしました 📊",
    "belOlmadi": "うまくいきませんでした",
    "belPdfHazir": "PDF ができました 📄",
    "belYaziAd": "文書名",
    "belBaslik": "タイトル",
    "belListe": "リスト",
    "belWordIndi": "Word をダウンロードしました 📘",
    "belFotoYok": "先に写真を追加してください",
    "belFotoBaslik": "タイトル（任意）",
    "belFotoEkle": "写真を追加",
    "belFotoAlt": "写真を追加（複数可）。並べ替えて1つの PDF にまとめ、ダウンロード/共有。",
    "belPdfYapPaylas": "PDF を作成 — ダウンロード / 共有",
    "belUrun": "商品/サービス",
    "belMiktar": "数量",
    "belFiyat": "単価",
    "belTutar": "金額",
    "belAraToplam": "小計",
    "belGenelToplam": "総合計",
    "belFaturaAd": "請求書名",
    "belSatici": "売り手（あなたの会社）",
    "belAlici": "買い手（顧客）",
    "belFaturaNo": "請求書番号",
    "belSatirEkle": "行を追加",
    "belSablonSec": "業種別の既製テンプレートを選択",
    "belSablonAlt": "業種を選ぶと既製ページが開きます。自分に合わせて記入し、Excel/Word/PDF をダウンロード。",
    "belPaylasildi": "共有しました ✓",
    "belMeslekAd": "ページ名",
    "belMeslekAlt": "業種に合わせて自分の紹介ページを作成：会社名、業務内容、サービス、電話、住所、写真。その後 PDF/写真をダウンロード、共有、または GLOXORG に公開。",
    "belFirma": "会社 / 屋号名",
    "belMeslekTur": "業種（例：美容室、仕立て屋、レストラン）",
    "belSlogan": "スローガン（短い紹介）",
    "belMeslekAciklama": "自分 / 仕事を紹介",
    "belHizmetler": "サービス（1行に1つ）",
    "belTelefon": "電話",
    "belAdres": "住所 / 場所",
    "belFotoDegis": "写真を変更",
    "belFotoEkleBtn": "写真 / ロゴを追加",
    "belFirmaOrnek": "会社名",
    "belPaylas": "共有",
    "belGloxorda": "GLOXORG で共有",
    "sanalAyna": "バーチャルミラー",
    "sanalAynaKisa": "ミラー"
  }
};
