// GLOXORG — KONUM HARİTASI (knh*), ADRES HARİTASI (adh*) ve CANLI AKIŞ (cy*) çevirileri (13 dil).
// i18n.js'te resources'a düz-birleştirilir. Bu sayfalar eskiden çevirisizdi → hep Türkçe kalıyordu; bu dosya çözer.
export const CEVIRI_HARITA_CANLI = {
  tr: {
    cyBaslat: "Canlı yayın başlat", cyBosYazi: "Henüz kısa video yok. İlk videoyu sen paylaş!", cyCanli: "CANLI YAYIN",
    cyHeroAlt: "Telefonundan canlı yayın aç, herkes seni anlık izlesin.", cyKisaVideolar: "Kısa Videolar", cyVideoPaylas: "Video paylaş",
    cyYakinda: "Bunun için özel bir canlı-yayın servisi kuruluyor (izleyicilere anlık, kesintisiz video). Hazır olunca buradan tek dokunuşla canlı yayın açacaksın. Şimdilik aşağıdaki kısa videoları izle, kendi videonu paylaş.",
    cyYakindaBas: "Gerçek canlı yayın çok yakında!",
    knhAcHaritaSen: "Kendini ve yakındaki arkadaşları gör — dokun", knhAra: "Yer, adres, mekân ara…", knhAraba: "Araba", knhArkadas: "Arkadaş",
    knhArkadasHaritada: "arkadaşın haritada — dokun", knhArkadasVar: "arkadaşın haritada", knhArkadasYok: "Yakınında arkadaş yok", knhBisiklet: "Bisiklet",
    knhBosArkadas: "Uygulamayı açıp konumunu paylaşan kişiler — uzakta ya da yakında — sana kaç km olduklarıyla burada fotoğraflarıyla görünecek.",
    knhBul: "Bul", knhDk: "dk", knhEnYakin: "En yakın", knhHepsiniGoster: "Hepsini göster", knhKonumum: "Ortala", knhMesaj: "Mesaj",
    knhNeKadarUzak: "Ne kadar uzak", knhPaylasimAcik: "Konumum açık", knhPaylasimKapali: "Konumum kapalı", knhPusula: "Kuzey", knhRotaHesap: "Rota çiziliyor…",
    knhSaat: "sa", knhSen: "Sen", knhSenBurada: "Sen buradasın 🙂", knhSonucYok: "Sonuç bulunamadı.", knhUzak: "Uzaklaştır", knhUzakta: "uzakta",
    knhYakin: "Yakınlaştır", knhYolTarifi: "Yol tarifi", knhYukleniyor: "Harita geliyor…", knhYurume: "Yürü",
    adhAc: "Adresini öğrenmek için dokun", adhAraYaz: "Adres/mekân yaz ara…", adhAraniyor: "Adres bulunuyor…", adhBaslik: "Adres bul ve kopyala",
    adhDokun: "Bir yere/mekâna dokun ya da yukarıdan ara", adhEkleDokun: "İşyerinin/yerin haritada olduğu noktaya dokun", adhEkleyen: "Ekleyen", adhEn: "İngilizce",
    adhFotoEkle: "Fotoğraf ekle", adhGiris: "Mekân eklemek için giriş yapmalısın.", adhHakkinda: "Hakkında (isteğe bağlı) — ne satıyorsun, çalışma saatleri…",
    adhKaydOlmadi: "Kaydedilemedi, tekrar dene.", adhKonumum: "Konumumu bul", adhKopyala: "Kopyala", adhKopyalandi: "Adres kopyalandı",
    adhSilOnay: "Bu mekânı silmek istiyor musun?", adhTelefon: "Telefon (isteğe bağlı)", adhYaziDuzenle: "Yazıyı düzenle", adhYeni: "Temizle / yeniden ara",
    adhYeniYer: "Yeni yer ekle", adhYerAdi: "Yerin adı (örn: Ahmet Market)", adhYerEkle: "Yerimi ekle", adhYerel: "Yerel dilde",
  },
  en: {
    cyBaslat: "Start live stream", cyBosYazi: "No short videos yet. Be the first to share one!", cyCanli: "LIVE STREAM",
    cyHeroAlt: "Go live from your phone, let everyone watch you in real time.", cyKisaVideolar: "Short Videos", cyVideoPaylas: "Share video",
    cyYakinda: "A dedicated live-streaming service is being built (real-time, uninterrupted video for viewers). Once it's ready you'll go live from here with one tap. For now, watch the short videos below and share your own.",
    cyYakindaBas: "Real live streaming is coming very soon!",
    knhAcHaritaSen: "See yourself and nearby friends — tap", knhAra: "Search place, address, venue…", knhAraba: "Car", knhArkadas: "Friend",
    knhArkadasHaritada: "friends on the map — tap", knhArkadasVar: "friends on the map", knhArkadasYok: "No friends nearby", knhBisiklet: "Bike",
    knhBosArkadas: "People who open the app and share their location — far or near — will appear here with their photos and how many km away they are.",
    knhBul: "Find", knhDk: "min", knhEnYakin: "Nearest", knhHepsiniGoster: "Show all", knhKonumum: "Center", knhMesaj: "Message",
    knhNeKadarUzak: "How far", knhPaylasimAcik: "My location is on", knhPaylasimKapali: "My location is off", knhPusula: "North", knhRotaHesap: "Drawing route…",
    knhSaat: "h", knhSen: "You", knhSenBurada: "You are here 🙂", knhSonucYok: "No results found.", knhUzak: "Zoom out", knhUzakta: "away",
    knhYakin: "Zoom in", knhYolTarifi: "Directions", knhYukleniyor: "Loading map…", knhYurume: "Walk",
    adhAc: "Tap to find your address", adhAraYaz: "Type an address/venue to search…", adhAraniyor: "Finding address…", adhBaslik: "Find and copy address",
    adhDokun: "Tap a place/venue or search above", adhEkleDokun: "Tap the exact spot of your workplace/venue on the map", adhEkleyen: "Added by", adhEn: "English",
    adhFotoEkle: "Add photo", adhGiris: "You must sign in to add a venue.", adhHakkinda: "About (optional) — what you sell, opening hours…",
    adhKaydOlmadi: "Couldn't save, try again.", adhKonumum: "Find my location", adhKopyala: "Copy", adhKopyalandi: "Address copied",
    adhSilOnay: "Do you want to delete this venue?", adhTelefon: "Phone (optional)", adhYaziDuzenle: "Edit text", adhYeni: "Clear / search again",
    adhYeniYer: "Add new place", adhYerAdi: "Place name (e.g. Ahmet Market)", adhYerEkle: "Add my place", adhYerel: "Local language",
  },
  de: {
    cyBaslat: "Livestream starten", cyBosYazi: "Noch keine kurzen Videos. Teile das erste!", cyCanli: "LIVESTREAM",
    cyHeroAlt: "Geh mit dem Handy live, alle sehen dich in Echtzeit.", cyKisaVideolar: "Kurze Videos", cyVideoPaylas: "Video teilen",
    cyYakinda: "Ein eigener Livestream-Dienst wird gebaut (Echtzeit-Video ohne Unterbrechung für Zuschauer). Sobald er fertig ist, gehst du von hier mit einem Tipp live. Schau vorerst die kurzen Videos unten und teile dein eigenes.",
    cyYakindaBas: "Echtes Live-Streaming kommt sehr bald!",
    knhAcHaritaSen: "Dich und Freunde in der Nähe sehen — tippen", knhAra: "Ort, Adresse, Lokal suchen…", knhAraba: "Auto", knhArkadas: "Freund",
    knhArkadasHaritada: "Freunde auf der Karte — tippen", knhArkadasVar: "Freunde auf der Karte", knhArkadasYok: "Keine Freunde in der Nähe", knhBisiklet: "Fahrrad",
    knhBosArkadas: "Personen, die die App öffnen und ihren Standort teilen — nah oder fern — erscheinen hier mit Foto und der Entfernung in km.",
    knhBul: "Finden", knhDk: "Min", knhEnYakin: "Am nächsten", knhHepsiniGoster: "Alle zeigen", knhKonumum: "Zentrieren", knhMesaj: "Nachricht",
    knhNeKadarUzak: "Wie weit", knhPaylasimAcik: "Mein Standort ist an", knhPaylasimKapali: "Mein Standort ist aus", knhPusula: "Norden", knhRotaHesap: "Route wird gezeichnet…",
    knhSaat: "Std", knhSen: "Du", knhSenBurada: "Du bist hier 🙂", knhSonucYok: "Keine Ergebnisse.", knhUzak: "Verkleinern", knhUzakta: "entfernt",
    knhYakin: "Vergrößern", knhYolTarifi: "Route", knhYukleniyor: "Karte lädt…", knhYurume: "Zu Fuß",
    adhAc: "Tippen, um deine Adresse zu finden", adhAraYaz: "Adresse/Lokal zum Suchen eingeben…", adhAraniyor: "Adresse wird gesucht…", adhBaslik: "Adresse finden und kopieren",
    adhDokun: "Auf einen Ort/ein Lokal tippen oder oben suchen", adhEkleDokun: "Tippe die genaue Stelle deines Geschäfts/Lokals auf der Karte", adhEkleyen: "Hinzugefügt von", adhEn: "Englisch",
    adhFotoEkle: "Foto hinzufügen", adhGiris: "Zum Hinzufügen eines Lokals musst du dich anmelden.", adhHakkinda: "Über (optional) — was du verkaufst, Öffnungszeiten…",
    adhKaydOlmadi: "Konnte nicht gespeichert werden, versuch es erneut.", adhKonumum: "Meinen Standort finden", adhKopyala: "Kopieren", adhKopyalandi: "Adresse kopiert",
    adhSilOnay: "Möchtest du dieses Lokal löschen?", adhTelefon: "Telefon (optional)", adhYaziDuzenle: "Text bearbeiten", adhYeni: "Löschen / erneut suchen",
    adhYeniYer: "Neuen Ort hinzufügen", adhYerAdi: "Name des Ortes (z. B. Ahmet Markt)", adhYerEkle: "Meinen Ort hinzufügen", adhYerel: "In der Landessprache",
  },
  ru: {
    cyBaslat: "Начать прямой эфир", cyBosYazi: "Пока нет коротких видео. Поделись первым!", cyCanli: "ПРЯМОЙ ЭФИР",
    cyHeroAlt: "Выходи в эфир с телефона, и все смотрят тебя в реальном времени.", cyKisaVideolar: "Короткие видео", cyVideoPaylas: "Поделиться видео",
    cyYakinda: "Создаётся отдельный сервис прямых трансляций (видео зрителям в реальном времени, без прерываний). Когда он будет готов, ты выйдешь в эфир отсюда одним касанием. А пока смотри короткие видео ниже и делись своим.",
    cyYakindaBas: "Настоящие прямые эфиры уже совсем скоро!",
    knhAcHaritaSen: "Увидь себя и друзей рядом — нажми", knhAra: "Поиск места, адреса, заведения…", knhAraba: "Авто", knhArkadas: "Друг",
    knhArkadasHaritada: "друзей на карте — нажми", knhArkadasVar: "друзей на карте", knhArkadasYok: "Рядом нет друзей", knhBisiklet: "Велосипед",
    knhBosArkadas: "Люди, которые открывают приложение и делятся геолокацией — далеко или рядом — появятся здесь с фото и расстоянием в км до тебя.",
    knhBul: "Найти", knhDk: "мин", knhEnYakin: "Ближайший", knhHepsiniGoster: "Показать всех", knhKonumum: "По центру", knhMesaj: "Сообщение",
    knhNeKadarUzak: "Как далеко", knhPaylasimAcik: "Моя геолокация включена", knhPaylasimKapali: "Моя геолокация выключена", knhPusula: "Север", knhRotaHesap: "Строится маршрут…",
    knhSaat: "ч", knhSen: "Ты", knhSenBurada: "Ты здесь 🙂", knhSonucYok: "Ничего не найдено.", knhUzak: "Отдалить", knhUzakta: "далеко",
    knhYakin: "Приблизить", knhYolTarifi: "Маршрут", knhYukleniyor: "Загрузка карты…", knhYurume: "Пешком",
    adhAc: "Нажми, чтобы узнать свой адрес", adhAraYaz: "Введи адрес/заведение для поиска…", adhAraniyor: "Поиск адреса…", adhBaslik: "Найти и скопировать адрес",
    adhDokun: "Нажми на место/заведение или найди сверху", adhEkleDokun: "Нажми точное место своего заведения на карте", adhEkleyen: "Добавил", adhEn: "Английский",
    adhFotoEkle: "Добавить фото", adhGiris: "Чтобы добавить заведение, нужно войти.", adhHakkinda: "О месте (необязательно) — что продаёшь, часы работы…",
    adhKaydOlmadi: "Не удалось сохранить, попробуй ещё раз.", adhKonumum: "Найти моё местоположение", adhKopyala: "Копировать", adhKopyalandi: "Адрес скопирован",
    adhSilOnay: "Удалить это заведение?", adhTelefon: "Телефон (необязательно)", adhYaziDuzenle: "Редактировать текст", adhYeni: "Очистить / искать снова",
    adhYeniYer: "Добавить новое место", adhYerAdi: "Название места (напр.: Магазин Ахмет)", adhYerEkle: "Добавить моё место", adhYerel: "На местном языке",
  },
  uk: {
    cyBaslat: "Почати прямий ефір", cyBosYazi: "Поки немає коротких відео. Поділись першим!", cyCanli: "ПРЯМИЙ ЕФІР",
    cyHeroAlt: "Виходь в ефір з телефона, і всі дивляться тебе в реальному часі.", cyKisaVideolar: "Короткі відео", cyVideoPaylas: "Поділитися відео",
    cyYakinda: "Створюється окремий сервіс прямих трансляцій (відео глядачам у реальному часі, без перерв). Коли він буде готовий, ти вийдеш в ефір звідси одним дотиком. А поки дивись короткі відео нижче й ділись своїм.",
    cyYakindaBas: "Справжні прямі ефіри вже зовсім скоро!",
    knhAcHaritaSen: "Побач себе й друзів поруч — торкнись", knhAra: "Пошук місця, адреси, закладу…", knhAraba: "Авто", knhArkadas: "Друг",
    knhArkadasHaritada: "друзів на карті — торкнись", knhArkadasVar: "друзів на карті", knhArkadasYok: "Поруч немає друзів", knhBisiklet: "Велосипед",
    knhBosArkadas: "Люди, які відкривають застосунок і діляться геолокацією — далеко чи поруч — з’являться тут із фото та відстанню в км до тебе.",
    knhBul: "Знайти", knhDk: "хв", knhEnYakin: "Найближчий", knhHepsiniGoster: "Показати всіх", knhKonumum: "По центру", knhMesaj: "Повідомлення",
    knhNeKadarUzak: "Як далеко", knhPaylasimAcik: "Моя геолокація увімкнена", knhPaylasimKapali: "Моя геолокація вимкнена", knhPusula: "Північ", knhRotaHesap: "Прокладається маршрут…",
    knhSaat: "год", knhSen: "Ти", knhSenBurada: "Ти тут 🙂", knhSonucYok: "Нічого не знайдено.", knhUzak: "Віддалити", knhUzakta: "далеко",
    knhYakin: "Наблизити", knhYolTarifi: "Маршрут", knhYukleniyor: "Завантаження карти…", knhYurume: "Пішки",
    adhAc: "Торкнись, щоб дізнатися свою адресу", adhAraYaz: "Введи адресу/заклад для пошуку…", adhAraniyor: "Пошук адреси…", adhBaslik: "Знайти й скопіювати адресу",
    adhDokun: "Торкнись місця/закладу або знайди зверху", adhEkleDokun: "Торкнись точного місця свого закладу на карті", adhEkleyen: "Додав", adhEn: "Англійська",
    adhFotoEkle: "Додати фото", adhGiris: "Щоб додати заклад, потрібно увійти.", adhHakkinda: "Про місце (необов’язково) — що продаєш, години роботи…",
    adhKaydOlmadi: "Не вдалося зберегти, спробуй ще раз.", adhKonumum: "Знайти моє місцезнаходження", adhKopyala: "Копіювати", adhKopyalandi: "Адресу скопійовано",
    adhSilOnay: "Видалити цей заклад?", adhTelefon: "Телефон (необов’язково)", adhYaziDuzenle: "Редагувати текст", adhYeni: "Очистити / шукати знову",
    adhYeniYer: "Додати нове місце", adhYerAdi: "Назва місця (напр.: Магазин Ахмет)", adhYerEkle: "Додати моє місце", adhYerel: "Місцевою мовою",
  },
  es: {
    cyBaslat: "Iniciar directo", cyBosYazi: "Aún no hay vídeos cortos. ¡Comparte el primero!", cyCanli: "EN DIRECTO",
    cyHeroAlt: "Emite en directo desde tu móvil, que todos te vean al instante.", cyKisaVideolar: "Vídeos cortos", cyVideoPaylas: "Compartir vídeo",
    cyYakinda: "Se está creando un servicio de directos propio (vídeo en tiempo real y sin cortes para los espectadores). Cuando esté listo, emitirás desde aquí con un toque. Por ahora, mira los vídeos cortos de abajo y comparte el tuyo.",
    cyYakindaBas: "¡Los directos reales llegan muy pronto!",
    knhAcHaritaSen: "Verte a ti y a amigos cercanos — toca", knhAra: "Buscar lugar, dirección, local…", knhAraba: "Coche", knhArkadas: "Amigo",
    knhArkadasHaritada: "amigos en el mapa — toca", knhArkadasVar: "amigos en el mapa", knhArkadasYok: "No hay amigos cerca", knhBisiklet: "Bici",
    knhBosArkadas: "Las personas que abran la app y compartan su ubicación — lejos o cerca — aparecerán aquí con su foto y a cuántos km están de ti.",
    knhBul: "Buscar", knhDk: "min", knhEnYakin: "Más cercano", knhHepsiniGoster: "Mostrar todos", knhKonumum: "Centrar", knhMesaj: "Mensaje",
    knhNeKadarUzak: "A qué distancia", knhPaylasimAcik: "Mi ubicación está activa", knhPaylasimKapali: "Mi ubicación está desactivada", knhPusula: "Norte", knhRotaHesap: "Trazando ruta…",
    knhSaat: "h", knhSen: "Tú", knhSenBurada: "Estás aquí 🙂", knhSonucYok: "Sin resultados.", knhUzak: "Alejar", knhUzakta: "de distancia",
    knhYakin: "Acercar", knhYolTarifi: "Cómo llegar", knhYukleniyor: "Cargando mapa…", knhYurume: "A pie",
    adhAc: "Toca para encontrar tu dirección", adhAraYaz: "Escribe una dirección/local para buscar…", adhAraniyor: "Buscando dirección…", adhBaslik: "Encontrar y copiar dirección",
    adhDokun: "Toca un lugar/local o busca arriba", adhEkleDokun: "Toca en el mapa el punto exacto de tu negocio/local", adhEkleyen: "Añadido por", adhEn: "Inglés",
    adhFotoEkle: "Añadir foto", adhGiris: "Debes iniciar sesión para añadir un local.", adhHakkinda: "Acerca de (opcional) — qué vendes, horario…",
    adhKaydOlmadi: "No se pudo guardar, inténtalo de nuevo.", adhKonumum: "Encontrar mi ubicación", adhKopyala: "Copiar", adhKopyalandi: "Dirección copiada",
    adhSilOnay: "¿Quieres eliminar este local?", adhTelefon: "Teléfono (opcional)", adhYaziDuzenle: "Editar texto", adhYeni: "Borrar / buscar de nuevo",
    adhYeniYer: "Añadir nuevo lugar", adhYerAdi: "Nombre del lugar (ej.: Mercado Ahmet)", adhYerEkle: "Añadir mi lugar", adhYerel: "En el idioma local",
  },
  fr: {
    cyBaslat: "Démarrer le direct", cyBosYazi: "Pas encore de vidéos courtes. Partage la première !", cyCanli: "EN DIRECT",
    cyHeroAlt: "Passe en direct depuis ton téléphone, que tout le monde te regarde en temps réel.", cyKisaVideolar: "Vidéos courtes", cyVideoPaylas: "Partager une vidéo",
    cyYakinda: "Un service de direct dédié est en cours de création (vidéo en temps réel et sans coupure pour les spectateurs). Dès qu'il sera prêt, tu passeras en direct d'ici d'un seul geste. Pour l'instant, regarde les vidéos courtes ci-dessous et partage la tienne.",
    cyYakindaBas: "Le vrai direct arrive très bientôt !",
    knhAcHaritaSen: "Vois-toi et tes amis à proximité — touche", knhAra: "Chercher lieu, adresse, endroit…", knhAraba: "Voiture", knhArkadas: "Ami",
    knhArkadasHaritada: "amis sur la carte — touche", knhArkadasVar: "amis sur la carte", knhArkadasYok: "Aucun ami à proximité", knhBisiklet: "Vélo",
    knhBosArkadas: "Les personnes qui ouvrent l'appli et partagent leur position — loin ou près — apparaîtront ici avec leur photo et la distance en km jusqu'à toi.",
    knhBul: "Trouver", knhDk: "min", knhEnYakin: "Le plus proche", knhHepsiniGoster: "Tout afficher", knhKonumum: "Centrer", knhMesaj: "Message",
    knhNeKadarUzak: "À quelle distance", knhPaylasimAcik: "Ma position est activée", knhPaylasimKapali: "Ma position est désactivée", knhPusula: "Nord", knhRotaHesap: "Tracé de l'itinéraire…",
    knhSaat: "h", knhSen: "Toi", knhSenBurada: "Tu es ici 🙂", knhSonucYok: "Aucun résultat.", knhUzak: "Dézoomer", knhUzakta: "de distance",
    knhYakin: "Zoomer", knhYolTarifi: "Itinéraire", knhYukleniyor: "Chargement de la carte…", knhYurume: "À pied",
    adhAc: "Touche pour trouver ton adresse", adhAraYaz: "Saisis une adresse/un lieu à chercher…", adhAraniyor: "Recherche de l'adresse…", adhBaslik: "Trouver et copier l'adresse",
    adhDokun: "Touche un lieu/endroit ou cherche ci-dessus", adhEkleDokun: "Touche l'emplacement exact de ton commerce/lieu sur la carte", adhEkleyen: "Ajouté par", adhEn: "Anglais",
    adhFotoEkle: "Ajouter une photo", adhGiris: "Tu dois te connecter pour ajouter un lieu.", adhHakkinda: "À propos (facultatif) — ce que tu vends, horaires…",
    adhKaydOlmadi: "Échec de l'enregistrement, réessaie.", adhKonumum: "Trouver ma position", adhKopyala: "Copier", adhKopyalandi: "Adresse copiée",
    adhSilOnay: "Veux-tu supprimer ce lieu ?", adhTelefon: "Téléphone (facultatif)", adhYaziDuzenle: "Modifier le texte", adhYeni: "Effacer / rechercher à nouveau",
    adhYeniYer: "Ajouter un nouveau lieu", adhYerAdi: "Nom du lieu (ex. : Marché Ahmet)", adhYerEkle: "Ajouter mon lieu", adhYerel: "Dans la langue locale",
  },
  it: {
    cyBaslat: "Avvia diretta", cyBosYazi: "Ancora nessun video breve. Condividi il primo!", cyCanli: "IN DIRETTA",
    cyHeroAlt: "Vai in diretta dal telefono, tutti ti guardano in tempo reale.", cyKisaVideolar: "Video brevi", cyVideoPaylas: "Condividi video",
    cyYakinda: "Stiamo creando un servizio di dirette dedicato (video in tempo reale e senza interruzioni per gli spettatori). Quando sarà pronto, andrai in diretta da qui con un tocco. Per ora guarda i video brevi qui sotto e condividi il tuo.",
    cyYakindaBas: "Le vere dirette arrivano prestissimo!",
    knhAcHaritaSen: "Vedi te e gli amici vicini — tocca", knhAra: "Cerca luogo, indirizzo, locale…", knhAraba: "Auto", knhArkadas: "Amico",
    knhArkadasHaritada: "amici sulla mappa — tocca", knhArkadasVar: "amici sulla mappa", knhArkadasYok: "Nessun amico nelle vicinanze", knhBisiklet: "Bici",
    knhBosArkadas: "Le persone che aprono l'app e condividono la posizione — lontane o vicine — appariranno qui con la foto e la distanza in km da te.",
    knhBul: "Trova", knhDk: "min", knhEnYakin: "Più vicino", knhHepsiniGoster: "Mostra tutti", knhKonumum: "Centra", knhMesaj: "Messaggio",
    knhNeKadarUzak: "Quanto lontano", knhPaylasimAcik: "La mia posizione è attiva", knhPaylasimKapali: "La mia posizione è disattivata", knhPusula: "Nord", knhRotaHesap: "Traccio il percorso…",
    knhSaat: "h", knhSen: "Tu", knhSenBurada: "Sei qui 🙂", knhSonucYok: "Nessun risultato.", knhUzak: "Riduci", knhUzakta: "di distanza",
    knhYakin: "Ingrandisci", knhYolTarifi: "Indicazioni", knhYukleniyor: "Caricamento mappa…", knhYurume: "A piedi",
    adhAc: "Tocca per trovare il tuo indirizzo", adhAraYaz: "Digita un indirizzo/locale da cercare…", adhAraniyor: "Ricerca indirizzo…", adhBaslik: "Trova e copia indirizzo",
    adhDokun: "Tocca un luogo/locale o cerca sopra", adhEkleDokun: "Tocca sulla mappa il punto esatto della tua attività/locale", adhEkleyen: "Aggiunto da", adhEn: "Inglese",
    adhFotoEkle: "Aggiungi foto", adhGiris: "Devi accedere per aggiungere un locale.", adhHakkinda: "Informazioni (facoltativo) — cosa vendi, orari…",
    adhKaydOlmadi: "Impossibile salvare, riprova.", adhKonumum: "Trova la mia posizione", adhKopyala: "Copia", adhKopyalandi: "Indirizzo copiato",
    adhSilOnay: "Vuoi eliminare questo locale?", adhTelefon: "Telefono (facoltativo)", adhYaziDuzenle: "Modifica testo", adhYeni: "Cancella / cerca di nuovo",
    adhYeniYer: "Aggiungi nuovo luogo", adhYerAdi: "Nome del luogo (es.: Market Ahmet)", adhYerEkle: "Aggiungi il mio luogo", adhYerel: "Nella lingua locale",
  },
  pt: {
    cyBaslat: "Iniciar transmissão", cyBosYazi: "Ainda não há vídeos curtos. Partilha o primeiro!", cyCanli: "AO VIVO",
    cyHeroAlt: "Transmite ao vivo do teu telemóvel, que todos te vejam em tempo real.", cyKisaVideolar: "Vídeos curtos", cyVideoPaylas: "Partilhar vídeo",
    cyYakinda: "Está a ser criado um serviço de transmissão ao vivo próprio (vídeo em tempo real e sem interrupções para os espectadores). Quando estiver pronto, ficarás ao vivo daqui com um toque. Por agora, vê os vídeos curtos abaixo e partilha o teu.",
    cyYakindaBas: "As transmissões ao vivo reais chegam muito em breve!",
    knhAcHaritaSen: "Vê-te a ti e aos amigos por perto — toca", knhAra: "Procurar local, endereço, estabelecimento…", knhAraba: "Carro", knhArkadas: "Amigo",
    knhArkadasHaritada: "amigos no mapa — toca", knhArkadasVar: "amigos no mapa", knhArkadasYok: "Sem amigos por perto", knhBisiklet: "Bicicleta",
    knhBosArkadas: "As pessoas que abrem a app e partilham a localização — longe ou perto — aparecerão aqui com a foto e a distância em km até ti.",
    knhBul: "Encontrar", knhDk: "min", knhEnYakin: "Mais próximo", knhHepsiniGoster: "Mostrar todos", knhKonumum: "Centrar", knhMesaj: "Mensagem",
    knhNeKadarUzak: "A que distância", knhPaylasimAcik: "A minha localização está ativa", knhPaylasimKapali: "A minha localização está desativada", knhPusula: "Norte", knhRotaHesap: "A traçar rota…",
    knhSaat: "h", knhSen: "Tu", knhSenBurada: "Estás aqui 🙂", knhSonucYok: "Sem resultados.", knhUzak: "Afastar", knhUzakta: "de distância",
    knhYakin: "Aproximar", knhYolTarifi: "Direções", knhYukleniyor: "A carregar o mapa…", knhYurume: "A pé",
    adhAc: "Toca para encontrar o teu endereço", adhAraYaz: "Escreve um endereço/estabelecimento para procurar…", adhAraniyor: "A procurar endereço…", adhBaslik: "Encontrar e copiar endereço",
    adhDokun: "Toca num local/estabelecimento ou procura acima", adhEkleDokun: "Toca no ponto exato do teu negócio/local no mapa", adhEkleyen: "Adicionado por", adhEn: "Inglês",
    adhFotoEkle: "Adicionar foto", adhGiris: "Tens de iniciar sessão para adicionar um local.", adhHakkinda: "Sobre (opcional) — o que vendes, horário…",
    adhKaydOlmadi: "Não foi possível guardar, tenta de novo.", adhKonumum: "Encontrar a minha localização", adhKopyala: "Copiar", adhKopyalandi: "Endereço copiado",
    adhSilOnay: "Queres eliminar este local?", adhTelefon: "Telefone (opcional)", adhYaziDuzenle: "Editar texto", adhYeni: "Limpar / procurar de novo",
    adhYeniYer: "Adicionar novo local", adhYerAdi: "Nome do local (ex.: Mercado Ahmet)", adhYerEkle: "Adicionar o meu local", adhYerel: "No idioma local",
  },
  ar: {
    cyBaslat: "ابدأ البث المباشر", cyBosYazi: "لا توجد مقاطع قصيرة بعد. كن أول من يشارك!", cyCanli: "بث مباشر",
    cyHeroAlt: "ابدأ البث من هاتفك ليشاهدك الجميع لحظيًا.", cyKisaVideolar: "مقاطع قصيرة", cyVideoPaylas: "شارك فيديو",
    cyYakinda: "يجري إنشاء خدمة بث مباشر خاصة (فيديو لحظي متواصل للمشاهدين). بمجرد جهوزها ستبدأ البث من هنا بلمسة واحدة. في الوقت الحالي شاهد المقاطع القصيرة أدناه وشارك مقطعك.",
    cyYakindaBas: "البث المباشر الحقيقي قريب جدًا!",
    knhAcHaritaSen: "شاهد نفسك والأصدقاء القريبين — المس", knhAra: "ابحث عن مكان أو عنوان أو محل…", knhAraba: "سيارة", knhArkadas: "صديق",
    knhArkadasHaritada: "أصدقاء على الخريطة — المس", knhArkadasVar: "أصدقاء على الخريطة", knhArkadasYok: "لا يوجد أصدقاء بالقرب", knhBisiklet: "دراجة",
    knhBosArkadas: "الأشخاص الذين يفتحون التطبيق ويشاركون موقعهم — بعيدًا أو قريبًا — سيظهرون هنا بصورهم وكم كيلومترًا يبعدون عنك.",
    knhBul: "ابحث", knhDk: "د", knhEnYakin: "الأقرب", knhHepsiniGoster: "عرض الكل", knhKonumum: "توسيط", knhMesaj: "رسالة",
    knhNeKadarUzak: "كم المسافة", knhPaylasimAcik: "موقعي مفعّل", knhPaylasimKapali: "موقعي متوقف", knhPusula: "الشمال", knhRotaHesap: "يجري رسم المسار…",
    knhSaat: "س", knhSen: "أنت", knhSenBurada: "أنت هنا 🙂", knhSonucYok: "لا توجد نتائج.", knhUzak: "تصغير", knhUzakta: "بعيدًا",
    knhYakin: "تكبير", knhYolTarifi: "الاتجاهات", knhYukleniyor: "جارٍ تحميل الخريطة…", knhYurume: "مشيًا",
    adhAc: "المس لمعرفة عنوانك", adhAraYaz: "اكتب عنوانًا/محلًا للبحث…", adhAraniyor: "جارٍ البحث عن العنوان…", adhBaslik: "ابحث عن العنوان وانسخه",
    adhDokun: "المس مكانًا/محلًا أو ابحث في الأعلى", adhEkleDokun: "المس الموقع الدقيق لعملك/مكانك على الخريطة", adhEkleyen: "أضافه", adhEn: "الإنجليزية",
    adhFotoEkle: "أضف صورة", adhGiris: "يجب تسجيل الدخول لإضافة مكان.", adhHakkinda: "نبذة (اختياري) — ماذا تبيع، ساعات العمل…",
    adhKaydOlmadi: "تعذّر الحفظ، حاول مرة أخرى.", adhKonumum: "ابحث عن موقعي", adhKopyala: "نسخ", adhKopyalandi: "تم نسخ العنوان",
    adhSilOnay: "هل تريد حذف هذا المكان؟", adhTelefon: "الهاتف (اختياري)", adhYaziDuzenle: "تحرير النص", adhYeni: "مسح / ابحث من جديد",
    adhYeniYer: "إضافة مكان جديد", adhYerAdi: "اسم المكان (مثال: بقالة أحمد)", adhYerEkle: "أضف مكاني", adhYerel: "باللغة المحلية",
  },
  zh: {
    cyBaslat: "开始直播", cyBosYazi: "还没有短视频。来分享第一个吧！", cyCanli: "直播",
    cyHeroAlt: "用手机开直播，让大家实时看你。", cyKisaVideolar: "短视频", cyVideoPaylas: "分享视频",
    cyYakinda: "正在搭建专门的直播服务（为观众提供实时、不间断的视频）。准备好后，你只需一键就能在这里开播。目前先看下面的短视频，分享你自己的吧。",
    cyYakindaBas: "真正的直播很快就来！",
    knhAcHaritaSen: "看看你和附近的好友 — 点按", knhAra: "搜索地点、地址、场所…", knhAraba: "开车", knhArkadas: "好友",
    knhArkadasHaritada: "位好友在地图上 — 点按", knhArkadasVar: "位好友在地图上", knhArkadasYok: "附近没有好友", knhBisiklet: "骑行",
    knhBosArkadas: "打开应用并分享位置的人——无论远近——都会带着照片和距你多少公里显示在这里。",
    knhBul: "查找", knhDk: "分钟", knhEnYakin: "最近", knhHepsiniGoster: "显示全部", knhKonumum: "居中", knhMesaj: "消息",
    knhNeKadarUzak: "多远", knhPaylasimAcik: "我的位置已开启", knhPaylasimKapali: "我的位置已关闭", knhPusula: "北", knhRotaHesap: "正在规划路线…",
    knhSaat: "小时", knhSen: "你", knhSenBurada: "你在这里 🙂", knhSonucYok: "未找到结果。", knhUzak: "缩小", knhUzakta: "远",
    knhYakin: "放大", knhYolTarifi: "路线", knhYukleniyor: "地图加载中…", knhYurume: "步行",
    adhAc: "点按查找你的地址", adhAraYaz: "输入地址/场所来搜索…", adhAraniyor: "正在查找地址…", adhBaslik: "查找并复制地址",
    adhDokun: "点按一个地点/场所或在上方搜索", adhEkleDokun: "在地图上点按你店铺/场所的准确位置", adhEkleyen: "添加者", adhEn: "英语",
    adhFotoEkle: "添加照片", adhGiris: "添加场所需要先登录。", adhHakkinda: "简介（可选）— 你卖什么、营业时间…",
    adhKaydOlmadi: "保存失败，请重试。", adhKonumum: "查找我的位置", adhKopyala: "复制", adhKopyalandi: "地址已复制",
    adhSilOnay: "要删除这个场所吗？", adhTelefon: "电话（可选）", adhYaziDuzenle: "编辑文字", adhYeni: "清除 / 重新搜索",
    adhYeniYer: "添加新地点", adhYerAdi: "地点名称（如：Ahmet 超市）", adhYerEkle: "添加我的地点", adhYerel: "用当地语言",
  },
  hi: {
    cyBaslat: "लाइव शुरू करें", cyBosYazi: "अभी कोई शॉर्ट वीडियो नहीं। पहला आप शेयर करें!", cyCanli: "लाइव",
    cyHeroAlt: "अपने फ़ोन से लाइव जाएँ, सब आपको रियल-टाइम में देखें।", cyKisaVideolar: "शॉर्ट वीडियो", cyVideoPaylas: "वीडियो शेयर करें",
    cyYakinda: "एक समर्पित लाइव-स्ट्रीमिंग सेवा बनाई जा रही है (दर्शकों के लिए रियल-टाइम, बिना रुकावट वीडियो)। तैयार होते ही आप यहाँ से एक टैप में लाइव जाएँगे। फ़िलहाल नीचे के शॉर्ट वीडियो देखें और अपना शेयर करें।",
    cyYakindaBas: "असली लाइव स्ट्रीमिंग बहुत जल्द आ रही है!",
    knhAcHaritaSen: "खुद को और पास के दोस्तों को देखें — टैप करें", knhAra: "जगह, पता, स्थान खोजें…", knhAraba: "कार", knhArkadas: "दोस्त",
    knhArkadasHaritada: "दोस्त मैप पर — टैप करें", knhArkadasVar: "दोस्त मैप पर", knhArkadasYok: "पास में कोई दोस्त नहीं", knhBisiklet: "साइकिल",
    knhBosArkadas: "जो लोग ऐप खोलकर अपनी लोकेशन शेयर करते हैं — दूर या पास — वे यहाँ अपनी फ़ोटो और आपसे कितने किमी दूर हैं, के साथ दिखेंगे।",
    knhBul: "खोजें", knhDk: "मिनट", knhEnYakin: "सबसे पास", knhHepsiniGoster: "सभी दिखाएँ", knhKonumum: "बीच में लाएँ", knhMesaj: "संदेश",
    knhNeKadarUzak: "कितनी दूर", knhPaylasimAcik: "मेरी लोकेशन चालू है", knhPaylasimKapali: "मेरी लोकेशन बंद है", knhPusula: "उत्तर", knhRotaHesap: "रास्ता बन रहा है…",
    knhSaat: "घंटा", knhSen: "आप", knhSenBurada: "आप यहाँ हैं 🙂", knhSonucYok: "कोई परिणाम नहीं मिला।", knhUzak: "ज़ूम आउट", knhUzakta: "दूर",
    knhYakin: "ज़ूम इन", knhYolTarifi: "दिशा-निर्देश", knhYukleniyor: "मैप लोड हो रहा है…", knhYurume: "पैदल",
    adhAc: "अपना पता जानने के लिए टैप करें", adhAraYaz: "खोजने के लिए पता/स्थान लिखें…", adhAraniyor: "पता खोजा जा रहा है…", adhBaslik: "पता खोजें और कॉपी करें",
    adhDokun: "किसी जगह/स्थान पर टैप करें या ऊपर खोजें", adhEkleDokun: "मैप पर अपने कारोबार/जगह का सटीक बिंदु टैप करें", adhEkleyen: "जोड़ने वाला", adhEn: "अंग्रेज़ी",
    adhFotoEkle: "फ़ोटो जोड़ें", adhGiris: "स्थान जोड़ने के लिए साइन इन करना होगा।", adhHakkinda: "बारे में (वैकल्पिक) — आप क्या बेचते हैं, समय…",
    adhKaydOlmadi: "सेव नहीं हुआ, फिर कोशिश करें।", adhKonumum: "मेरी लोकेशन खोजें", adhKopyala: "कॉपी करें", adhKopyalandi: "पता कॉपी हुआ",
    adhSilOnay: "क्या इस स्थान को हटाना है?", adhTelefon: "फ़ोन (वैकल्पिक)", adhYaziDuzenle: "टेक्स्ट संपादित करें", adhYeni: "साफ़ करें / फिर खोजें",
    adhYeniYer: "नई जगह जोड़ें", adhYerAdi: "जगह का नाम (जैसे: Ahmet मार्केट)", adhYerEkle: "मेरी जगह जोड़ें", adhYerel: "स्थानीय भाषा में",
  },
  ja: {
    cyBaslat: "ライブ配信を始める", cyBosYazi: "まだショート動画がありません。最初の一本をシェアしよう！", cyCanli: "ライブ配信",
    cyHeroAlt: "スマホからライブ配信して、みんなにリアルタイムで見てもらおう。", cyKisaVideolar: "ショート動画", cyVideoPaylas: "動画をシェア",
    cyYakinda: "専用のライブ配信サービスを準備中です（視聴者にリアルタイムで途切れない動画）。準備ができたら、ここからワンタップでライブ配信できます。今はまず下のショート動画を見て、あなたの動画もシェアしてください。",
    cyYakindaBas: "本物のライブ配信がまもなく登場！",
    knhAcHaritaSen: "自分と近くの友だちを見る — タップ", knhAra: "場所・住所・お店を検索…", knhAraba: "車", knhArkadas: "友だち",
    knhArkadasHaritada: "人の友だちが地図に — タップ", knhArkadasVar: "人の友だちが地図に", knhArkadasYok: "近くに友だちがいません", knhBisiklet: "自転車",
    knhBosArkadas: "アプリを開いて位置を共有した人が — 遠くても近くても — 写真とあなたまでの距離（km）とともにここに表示されます。",
    knhBul: "探す", knhDk: "分", knhEnYakin: "最も近い", knhHepsiniGoster: "すべて表示", knhKonumum: "中央に", knhMesaj: "メッセージ",
    knhNeKadarUzak: "どのくらい遠い", knhPaylasimAcik: "位置情報オン", knhPaylasimKapali: "位置情報オフ", knhPusula: "北", knhRotaHesap: "ルートを描画中…",
    knhSaat: "時間", knhSen: "あなた", knhSenBurada: "あなたはここ 🙂", knhSonucYok: "結果が見つかりません。", knhUzak: "縮小", knhUzakta: "先",
    knhYakin: "拡大", knhYolTarifi: "ルート案内", knhYukleniyor: "地図を読み込み中…", knhYurume: "徒歩",
    adhAc: "タップして住所を調べる", adhAraYaz: "住所・お店を入力して検索…", adhAraniyor: "住所を検索中…", adhBaslik: "住所を調べてコピー",
    adhDokun: "場所・お店をタップするか上で検索", adhEkleDokun: "地図上であなたの店舗・場所の正確な地点をタップ", adhEkleyen: "追加者", adhEn: "英語",
    adhFotoEkle: "写真を追加", adhGiris: "場所を追加するにはログインが必要です。", adhHakkinda: "紹介（任意）— 何を売っているか、営業時間…",
    adhKaydOlmadi: "保存できませんでした。もう一度お試しください。", adhKonumum: "現在地を探す", adhKopyala: "コピー", adhKopyalandi: "住所をコピーしました",
    adhSilOnay: "この場所を削除しますか？", adhTelefon: "電話（任意）", adhYaziDuzenle: "テキストを編集", adhYeni: "クリア / もう一度検索",
    adhYeniYer: "新しい場所を追加", adhYerAdi: "場所の名前（例：Ahmet マーケット）", adhYerEkle: "自分の場所を追加", adhYerel: "現地の言語で",
  },
};

// Alt menüdeki "Makara" (kısa video) etiketi — eskiden translate="no" ile Türkçe kalıyordu, artık çevriliyor.
export const NAV_MAKARA = {
  tr: "Makara", en: "Reels", de: "Reels", ru: "Ролики", uk: "Ролики", es: "Reels", fr: "Reels",
  it: "Reels", pt: "Reels", ar: "مقاطع", zh: "短视频", hi: "रील्स", ja: "リール",
};
