// GLOXORG — GLOXOO SESİ MENÜSÜ ÇEVİRİLERİ (ses adları, cins, ton/hız etiketleri) — 13 dil.
// Marka "Gloxoo" hiçbir dilde çevrilmez.
export const CEVIRI_GLOXSES = {
  tr: { gsBaslik: "Gloxoo Sesi", gsTon: "Ses Tonu", gsInce: "İnce", gsKalin: "Kalın", gsHiz: "Konuşma Hızı", gsYavas: "Yavaş", gsNormal: "Normal", gsHizli: "Hızlı", cinsKadin: "Kadın", cinsErkek: "Erkek", ses_sicak: "Sıcak", ses_net: "Net", ses_genc: "Genç", ses_berrak: "Berrak", ses_derin: "Derin", ses_neseli: "Neşeli", ses_sakin: "Sakin", ses_guclu: "Güçlü" },
  en: { gsBaslik: "Gloxoo Voice", gsTon: "Voice Tone", gsInce: "Thin", gsKalin: "Deep", gsHiz: "Speech Speed", gsYavas: "Slow", gsNormal: "Normal", gsHizli: "Fast", cinsKadin: "Female", cinsErkek: "Male", ses_sicak: "Warm", ses_net: "Clear", ses_genc: "Young", ses_berrak: "Bright", ses_derin: "Deep", ses_neseli: "Cheerful", ses_sakin: "Calm", ses_guclu: "Strong" },
  de: { gsBaslik: "Gloxoo-Stimme", gsTon: "Stimmton", gsInce: "Hell", gsKalin: "Tief", gsHiz: "Sprechtempo", gsYavas: "Langsam", gsNormal: "Normal", gsHizli: "Schnell", cinsKadin: "Weiblich", cinsErkek: "Männlich", ses_sicak: "Warm", ses_net: "Klar", ses_genc: "Jung", ses_berrak: "Hell", ses_derin: "Tief", ses_neseli: "Fröhlich", ses_sakin: "Ruhig", ses_guclu: "Kräftig" },
  ru: { gsBaslik: "Голос Gloxoo", gsTon: "Тон голоса", gsInce: "Тонкий", gsKalin: "Низкий", gsHiz: "Скорость речи", gsYavas: "Медленно", gsNormal: "Обычно", gsHizli: "Быстро", cinsKadin: "Женский", cinsErkek: "Мужской", ses_sicak: "Тёплый", ses_net: "Чёткий", ses_genc: "Молодой", ses_berrak: "Ясный", ses_derin: "Глубокий", ses_neseli: "Весёлый", ses_sakin: "Спокойный", ses_guclu: "Сильный" },
  uk: { gsBaslik: "Голос Gloxoo", gsTon: "Тон голосу", gsInce: "Тонкий", gsKalin: "Низький", gsHiz: "Швидкість мовлення", gsYavas: "Повільно", gsNormal: "Звичайно", gsHizli: "Швидко", cinsKadin: "Жіночий", cinsErkek: "Чоловічий", ses_sicak: "Теплий", ses_net: "Чіткий", ses_genc: "Молодий", ses_berrak: "Ясний", ses_derin: "Глибокий", ses_neseli: "Веселий", ses_sakin: "Спокійний", ses_guclu: "Сильний" },
  es: { gsBaslik: "Voz de Gloxoo", gsTon: "Tono de voz", gsInce: "Agudo", gsKalin: "Grave", gsHiz: "Velocidad de habla", gsYavas: "Lento", gsNormal: "Normal", gsHizli: "Rápido", cinsKadin: "Femenino", cinsErkek: "Masculino", ses_sicak: "Cálido", ses_net: "Nítido", ses_genc: "Joven", ses_berrak: "Claro", ses_derin: "Profundo", ses_neseli: "Alegre", ses_sakin: "Tranquilo", ses_guclu: "Fuerte" },
  fr: { gsBaslik: "Voix de Gloxoo", gsTon: "Ton de voix", gsInce: "Aigu", gsKalin: "Grave", gsHiz: "Vitesse de parole", gsYavas: "Lent", gsNormal: "Normal", gsHizli: "Rapide", cinsKadin: "Féminin", cinsErkek: "Masculin", ses_sicak: "Chaleureux", ses_net: "Net", ses_genc: "Jeune", ses_berrak: "Clair", ses_derin: "Profond", ses_neseli: "Joyeux", ses_sakin: "Calme", ses_guclu: "Fort" },
  it: { gsBaslik: "Voce di Gloxoo", gsTon: "Tono di voce", gsInce: "Acuto", gsKalin: "Grave", gsHiz: "Velocità del parlato", gsYavas: "Lento", gsNormal: "Normale", gsHizli: "Veloce", cinsKadin: "Femminile", cinsErkek: "Maschile", ses_sicak: "Caldo", ses_net: "Nitido", ses_genc: "Giovane", ses_berrak: "Chiaro", ses_derin: "Profondo", ses_neseli: "Allegro", ses_sakin: "Calmo", ses_guclu: "Forte" },
  pt: { gsBaslik: "Voz do Gloxoo", gsTon: "Tom de voz", gsInce: "Agudo", gsKalin: "Grave", gsHiz: "Velocidade da fala", gsYavas: "Lento", gsNormal: "Normal", gsHizli: "Rápido", cinsKadin: "Feminino", cinsErkek: "Masculino", ses_sicak: "Caloroso", ses_net: "Nítido", ses_genc: "Jovem", ses_berrak: "Claro", ses_derin: "Profundo", ses_neseli: "Alegre", ses_sakin: "Calmo", ses_guclu: "Forte" },
  ar: { gsBaslik: "صوت Gloxoo", gsTon: "نبرة الصوت", gsInce: "حاد", gsKalin: "عميق", gsHiz: "سرعة الكلام", gsYavas: "بطيء", gsNormal: "عادي", gsHizli: "سريع", cinsKadin: "أنثى", cinsErkek: "ذكر", ses_sicak: "دافئ", ses_net: "واضح", ses_genc: "شاب", ses_berrak: "صافٍ", ses_derin: "عميق", ses_neseli: "مرح", ses_sakin: "هادئ", ses_guclu: "قوي" },
  hi: { gsBaslik: "Gloxoo आवाज़", gsTon: "आवाज़ का सुर", gsInce: "पतला", gsKalin: "गहरा", gsHiz: "बोलने की गति", gsYavas: "धीमा", gsNormal: "सामान्य", gsHizli: "तेज़", cinsKadin: "महिला", cinsErkek: "पुरुष", ses_sicak: "गर्म", ses_net: "स्पष्ट", ses_genc: "युवा", ses_berrak: "उजला", ses_derin: "गहरा", ses_neseli: "खुशमिज़ाज", ses_sakin: "शांत", ses_guclu: "मज़बूत" },
  zh: { gsBaslik: "Gloxoo 声音", gsTon: "音调", gsInce: "尖细", gsKalin: "低沉", gsHiz: "语速", gsYavas: "慢", gsNormal: "正常", gsHizli: "快", cinsKadin: "女声", cinsErkek: "男声", ses_sicak: "温暖", ses_net: "清晰", ses_genc: "年轻", ses_berrak: "明亮", ses_derin: "低沉", ses_neseli: "欢快", ses_sakin: "平静", ses_guclu: "有力" },
  ja: { gsBaslik: "Gloxooの声", gsTon: "声のトーン", gsInce: "高い", gsKalin: "低い", gsHiz: "話す速さ", gsYavas: "遅い", gsNormal: "普通", gsHizli: "速い", cinsKadin: "女性", cinsErkek: "男性", ses_sicak: "温かい", ses_net: "クリア", ses_genc: "若い", ses_berrak: "明るい", ses_derin: "深い", ses_neseli: "陽気", ses_sakin: "穏やか", ses_guclu: "力強い" },
};
