// GLOXORG — Bildirim metinleri ({{ad}}/{{metin}} korunur) + yazı tipi etiketleri 13 dil (B125).
export const AYAR_CEVIRI7 = {
  tr: { bildBegeni:"{{ad}} gönderini beğendi", bildYorum:"{{ad}} yorum yaptı: {{metin}}", bildMesaj:"{{ad}} sana mesaj gönderdi", bildTakip:"{{ad}} seni takip etmeye başladı", ytZarif:"Zarif", ytModern:"Modern", ytDar:"Dar", ytTabela:"Tabela", ytKalin:"Kalın", ytSik:"Şık", ytTatli:"Tatlı", ytElYazisi:"El Yazısı", ytZarifEl:"Zarif El", ytRetro:"Retro" },
  en: { bildBegeni:"{{ad}} liked your post", bildYorum:"{{ad}} commented: {{metin}}", bildMesaj:"{{ad}} sent you a message", bildTakip:"{{ad}} started following you", ytZarif:"Elegant", ytModern:"Modern", ytDar:"Condensed", ytTabela:"Display", ytKalin:"Bold", ytSik:"Stylish", ytTatli:"Playful", ytElYazisi:"Handwriting", ytZarifEl:"Script", ytRetro:"Retro" },
  de: { bildBegeni:"{{ad}} gefällt dein Beitrag", bildYorum:"{{ad}} hat kommentiert: {{metin}}", bildMesaj:"{{ad}} hat dir eine Nachricht gesendet", bildTakip:"{{ad}} folgt dir jetzt", ytZarif:"Elegant", ytModern:"Modern", ytDar:"Schmal", ytTabela:"Display", ytKalin:"Fett", ytSik:"Stilvoll", ytTatli:"Verspielt", ytElYazisi:"Handschrift", ytZarifEl:"Schreibschrift", ytRetro:"Retro" },
  fr: { bildBegeni:"{{ad}} a aimé votre publication", bildYorum:"{{ad}} a commenté : {{metin}}", bildMesaj:"{{ad}} vous a envoyé un message", bildTakip:"{{ad}} a commencé à vous suivre", ytZarif:"Élégant", ytModern:"Moderne", ytDar:"Étroit", ytTabela:"Display", ytKalin:"Gras", ytSik:"Chic", ytTatli:"Ludique", ytElYazisi:"Manuscrit", ytZarifEl:"Script", ytRetro:"Rétro" },
  es: { bildBegeni:"a {{ad}} le gustó tu publicación", bildYorum:"{{ad}} comentó: {{metin}}", bildMesaj:"{{ad}} te envió un mensaje", bildTakip:"{{ad}} empezó a seguirte", ytZarif:"Elegante", ytModern:"Moderno", ytDar:"Estrecho", ytTabela:"Display", ytKalin:"Negrita", ytSik:"Chic", ytTatli:"Divertido", ytElYazisi:"Manuscrito", ytZarifEl:"Cursiva", ytRetro:"Retro" },
  it: { bildBegeni:"a {{ad}} piace il tuo post", bildYorum:"{{ad}} ha commentato: {{metin}}", bildMesaj:"{{ad}} ti ha inviato un messaggio", bildTakip:"{{ad}} ha iniziato a seguirti", ytZarif:"Elegante", ytModern:"Moderno", ytDar:"Stretto", ytTabela:"Display", ytKalin:"Grassetto", ytSik:"Chic", ytTatli:"Giocoso", ytElYazisi:"Corsivo", ytZarifEl:"Script", ytRetro:"Retro" },
  pt: { bildBegeni:"{{ad}} curtiu sua publicação", bildYorum:"{{ad}} comentou: {{metin}}", bildMesaj:"{{ad}} te enviou uma mensagem", bildTakip:"{{ad}} começou a te seguir", ytZarif:"Elegante", ytModern:"Moderno", ytDar:"Estreito", ytTabela:"Display", ytKalin:"Negrito", ytSik:"Chique", ytTatli:"Divertido", ytElYazisi:"Manuscrito", ytZarifEl:"Cursiva", ytRetro:"Retrô" },
  ru: { bildBegeni:"{{ad}} оценил(а) вашу публикацию", bildYorum:"{{ad}} прокомментировал(а): {{metin}}", bildMesaj:"{{ad}} отправил(а) вам сообщение", bildTakip:"{{ad}} подписал(ся/ась) на вас", ytZarif:"Элегантный", ytModern:"Современный", ytDar:"Узкий", ytTabela:"Дисплейный", ytKalin:"Жирный", ytSik:"Стильный", ytTatli:"Игривый", ytElYazisi:"Рукописный", ytZarifEl:"Каллиграфия", ytRetro:"Ретро" },
  uk: { bildBegeni:"{{ad}} вподобав(ла) вашу публікацію", bildYorum:"{{ad}} прокоментував(ла): {{metin}}", bildMesaj:"{{ad}} надіслав(ла) вам повідомлення", bildTakip:"{{ad}} підписав(ся/лась) на вас", ytZarif:"Елегантний", ytModern:"Сучасний", ytDar:"Вузький", ytTabela:"Дисплейний", ytKalin:"Жирний", ytSik:"Стильний", ytTatli:"Грайливий", ytElYazisi:"Рукописний", ytZarifEl:"Каліграфія", ytRetro:"Ретро" },
  ar: { bildBegeni:"أعجب {{ad}} بمنشورك", bildYorum:"علّق {{ad}}: {{metin}}", bildMesaj:"أرسل لك {{ad}} رسالة", bildTakip:"بدأ {{ad}} بمتابعتك", ytZarif:"أنيق", ytModern:"عصري", ytDar:"ضيّق", ytTabela:"عرض", ytKalin:"عريض", ytSik:"شيك", ytTatli:"مرح", ytElYazisi:"خط اليد", ytZarifEl:"خط متصل", ytRetro:"ريترو" },
  zh: { bildBegeni:"{{ad}} 赞了你的帖子", bildYorum:"{{ad}} 评论道：{{metin}}", bildMesaj:"{{ad}} 给你发了消息", bildTakip:"{{ad}} 开始关注你", ytZarif:"优雅", ytModern:"现代", ytDar:"窄体", ytTabela:"展示", ytKalin:"粗体", ytSik:"时尚", ytTatli:"俏皮", ytElYazisi:"手写", ytZarifEl:"花体", ytRetro:"复古" },
  ja: { bildBegeni:"{{ad}}さんがあなたの投稿にいいねしました", bildYorum:"{{ad}}さんがコメントしました：{{metin}}", bildMesaj:"{{ad}}さんがメッセージを送りました", bildTakip:"{{ad}}さんがあなたをフォローしました", ytZarif:"エレガント", ytModern:"モダン", ytDar:"細身", ytTabela:"ディスプレイ", ytKalin:"太字", ytSik:"シック", ytTatli:"かわいい", ytElYazisi:"手書き", ytZarifEl:"筆記体", ytRetro:"レトロ" },
  hi: { bildBegeni:"{{ad}} ने आपकी पोस्ट पसंद की", bildYorum:"{{ad}} ने टिप्पणी की: {{metin}}", bildMesaj:"{{ad}} ने आपको संदेश भेजा", bildTakip:"{{ad}} ने आपको फ़ॉलो करना शुरू किया", ytZarif:"सुरुचिपूर्ण", ytModern:"आधुनिक", ytDar:"संकरा", ytTabela:"डिस्प्ले", ytKalin:"मोटा", ytSik:"स्टाइलिश", ytTatli:"चंचल", ytElYazisi:"हस्तलेख", ytZarifEl:"सुलेख", ytRetro:"रेट्रो" },
};
