// GLOXORG — AKADEMİ sayfası çevirileri (13 dil). i18n.js'te resources'a eklenir.
// Not: "GLOXORG" marka adı çevrilmez. AI ile üretilen ders/çeşit içeriği zaten kullanıcının dilinde gelir.
export const CEVIRI_AKADEMI = {
  tr: {
    akAkademi: "AKADEMİ", akAra: "Meslek ara…", akBaslik: "GLOXORG Akademi", akBitir: "Sınavı bitir", akBitti: "Anlatım tamamlandı",
    akCesitAlt2: "Bir çeşide dokun; Gloxoo onu ölçüsü ve adım adım yapılışıyla anlatır. Listede yoksa aşağıya kendin yaz, Gloxoo onu da anlatır.",
    akCesitGetir: "Çeşitleri getir", akCesitOlmadi: "Alınamadı.", akCesitYuk: "Çeşitler getiriliyor…", akCesitler: "Çeşitler — hepsi tek tek",
    akDersOlmadi: "Eğitim şu an alınamadı, tekrar dene.", akEgitimAl: "Eğitimi başlat", akFoto: "Foto", akFotoEkle: "Foto ekle", akGecti: "Geçtin!",
    akGorselHazir2: "Fotoğraf hazırlanıyor…", akHazirliyor2: "Gloxoo eğitimi hazırlıyor", akHenuzYok: "Henüz sertifikan yok. Bir eğitim al, sınavı geç, işini göster!",
    akHeroAlt: "Her meslek için eğitim al, çeşitleri tek tek öğren, Gloxoo sınavını geç, işini göster — doğrulanabilir sertifikanı kazan.",
    akIsAlt: "Kendi yaptığın işi foto ve/veya video ile yükle — sertifikanda kanıt olarak kalır.", akIsGoster: "Yaptığın işi göster",
    akKaldi: "Geçemedin", akKaydOlmadi: "Sertifika oluşturulamadı, tekrar dene.", akKod: "Doğrulama kodu",
    akKonuAraYer: "Başka bir çeşit/model yaz (örn. dünyadan bir ekmek)…", akKonuOlmadi: "Şu an alınamadı, tekrar dene.", akKonuYuk3: "Gloxoo tarifi hazırlıyor",
    akOnceIs: "Önce yaptığın işi foto ya da video ile göster.", akOnceSinav: "Önce sınavı geç.", akPuan: "Sınav", akSertifika: "SERTİFİKA",
    akSertifikalarim: "Sertifikalarım", akSertifikamiAl: "Sertifikamı al", akSinav: "Sınav (ciddi)",
    akSinavAlt: "Gerçek mesleki sorular. Sertifika için en az %70 gerekir.", akSinavOlmadi: "Sınav alınamadı, tekrar dene.", akSinavaGir: "Sınava gir",
    akSor: "Sor", akSorular: "Sorular hazırlanıyor…", akSrtNot: "Bu bir GLOXORG Akademi belgesidir. Kod ile doğrulanabilir.", akSertifikayiIndir: "Sertifikayı indir", akPaylas: "Paylaş", akHazirlaniyor: "Hazırlanıyor…", akIndirildi: "İndirildi", akSrtOlmadi: "Sertifika resmi hazırlanamadı, tekrar dene.",
    akTamamladi: "eğitimini başarıyla tamamladı", akTekrarSinav: "Tekrar dene", akTemelAlt: "Gloxoo bu meslek hakkında genel bilgiyi öğretir.",
    akTemelEgitim: "Temel Eğitim", akVideo: "Video", akVideoEkle: "Video ekle",
    akSesliAnlat: "Sesli anlat", akDurdur: "Durdur", akKopyala: "Kopyala", akKopyalandi: "Kopyalandı", akIndir: "İndir", akPaylas: "Paylaş",
  },
  en: {
    akAkademi: "ACADEMY", akAra: "Search profession…", akBaslik: "GLOXORG Academy", akBitir: "Finish exam", akBitti: "Explanation complete",
    akCesitAlt2: "Tap a variety; Gloxoo explains it with measurements, step by step. Not listed? Type it below and Gloxoo will explain it too.",
    akCesitGetir: "Load varieties", akCesitOlmadi: "Couldn't load.", akCesitYuk: "Loading varieties…", akCesitler: "Varieties — one by one",
    akDersOlmadi: "Couldn't load the lesson now, try again.", akEgitimAl: "Start training", akFoto: "Photo", akFotoEkle: "Add photo", akGecti: "You passed!",
    akGorselHazir2: "Preparing photo…", akHazirliyor2: "Gloxoo is preparing the lesson", akHenuzYok: "No certificate yet. Take a course, pass the exam, show your work!",
    akHeroAlt: "Get training for every profession, learn each variety, pass Gloxoo's exam, show your work — earn your verifiable certificate.",
    akIsAlt: "Upload your own work as a photo and/or video — it stays as proof on your certificate.", akIsGoster: "Show your work",
    akKaldi: "You didn't pass", akKaydOlmadi: "Couldn't create the certificate, try again.", akKod: "Verification code",
    akKonuAraYer: "Type another variety/model (e.g. a bread from the world)…", akKonuOlmadi: "Couldn't load now, try again.", akKonuYuk3: "Gloxoo is preparing the recipe",
    akOnceIs: "First show your work with a photo or video.", akOnceSinav: "Pass the exam first.", akPuan: "Exam", akSertifika: "CERTIFICATE",
    akSertifikalarim: "My Certificates", akSertifikamiAl: "Get my certificate", akSinav: "Exam (serious)",
    akSinavAlt: "Real professional questions. At least 70% is required for the certificate.", akSinavOlmadi: "Couldn't load the exam, try again.", akSinavaGir: "Take the exam",
    akSor: "Ask", akSorular: "Preparing questions…", akSrtNot: "This is a GLOXORG Academy document. It can be verified by code.", akSertifikayiIndir: "Download certificate", akPaylas: "Share", akHazirlaniyor: "Preparing…", akIndirildi: "Downloaded", akSrtOlmadi: "Could not create the certificate image, try again.",
    akTamamladi: "successfully completed this training", akTekrarSinav: "Try again", akTemelAlt: "Gloxoo teaches general knowledge about this profession.",
    akTemelEgitim: "Basic Training", akVideo: "Video", akVideoEkle: "Add video",
    akSesliAnlat: "Read aloud", akDurdur: "Stop", akKopyala: "Copy", akKopyalandi: "Copied", akIndir: "Download", akPaylas: "Share",
  },
  de: {
    akAkademi: "AKADEMIE", akAra: "Beruf suchen…", akBaslik: "GLOXORG Akademie", akBitir: "Prüfung beenden", akBitti: "Erklärung abgeschlossen",
    akCesitAlt2: "Tippe auf eine Sorte; Gloxoo erklärt sie mit Mengen, Schritt für Schritt. Nicht dabei? Schreib sie unten, Gloxoo erklärt sie auch.",
    akCesitGetir: "Sorten laden", akCesitOlmadi: "Konnte nicht geladen werden.", akCesitYuk: "Sorten werden geladen…", akCesitler: "Sorten — einzeln",
    akDersOlmadi: "Lektion konnte gerade nicht geladen werden, versuche es erneut.", akEgitimAl: "Schulung starten", akFoto: "Foto", akFotoEkle: "Foto hinzufügen", akGecti: "Bestanden!",
    akGorselHazir2: "Foto wird vorbereitet…", akHazirliyor2: "Gloxoo bereitet die Lektion vor", akHenuzYok: "Noch kein Zertifikat. Mach eine Schulung, bestehe die Prüfung, zeige deine Arbeit!",
    akHeroAlt: "Lass dich für jeden Beruf schulen, lerne jede Sorte, bestehe Gloxoos Prüfung, zeige deine Arbeit — verdiene dein überprüfbares Zertifikat.",
    akIsAlt: "Lade deine eigene Arbeit als Foto und/oder Video hoch — sie bleibt als Nachweis in deinem Zertifikat.", akIsGoster: "Zeige deine Arbeit",
    akKaldi: "Nicht bestanden", akKaydOlmadi: "Zertifikat konnte nicht erstellt werden, versuche es erneut.", akKod: "Prüfcode",
    akKonuAraYer: "Schreibe eine andere Sorte/Modell (z. B. ein Brot aus der Welt)…", akKonuOlmadi: "Konnte gerade nicht geladen werden, versuche es erneut.", akKonuYuk3: "Gloxoo bereitet das Rezept vor",
    akOnceIs: "Zeige zuerst deine Arbeit mit Foto oder Video.", akOnceSinav: "Bestehe zuerst die Prüfung.", akPuan: "Prüfung", akSertifika: "ZERTIFIKAT",
    akSertifikalarim: "Meine Zertifikate", akSertifikamiAl: "Mein Zertifikat erhalten", akSinav: "Prüfung (ernst)",
    akSinavAlt: "Echte fachliche Fragen. Für das Zertifikat sind mindestens 70 % nötig.", akSinavOlmadi: "Prüfung konnte nicht geladen werden, versuche es erneut.", akSinavaGir: "Prüfung starten",
    akSor: "Fragen", akSorular: "Fragen werden vorbereitet…", akSrtNot: "Dies ist ein GLOXORG-Akademie-Dokument. Es kann per Code überprüft werden.", akSertifikayiIndir: "Zertifikat herunterladen", akPaylas: "Teilen", akHazirlaniyor: "Wird vorbereitet…", akIndirildi: "Heruntergeladen", akSrtOlmadi: "Zertifikatsbild konnte nicht erstellt werden, versuch es erneut.",
    akTamamladi: "hat diese Schulung erfolgreich abgeschlossen", akTekrarSinav: "Erneut versuchen", akTemelAlt: "Gloxoo vermittelt allgemeines Wissen über diesen Beruf.",
    akTemelEgitim: "Grundschulung", akVideo: "Video", akVideoEkle: "Video hinzufügen",
    akSesliAnlat: "Vorlesen", akDurdur: "Stopp", akKopyala: "Kopieren", akKopyalandi: "Kopiert", akIndir: "Herunterladen", akPaylas: "Teilen",
  },
  ru: {
    akAkademi: "АКАДЕМИЯ", akAra: "Поиск профессии…", akBaslik: "GLOXORG Академия", akBitir: "Завершить экзамен", akBitti: "Объяснение завершено",
    akCesitAlt2: "Нажмите на вид; Gloxoo объяснит его с мерами, шаг за шагом. Нет в списке? Напишите ниже, Gloxoo тоже объяснит.",
    akCesitGetir: "Загрузить виды", akCesitOlmadi: "Не удалось загрузить.", akCesitYuk: "Загрузка видов…", akCesitler: "Виды — по одному",
    akDersOlmadi: "Не удалось загрузить урок, попробуйте ещё раз.", akEgitimAl: "Начать обучение", akFoto: "Фото", akFotoEkle: "Добавить фото", akGecti: "Вы прошли!",
    akGorselHazir2: "Готовим фото…", akHazirliyor2: "Gloxoo готовит урок", akHenuzYok: "Сертификата пока нет. Пройдите обучение, сдайте экзамен, покажите свою работу!",
    akHeroAlt: "Обучайтесь любой профессии, изучайте каждый вид, сдайте экзамен Gloxoo, покажите работу — получите проверяемый сертификат.",
    akIsAlt: "Загрузите свою работу фото и/или видео — она останется доказательством в сертификате.", akIsGoster: "Покажите свою работу",
    akKaldi: "Вы не прошли", akKaydOlmadi: "Не удалось создать сертификат, попробуйте ещё раз.", akKod: "Код проверки",
    akKonuAraYer: "Напишите другой вид/модель (напр. хлеб из мира)…", akKonuOlmadi: "Не удалось загрузить, попробуйте ещё раз.", akKonuYuk3: "Gloxoo готовит рецепт",
    akOnceIs: "Сначала покажите работу фото или видео.", akOnceSinav: "Сначала сдайте экзамен.", akPuan: "Экзамен", akSertifika: "СЕРТИФИКАТ",
    akSertifikalarim: "Мои сертификаты", akSertifikamiAl: "Получить сертификат", akSinav: "Экзамен (серьёзный)",
    akSinavAlt: "Настоящие профессиональные вопросы. Для сертификата нужно минимум 70%.", akSinavOlmadi: "Не удалось загрузить экзамен, попробуйте ещё раз.", akSinavaGir: "Сдать экзамен",
    akSor: "Спросить", akSorular: "Готовим вопросы…", akSrtNot: "Это документ GLOXORG Академии. Его можно проверить по коду.", akSertifikayiIndir: "Скачать сертификат", akPaylas: "Поделиться", akHazirlaniyor: "Готовим…", akIndirildi: "Скачано", akSrtOlmadi: "Не удалось создать изображение сертификата, попробуйте ещё раз.",
    akTamamladi: "успешно завершил(а) это обучение", akTekrarSinav: "Ещё раз", akTemelAlt: "Gloxoo обучает общим знаниям об этой профессии.",
    akTemelEgitim: "Базовое обучение", akVideo: "Видео", akVideoEkle: "Добавить видео",
    akSesliAnlat: "Озвучить", akDurdur: "Стоп", akKopyala: "Копировать", akKopyalandi: "Скопировано", akIndir: "Скачать", akPaylas: "Поделиться",
  },
  uk: {
    akAkademi: "АКАДЕМІЯ", akAra: "Пошук професії…", akBaslik: "GLOXORG Академія", akBitir: "Завершити іспит", akBitti: "Пояснення завершено",
    akCesitAlt2: "Торкніться виду; Gloxoo пояснить його з мірками, крок за кроком. Немає в списку? Напишіть нижче, Gloxoo теж пояснить.",
    akCesitGetir: "Завантажити види", akCesitOlmadi: "Не вдалося завантажити.", akCesitYuk: "Завантаження видів…", akCesitler: "Види — по одному",
    akDersOlmadi: "Не вдалося завантажити урок, спробуйте ще раз.", akEgitimAl: "Почати навчання", akFoto: "Фото", akFotoEkle: "Додати фото", akGecti: "Ви склали!",
    akGorselHazir2: "Готуємо фото…", akHazirliyor2: "Gloxoo готує урок", akHenuzYok: "Сертифіката ще немає. Пройдіть навчання, складіть іспит, покажіть свою роботу!",
    akHeroAlt: "Навчайтеся будь-якій професії, вивчайте кожен вид, складіть іспит Gloxoo, покажіть роботу — отримайте сертифікат, який можна перевірити.",
    akIsAlt: "Завантажте свою роботу фото та/або відео — вона залишиться доказом у сертифікаті.", akIsGoster: "Покажіть свою роботу",
    akKaldi: "Ви не склали", akKaydOlmadi: "Не вдалося створити сертифікат, спробуйте ще раз.", akKod: "Код перевірки",
    akKonuAraYer: "Напишіть інший вид/модель (напр. хліб зі світу)…", akKonuOlmadi: "Не вдалося завантажити, спробуйте ще раз.", akKonuYuk3: "Gloxoo готує рецепт",
    akOnceIs: "Спершу покажіть роботу фото або відео.", akOnceSinav: "Спершу складіть іспит.", akPuan: "Іспит", akSertifika: "СЕРТИФІКАТ",
    akSertifikalarim: "Мої сертифікати", akSertifikamiAl: "Отримати сертифікат", akSinav: "Іспит (серйозний)",
    akSinavAlt: "Справжні фахові запитання. Для сертифіката потрібно щонайменше 70%.", akSinavOlmadi: "Не вдалося завантажити іспит, спробуйте ще раз.", akSinavaGir: "Скласти іспит",
    akSor: "Запитати", akSorular: "Готуємо запитання…", akSrtNot: "Це документ GLOXORG Академії. Його можна перевірити за кодом.", akSertifikayiIndir: "Завантажити сертифікат", akPaylas: "Поділитися", akHazirlaniyor: "Готуємо…", akIndirildi: "Завантажено", akSrtOlmadi: "Не вдалося створити зображення сертифіката, спробуйте ще раз.",
    akTamamladi: "успішно завершив(ла) це навчання", akTekrarSinav: "Ще раз", akTemelAlt: "Gloxoo навчає загальних знань про цю професію.",
    akTemelEgitim: "Базове навчання", akVideo: "Відео", akVideoEkle: "Додати відео",
    akSesliAnlat: "Озвучити", akDurdur: "Стоп", akKopyala: "Копіювати", akKopyalandi: "Скопійовано", akIndir: "Завантажити", akPaylas: "Поділитися",
  },
  es: {
    akAkademi: "ACADEMIA", akAra: "Buscar profesión…", akBaslik: "GLOXORG Academia", akBitir: "Terminar examen", akBitti: "Explicación completada",
    akCesitAlt2: "Toca una variedad; Gloxoo la explica con medidas, paso a paso. ¿No está? Escríbela abajo y Gloxoo también la explicará.",
    akCesitGetir: "Cargar variedades", akCesitOlmadi: "No se pudo cargar.", akCesitYuk: "Cargando variedades…", akCesitler: "Variedades — una por una",
    akDersOlmadi: "No se pudo cargar la lección, inténtalo de nuevo.", akEgitimAl: "Empezar formación", akFoto: "Foto", akFotoEkle: "Añadir foto", akGecti: "¡Aprobaste!",
    akGorselHazir2: "Preparando foto…", akHazirliyor2: "Gloxoo está preparando la lección", akHenuzYok: "Aún no tienes certificado. Haz un curso, aprueba el examen, ¡muestra tu trabajo!",
    akHeroAlt: "Fórmate en cada profesión, aprende cada variedad, aprueba el examen de Gloxoo, muestra tu trabajo — gana tu certificado verificable.",
    akIsAlt: "Sube tu propio trabajo como foto y/o vídeo — queda como prueba en tu certificado.", akIsGoster: "Muestra tu trabajo",
    akKaldi: "No aprobaste", akKaydOlmadi: "No se pudo crear el certificado, inténtalo de nuevo.", akKod: "Código de verificación",
    akKonuAraYer: "Escribe otra variedad/modelo (p. ej. un pan del mundo)…", akKonuOlmadi: "No se pudo cargar, inténtalo de nuevo.", akKonuYuk3: "Gloxoo está preparando la receta",
    akOnceIs: "Primero muestra tu trabajo con foto o vídeo.", akOnceSinav: "Aprueba primero el examen.", akPuan: "Examen", akSertifika: "CERTIFICADO",
    akSertifikalarim: "Mis certificados", akSertifikamiAl: "Obtener mi certificado", akSinav: "Examen (serio)",
    akSinavAlt: "Preguntas profesionales reales. Se requiere al menos 70% para el certificado.", akSinavOlmadi: "No se pudo cargar el examen, inténtalo de nuevo.", akSinavaGir: "Hacer el examen",
    akSor: "Preguntar", akSorular: "Preparando preguntas…", akSrtNot: "Este es un documento de GLOXORG Academia. Se puede verificar por código.", akSertifikayiIndir: "Descargar certificado", akPaylas: "Compartir", akHazirlaniyor: "Preparando…", akIndirildi: "Descargado", akSrtOlmadi: "No se pudo crear la imagen del certificado, inténtalo de nuevo.",
    akTamamladi: "completó con éxito esta formación", akTekrarSinav: "Intentar de nuevo", akTemelAlt: "Gloxoo enseña conocimientos generales sobre esta profesión.",
    akTemelEgitim: "Formación básica", akVideo: "Vídeo", akVideoEkle: "Añadir vídeo",
    akSesliAnlat: "Leer en voz alta", akDurdur: "Detener", akKopyala: "Copiar", akKopyalandi: "Copiado", akIndir: "Descargar", akPaylas: "Compartir",
  },
  fr: {
    akAkademi: "ACADÉMIE", akAra: "Rechercher un métier…", akBaslik: "GLOXORG Académie", akBitir: "Terminer l'examen", akBitti: "Explication terminée",
    akCesitAlt2: "Touchez une variété ; Gloxoo l'explique avec les mesures, étape par étape. Absente ? Écrivez-la ci-dessous, Gloxoo l'expliquera aussi.",
    akCesitGetir: "Charger les variétés", akCesitOlmadi: "Impossible de charger.", akCesitYuk: "Chargement des variétés…", akCesitler: "Variétés — une par une",
    akDersOlmadi: "Impossible de charger la leçon, réessayez.", akEgitimAl: "Commencer la formation", akFoto: "Photo", akFotoEkle: "Ajouter une photo", akGecti: "Réussi !",
    akGorselHazir2: "Préparation de la photo…", akHazirliyor2: "Gloxoo prépare la leçon", akHenuzYok: "Pas encore de certificat. Suivez un cours, réussissez l'examen, montrez votre travail !",
    akHeroAlt: "Formez-vous à chaque métier, apprenez chaque variété, réussissez l'examen de Gloxoo, montrez votre travail — obtenez votre certificat vérifiable.",
    akIsAlt: "Téléversez votre propre travail en photo et/ou vidéo — il reste comme preuve sur votre certificat.", akIsGoster: "Montrez votre travail",
    akKaldi: "Échec", akKaydOlmadi: "Impossible de créer le certificat, réessayez.", akKod: "Code de vérification",
    akKonuAraYer: "Écrivez une autre variété/modèle (ex. un pain du monde)…", akKonuOlmadi: "Impossible de charger, réessayez.", akKonuYuk3: "Gloxoo prépare la recette",
    akOnceIs: "Montrez d'abord votre travail avec une photo ou vidéo.", akOnceSinav: "Réussissez d'abord l'examen.", akPuan: "Examen", akSertifika: "CERTIFICAT",
    akSertifikalarim: "Mes certificats", akSertifikamiAl: "Obtenir mon certificat", akSinav: "Examen (sérieux)",
    akSinavAlt: "De vraies questions professionnelles. Au moins 70 % requis pour le certificat.", akSinavOlmadi: "Impossible de charger l'examen, réessayez.", akSinavaGir: "Passer l'examen",
    akSor: "Demander", akSorular: "Préparation des questions…", akSrtNot: "Ceci est un document de GLOXORG Académie. Vérifiable par code.", akSertifikayiIndir: "Télécharger le certificat", akPaylas: "Partager", akHazirlaniyor: "Préparation…", akIndirildi: "Téléchargé", akSrtOlmadi: "Impossible de créer l’image du certificat, réessaie.",
    akTamamladi: "a terminé cette formation avec succès", akTekrarSinav: "Réessayer", akTemelAlt: "Gloxoo enseigne les connaissances générales sur ce métier.",
    akTemelEgitim: "Formation de base", akVideo: "Vidéo", akVideoEkle: "Ajouter une vidéo",
    akSesliAnlat: "Lire à voix haute", akDurdur: "Arrêter", akKopyala: "Copier", akKopyalandi: "Copié", akIndir: "Télécharger", akPaylas: "Partager",
  },
  it: {
    akAkademi: "ACCADEMIA", akAra: "Cerca professione…", akBaslik: "GLOXORG Accademia", akBitir: "Termina esame", akBitti: "Spiegazione completata",
    akCesitAlt2: "Tocca una varietà; Gloxoo la spiega con le dosi, passo dopo passo. Non c'è? Scrivila sotto e Gloxoo la spiegherà.",
    akCesitGetir: "Carica le varietà", akCesitOlmadi: "Impossibile caricare.", akCesitYuk: "Caricamento varietà…", akCesitler: "Varietà — una per una",
    akDersOlmadi: "Impossibile caricare la lezione, riprova.", akEgitimAl: "Inizia la formazione", akFoto: "Foto", akFotoEkle: "Aggiungi foto", akGecti: "Superato!",
    akGorselHazir2: "Preparazione foto…", akHazirliyor2: "Gloxoo sta preparando la lezione", akHenuzYok: "Ancora nessun certificato. Segui un corso, supera l'esame, mostra il tuo lavoro!",
    akHeroAlt: "Formati per ogni professione, impara ogni varietà, supera l'esame di Gloxoo, mostra il tuo lavoro — ottieni il tuo certificato verificabile.",
    akIsAlt: "Carica il tuo lavoro come foto e/o video — resta come prova nel tuo certificato.", akIsGoster: "Mostra il tuo lavoro",
    akKaldi: "Non superato", akKaydOlmadi: "Impossibile creare il certificato, riprova.", akKod: "Codice di verifica",
    akKonuAraYer: "Scrivi un'altra varietà/modello (es. un pane dal mondo)…", akKonuOlmadi: "Impossibile caricare, riprova.", akKonuYuk3: "Gloxoo sta preparando la ricetta",
    akOnceIs: "Mostra prima il tuo lavoro con foto o video.", akOnceSinav: "Supera prima l'esame.", akPuan: "Esame", akSertifika: "CERTIFICATO",
    akSertifikalarim: "I miei certificati", akSertifikamiAl: "Ottieni il mio certificato", akSinav: "Esame (serio)",
    akSinavAlt: "Vere domande professionali. Per il certificato serve almeno il 70%.", akSinavOlmadi: "Impossibile caricare l'esame, riprova.", akSinavaGir: "Fai l'esame",
    akSor: "Chiedi", akSorular: "Preparazione domande…", akSrtNot: "Questo è un documento di GLOXORG Accademia. Verificabile tramite codice.", akSertifikayiIndir: "Scarica il certificato", akPaylas: "Condividi", akHazirlaniyor: "Preparazione…", akIndirildi: "Scaricato", akSrtOlmadi: "Impossibile creare l’immagine del certificato, riprova.",
    akTamamladi: "ha completato con successo questa formazione", akTekrarSinav: "Riprova", akTemelAlt: "Gloxoo insegna le conoscenze generali su questa professione.",
    akTemelEgitim: "Formazione di base", akVideo: "Video", akVideoEkle: "Aggiungi video",
    akSesliAnlat: "Leggi ad alta voce", akDurdur: "Ferma", akKopyala: "Copia", akKopyalandi: "Copiato", akIndir: "Scarica", akPaylas: "Condividi",
  },
  pt: {
    akAkademi: "ACADEMIA", akAra: "Pesquisar profissão…", akBaslik: "GLOXORG Academia", akBitir: "Terminar exame", akBitti: "Explicação concluída",
    akCesitAlt2: "Toque numa variedade; Gloxoo explica com medidas, passo a passo. Não está? Escreva abaixo e Gloxoo também explica.",
    akCesitGetir: "Carregar variedades", akCesitOlmadi: "Não foi possível carregar.", akCesitYuk: "A carregar variedades…", akCesitler: "Variedades — uma a uma",
    akDersOlmadi: "Não foi possível carregar a lição, tente de novo.", akEgitimAl: "Iniciar formação", akFoto: "Foto", akFotoEkle: "Adicionar foto", akGecti: "Passou!",
    akGorselHazir2: "A preparar foto…", akHazirliyor2: "Gloxoo está a preparar a lição", akHenuzYok: "Ainda sem certificado. Faça um curso, passe no exame, mostre o seu trabalho!",
    akHeroAlt: "Forme-se em cada profissão, aprenda cada variedade, passe no exame do Gloxoo, mostre o seu trabalho — ganhe o seu certificado verificável.",
    akIsAlt: "Carregue o seu trabalho como foto e/ou vídeo — fica como prova no seu certificado.", akIsGoster: "Mostre o seu trabalho",
    akKaldi: "Não passou", akKaydOlmadi: "Não foi possível criar o certificado, tente de novo.", akKod: "Código de verificação",
    akKonuAraYer: "Escreva outra variedade/modelo (ex. um pão do mundo)…", akKonuOlmadi: "Não foi possível carregar, tente de novo.", akKonuYuk3: "Gloxoo está a preparar a receita",
    akOnceIs: "Mostre primeiro o seu trabalho com foto ou vídeo.", akOnceSinav: "Passe no exame primeiro.", akPuan: "Exame", akSertifika: "CERTIFICADO",
    akSertifikalarim: "Os meus certificados", akSertifikamiAl: "Obter o meu certificado", akSinav: "Exame (sério)",
    akSinavAlt: "Perguntas profissionais reais. É preciso pelo menos 70% para o certificado.", akSinavOlmadi: "Não foi possível carregar o exame, tente de novo.", akSinavaGir: "Fazer o exame",
    akSor: "Perguntar", akSorular: "A preparar perguntas…", akSrtNot: "Este é um documento da GLOXORG Academia. Pode ser verificado por código.", akSertifikayiIndir: "Baixar certificado", akPaylas: "Partilhar", akHazirlaniyor: "A preparar…", akIndirildi: "Baixado", akSrtOlmadi: "Não foi possível criar a imagem do certificado, tenta de novo.",
    akTamamladi: "concluiu esta formação com sucesso", akTekrarSinav: "Tentar de novo", akTemelAlt: "Gloxoo ensina conhecimentos gerais sobre esta profissão.",
    akTemelEgitim: "Formação básica", akVideo: "Vídeo", akVideoEkle: "Adicionar vídeo",
    akSesliAnlat: "Ler em voz alta", akDurdur: "Parar", akKopyala: "Copiar", akKopyalandi: "Copiado", akIndir: "Transferir", akPaylas: "Partilhar",
  },
  ar: {
    akAkademi: "الأكاديمية", akAra: "ابحث عن مهنة…", akBaslik: "أكاديمية GLOXORG", akBitir: "إنهاء الاختبار", akBitti: "اكتمل الشرح",
    akCesitAlt2: "اضغط على نوع؛ يشرحه Gloxoo بالمقادير خطوة بخطوة. غير موجود؟ اكتبه بالأسفل وسيشرحه Gloxoo أيضًا.",
    akCesitGetir: "تحميل الأنواع", akCesitOlmadi: "تعذّر التحميل.", akCesitYuk: "جارٍ تحميل الأنواع…", akCesitler: "الأنواع — واحدًا تلو الآخر",
    akDersOlmadi: "تعذّر تحميل الدرس الآن، حاول مجددًا.", akEgitimAl: "ابدأ التدريب", akFoto: "صورة", akFotoEkle: "إضافة صورة", akGecti: "لقد نجحت!",
    akGorselHazir2: "جارٍ تحضير الصورة…", akHazirliyor2: "يقوم Gloxoo بتحضير الدرس", akHenuzYok: "لا شهادة بعد. خذ دورة، اجتز الاختبار، اعرض عملك!",
    akHeroAlt: "تدرّب على كل مهنة، تعلّم كل نوع، اجتز اختبار Gloxoo، اعرض عملك — احصل على شهادتك القابلة للتحقق.",
    akIsAlt: "ارفع عملك كصورة و/أو فيديو — يبقى كدليل في شهادتك.", akIsGoster: "اعرض عملك",
    akKaldi: "لم تنجح", akKaydOlmadi: "تعذّر إنشاء الشهادة، حاول مجددًا.", akKod: "رمز التحقق",
    akKonuAraYer: "اكتب نوعًا/نموذجًا آخر (مثل خبز من العالم)…", akKonuOlmadi: "تعذّر التحميل، حاول مجددًا.", akKonuYuk3: "يقوم Gloxoo بتحضير الوصفة",
    akOnceIs: "اعرض عملك أولًا بصورة أو فيديو.", akOnceSinav: "اجتز الاختبار أولًا.", akPuan: "الاختبار", akSertifika: "شهادة",
    akSertifikalarim: "شهاداتي", akSertifikamiAl: "احصل على شهادتي", akSinav: "اختبار (جدّي)",
    akSinavAlt: "أسئلة مهنية حقيقية. يلزم 70% على الأقل للشهادة.", akSinavOlmadi: "تعذّر تحميل الاختبار، حاول مجددًا.", akSinavaGir: "ادخل الاختبار",
    akSor: "اسأل", akSorular: "جارٍ تحضير الأسئلة…", akSrtNot: "هذه وثيقة من أكاديمية GLOXORG. يمكن التحقق منها بالرمز.", akSertifikayiIndir: "تنزيل الشهادة", akPaylas: "مشاركة", akHazirlaniyor: "جارٍ التحضير…", akIndirildi: "تم التنزيل", akSrtOlmadi: "تعذّر إنشاء صورة الشهادة، حاول مرة أخرى.",
    akTamamladi: "أتمّ هذا التدريب بنجاح", akTekrarSinav: "حاول مجددًا", akTemelAlt: "يعلّم Gloxoo المعرفة العامة عن هذه المهنة.",
    akTemelEgitim: "تدريب أساسي", akVideo: "فيديو", akVideoEkle: "إضافة فيديو",
    akSesliAnlat: "قراءة صوتية", akDurdur: "إيقاف", akKopyala: "نسخ", akKopyalandi: "تم النسخ", akIndir: "تنزيل", akPaylas: "مشاركة",
  },
  zh: {
    akAkademi: "学院", akAra: "搜索职业…", akBaslik: "GLOXORG 学院", akBitir: "结束考试", akBitti: "讲解完成",
    akCesitAlt2: "点一个品种；Gloxoo 会用配料一步步讲解。没有？在下方输入，Gloxoo 也会讲解。",
    akCesitGetir: "加载品种", akCesitOlmadi: "无法加载。", akCesitYuk: "正在加载品种…", akCesitler: "品种 — 逐个",
    akDersOlmadi: "暂时无法加载课程，请重试。", akEgitimAl: "开始培训", akFoto: "照片", akFotoEkle: "添加照片", akGecti: "你通过了！",
    akGorselHazir2: "正在准备照片…", akHazirliyor2: "Gloxoo 正在准备课程", akHenuzYok: "还没有证书。上一门课，通过考试，展示你的作品！",
    akHeroAlt: "为每种职业接受培训，逐个学习品种，通过 Gloxoo 的考试，展示作品 — 赢得可验证的证书。",
    akIsAlt: "以照片和/或视频上传你的作品 — 它会作为证明留在证书上。", akIsGoster: "展示你的作品",
    akKaldi: "未通过", akKaydOlmadi: "无法创建证书，请重试。", akKod: "验证码",
    akKonuAraYer: "输入另一个品种/款式（例如世界上的一种面包）…", akKonuOlmadi: "暂时无法加载，请重试。", akKonuYuk3: "Gloxoo 正在准备做法",
    akOnceIs: "请先用照片或视频展示你的作品。", akOnceSinav: "请先通过考试。", akPuan: "考试", akSertifika: "证书",
    akSertifikalarim: "我的证书", akSertifikamiAl: "获取我的证书", akSinav: "考试（正式）",
    akSinavAlt: "真实的专业题目。证书至少需要 70%。", akSinavOlmadi: "无法加载考试，请重试。", akSinavaGir: "参加考试",
    akSor: "提问", akSorular: "正在准备题目…", akSrtNot: "这是 GLOXORG 学院文件，可通过代码验证。", akSertifikayiIndir: "下载证书", akPaylas: "分享", akHazirlaniyor: "准备中…", akIndirildi: "已下载", akSrtOlmadi: "无法生成证书图片，请重试。",
    akTamamladi: "已成功完成此培训", akTekrarSinav: "再试一次", akTemelAlt: "Gloxoo 讲授关于该职业的通用知识。",
    akTemelEgitim: "基础培训", akVideo: "视频", akVideoEkle: "添加视频",
    akSesliAnlat: "朗读", akDurdur: "停止", akKopyala: "复制", akKopyalandi: "已复制", akIndir: "下载", akPaylas: "分享",
  },
  hi: {
    akAkademi: "अकादमी", akAra: "पेशा खोजें…", akBaslik: "GLOXORG अकादमी", akBitir: "परीक्षा समाप्त करें", akBitti: "व्याख्या पूरी हुई",
    akCesitAlt2: "किसी प्रकार पर टैप करें; Gloxoo उसे माप के साथ चरण-दर-चरण समझाता है। सूची में नहीं? नीचे लिखें, Gloxoo उसे भी समझाएगा।",
    akCesitGetir: "प्रकार लाएँ", akCesitOlmadi: "लोड नहीं हो सका।", akCesitYuk: "प्रकार लोड हो रहे हैं…", akCesitler: "प्रकार — एक-एक करके",
    akDersOlmadi: "अभी पाठ लोड नहीं हो सका, फिर से कोशिश करें।", akEgitimAl: "प्रशिक्षण शुरू करें", akFoto: "फ़ोटो", akFotoEkle: "फ़ोटो जोड़ें", akGecti: "आप पास हुए!",
    akGorselHazir2: "फ़ोटो तैयार हो रही है…", akHazirliyor2: "Gloxoo पाठ तैयार कर रहा है", akHenuzYok: "अभी कोई प्रमाणपत्र नहीं। कोर्स करें, परीक्षा पास करें, अपना काम दिखाएँ!",
    akHeroAlt: "हर पेशे के लिए प्रशिक्षण लें, हर प्रकार सीखें, Gloxoo की परीक्षा पास करें, अपना काम दिखाएँ — अपना सत्यापन-योग्य प्रमाणपत्र पाएँ।",
    akIsAlt: "अपना काम फ़ोटो और/या वीडियो के रूप में अपलोड करें — यह आपके प्रमाणपत्र में प्रमाण के रूप में रहता है।", akIsGoster: "अपना काम दिखाएँ",
    akKaldi: "आप पास नहीं हुए", akKaydOlmadi: "प्रमाणपत्र नहीं बन सका, फिर से कोशिश करें।", akKod: "सत्यापन कोड",
    akKonuAraYer: "कोई और प्रकार/मॉडल लिखें (जैसे दुनिया की कोई रोटी)…", akKonuOlmadi: "अभी लोड नहीं हो सका, फिर से कोशिश करें।", akKonuYuk3: "Gloxoo विधि तैयार कर रहा है",
    akOnceIs: "पहले अपना काम फ़ोटो या वीडियो से दिखाएँ।", akOnceSinav: "पहले परीक्षा पास करें।", akPuan: "परीक्षा", akSertifika: "प्रमाणपत्र",
    akSertifikalarim: "मेरे प्रमाणपत्र", akSertifikamiAl: "मेरा प्रमाणपत्र पाएँ", akSinav: "परीक्षा (गंभीर)",
    akSinavAlt: "असली पेशेवर प्रश्न। प्रमाणपत्र के लिए कम से कम 70% चाहिए।", akSinavOlmadi: "परीक्षा लोड नहीं हो सकी, फिर से कोशिश करें।", akSinavaGir: "परीक्षा दें",
    akSor: "पूछें", akSorular: "प्रश्न तैयार हो रहे हैं…", akSrtNot: "यह GLOXORG अकादमी का दस्तावेज़ है। कोड से सत्यापित किया जा सकता है।", akSertifikayiIndir: "प्रमाणपत्र डाउनलोड करें", akPaylas: "शेयर", akHazirlaniyor: "तैयार हो रहा है…", akIndirildi: "डाउनलोड हो गया", akSrtOlmadi: "प्रमाणपत्र की छवि नहीं बन सकी, फिर कोशिश करें।",
    akTamamladi: "ने यह प्रशिक्षण सफलतापूर्वक पूरा किया", akTekrarSinav: "फिर से कोशिश करें", akTemelAlt: "Gloxoo इस पेशे के बारे में सामान्य ज्ञान सिखाता है।",
    akTemelEgitim: "बुनियादी प्रशिक्षण", akVideo: "वीडियो", akVideoEkle: "वीडियो जोड़ें",
    akSesliAnlat: "ज़ोर से पढ़ें", akDurdur: "रोकें", akKopyala: "कॉपी करें", akKopyalandi: "कॉपी हुआ", akIndir: "डाउनलोड", akPaylas: "साझा करें",
  },
  ja: {
    akAkademi: "アカデミー", akAra: "職業を検索…", akBaslik: "GLOXORG アカデミー", akBitir: "試験を終える", akBitti: "説明が完了しました",
    akCesitAlt2: "種類をタップ。Gloxoo が分量とともに順を追って説明します。ない場合は下に入力すれば説明します。",
    akCesitGetir: "種類を読み込む", akCesitOlmadi: "読み込めませんでした。", akCesitYuk: "種類を読み込み中…", akCesitler: "種類 — ひとつずつ",
    akDersOlmadi: "今はレッスンを読み込めません。もう一度お試しください。", akEgitimAl: "トレーニングを開始", akFoto: "写真", akFotoEkle: "写真を追加", akGecti: "合格！",
    akGorselHazir2: "写真を準備中…", akHazirliyor2: "Gloxoo がレッスンを準備中", akHenuzYok: "まだ証明書がありません。コースを受け、試験に合格し、作品を見せましょう！",
    akHeroAlt: "あらゆる職業のトレーニングを受け、各種類を学び、Gloxoo の試験に合格し、作品を見せて — 検証可能な証明書を獲得。",
    akIsAlt: "自分の作品を写真や動画でアップロード — 証明書に証拠として残ります。", akIsGoster: "作品を見せる",
    akKaldi: "不合格", akKaydOlmadi: "証明書を作成できませんでした。もう一度お試しください。", akKod: "確認コード",
    akKonuAraYer: "別の種類/モデルを入力（例：世界のパン）…", akKonuOlmadi: "今は読み込めません。もう一度。", akKonuYuk3: "Gloxoo がレシピを準備中",
    akOnceIs: "まず作品を写真か動画で見せてください。", akOnceSinav: "先に試験に合格してください。", akPuan: "試験", akSertifika: "証明書",
    akSertifikalarim: "私の証明書", akSertifikamiAl: "証明書を取得", akSinav: "試験（本格）",
    akSinavAlt: "本物の専門的な問題。証明書には最低70%が必要です。", akSinavOlmadi: "試験を読み込めません。もう一度。", akSinavaGir: "試験を受ける",
    akSor: "質問", akSorular: "問題を準備中…", akSrtNot: "これは GLOXORG アカデミーの書類です。コードで検証できます。", akSertifikayiIndir: "証明書をダウンロード", akPaylas: "共有", akHazirlaniyor: "準備中…", akIndirildi: "ダウンロード済み", akSrtOlmadi: "証明書の画像を作成できませんでした。もう一度お試しください。",
    akTamamladi: "このトレーニングを無事に修了しました", akTekrarSinav: "もう一度", akTemelAlt: "Gloxoo はこの職業の一般知識を教えます。",
    akTemelEgitim: "基礎トレーニング", akVideo: "動画", akVideoEkle: "動画を追加",
    akSesliAnlat: "読み上げ", akDurdur: "停止", akKopyala: "コピー", akKopyalandi: "コピーしました", akIndir: "ダウンロード", akPaylas: "共有",
  },
};

// KURULUŞ & FİZİBİLİTE adımı (fabrika/imalathane kurulumu) — 13 dil. i18n.js'te CEVIRI_AKADEMI ile birlikte merge edilir.
export const CEVIRI_AKADEMI_KURULUS = {
  tr: { akKurulus: "Kuruluş & Fizibilite", akKurulusAl: "Fizibiliteyi hazırla", akKurulusHazir: "Gloxoo fizibiliteyi hazırlıyor", akKurulusAlt: "Bu işin imalathanesi/fabrikası nasıl kurulur: makine-teçhizat, ham madde nedir ve nasıl temin edilir, üretim akışı, maliyet ve kâr — eksiksiz fizibilite." },
  en: { akKurulus: "Setup & Feasibility", akKurulusAl: "Prepare feasibility", akKurulusHazir: "Gloxoo is preparing the feasibility study", akKurulusAlt: "How to set up a workshop/factory for this work: machinery & equipment, what the raw materials are and how to source them, production flow, costs and profit — a complete feasibility study." },
  de: { akKurulus: "Gründung & Machbarkeit", akKurulusAl: "Machbarkeit erstellen", akKurulusHazir: "Gloxoo erstellt die Machbarkeitsstudie", akKurulusAlt: "Wie man für diese Arbeit eine Werkstatt/Fabrik aufbaut: Maschinen & Ausrüstung, welche Rohstoffe nötig sind und wie man sie beschafft, Produktionsablauf, Kosten und Gewinn — eine vollständige Machbarkeitsstudie." },
  ru: { akKurulus: "Открытие и ТЭО", akKurulusAl: "Составить ТЭО", akKurulusHazir: "Gloxoo готовит ТЭО", akKurulusAlt: "Как открыть мастерскую/фабрику для этого дела: машины и оборудование, какое сырьё нужно и как его достать, процесс производства, затраты и прибыль — полное технико-экономическое обоснование." },
  uk: { akKurulus: "Відкриття та ТЕО", akKurulusAl: "Скласти ТЕО", akKurulusHazir: "Gloxoo готує ТЕО", akKurulusAlt: "Як відкрити майстерню/фабрику для цієї справи: машини та обладнання, яка сировина потрібна і як її дістати, процес виробництва, витрати та прибуток — повне техніко-економічне обґрунтування." },
  es: { akKurulus: "Montaje y Viabilidad", akKurulusAl: "Preparar viabilidad", akKurulusHazir: "Gloxoo está preparando el estudio de viabilidad", akKurulusAlt: "Cómo montar un taller/fábrica para este oficio: maquinaria y equipo, qué materias primas se necesitan y cómo conseguirlas, flujo de producción, costos y ganancia — un estudio de viabilidad completo." },
  fr: { akKurulus: "Création et Faisabilité", akKurulusAl: "Préparer la faisabilité", akKurulusHazir: "Gloxoo prépare l'étude de faisabilité", akKurulusAlt: "Comment créer un atelier/une usine pour ce métier : machines et équipement, quelles matières premières et comment les approvisionner, flux de production, coûts et profit — une étude de faisabilité complète." },
  it: { akKurulus: "Avvio e Fattibilità", akKurulusAl: "Prepara la fattibilità", akKurulusHazir: "Gloxoo sta preparando lo studio di fattibilità", akKurulusAlt: "Come avviare un laboratorio/una fabbrica per questo lavoro: macchinari e attrezzature, quali materie prime servono e come procurarle, flusso di produzione, costi e profitto — uno studio di fattibilità completo." },
  pt: { akKurulus: "Montagem e Viabilidade", akKurulusAl: "Preparar viabilidade", akKurulusHazir: "Gloxoo está preparando o estudo de viabilidade", akKurulusAlt: "Como montar uma oficina/fábrica para este ofício: máquinas e equipamentos, quais matérias-primas e como obtê-las, fluxo de produção, custos e lucro — um estudo de viabilidade completo." },
  ar: { akKurulus: "التأسيس ودراسة الجدوى", akKurulusAl: "إعداد دراسة الجدوى", akKurulusHazir: "غلوكسو يُعدّ دراسة الجدوى", akKurulusAlt: "كيف تنشئ ورشة/مصنعًا لهذا العمل: الآلات والمعدات، وما المواد الخام وكيفية توفيرها، وسير الإنتاج، والتكاليف والربح — دراسة جدوى كاملة." },
  zh: { akKurulus: "建厂与可行性", akKurulusAl: "生成可行性方案", akKurulusHazir: "Gloxoo 正在准备可行性研究", akKurulusAlt: "如何为这门行当建立作坊/工厂：机器与设备、需要哪些原材料及如何采购、生产流程、成本与利润——一份完整的可行性研究。" },
  hi: { akKurulus: "स्थापना और व्यवहार्यता", akKurulusAl: "व्यवहार्यता तैयार करें", akKurulusHazir: "Gloxoo व्यवहार्यता अध्ययन तैयार कर रहा है", akKurulusAlt: "इस काम के लिए वर्कशॉप/फ़ैक्ट्री कैसे लगाएँ: मशीनरी और उपकरण, कच्चा माल क्या है और कैसे प्राप्त करें, उत्पादन प्रवाह, लागत और लाभ — एक पूर्ण व्यवहार्यता अध्ययन।" },
  ja: { akKurulus: "設立と実現可能性", akKurulusAl: "実現可能性を作成", akKurulusHazir: "Gloxoo が実現可能性調査を作成中", akKurulusAlt: "この仕事の工房・工場をどう立ち上げるか：機械と設備、必要な原材料と入手方法、生産の流れ、コストと利益——完全な実現可能性調査。" },
};
