// GLOXORG — FİRMA ÜRÜN GALERİSİ + AMBLEM RENKLERİ + TAM EKRAN GEZİNME + HİKÂYE yedek metni çevirileri (13 dil).
// Yeni eklenen metinler burada toplanır; i18n.js her dile Object.assign ile katar. Marka "Gloxoo" çevrilmez.
export const CEVIRI_GALERI = {
  tr: { fkTamAc: "Tam ekran aç", fkAmblemZemin: "Amblem zemin rengi", fkAmblemYazi: "Firma ismi rengi", renkKrem: "Krem", renkAltin: "Altın", renkMavi: "Mavi", renkYesil: "Yeşil", renkPembe: "Pembe", renkMor: "Mor", yaziKahve: "Kahve", yaziAltin: "Altın", yaziKirmizi: "Kırmızı", yaziLacivert: "Lacivert", yaziYesil: "Yeşil", yaziBeyaz: "Beyaz", fkUrunGaleri: "Ürün foto / videoları", fkGaleriAciklama: "Bu ne? (istersen birkaç kelime yaz, Gloxoo güzelleştirir)", fkGaleriEkle: "Ürün foto/video ekle", fkGaleriGloxoo: "Gloxoo açıklasın", fkUrunler: "Ürünler / Görseller", onceki: "Önceki", sonraki: "Sonraki", hikGosterilemiyor: "Bu hikâye şu an görüntülenemiyor" },
  en: { fkTamAc: "Open full screen", fkAmblemZemin: "Emblem background color", fkAmblemYazi: "Business name color", renkKrem: "Cream", renkAltin: "Gold", renkMavi: "Blue", renkYesil: "Green", renkPembe: "Pink", renkMor: "Purple", yaziKahve: "Brown", yaziAltin: "Gold", yaziKirmizi: "Red", yaziLacivert: "Navy", yaziYesil: "Green", yaziBeyaz: "White", fkUrunGaleri: "Product photos / videos", fkGaleriAciklama: "What is this? (write a few words, Gloxoo will polish it)", fkGaleriEkle: "Add product photo/video", fkGaleriGloxoo: "Let Gloxoo describe", fkUrunler: "Products / Images", onceki: "Previous", sonraki: "Next", hikGosterilemiyor: "This story can't be shown right now" },
  de: { fkTamAc: "Vollbild öffnen", fkAmblemZemin: "Emblem-Hintergrundfarbe", fkAmblemYazi: "Farbe des Firmennamens", renkKrem: "Creme", renkAltin: "Gold", renkMavi: "Blau", renkYesil: "Grün", renkPembe: "Rosa", renkMor: "Lila", yaziKahve: "Braun", yaziAltin: "Gold", yaziKirmizi: "Rot", yaziLacivert: "Marineblau", yaziYesil: "Grün", yaziBeyaz: "Weiß", fkUrunGaleri: "Produktfotos / -videos", fkGaleriAciklama: "Was ist das? (ein paar Worte, Gloxoo verfeinert es)", fkGaleriEkle: "Produktfoto/-video hinzufügen", fkGaleriGloxoo: "Gloxoo beschreiben lassen", fkUrunler: "Produkte / Bilder", onceki: "Zurück", sonraki: "Weiter", hikGosterilemiyor: "Diese Story kann gerade nicht angezeigt werden" },
  ru: { fkTamAc: "Открыть на весь экран", fkAmblemZemin: "Цвет фона эмблемы", fkAmblemYazi: "Цвет названия фирмы", renkKrem: "Кремовый", renkAltin: "Золотой", renkMavi: "Синий", renkYesil: "Зелёный", renkPembe: "Розовый", renkMor: "Фиолетовый", yaziKahve: "Коричневый", yaziAltin: "Золотой", yaziKirmizi: "Красный", yaziLacivert: "Тёмно-синий", yaziYesil: "Зелёный", yaziBeyaz: "Белый", fkUrunGaleri: "Фото / видео товаров", fkGaleriAciklama: "Что это? (напиши пару слов, Gloxoo улучшит)", fkGaleriEkle: "Добавить фото/видео товара", fkGaleriGloxoo: "Пусть Gloxoo опишет", fkUrunler: "Товары / Изображения", onceki: "Назад", sonraki: "Далее", hikGosterilemiyor: "Эту историю сейчас нельзя показать" },
  uk: { fkTamAc: "Відкрити на весь екран", fkAmblemZemin: "Колір фону емблеми", fkAmblemYazi: "Колір назви фірми", renkKrem: "Кремовий", renkAltin: "Золотий", renkMavi: "Синій", renkYesil: "Зелений", renkPembe: "Рожевий", renkMor: "Фіолетовий", yaziKahve: "Коричневий", yaziAltin: "Золотий", yaziKirmizi: "Червоний", yaziLacivert: "Темно-синій", yaziYesil: "Зелений", yaziBeyaz: "Білий", fkUrunGaleri: "Фото / відео товарів", fkGaleriAciklama: "Що це? (напиши кілька слів, Gloxoo покращить)", fkGaleriEkle: "Додати фото/відео товару", fkGaleriGloxoo: "Хай Gloxoo опише", fkUrunler: "Товари / Зображення", onceki: "Назад", sonraki: "Далі", hikGosterilemiyor: "Цю історію зараз не можна показати" },
  es: { fkTamAc: "Abrir en pantalla completa", fkAmblemZemin: "Color de fondo del emblema", fkAmblemYazi: "Color del nombre del negocio", renkKrem: "Crema", renkAltin: "Dorado", renkMavi: "Azul", renkYesil: "Verde", renkPembe: "Rosa", renkMor: "Morado", yaziKahve: "Marrón", yaziAltin: "Dorado", yaziKirmizi: "Rojo", yaziLacivert: "Azul marino", yaziYesil: "Verde", yaziBeyaz: "Blanco", fkUrunGaleri: "Fotos / vídeos de productos", fkGaleriAciklama: "¿Qué es esto? (unas palabras, Gloxoo lo pulirá)", fkGaleriEkle: "Añadir foto/vídeo de producto", fkGaleriGloxoo: "Que Gloxoo lo describa", fkUrunler: "Productos / Imágenes", onceki: "Anterior", sonraki: "Siguiente", hikGosterilemiyor: "Esta historia no se puede mostrar ahora" },
  fr: { fkTamAc: "Ouvrir en plein écran", fkAmblemZemin: "Couleur de fond de l'emblème", fkAmblemYazi: "Couleur du nom de l'entreprise", renkKrem: "Crème", renkAltin: "Or", renkMavi: "Bleu", renkYesil: "Vert", renkPembe: "Rose", renkMor: "Violet", yaziKahve: "Marron", yaziAltin: "Or", yaziKirmizi: "Rouge", yaziLacivert: "Bleu marine", yaziYesil: "Vert", yaziBeyaz: "Blanc", fkUrunGaleri: "Photos / vidéos des produits", fkGaleriAciklama: "Qu'est-ce que c'est ? (quelques mots, Gloxoo peaufine)", fkGaleriEkle: "Ajouter photo/vidéo du produit", fkGaleriGloxoo: "Laisser Gloxoo décrire", fkUrunler: "Produits / Images", onceki: "Précédent", sonraki: "Suivant", hikGosterilemiyor: "Cette story ne peut pas être affichée pour le moment" },
  it: { fkTamAc: "Apri a schermo intero", fkAmblemZemin: "Colore sfondo emblema", fkAmblemYazi: "Colore nome attività", renkKrem: "Crema", renkAltin: "Oro", renkMavi: "Blu", renkYesil: "Verde", renkPembe: "Rosa", renkMor: "Viola", yaziKahve: "Marrone", yaziAltin: "Oro", yaziKirmizi: "Rosso", yaziLacivert: "Blu scuro", yaziYesil: "Verde", yaziBeyaz: "Bianco", fkUrunGaleri: "Foto / video dei prodotti", fkGaleriAciklama: "Cos'è? (due parole, Gloxoo rifinisce)", fkGaleriEkle: "Aggiungi foto/video prodotto", fkGaleriGloxoo: "Fai descrivere a Gloxoo", fkUrunler: "Prodotti / Immagini", onceki: "Precedente", sonraki: "Successivo", hikGosterilemiyor: "Questa storia non può essere mostrata ora" },
  pt: { fkTamAc: "Abrir em ecrã inteiro", fkAmblemZemin: "Cor de fundo do emblema", fkAmblemYazi: "Cor do nome do negócio", renkKrem: "Creme", renkAltin: "Dourado", renkMavi: "Azul", renkYesil: "Verde", renkPembe: "Rosa", renkMor: "Roxo", yaziKahve: "Castanho", yaziAltin: "Dourado", yaziKirmizi: "Vermelho", yaziLacivert: "Azul-marinho", yaziYesil: "Verde", yaziBeyaz: "Branco", fkUrunGaleri: "Fotos / vídeos de produtos", fkGaleriAciklama: "O que é isto? (umas palavras, Gloxoo melhora)", fkGaleriEkle: "Adicionar foto/vídeo do produto", fkGaleriGloxoo: "Deixa o Gloxoo descrever", fkUrunler: "Produtos / Imagens", onceki: "Anterior", sonraki: "Seguinte", hikGosterilemiyor: "Esta história não pode ser mostrada agora" },
  ar: { fkTamAc: "فتح ملء الشاشة", fkAmblemZemin: "لون خلفية الشعار", fkAmblemYazi: "لون اسم النشاط", renkKrem: "كريمي", renkAltin: "ذهبي", renkMavi: "أزرق", renkYesil: "أخضر", renkPembe: "وردي", renkMor: "بنفسجي", yaziKahve: "بني", yaziAltin: "ذهبي", yaziKirmizi: "أحمر", yaziLacivert: "كحلي", yaziYesil: "أخضر", yaziBeyaz: "أبيض", fkUrunGaleri: "صور / فيديوهات المنتجات", fkGaleriAciklama: "ما هذا؟ (اكتب بضع كلمات وسيحسّنها Gloxoo)", fkGaleriEkle: "إضافة صورة/فيديو للمنتج", fkGaleriGloxoo: "دع Gloxoo يصف", fkUrunler: "المنتجات / الصور", onceki: "السابق", sonraki: "التالي", hikGosterilemiyor: "لا يمكن عرض هذه القصة الآن" },
  zh: { fkTamAc: "全屏打开", fkAmblemZemin: "徽标背景色", fkAmblemYazi: "商家名称颜色", renkKrem: "米色", renkAltin: "金色", renkMavi: "蓝色", renkYesil: "绿色", renkPembe: "粉色", renkMor: "紫色", yaziKahve: "棕色", yaziAltin: "金色", yaziKirmizi: "红色", yaziLacivert: "藏青色", yaziYesil: "绿色", yaziBeyaz: "白色", fkUrunGaleri: "产品照片 / 视频", fkGaleriAciklama: "这是什么？（写几个字，Gloxoo 会润色）", fkGaleriEkle: "添加产品照片/视频", fkGaleriGloxoo: "让 Gloxoo 描述", fkUrunler: "产品 / 图片", onceki: "上一个", sonraki: "下一个", hikGosterilemiyor: "此故事暂时无法显示" },
  hi: { fkTamAc: "पूर्ण स्क्रीन खोलें", fkAmblemZemin: "प्रतीक पृष्ठभूमि रंग", fkAmblemYazi: "व्यवसाय नाम का रंग", renkKrem: "क्रीम", renkAltin: "सुनहरा", renkMavi: "नीला", renkYesil: "हरा", renkPembe: "गुलाबी", renkMor: "बैंगनी", yaziKahve: "भूरा", yaziAltin: "सुनहरा", yaziKirmizi: "लाल", yaziLacivert: "गहरा नीला", yaziYesil: "हरा", yaziBeyaz: "सफेद", fkUrunGaleri: "उत्पाद फोटो / वीडियो", fkGaleriAciklama: "यह क्या है? (कुछ शब्द लिखें, Gloxoo निखारेगा)", fkGaleriEkle: "उत्पाद फोटो/वीडियो जोड़ें", fkGaleriGloxoo: "Gloxoo से वर्णन कराएं", fkUrunler: "उत्पाद / छवियाँ", onceki: "पिछला", sonraki: "अगला", hikGosterilemiyor: "यह कहानी अभी नहीं दिखाई जा सकती" },
  ja: { fkTamAc: "全画面で開く", fkAmblemZemin: "エンブレムの背景色", fkAmblemYazi: "店名の色", renkKrem: "クリーム", renkAltin: "ゴールド", renkMavi: "ブルー", renkYesil: "グリーン", renkPembe: "ピンク", renkMor: "パープル", yaziKahve: "ブラウン", yaziAltin: "ゴールド", yaziKirmizi: "レッド", yaziLacivert: "ネイビー", yaziYesil: "グリーン", yaziBeyaz: "ホワイト", fkUrunGaleri: "商品の写真・動画", fkGaleriAciklama: "これは何？（数語書けばGloxooが仕上げます）", fkGaleriEkle: "商品の写真/動画を追加", fkGaleriGloxoo: "Gloxooに説明してもらう", fkUrunler: "商品 / 画像", onceki: "前へ", sonraki: "次へ", hikGosterilemiyor: "このストーリーは今表示できません" },
};
