// GLOXORG — eksik meslek adlarinin 12 dile cevirisi (B53). meslekCevir ile birlestirilir (mc kullanir).
// Anahtar = Turkce meslek adi; tr gerekmez (mc tr icin adi dondurur).
export const MESLEK_EK5 = {
 "Tornacı / CNC Operatörü": {
  "en": "Lathe / CNC Operator",
  "de": "Dreher / CNC-Bediener",
  "ru": "Токарь / Оператор ЧПУ",
  "uk": "Токар / Оператор ЧПК",
  "es": "Tornero / Operador CNC",
  "fr": "Tourneur / Opérateur CNC",
  "it": "Tornitore / Operatore CNC",
  "pt": "Torneiro / Operador CNC",
  "ar": "خرّاط / مشغّل CNC",
  "hi": "खरादी / CNC ऑपरेटर",
  "zh": "车工 / CNC操作员",
  "ja": "旋盤工 / CNCオペレーター"
 },
 "Kalıpçı / Dökümcü": {
  "en": "Mold Maker / Caster",
  "de": "Formenbauer / Gießer",
  "ru": "Формовщик / Литейщик",
  "uk": "Формувальник / Ливарник",
  "es": "Moldista / Fundidor",
  "fr": "Mouliste / Fondeur",
  "it": "Stampista / Fonditore",
  "pt": "Moldador / Fundidor",
  "ar": "صانع قوالب / سبّاك",
  "hi": "साँचा बनाने वाला / ढलाईगर",
  "zh": "模具工 / 铸造工",
  "ja": "金型工 / 鋳造工"
 },
 "Paletçi / Ahşap Palet": {
  "en": "Pallet Maker / Wooden Pallets",
  "de": "Palettenbauer / Holzpaletten",
  "ru": "Паллетчик / Деревянные поддоны",
  "uk": "Палетник / Дерев'яні піддони",
  "es": "Fabricante de palés de madera",
  "fr": "Fabricant de palettes en bois",
  "it": "Pallettista / Pallet in legno",
  "pt": "Paleteiro / Paletes de madeira",
  "ar": "صانع منصّات نقل / منصّات خشبية",
  "hi": "पैलेट निर्माता / लकड़ी के पैलेट",
  "zh": "托盘工 / 木托盘",
  "ja": "パレット工 / 木製パレット"
 },
 "Vinç / İş Makinesi Operatörü": {
  "en": "Crane / Heavy Machinery Operator",
  "de": "Kran- / Baumaschinenführer",
  "ru": "Оператор крана / спецтехники",
  "uk": "Оператор крана / спецтехніки",
  "es": "Operador de grúa / maquinaria",
  "fr": "Grutier / Opérateur d'engins",
  "it": "Operatore di gru / macchine da cantiere",
  "pt": "Operador de guindaste / máquinas",
  "ar": "مشغّل رافعة / آليات ثقيلة",
  "hi": "क्रेन / भारी मशीन ऑपरेटर",
  "zh": "起重机 / 工程机械操作员",
  "ja": "クレーン / 重機オペレーター"
 },
 "Sıvacı / Alçıpan": {
  "en": "Plasterer / Drywall",
  "de": "Putzer / Trockenbau",
  "ru": "Штукатур / Гипсокартон",
  "uk": "Штукатур / Гіпсокартон",
  "es": "Enlucidor / Pladur",
  "fr": "Plâtrier / Placoplâtre",
  "it": "Intonacatore / Cartongesso",
  "pt": "Rebocador / Gesso acartonado",
  "ar": "مبيّض / جبس بورد",
  "hi": "प्लास्टर मिस्त्री / जिप्सम बोर्ड",
  "zh": "抹灰工 / 石膏板",
  "ja": "左官 / 石膏ボード"
 },
 "İzolasyon / Mantolama": {
  "en": "Insulation / Cladding",
  "de": "Dämmung / Fassadendämmung",
  "ru": "Изоляция / Утепление фасадов",
  "uk": "Ізоляція / Утеплення фасадів",
  "es": "Aislamiento / Fachadas",
  "fr": "Isolation / Bardage",
  "it": "Isolamento / Cappotto termico",
  "pt": "Isolamento / Revestimento térmico",
  "ar": "عزل / تكسية حرارية",
  "hi": "इन्सुलेशन / बाहरी क्लैडिंग",
  "zh": "隔热 / 外墙保温",
  "ja": "断熱 / 外壁断熱"
 },
 "Çatı / Oluk Ustası": {
  "en": "Roof / Gutter Specialist",
  "de": "Dach- / Dachrinnenmeister",
  "ru": "Кровельщик / Мастер по водостокам",
  "uk": "Покрівельник / Майстер водостоків",
  "es": "Techador / Canalones",
  "fr": "Couvreur / Gouttières",
  "it": "Tetti / Grondaie",
  "pt": "Telhados / Calhas",
  "ar": "فنّي أسطح / مزاريب",
  "hi": "छत / नाली मिस्त्री",
  "zh": "屋顶 / 天沟师傅",
  "ja": "屋根 / 雨樋職人"
 },
 "Doğalgaz Tesisatçısı": {
  "en": "Gas Fitter",
  "de": "Gasinstallateur",
  "ru": "Газовщик",
  "uk": "Газівник",
  "es": "Instalador de gas natural",
  "fr": "Installateur de gaz naturel",
  "it": "Installatore gas",
  "pt": "Instalador de gás",
  "ar": "سبّاك غاز طبيعي",
  "hi": "गैस फिटर",
  "zh": "天然气安装工",
  "ja": "ガス配管工"
 },
 "Asansör Teknisyeni": {
  "en": "Elevator Technician",
  "de": "Aufzugstechniker",
  "ru": "Лифтёр-техник",
  "uk": "Технік ліфтів",
  "es": "Técnico de ascensores",
  "fr": "Technicien d'ascenseurs",
  "it": "Tecnico ascensori",
  "pt": "Técnico de elevadores",
  "ar": "فنّي مصاعد",
  "hi": "लिफ्ट तकनीशियन",
  "zh": "电梯技师",
  "ja": "エレベーター技師"
 },
 "Oto Elektrik": {
  "en": "Auto Electrics",
  "de": "Autoelektrik",
  "ru": "Автоэлектрик",
  "uk": "Автоелектрик",
  "es": "Electricidad del automóvil",
  "fr": "Électricité automobile",
  "it": "Elettrauto",
  "pt": "Eletricista de autos",
  "ar": "كهرباء سيارات",
  "hi": "ऑटो इलेक्ट्रिशियन",
  "zh": "汽车电工",
  "ja": "自動車電装"
 },
 "Lastik / Rot Balans": {
  "en": "Tires / Wheel Alignment",
  "de": "Reifen / Achsvermessung",
  "ru": "Шиномонтаж / Сход-развал",
  "uk": "Шиномонтаж / Розвал-сходження",
  "es": "Neumáticos / Alineación y balanceo",
  "fr": "Pneus / Parallélisme et équilibrage",
  "it": "Gommista / Convergenza ed equilibratura",
  "pt": "Borracheiro / Alinhamento e balanceamento",
  "ar": "إطارات / ترصيص وميزان",
  "hi": "टायर / व्हील अलाइनमेंट",
  "zh": "轮胎 / 四轮定位",
  "ja": "タイヤ / ホイールアライメント"
 },
 "Arıcı": {
  "en": "Beekeeper",
  "de": "Imker",
  "ru": "Пчеловод",
  "uk": "Бджоляр",
  "es": "Apicultor",
  "fr": "Apiculteur",
  "it": "Apicoltore",
  "pt": "Apicultor",
  "ar": "نحّال",
  "hi": "मधुमक्खी पालक",
  "zh": "养蜂人",
  "ja": "養蜂家"
 },
 "Çiftçi / Tarım": {
  "en": "Farmer / Agriculture",
  "de": "Landwirt / Landwirtschaft",
  "ru": "Фермер / Сельское хозяйство",
  "uk": "Фермер / Сільське господарство",
  "es": "Agricultor",
  "fr": "Agriculteur",
  "it": "Agricoltore",
  "pt": "Agricultor",
  "ar": "مزارع / زراعة",
  "hi": "किसान / कृषि",
  "zh": "农民 / 农业",
  "ja": "農家 / 農業"
 },
 "Seracı / Bahçıvan": {
  "en": "Greenhouse Grower / Gardener",
  "de": "Gewächshausgärtner / Gärtner",
  "ru": "Тепличник / Садовник",
  "uk": "Тепличник / Садівник",
  "es": "Horticultor / Jardinero",
  "fr": "Maraîcher / Jardinier",
  "it": "Serricoltore / Giardiniere",
  "pt": "Produtor de estufa / Jardineiro",
  "ar": "صاحب بيوت محمية / بستاني",
  "hi": "ग्रीनहाउस उत्पादक / माली",
  "zh": "温室工 / 园丁",
  "ja": "温室栽培 / 庭師"
 },
 "Balıkçı / Su Ürünleri": {
  "en": "Fisher / Seafood",
  "de": "Fischer / Meeresfrüchte",
  "ru": "Рыбак / Морепродукты",
  "uk": "Рибалка / Морепродукти",
  "es": "Pescador / Productos del mar",
  "fr": "Pêcheur / Produits de la mer",
  "it": "Pescatore / Prodotti ittici",
  "pt": "Pescador / Frutos do mar",
  "ar": "صيّاد / منتجات بحرية",
  "hi": "मछुआरा / जलीय उत्पाद",
  "zh": "渔民 / 水产",
  "ja": "漁師 / 水産"
 },
 "Ormancı": {
  "en": "Forester",
  "de": "Förster",
  "ru": "Лесник",
  "uk": "Лісник",
  "es": "Forestal",
  "fr": "Forestier",
  "it": "Forestale",
  "pt": "Trabalhador florestal",
  "ar": "حرّاج",
  "hi": "वनकर्मी",
  "zh": "林业工",
  "ja": "林業従事者"
 },
 "Madenci": {
  "en": "Miner",
  "de": "Bergmann",
  "ru": "Шахтёр",
  "uk": "Шахтар",
  "es": "Minero",
  "fr": "Mineur",
  "it": "Minatore",
  "pt": "Mineiro",
  "ar": "عامل مناجم",
  "hi": "खनिक",
  "zh": "矿工",
  "ja": "鉱夫"
 },
 "Bağcı / Şarapçı": {
  "en": "Vineyard Grower / Winemaker",
  "de": "Winzer / Weinbauer",
  "ru": "Виноградарь / Винодел",
  "uk": "Виноградар / Винороб",
  "es": "Viticultor / Vinicultor",
  "fr": "Viticulteur / Vigneron",
  "it": "Viticoltore / Vinificatore",
  "pt": "Viticultor / Produtor de vinho",
  "ar": "مزارع كروم / صانع نبيذ",
  "hi": "अंगूर उत्पादक / वाइन निर्माता",
  "zh": "葡萄种植 / 酿酒",
  "ja": "ブドウ栽培 / ワイン醸造"
 },
 "Zeytin / Zeytinyağı": {
  "en": "Olives / Olive Oil",
  "de": "Oliven / Olivenöl",
  "ru": "Оливки / Оливковое масло",
  "uk": "Оливки / Оливкова олія",
  "es": "Olivar / Aceite de oliva",
  "fr": "Oliveraie / Huile d'olive",
  "it": "Olive / Olio d'oliva",
  "pt": "Azeitona / Azeite",
  "ar": "زيتون / زيت زيتون",
  "hi": "जैतून / जैतून तेल",
  "zh": "橄榄 / 橄榄油",
  "ja": "オリーブ / オリーブオイル"
 },
 "Değirmenci / Un": {
  "en": "Miller / Flour",
  "de": "Müller / Mehl",
  "ru": "Мельник / Мука",
  "uk": "Мірошник / Борошно",
  "es": "Molinero / Harina",
  "fr": "Meunier / Farine",
  "it": "Mugnaio / Farina",
  "pt": "Moleiro / Farinha",
  "ar": "طحّان / دقيق",
  "hi": "चक्कीवाला / आटा",
  "zh": "磨坊工 / 面粉",
  "ja": "製粉工 / 小麦粉"
 },
 "Hemşire / Sağlık": {
  "en": "Nurse / Healthcare",
  "de": "Krankenpfleger / Gesundheit",
  "ru": "Медсестра / Здоровье",
  "uk": "Медсестра / Здоров'я",
  "es": "Enfermero / Salud",
  "fr": "Infirmier / Santé",
  "it": "Infermiere / Sanità",
  "pt": "Enfermeiro / Saúde",
  "ar": "ممرّض / صحّة",
  "hi": "नर्स / स्वास्थ्य",
  "zh": "护士 / 医疗",
  "ja": "看護師 / 医療"
 },
 "Diş Teknisyeni": {
  "en": "Dental Technician",
  "de": "Zahntechniker",
  "ru": "Зубной техник",
  "uk": "Зубний технік",
  "es": "Protésico dental",
  "fr": "Prothésiste dentaire",
  "it": "Odontotecnico",
  "pt": "Protético dentário",
  "ar": "فنّي أسنان",
  "hi": "डेंटल तकनीशियन",
  "zh": "牙科技师",
  "ja": "歯科技工士"
 },
 "Optisyen / Gözlükçü": {
  "en": "Optician",
  "de": "Optiker",
  "ru": "Оптик / Очки",
  "uk": "Оптик / Окуляри",
  "es": "Óptico",
  "fr": "Opticien",
  "it": "Ottico",
  "pt": "Ótico",
  "ar": "أخصائي بصريات / نظارات",
  "hi": "ऑप्टिशियन / चश्मे वाला",
  "zh": "验光师 / 眼镜商",
  "ja": "眼鏡技師 / 眼鏡店"
 },
 "Yazılımcı / Kodlama": {
  "en": "Software Developer / Coding",
  "de": "Softwareentwickler / Programmierung",
  "ru": "Программист / Код",
  "uk": "Програміст / Код",
  "es": "Programador / Código",
  "fr": "Développeur / Code",
  "it": "Sviluppatore / Programmazione",
  "pt": "Desenvolvedor / Programação",
  "ar": "مبرمج / برمجة",
  "hi": "सॉफ्टवेयर डेवलपर / कोडिंग",
  "zh": "软件工程师 / 编程",
  "ja": "ソフトウェア開発 / コーディング"
 },
 "Web Tasarımcı": {
  "en": "Web Designer",
  "de": "Webdesigner",
  "ru": "Веб-дизайнер",
  "uk": "Веб-дизайнер",
  "es": "Diseñador web",
  "fr": "Concepteur web",
  "it": "Web designer",
  "pt": "Web designer",
  "ar": "مصمم مواقع",
  "hi": "वेब डिज़ाइनर",
  "zh": "网页设计师",
  "ja": "Webデザイナー"
 },
 "Muhasebeci": {
  "en": "Accountant",
  "de": "Buchhalter",
  "ru": "Бухгалтер",
  "uk": "Бухгалтер",
  "es": "Contable",
  "fr": "Comptable",
  "it": "Commercialista",
  "pt": "Contador",
  "ar": "محاسب",
  "hi": "लेखाकार",
  "zh": "会计",
  "ja": "会計士"
 },
 "Çevirmen / Tercüman": {
  "en": "Translator / Interpreter",
  "de": "Übersetzer / Dolmetscher",
  "ru": "Переводчик",
  "uk": "Перекладач",
  "es": "Traductor / Intérprete",
  "fr": "Traducteur / Interprète",
  "it": "Traduttore / Interprete",
  "pt": "Tradutor / Intérprete",
  "ar": "مترجم / ترجمان",
  "hi": "अनुवादक / दुभाषिया",
  "zh": "翻译 / 口译",
  "ja": "翻訳 / 通訳"
 },
 "İnşaat Mühendisi": {
  "en": "Civil Engineer",
  "de": "Bauingenieur",
  "ru": "Инженер-строитель",
  "uk": "Інженер-будівельник",
  "es": "Ingeniero civil",
  "fr": "Ingénieur civil",
  "it": "Ingegnere civile",
  "pt": "Engenheiro civil",
  "ar": "مهندس إنشائي",
  "hi": "सिविल इंजीनियर",
  "zh": "土木工程师",
  "ja": "土木技師"
 },
 "Elektronik Tamir": {
  "en": "Electronics Repair",
  "de": "Elektronikreparatur",
  "ru": "Ремонт электроники",
  "uk": "Ремонт електроніки",
  "es": "Reparación electrónica",
  "fr": "Réparation électronique",
  "it": "Riparazione elettronica",
  "pt": "Reparo de eletrônicos",
  "ar": "إصلاح إلكترونيات",
  "hi": "इलेक्ट्रॉनिक्स मरम्मत",
  "zh": "电子维修",
  "ja": "電子機器修理"
 },
 "Telefon / Bilgisayar Tamir": {
  "en": "Phone / Computer Repair",
  "de": "Handy- / Computerreparatur",
  "ru": "Ремонт телефонов / компьютеров",
  "uk": "Ремонт телефонів / комп'ютерів",
  "es": "Reparación de móviles / ordenadores",
  "fr": "Réparation téléphones / ordinateurs",
  "it": "Riparazione telefoni / computer",
  "pt": "Reparo de celulares / computadores",
  "ar": "إصلاح هواتف / حواسيب",
  "hi": "फ़ोन / कंप्यूटर मरम्मत",
  "zh": "手机 / 电脑维修",
  "ja": "スマホ / パソコン修理"
 },
 "Ayakkabı Tamir / Kunduracı": {
  "en": "Shoe Repair / Cobbler",
  "de": "Schuhreparatur / Schuster",
  "ru": "Ремонт обуви / Сапожник",
  "uk": "Ремонт взуття / Швець",
  "es": "Reparación de calzado / Zapatero",
  "fr": "Réparation de chaussures / Cordonnier",
  "it": "Riparazione scarpe / Calzolaio",
  "pt": "Reparo de sapatos / Sapateiro",
  "ar": "إصلاح أحذية / إسكافي",
  "hi": "जूता मरम्मत / मोची",
  "zh": "补鞋 / 鞋匠",
  "ja": "靴修理 / 靴職人"
 },
 "Matbaacı / Baskı": {
  "en": "Printer / Printing",
  "de": "Drucker / Druckerei",
  "ru": "Типография / Печать",
  "uk": "Друкарня / Друк",
  "es": "Imprenta / Impresión",
  "fr": "Imprimeur / Impression",
  "it": "Tipografo / Stampa",
  "pt": "Gráfico / Impressão",
  "ar": "طبّاع / طباعة",
  "hi": "मुद्रक / छपाई",
  "zh": "印刷工 / 印刷",
  "ja": "印刷工 / 印刷"
 },
 "Reklam / Tabela": {
  "en": "Advertising / Signage",
  "de": "Werbung / Beschilderung",
  "ru": "Реклама / Вывески",
  "uk": "Реклама / Вивіски",
  "es": "Publicidad / Rótulos",
  "fr": "Publicité / Enseignes",
  "it": "Pubblicità / Insegne",
  "pt": "Publicidade / Letreiros",
  "ar": "دعاية / لافتات",
  "hi": "विज्ञापन / साइनबोर्ड",
  "zh": "广告 / 招牌",
  "ja": "広告 / 看板"
 },
 "Nakış / Baskılı Tekstil": {
  "en": "Embroidery / Printed Textiles",
  "de": "Stickerei / Bedruckte Textilien",
  "ru": "Вышивка / Печать на текстиле",
  "uk": "Вишивка / Друк на текстилі",
  "es": "Bordado / Textil estampado",
  "fr": "Broderie / Textile imprimé",
  "it": "Ricamo / Tessuti stampati",
  "pt": "Bordado / Têxtil estampado",
  "ar": "تطريز / طباعة أقمشة",
  "hi": "कढ़ाई / प्रिंटेड कपड़ा",
  "zh": "刺绣 / 印花纺织",
  "ja": "刺繍 / プリント繊維"
 },
 "Cam / Alüminyum Doğrama": {
  "en": "Glass / Aluminum Fitting",
  "de": "Glas- / Aluminiumbau",
  "ru": "Стекло / Алюминиевые конструкции",
  "uk": "Скло / Алюмінієві конструкції",
  "es": "Carpintería de vidrio / aluminio",
  "fr": "Menuiserie verre / aluminium",
  "it": "Serramenti in vetro / alluminio",
  "pt": "Esquadrias de vidro / alumínio",
  "ar": "زجاج / ألمنيوم",
  "hi": "कांच / एल्युमिनियम फ्रेम",
  "zh": "玻璃 / 铝型材",
  "ja": "ガラス / アルミサッシ"
 },
 "Su Tesisatçısı": {
  "en": "Plumber",
  "de": "Klempner",
  "ru": "Сантехник",
  "uk": "Сантехнік",
  "es": "Fontanero",
  "fr": "Plombier",
  "it": "Idraulico",
  "pt": "Encanador",
  "ar": "سبّاك مياه",
  "hi": "प्लंबर",
  "zh": "水管工",
  "ja": "水道配管工"
 },
 "Veteriner / Pet Bakım": {
  "en": "Vet / Pet Care",
  "de": "Tierarzt / Tierpflege",
  "ru": "Ветеринар / Уход за питомцами",
  "uk": "Ветеринар / Догляд за тваринами",
  "es": "Veterinario / Cuidado de mascotas",
  "fr": "Vétérinaire / Soins animaliers",
  "it": "Veterinario / Cura animali",
  "pt": "Veterinário / Cuidado de pets",
  "ar": "بيطري / عناية بالحيوانات",
  "hi": "पशु चिकित्सक / पालतू देखभाल",
  "zh": "兽医 / 宠物护理",
  "ja": "獣医 / ペットケア"
 },
 "Geri Dönüşüm / Hurdacı": {
  "en": "Recycling / Scrap Dealer",
  "de": "Recycling / Schrotthändler",
  "ru": "Переработка / Приём металлолома",
  "uk": "Переробка / Прийом металобрухту",
  "es": "Reciclaje / Chatarrero",
  "fr": "Recyclage / Ferrailleur",
  "it": "Riciclaggio / Rottamaio",
  "pt": "Reciclagem / Sucateiro",
  "ar": "إعادة تدوير / خردة",
  "hi": "रीसाइक्लिंग / कबाड़ी",
  "zh": "回收 / 废品",
  "ja": "リサイクル / 廃品回収"
 },
 "Pelet / Biyoyakıt": {
  "en": "Pellets / Biofuel",
  "de": "Pellets / Biokraftstoff",
  "ru": "Пеллеты / Биотопливо",
  "uk": "Пелети / Біопаливо",
  "es": "Pellet / Biocombustible",
  "fr": "Pellets / Biocarburant",
  "it": "Pellet / Biocarburante",
  "pt": "Pellet / Biocombustível",
  "ar": "حبيبات خشب / وقود حيوي",
  "hi": "पेलेट / जैव-ईंधन",
  "zh": "颗粒燃料 / 生物燃料",
  "ja": "ペレット / バイオ燃料"
 }
};
